In [8]:
import pandas as pd

df_hos = pd.read_excel('data/전국 병의원 및 약국 현황 2025.12/1.병원정보서비스(2025.12.).xlsx')
df_soa = pd.read_excel('data/전국 병의원 및 약국 현황 2025.12/5.의료기관별상세정보서비스_03_진료과목정보 2025.12..xlsx')

In [9]:
df_hos['종별코드명'].unique()

array(['의원', '정신병원', '치과의원', '병원', '한의원', '한방병원', '종합병원', '요양병원', '치과병원',
       '보건진료소', '보건지소', '상급종합', '보건소', '보건의료원', '조산원'], dtype=object)

In [10]:
df_hos = df_hos[df_hos['종별코드명'].isin(['의원', '병원', '종합병원'])]

In [11]:
df_hos = df_hos[['암호화요양기호','종별코드명', '요양기관명', '시도코드명', '시군구코드명', '읍면동', '위도','경도']]

In [12]:
df_hos

,암호화요양기호,종별코드명,요양기관명,시도코드명,시군구코드명,읍면동,위도,경도
0,JDQ4MTYyMiM4MSMkMiMkMCMkMDAkNDgxOTYxIzIxIyQxIy...,의원,(VOM)봄안과의원,대구,대구동구,율하동,35.869852,128.691894
2,JDQ4MTYyMiM4MSMkMiMkMCMkMDAkNDgxOTYxIzUxIyQxIy...,의원,(사) 경찰공제회 포항의원,경북,포항남구,오천읍,35.942257,129.392899
3,JDQ4MTg4MSM1MSMkMiMkOCMkMDAkMzgxOTYxIzUxIyQxIy...,의원,(사)경찰공제회 강서적성의원,서울,강서구,외발산동,37.549498,126.821985
4,JDU4MTI3MSM1MSMkMiMkMCMkMDAkNDgxOTYxIzIxIyQxIy...,의원,(사)경찰공제회남부의원,인천,인천남동구,고잔동,37.384910,126.708861
5,JDQ4MTAxMiM1MSMkMiMkMCMkMDAkNDgxMzUxIzMxIyQxIy...,의원,(사)대한산업보건협회 남부산의원,부산,부산강서구,명지동,35.094700,128.900150
...,...,...,...,...,...,...,...,...
79419,JDQ4MTg4MSM1MSMkMSMkNCMkOTkkMzgxMzUxIzExIyQxIy...,병원,힘찬병원,서울,양천구,목동,37.524972,126.876828
79420,JDQ4MTg4MSM1MSMkMiMkNCMkMDAkMzgxMzUxIzUxIyQxIy...,의원,힘찬부성정형외과의원,서울,강서구,화곡동,37.531819,126.857783
79422,JDQ4MTYyMiM3MSMkMiMkMCMkMDAkMzgxMTkxIzMxIyQxIy...,의원,힘찬우리의원,전남,목포시,용해동,34.817429,126.397895
79430,JDQ4MTYyMiM3MSMkMSMkMCMkOTkkMzgxMzUxIzIxIyQxIy...,병원,힘플러스병원,전남,순천시,조례동,34.960448,127.519845
79431,JDU4MTI3MSM1MSMkMiMkMCMkMDAkMzgxNzAyIzIxIyQxIy...,의원,힙스청담의원,경기,성남분당구,정자동,37.365752,127.107331

In [13]:
cities = ['성남', '고양', '부천', '광명', '하남', '남양주', '용인', '김포', '구리', '안양']

inst = df_hos[
    (df_hos['시도코드명'].isin(['서울', '인천'])) |
    (df_hos['시군구코드명'].str.contains('|'.join(cities), na=False))
].copy()

In [14]:
df_ped = df_soa[df_soa['진료과목코드명'] == '소아청소년과'].copy()

In [15]:
df_merge = pd.merge(
    inst,
    df_ped,
    on='암호화요양기호',
    how='inner'
)

In [16]:
len(df_merge['읍면동'].unique())

524

In [17]:
df_merge

,암호화요양기호,종별코드명,요양기관명_x,시도코드명,시군구코드명,읍면동,위도,경도,요양기관명_y,진료과목코드,진료과목코드명,과목별 전문의수,선택진료 의사수
0,JDQ4MTg4MSM1MSMkMiMkMCMkMDAkMzgxNzAyIzIxIyQxIy...,의원,(사)인구보건복지협회 서울지회 가족보건의원,서울,광진구,중곡동,37.565080,127.083230,(사)인구보건복지협회 서울지회 가족보건의원,11,소아청소년과,0,0
1,JDQ4MTg4MSM1MSMkMiMkNCMkMDAkNDgxNzAyIzMxIyQxIy...,의원,(사)한국뇌전증협회로빈슨기념의원,서울,중구,만리동2가,37.554704,126.965493,(사)한국뇌전증협회로빈슨기념의원,11,소아청소년과,1,0
2,JDQ4MTg4MSM1MSMkMiMkMCMkMDAkNDgxMzUxIzIxIyQxIy...,의원,(사)한국한센복지협회서울특별시지부부설의원,서울,동작구,상도동,37.504079,126.938053,(사)한국한센복지협회서울특별시지부부설의원,11,소아청소년과,0,0
3,JDQ4MTg4MSM1MSMkMiMkNCMkMDAkNDgxMTkxIzIxIyQxIy...,의원,(스카이메디)연세건강증진내과의원,서울,송파구,석촌동,37.500798,127.110766,(스카이메디)연세건강증진내과의원,11,소아청소년과,0,0
4,JDQ4MTg4MSM1MSMkMiMkMCMkMDAkNTgxOTYxIzMxIyQxIy...,의원,(의) 열린의료재단 강동열린의원,서울,강동구,성내동,37.535230,127.132614,(의) 열린의료재단 강동열린의원,11,소아청소년과,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5987,JDQ4MTg4MSM1MSMkMiMkOCMkMDAkMzgxMzUxIzUxIyQxIy...,의원,히포크라타의원,서울,서초구,잠원동,37.512821,127.010667,히포크라타의원,11,소아청소년과,0,0
5988,JDQ4MTYyMiM1MSMkMiMkMCMkMDAkNTgxMzUxIzMxIyQxIy...,의원,힐락소아청소년과의원,경기,부천원미구,상동,37.504110,126.756663,힐락소아청소년과의원,11,소아청소년과,1,0
5989,JDQ4MTYyMiM1MSMkMiMkMCMkMDAkMzgxOTYxIzUxIyQxIy...,의원,힐락의원,경기,부천원미구,상동,37.504110,126.756663,힐락의원,11,소아청소년과,1,0
5990,JDQ4MTYyMiM1MSMkMiMkMCMkMDAkNDgxNzAyIzQxIyQxIy...,의원,힐메디의원,경기,김포시,고촌읍,37.596390,126.767652,힐메디의원,11,소아청소년과,0,0
5991,JDQ4MTg4MSM1MSMkMiMkNCMkMDAkMzgxMzUxIzUxIyQxIy...,의원,힘찬부성정형외과의원,서울,강서구,화곡동,37.531819,126.857783,힘찬부성정형외과의원,11,소아청소년과,0,0

In [19]:
df_in = pd.read_excel('[공통] 전체_인구통계_정제완료.xlsx')

In [20]:
df_in.columns.get_loc('17세여자') # 5~22 116~133

133

In [21]:
df_in['아동인구수'] = df_in.iloc[:,5:23].sum(axis=1) + df_in.iloc[:,116:134].sum(axis=1)

In [22]:
df_in = df_in[['시도명','시군구명','읍면동명','아동인구수']]

In [23]:
df_in

       시도명 시군구명   읍면동명  아동인구수
0    서울특별시  종로구  청운효자동   1258
1    서울특별시  종로구    사직동    858
2    서울특별시  종로구    삼청동    181
3    서울특별시  종로구    부암동    881
4    서울특별시  종로구    평창동   2039
..     ...  ...    ...    ...
858    경기도  김포시    풍무동   9962
859    경기도  김포시    장기동   8419
860    경기도  김포시    구래동   8787
861    경기도  김포시    마산동   7726
862    경기도  김포시    운양동  10621

[863 rows x 4 columns]

In [24]:
df_hos_sum = (
    df_merge.groupby(['시도코드명', '시군구코드명', '읍면동'], as_index=False)
    .agg({
        '과목별 전문의수': 'sum',
        '위도': 'mean',
        '경도': 'mean'
    })
)

In [25]:
df_hos_sum['시도코드명'] = df_hos_sum['시도코드명'].replace({
    '서울': '서울특별시',
    '인천': '인천광역시',
    '경기': '경기도'
})

In [26]:
df_hos_sum['시군구코드명'] = df_hos_sum['시군구코드명'].replace({
    '인천중구': '중구',
    '인천동구': '동구',
    '인천미추홀구': '미추홀구',
    '인천연수구': '연수구',
    '인천남동구': '남동구',
    '인천부평구': '부평구',
    '인천계양구': '계양구',
    '인천서구': '서구',
    '인천강화군': '강화군',
    '인천옹진군': '옹진군',

    '서울강남구': '강남구',
    '서울강동구': '강동구',
    '서울강북구': '강북구',
    '서울강서구': '강서구',
    '서울관악구': '관악구',
    '서울광진구': '광진구',
    '서울구로구': '구로구',
    '서울금천구': '금천구',
    '서울노원구': '노원구',
    '서울도봉구': '도봉구',
    '서울동대문구': '동대문구',
    '서울동작구': '동작구',
    '서울마포구': '마포구',
    '서울서대문구': '서대문구',
    '서울서초구': '서초구',
    '서울성동구': '성동구',
    '서울성북구': '성북구',
    '서울송파구': '송파구',
    '서울양천구': '양천구',
    '서울영등포구': '영등포구',
    '서울용산구': '용산구',
    '서울은평구': '은평구',
    '서울종로구': '종로구',
    '서울중구': '중구',
    '서울중랑구': '중랑구',

    '부천원미구': '부천시 원미구',
    '부천소사구': '부천시 소사구',
    '부천오정구': '부천시 오정구',
    '성남분당구': '성남시 분당구',
    '성남수정구': '성남시 수정구',
    '성남중원구': '성남시 중원구',
    '안양동안구': '안양시 동안구',
    '안양만안구': '안양시 만안구',
    '안산단원구': '안산시 단원구',
    '안산상록구': '안산시 상록구',
    '고양덕양구': '고양시 덕양구',
    '고양일산동구': '고양시 일산동구',
    '고양일산서구': '고양시 일산서구',
    '용인기흥구': '용인시 기흥구',
    '용인수지구': '용인시 수지구',
    '용인처인구': '용인시 처인구',
    '수원권선구': '수원시 권선구',
    '수원영통구': '수원시 영통구',
    '수원장안구': '수원시 장안구',
    '수원팔달구': '수원시 팔달구'
})

In [27]:
df_hos_sum

     시도코드명   시군구코드명   읍면동  과목별 전문의수         위도          경도
0      경기도  고양시 덕양구   고양동         0  37.705393  126.902248
1      경기도  고양시 덕양구   관산동         2  37.695134  126.861178
2      경기도  고양시 덕양구   내유동         0  37.726148  126.845309
3      경기도  고양시 덕양구   덕은동         2  37.579933  126.869387
4      경기도  고양시 덕양구   도내동         3  37.632802  126.870760
..     ...      ...   ...       ...        ...         ...
535  인천광역시       중구    유동         0  37.469148  126.636661
536  인천광역시       중구   율목동         1  37.471216  126.632122
537  인천광역시       중구   인현동         0  37.473888  126.629731
538  인천광역시       중구   중산동         3  37.488719  126.559908
539  인천광역시       중구  항동7가         0  37.453822  126.604789

[540 rows x 6 columns]

In [28]:
import requests
import pandas as pd
import time

url = "https://dapi.kakao.com/v2/local/geo/coord2regioncode.json"
headers = {"Authorization": "KakaoAK YOUR_KAKAO_API_KEY"}

def get_dong(lat, lon):
    try:
        params = {"x": lon, "y": lat}
        res = requests.get(url, headers=headers, params=params, timeout=5)
        data = res.json()

        time.sleep(0.2)

        for doc in data.get('documents', []):
            if doc['region_type'] == 'H':
                return doc['region_3depth_name']

        return None
    except:
        return None

In [29]:
df_hos_sum['행정동'] = df_hos_sum.apply(
    lambda row: get_dong(row['위도'], row['경도']),
    axis=1
)

In [30]:
df_hos_sum

     시도코드명   시군구코드명   읍면동  과목별 전문의수         위도          경도   행정동
0      경기도  고양시 덕양구   고양동         0  37.705393  126.902248   고양동
1      경기도  고양시 덕양구   관산동         2  37.695134  126.861178   관산동
2      경기도  고양시 덕양구   내유동         0  37.726148  126.845309   관산동
3      경기도  고양시 덕양구   덕은동         2  37.579933  126.869387   대덕동
4      경기도  고양시 덕양구   도내동         3  37.632802  126.870760   흥도동
..     ...      ...   ...       ...        ...         ...   ...
535  인천광역시       중구    유동         0  37.469148  126.636661   율목동
536  인천광역시       중구   율목동         1  37.471216  126.632122   율목동
537  인천광역시       중구   인현동         0  37.473888  126.629731  동인천동
538  인천광역시       중구   중산동         3  37.488719  126.559908  영종1동
539  인천광역시       중구  항동7가         0  37.453822  126.604789   연안동

[540 rows x 7 columns]

In [31]:
set(df_hos_sum['시군구코드명']) - set(df_in['시군구명'])

set()

In [32]:
set(df_in['시군구명']) - set(df_hos_sum['시군구코드명'])

set()

In [33]:
set(
    zip(df_in['시도명'], df_in['시군구명'], df_in['읍면동명'])
) - set(
    zip(df_hos_sum['시도코드명'], df_hos_sum['시군구코드명'], df_hos_sum['행정동'])
)

{('경기도', '고양시 덕양구', '성사2동'),
 ('경기도', '고양시 덕양구', '주교동'),
 ('경기도', '고양시 덕양구', '행신2동'),
 ('경기도', '고양시 덕양구', '행신3동'),
 ('경기도', '고양시 덕양구', '행신4동'),
 ('경기도', '고양시 덕양구', '행주동'),
 ('경기도', '고양시 덕양구', '화정1동'),
 ('경기도', '고양시 일산동구', '마두2동'),
 ('경기도', '고양시 일산동구', '백석2동'),
 ('경기도', '고양시 일산동구', '장항1동'),
 ('경기도', '고양시 일산동구', '중산1동'),
 ('경기도', '고양시 일산서구', '송포동'),
 ('경기도', '고양시 일산서구', '일산1동'),
 ('경기도', '고양시 일산서구', '일산3동'),
 ('경기도', '고양시 일산서구', '주엽2동'),
 ('경기도', '고양시 일산서구', '탄현2동'),
 ('경기도', '광명시', '광명1동'),
 ('경기도', '광명시', '광명2동'),
 ('경기도', '광명시', '광명3동'),
 ('경기도', '광명시', '광명5동'),
 ('경기도', '광명시', '광명6동'),
 ('경기도', '광명시', '광명7동'),
 ('경기도', '광명시', '소하1동'),
 ('경기도', '광명시', '철산1동'),
 ('경기도', '광명시', '철산2동'),
 ('경기도', '광명시', '철산4동'),
 ('경기도', '광명시', '하안1동'),
 ('경기도', '광명시', '하안3동'),
 ('경기도', '광명시', '하안4동'),
 ('경기도', '광명시', '학온동'),
 ('경기도', '구리시', '교문2동'),
 ('경기도', '구리시', '수택1동'),
 ('경기도', '구리시', '수택3동'),
 ('경기도', '구리시', '인창동'),
 ('경기도', '김포시', '월곶면'),
 ('경기도', '김포시', '장기본동'),
 ('경기도', '남양주시', '양정동'),
 ('경기도', '남양주시', '조안면'),
 ('경기도', '남양주시', '화도읍남부출장소'),
 ('경기도', '남양주시', '화도읍동부출장소'),
 ('경기도', '부천시 소사구', '괴안동'),
 ('경기도', '부천시 소사구', '소사본동'),
 ('경기도', '부천시 소사구', '송내2동'),
 ('경기도', '부천시 소사구', '심곡본1동'),
 ('경기도', '부천시 오정구', '고강1동'),
 ('경기도', '부천시 오정구', '원종1동'),
 ('경기도', '부천시 원미구', '상1동'),
 ('경기도', '부천시 원미구', '상3동'),
 ('경기도', '부천시 원미구', '상동'),
 ('경기도', '부천시 원미구', '심곡2동'),
 ('경기도', '부천시 원미구', '심곡3동'),
 ('경기도', '부천시 원미구', '역곡2동'),
 ('경기도', '부천시 원미구', '원미2동'),
 ('경기도', '부천시 원미구', '중2동'),
 ('경기도', '부천시 원미구', '중3동'),
 ('경기도', '부천시 원미구', '중4동'),
 ('경기도', '부천시 원미구', '중동'),
 ('경기도', '성남시 분당구', '구미1동'),
 ('경기도', '성남시 분당구', '서현2동'),
 ('경기도', '성남시 분당구', '수내1동'),
 ('경기도', '성남시 분당구', '수내3동'),
 ('경기도', '성남시 분당구', '야탑2동'),
 ('경기도', '성남시 분당구', '야탑3동'),
 ('경기도', '성남시 분당구', '이매2동'),
 ('경기도', '성남시 분당구', '정자1동'),
 ('경기도', '성남시 분당구', '정자2동'),
 ('경기도', '성남시 분당구', '정자3동'),
 ('경기도', '성남시 수정구', '수진1동'),
 ('경기도', '성남시 수정구', '시흥동'),
 ('경기도', '성남시 수정구', '신촌동'),
 ('경기도', '성남시 수정구', '신흥1동'),
 ('경기도', '성남시 수정구', '신흥2동'),
 ('경기도', '성남시 수정구', '태평1동'),
 ('경기도', '성남시 수정구', '태평2동'),
 ('경기도', '성남시 수정구', '태평4동'),
 ('경기도', '성남시 중원구', '금광1동'),
 ('경기도', '성남시 중원구', '상대원2동'),
 ('경기도', '성남시 중원구', '상대원3동'),
 ('경기도', '성남시 중원구', '은행1동'),
 ('경기도', '안양시 동안구', '갈산동'),
 ('경기도', '안양시 동안구', '관양동'),
 ('경기도', '안양시 동안구', '귀인동'),
 ('경기도', '안양시 동안구', '달안동'),
 ('경기도', '안양시 동안구', '범계동'),
 ('경기도', '안양시 동안구', '부림동'),
 ('경기도', '안양시 동안구', '부흥동'),
 ('경기도', '안양시 동안구', '비산1동'),
 ('경기도', '안양시 동안구', '비산3동'),
 ('경기도', '안양시 동안구', '신촌동'),
 ('경기도', '안양시 동안구', '평촌동'),
 ('경기도', '안양시 동안구', '호계2동'),
 ('경기도', '안양시 동안구', '호계3동'),
 ('경기도', '안양시 만안구', '석수1동'),
 ('경기도', '안양시 만안구', '안양1동'),
 ('경기도', '안양시 만안구', '안양2동'),
 ('경기도', '안양시 만안구', '안양3동'),
 ('경기도', '안양시 만안구', '안양4동'),
 ('경기도', '안양시 만안구', '안양6동'),
 ('경기도', '안양시 만안구', '안양7동'),
 ('경기도', '안양시 만안구', '안양8동'),
 ('경기도', '안양시 만안구', '안양9동'),
 ('경기도', '안양시 만안구', '충훈동'),
 ('경기도', '안양시 만안구', '호현동'),
 ('경기도', '용인시 기흥구', '동백3동'),
 ('경기도', '용인시 기흥구', '영덕2동'),
 ('경기도', '용인시 수지구', '상현2동'),
 ('경기도', '용인시 수지구', '상현3동'),
 ('경기도', '용인시 수지구', '죽전2동'),
 ('경기도', '용인시 수지구', '죽전3동'),
 ('경기도', '용인시 수지구', '풍덕천1동'),
 ('경기도', '하남시', '감북동'),
 ('경기도', '하남시', '덕풍1동'),
 ('경기도', '하남시', '덕풍3동'),
 ('경기도', '하남시', '신장1동'),
 ('경기도', '하남시', '천현동'),
 ('경기도', '하남시', '초이동'),
 ('경기도', '하남시', '춘궁동'),
 ('서울특별시', '강남구', '개포2동'),
 ('서울특별시', '강남구', '개포3동'),
 ('서울특별시', '강남구', '개포4동'),
 ('서울특별시', '강남구', '논현1동'),
 ('서울특별시', '강남구', '대치2동'),
 ('서울특별시', '강남구', '대치4동'),
 ('서울특별시', '강남구', '도곡2동'),
 ('서울특별시', '강남구', '삼성1동'),
 ('서울특별시', '강남구', '신사동'),
 ('서울특별시', '강남구', '역삼1동'),
 ('서울특별시', '강남구', '일원1동'),
 ('서울특별시', '강동구', '고덕1동'),
 ('서울특별시', '강동구', '둔촌1동'),
 ('서울특별시', '강동구', '명일2동'),
 ('서울특별시', '강동구', '상일2동'),
 ('서울특별시', '강동구', '성내2동'),
 ('서울특별시', '강동구', '성내3동'),
 ('서울특별시', '강동구', '암사2동'),
 ('서울특별시', '강동구', '암사3동'),
 ('서울특별시', '강동구', '천호2동'),
 ('서울특별시', '강동구', '천호3동'),
 ('서울특별시', '강북구', '미아동'),
 ('서울특별시', '강북구', '번1동'),
 ('서울특별시', '강북구', '번3동'),
 ('서울특별시', '강북구', '삼각산동'),
 ('서울특별시', '강북구', '삼양동'),
 ('서울특별시', '강북구', '송중동'),
 ('서울특별시', '강북구', '수유1동'),
 ('서울특별시', '강북구', '수유2동'),
 ('서울특별시', '강북구', '인수동'),
 ('서울특별시', '강서구', '가양3동'),
 ('서울특별시', '강서구', '등촌2동'),
 ('서울특별시', '강서구', '등촌3동'),
 ('서울특별시', '강서구', '방화1동'),
 ('서울특별시', '강서구', '방화3동'),
 ('서울특별시', '강서구', '우장산동'),
 ('서울특별시', '강서구', '화곡1동'),
 ('서울특별시', '강서구', '화곡2동'),
 ('서울특별시', '강서구', '화곡3동'),
 ('서울특별시', '강서구', '화곡4동'),
 ('서울특별시', '강서구', '화곡6동'),
 ('서울특별시', '강서구', '화곡8동'),
 ('서울특별시', '관악구', '낙성대동'),
 ('서울특별시', '관악구', '난곡동'),
 ('서울특별시', '관악구', '난향동'),
 ('서울특별시', '관악구', '대학동'),
 ('서울특별시', '관악구', '미성동'),
 ('서울특별시', '관악구', '보라매동'),
 ('서울특별시', '관악구', '삼성동'),
 ('서울특별시', '관악구', '서림동'),
 ('서울특별시', '관악구', '서원동'),
 ('서울특별시', '관악구', '성현동'),
 ('서울특별시', '관악구', '신림동'),
 ('서울특별시', '관악구', '신사동'),
 ('서울특별시', '관악구', '은천동'),
 ('서울특별시', '관악구', '인헌동'),
 ('서울특별시', '관악구', '조원동'),
 ('서울특별시', '관악구', '청룡동'),
 ('서울특별시', '관악구', '청림동'),
 ('서울특별시', '관악구', '행운동'),
 ('서울특별시', '광진구', '구의1동'),
 ('서울특별시', '광진구', '구의2동'),
 ('서울특별시', '광진구', '자양1동'),
 ('서울특별시', '광진구', '자양2동'),
 ('서울특별시', '광진구', '자양4동'),
 ('서울특별시', '광진구', '중곡1동'),
 ('서울특별시', '광진구', '중곡3동'),
 ('서울특별시', '광진구', '중곡4동'),
 ('서울특별시', '구로구', '개봉1동'),
 ('서울특별시', '구로구', '개봉3동'),
 ('서울특별시', '구로구', '고척1동'),
 ('서울특별시', '구로구', '구로1동'),
 ('서울특별시', '구로구', '구로3동'),
 ('서울특별시', '구로구', '구로4동'),
 ('서울특별시', '구로구', '구로5동'),
 ('서울특별시', '구로구', '오류1동'),
 ('서울특별시', '금천구', '독산1동'),
 ('서울특별시', '금천구', '독산2동'),
 ('서울특별시', '금천구', '독산3동'),
 ('서울특별시', '금천구', '시흥2동'),
 ('서울특별시', '금천구', '시흥3동'),
 ('서울특별시', '금천구', '시흥4동'),
 ('서울특별시', '금천구', '시흥5동'),
 ('서울특별시', '노원구', '공릉1동'),
 ('서울특별시', '노원구', '상계1동'),
 ('서울특별시', '노원구', '상계2동'),
 ('서울특별시', '노원구', '상계3.4동'),
 ('서울특별시', '노원구', '상계5동'),
 ('서울특별시', '노원구', '상계6.7동'),
 ('서울특별시', '노원구', '상계8동'),
 ('서울특별시', '노원구', '상계9동'),
 ('서울특별시', '노원구', '월계2동'),
 ('서울특별시', '노원구', '월계3동'),
 ('서울특별시', '노원구', '중계2.3동'),
 ('서울특별시', '노원구', '중계4동'),
 ('서울특별시', '노원구', '중계본동'),
 ('서울특별시', '노원구', '하계2동'),
 ('서울특별시', '도봉구', '도봉1동'),
 ('서울특별시', '도봉구', '방학2동'),
 ('서울특별시', '도봉구', '방학3동'),
 ('서울특별시', '도봉구', '쌍문1동'),
 ('서울특별시', '도봉구', '쌍문2동'),
 ('서울특별시', '도봉구', '쌍문3동'),
 ('서울특별시', '도봉구', '창2동'),
 ('서울특별시', '도봉구', '창3동'),
 ('서울특별시', '도봉구', '창4동'),
 ('서울특별시', '도봉구', '창5동'),
 ('서울특별시', '동대문구', '답십리2동'),
 ('서울특별시', '동대문구', '이문2동'),
 ('서울특별시', '동대문구', '장안2동'),
 ('서울특별시', '동대문구', '전농2동'),
 ('서울특별시', '동대문구', '휘경1동'),
 ('서울특별시', '동작구', '노량진2동'),
 ('서울특별시', '동작구', '사당1동'),
 ('서울특별시', '동작구', '사당2동'),
 ('서울특별시', '동작구', '사당4동'),
 ('서울특별시', '동작구', '사당5동'),
 ('서울특별시', '동작구', '상도3동'),
 ('서울특별시', '동작구', '상도4동'),
 ('서울특별시', '동작구', '신대방1동'),
 ('서울특별시', '마포구', '망원2동'),
 ('서울특별시', '마포구', '성산1동'),
 ('서울특별시', '마포구', '아현동'),
 ('서울특별시', '마포구', '합정동'),
 ('서울특별시', '서대문구', '남가좌1동'),
 ('서울특별시', '서대문구', '북가좌1동'),
 ('서울특별시', '서대문구', '홍은2동'),
 ('서울특별시', '서대문구', '홍제1동'),
 ('서울특별시', '서대문구', '홍제2동'),
 ('서울특별시', '서초구', '반포1동'),
 ('서울특별시', '서초구', '반포2동'),
 ('서울특별시', '서초구', '반포3동'),
 ('서울특별시', '서초구', '반포본동'),
 ('서울특별시', '서초구', '방배1동'),
 ('서울특별시', '서초구', '방배2동'),
 ('서울특별시', '서초구', '방배3동'),
 ('서울특별시', '서초구', '방배본동'),
 ('서울특별시', '서초구', '서초2동'),
 ('서울특별시', '서초구', '서초3동'),
 ('서울특별시', '서초구', '서초4동'),
 ('서울특별시', '성동구', '사근동'),
 ('서울특별시', '성동구', '성수1가1동'),
 ('서울특별시', '성동구', '성수2가3동'),
 ('서울특별시', '성동구', '왕십리2동'),
 ('서울특별시', '성동구', '행당1동'),
 ('서울특별시', '성북구', '길음2동'),
 ('서울특별시', '성북구', '돈암2동'),
 ('서울특별시', '성북구', '장위1동'),
 ('서울특별시', '성북구', '장위3동'),
 ('서울특별시', '성북구', '정릉1동'),
 ('서울특별시', '성북구', '정릉3동'),
 ('서울특별시', '성북구', '정릉4동'),
 ('서울특별시', '송파구', '가락1동'),
 ('서울특별시', '송파구', '가락2동'),
 ('서울특별시', '송파구', '거여1동'),
 ('서울특별시', '송파구', '마천1동'),
 ('서울특별시', '송파구', '문정2동'),
 ('서울특별시', '송파구', '방이1동'),
 ('서울특별시', '송파구', '송파2동'),
 ('서울특별시', '송파구', '오륜동'),
 ('서울특별시', '송파구', '잠실2동'),
 ('서울특별시', '송파구', '잠실3동'),
 ('서울특별시', '송파구', '잠실4동'),
 ('서울특별시', '송파구', '잠실7동'),
 ('서울특별시', '송파구', '장지동'),
 ('서울특별시', '송파구', '풍납1동'),
 ('서울특별시', '양천구', '목1동'),
 ('서울특별시', '양천구', '목2동'),
 ('서울특별시', '양천구', '목3동'),
 ('서울특별시', '양천구', '목5동'),
 ('서울특별시', '양천구', '신월1동'),
 ('서울특별시', '양천구', '신월2동'),
 ('서울특별시', '양천구', '신월3동'),
 ('서울특별시', '양천구', '신월5동'),
 ('서울특별시', '양천구', '신월6동'),
 ('서울특별시', '양천구', '신월7동'),
 ('서울특별시', '양천구', '신정2동'),
 ('서울특별시', '양천구', '신정3동'),
 ('서울특별시', '양천구', '신정4동'),
 ('서울특별시', '양천구', '신정6동'),
 ('서울특별시', '양천구', '신정7동'),
 ('서울특별시', '영등포구', '대림2동'),
 ('서울특별시', '영등포구', '대림3동'),
 ('서울특별시', '영등포구', '신길1동'),
 ('서울특별시', '영등포구', '신길3동'),
 ('서울특별시', '영등포구', '신길5동'),
 ('서울특별시', '영등포구', '신길6동'),
 ('서울특별시', '영등포구', '신길7동'),
 ('서울특별시', '용산구', '서빙고동'),
 ('서울특별시', '용산구', '이촌2동'),
 ('서울특별시', '용산구', '이태원2동'),
 ('서울특별시', '은평구', '갈현2동'),
 ('서울특별시', '은평구', '불광2동'),
 ('서울특별시', '은평구', '신사2동'),
 ('서울특별시', '은평구', '응암1동'),
 ('서울특별시', '은평구', '응암3동'),
 ('서울특별시', '종로구', '가회동'),
 ('서울특별시', '종로구', '삼청동'),
 ('서울특별시', '종로구', '숭인1동'),
 ('서울특별시', '종로구', '창신2동'),
 ('서울특별시', '종로구', '창신3동'),
 ('서울특별시', '중구', '다산동'),
 ('서울특별시', '중구', '동화동'),
 ('서울특별시', '중구', '신당5동'),
 ('서울특별시', '중구', '약수동'),
 ('서울특별시', '중구', '을지로동'),
 ('서울특별시', '중랑구', '망우3동'),
 ('서울특별시', '중랑구', '면목2동'),
 ('서울특별시', '중랑구', '면목3.8동'),
 ('서울특별시', '중랑구', '면목4동'),
 ('서울특별시', '중랑구', '면목5동'),
 ('서울특별시', '중랑구', '면목7동'),
 ('서울특별시', '중랑구', '묵2동'),
 ('서울특별시', '중랑구', '상봉2동'),
 ('서울특별시', '중랑구', '신내2동'),
 ('서울특별시', '중랑구', '중화2동'),
 ('인천광역시', '강화군', '교동면'),
 ('인천광역시', '강화군', '내가면'),
 ('인천광역시', '강화군', '불은면'),
 ('인천광역시', '강화군', '삼산면'),
 ('인천광역시', '강화군', '서도면'),
 ('인천광역시', '강화군', '서도면볼음출장소'),
 ('인천광역시', '강화군', '선원면'),
 ('인천광역시', '강화군', '송해면'),
 ('인천광역시', '강화군', '양도면'),
 ('인천광역시', '강화군', '양사면'),
 ('인천광역시', '강화군', '하점면'),
 ('인천광역시', '강화군', '화도면'),
 ('인천광역시', '계양구', '계산2동'),
 ('인천광역시', '계양구', '계산3동'),
 ('인천광역시', '계양구', '작전2동'),
 ('인천광역시', '계양구', '작전서운동'),
 ('인천광역시', '계양구', '효성2동'),
 ('인천광역시', '남동구', '간석2동'),
 ('인천광역시', '남동구', '간석3동'),
 ('인천광역시', '남동구', '간석4동'),
 ('인천광역시', '남동구', '구월2동'),
 ('인천광역시', '남동구', '구월3동'),
 ('인천광역시', '남동구', '구월4동'),
 ('인천광역시', '남동구', '논현1동'),
 ('인천광역시', '남동구', '논현2동'),
 ('인천광역시', '남동구', '만수1동'),
 ('인천광역시', '남동구', '만수2동'),
 ('인천광역시', '남동구', '만수3동'),
 ('인천광역시', '남동구', '만수4동'),
 ('인천광역시', '남동구', '만수6동'),
 ('인천광역시', '남동구', '장수서창동'),
 ('인천광역시', '동구', '송림1동'),
 ('인천광역시', '동구', '송림2동'),
 ('인천광역시', '동구', '송림3.5동'),
 ('인천광역시', '동구', '송림4동'),
 ('인천광역시', '동구', '송현3동'),
 ('인천광역시', '동구', '화수2동'),
 ('인천광역시', '미추홀구', '도화2.3동'),
 ('인천광역시', '미추홀구', '숭의1.3동'),
 ('인천광역시', '미추홀구', '숭의4동'),
 ('인천광역시', '미추홀구', '용현1.4동'),
 ('인천광역시', '미추홀구', '용현3동'),
 ('인천광역시', '미추홀구', '용현5동'),
 ('인천광역시', '미추홀구', '주안1동'),
 ('인천광역시', '미추홀구', '주안2동'),
 ('인천광역시', '미추홀구', '주안3동'),
 ('인천광역시', '미추홀구', '주안5동'),
 ('인천광역시', '미추홀구', '주안6동'),
 ('인천광역시', '미추홀구', '주안7동'),
 ('인천광역시', '미추홀구', '주안8동'),
 ('인천광역시', '미추홀구', '학익2동'),
 ('인천광역시', '부평구', '갈산2동'),
 ('인천광역시', '부평구', '부개1동'),
 ('인천광역시', '부평구', '부개3동'),
 ('인천광역시', '부평구', '부평1동'),
 ('인천광역시', '부평구', '부평2동'),
 ('인천광역시', '부평구', '부평3동'),
 ('인천광역시', '부평구', '부평4동'),
 ('인천광역시', '부평구', '부평6동'),
 ('인천광역시', '부평구', '산곡1동'),
 ('인천광역시', '부평구', '산곡3동'),
 ('인천광역시', '부평구', '산곡4동'),
 ('인천광역시', '부평구', '삼산1동'),
 ('인천광역시', '부평구', '십정1동'),
 ('인천광역시', '부평구', '청천1동'),
 ('인천광역시', '서구', '가정2동'),
 ('인천광역시', '서구', '가정3동'),
 ('인천광역시', '서구', '가좌1동'),
 ('인천광역시', '서구', '가좌2동'),
 ('인천광역시', '서구', '가좌4동'),
 ('인천광역시', '서구', '마전동'),
 ('인천광역시', '서구', '석남2동'),
 ('인천광역시', '서구', '석남3동'),
 ('인천광역시', '서구', '아라1동'),
 ('인천광역시', '서구', '청라1동'),
 ('인천광역시', '서구', '청라3동'),
 ('인천광역시', '연수구', '동춘1동'),
 ('인천광역시', '연수구', '동춘3동'),
 ('인천광역시', '연수구', '송도1동'),
 ('인천광역시', '연수구', '송도3동'),
 ('인천광역시', '연수구', '송도4동'),
 ('인천광역시', '연수구', '송도5동'),
 ('인천광역시', '연수구', '연수1동'),
 ('인천광역시', '연수구', '연수2동'),
 ('인천광역시', '연수구', '옥련1동'),
 ('인천광역시', '옹진군', '대청면'),
 ('인천광역시', '옹진군', '대청면소청출장소'),
 ('인천광역시', '옹진군', '덕적면'),
 ('인천광역시', '옹진군', '북도면'),
 ('인천광역시', '옹진군', '북도면장봉출장소'),
 ('인천광역시', '옹진군', '연평면'),
 ('인천광역시', '옹진군', '자월면'),
 ('인천광역시', '옹진군', '자월면이작출장소'),
 ('인천광역시', '중구', '개항동'),
 ('인천광역시', '중구', '도원동'),
 ('인천광역시', '중구', '영종2동'),
 ('인천광역시', '중구', '용유동'),
 ('인천광역시', '중구', '운서2동')}

In [34]:
df_hos_sum = df_hos_sum.rename(columns={
    '시도코드명': '시도명',
    '시군구코드명': '시군구명',
    '행정동': '읍면동명'
})

In [35]:
df_hos_sum=df_hos_sum.drop(columns=('읍면동'))

In [36]:
df_hos_sum = df_hos_sum.drop(columns=(['위도', '경도']))

In [37]:
df_hos_sum = (
    df_hos_sum.groupby(['시도명', '시군구명', '읍면동명'], as_index=False)['과목별 전문의수']
    .sum()
)

In [38]:
df_hos_sum

       시도명     시군구명  읍면동명  과목별 전문의수
0      경기도  고양시 덕양구   고양동         0
1      경기도  고양시 덕양구   관산동         2
2      경기도  고양시 덕양구   능곡동         1
3      경기도  고양시 덕양구   대덕동         2
4      경기도  고양시 덕양구  삼송1동         1
..     ...      ...   ...       ...
429  인천광역시       중구   연안동         0
430  인천광역시       중구  영종1동         3
431  인천광역시       중구   영종동         0
432  인천광역시       중구  운서1동         2
433  인천광역시       중구   율목동         1

[434 rows x 4 columns]

In [39]:
df_in

       시도명 시군구명   읍면동명  아동인구수
0    서울특별시  종로구  청운효자동   1258
1    서울특별시  종로구    사직동    858
2    서울특별시  종로구    삼청동    181
3    서울특별시  종로구    부암동    881
4    서울특별시  종로구    평창동   2039
..     ...  ...    ...    ...
858    경기도  김포시    풍무동   9962
859    경기도  김포시    장기동   8419
860    경기도  김포시    구래동   8787
861    경기도  김포시    마산동   7726
862    경기도  김포시    운양동  10621

[863 rows x 4 columns]

In [40]:
df_final = pd.merge(
    df_in,
    df_hos_sum,
    on=['시도명', '시군구명', '읍면동명'],
    how='left'
)

In [41]:
df_final

       시도명 시군구명   읍면동명  아동인구수  과목별 전문의수
0    서울특별시  종로구  청운효자동   1258       1.0
1    서울특별시  종로구    사직동    858       2.0
2    서울특별시  종로구    삼청동    181       NaN
3    서울특별시  종로구    부암동    881       0.0
4    서울특별시  종로구    평창동   2039       0.0
..     ...  ...    ...    ...       ...
858    경기도  김포시    풍무동   9962      15.0
859    경기도  김포시    장기동   8419      15.0
860    경기도  김포시    구래동   8787      15.0
861    경기도  김포시    마산동   7726       1.0
862    경기도  김포시    운양동  10621       7.0

[863 rows x 5 columns]

In [42]:
df_final['과목별 전문의수'] = df_final['과목별 전문의수'].fillna(0)

In [43]:
df_final['과목별 전문의수'].isna().sum()

np.int64(0)

In [44]:
df_final

       시도명 시군구명   읍면동명  아동인구수  과목별 전문의수
0    서울특별시  종로구  청운효자동   1258       1.0
1    서울특별시  종로구    사직동    858       2.0
2    서울특별시  종로구    삼청동    181       0.0
3    서울특별시  종로구    부암동    881       0.0
4    서울특별시  종로구    평창동   2039       0.0
..     ...  ...    ...    ...       ...
858    경기도  김포시    풍무동   9962      15.0
859    경기도  김포시    장기동   8419      15.0
860    경기도  김포시    구래동   8787      15.0
861    경기도  김포시    마산동   7726       1.0
862    경기도  김포시    운양동  10621       7.0

[863 rows x 5 columns]

In [45]:
df_final['소아청소년과_접근성'] = (
    df_final['과목별 전문의수'] / df_final['아동인구수'] * 1000
)

In [46]:
min_val = df_final['소아청소년과_접근성'].min()
max_val = df_final['소아청소년과_접근성'].max()

df_final['소아청소년과_정규화'] = (
    (df_final['소아청소년과_접근성'] - min_val) /
    (max_val - min_val)
)

In [47]:
df_final['소아청소년과_가중치점수'] = df_final['소아청소년과_정규화'] * 0.1275

In [49]:
df_final.to_excel('[건강]소아과.xlsx')

In [50]:
df_final

       시도명 시군구명   읍면동명  아동인구수  과목별 전문의수  소아청소년과_접근성  소아청소년과_정규화  소아청소년과_가중치점수
0    서울특별시  종로구  청운효자동   1258       1.0    0.794913    0.030154      0.003845
1    서울특별시  종로구    사직동    858       2.0    2.331002    0.088423      0.011274
2    서울특별시  종로구    삼청동    181       0.0    0.000000    0.000000      0.000000
3    서울특별시  종로구    부암동    881       0.0    0.000000    0.000000      0.000000
4    서울특별시  종로구    평창동   2039       0.0    0.000000    0.000000      0.000000
..     ...  ...    ...    ...       ...         ...         ...           ...
858    경기도  김포시    풍무동   9962      15.0    1.505722    0.057117      0.007282
859    경기도  김포시    장기동   8419      15.0    1.781684    0.067585      0.008617
860    경기도  김포시    구래동   8787      15.0    1.707067    0.064755      0.008256
861    경기도  김포시    마산동   7726       1.0    0.129433    0.004910      0.000626
862    경기도  김포시    운양동  10621       7.0    0.659072    0.025001      0.003188

[863 rows x 8 columns]

In [53]:
df_bok = pd.read_csv('[건강]예방접종_동별지수.csv')

In [52]:
df_bok['최종'] = df_bok['예방접종_가중치'] + df_final['소아청소년과_가중치점수']

In [55]:
df_bok

       시도명 시군구명    행정동    예방접종_원값  예방접종_정규화  예방접종_가중치
0    서울특별시  종로구  청운효자동  81.433333  0.000000   0.00000
1    서울특별시  종로구    사직동  81.433333  0.000000   0.00000
2    서울특별시  종로구    삼청동  81.433333  0.000000   0.00000
3    서울특별시  종로구    부암동  81.433333  0.000000   0.00000
4    서울특별시  종로구    평창동  81.433333  0.000000   0.00000
..     ...  ...    ...        ...       ...       ...
858    경기도  김포시    풍무동  91.633333  0.833787   0.08046
859    경기도  김포시    장기동  91.633333  0.833787   0.08046
860    경기도  김포시    구래동  91.633333  0.833787   0.08046
861    경기도  김포시    마산동  91.633333  0.833787   0.08046
862    경기도  김포시    운양동  91.633333  0.833787   0.08046

[863 rows x 6 columns]

In [56]:
df_final

       시도명 시군구명   읍면동명  아동인구수  과목별 전문의수  소아청소년과_접근성  소아청소년과_정규화  소아청소년과_가중치점수
0    서울특별시  종로구  청운효자동   1258       1.0    0.794913    0.030154      0.003845
1    서울특별시  종로구    사직동    858       2.0    2.331002    0.088423      0.011274
2    서울특별시  종로구    삼청동    181       0.0    0.000000    0.000000      0.000000
3    서울특별시  종로구    부암동    881       0.0    0.000000    0.000000      0.000000
4    서울특별시  종로구    평창동   2039       0.0    0.000000    0.000000      0.000000
..     ...  ...    ...    ...       ...         ...         ...           ...
858    경기도  김포시    풍무동   9962      15.0    1.505722    0.057117      0.007282
859    경기도  김포시    장기동   8419      15.0    1.781684    0.067585      0.008617
860    경기도  김포시    구래동   8787      15.0    1.707067    0.064755      0.008256
861    경기도  김포시    마산동   7726       1.0    0.129433    0.004910      0.000626
862    경기도  김포시    운양동  10621       7.0    0.659072    0.025001      0.003188

[863 rows x 8 columns]

In [265]:
df_final = df_final.rename(columns={'읍면동명': '행정동'}).copy()

In [267]:
df_merge_score = pd.merge(
    df_bok,
    df_final[['시도명', '시군구명', '행정동', '소아청소년과_가중치점수']],
    on=['시도명', '시군구명', '행정동'],
    how='left'
)

In [268]:
df_merge_score

       시도명 시군구명    행정동    예방접종_원값  예방접종_정규화  예방접종_가중치  소아청소년과_가중치점수
0    서울특별시  종로구  청운효자동  81.433333  0.000000   0.00000      0.003845
1    서울특별시  종로구    사직동  81.433333  0.000000   0.00000      0.011274
2    서울특별시  종로구    삼청동  81.433333  0.000000   0.00000      0.000000
3    서울특별시  종로구    부암동  81.433333  0.000000   0.00000      0.000000
4    서울특별시  종로구    평창동  81.433333  0.000000   0.00000      0.000000
..     ...  ...    ...        ...       ...       ...           ...
858    경기도  김포시    풍무동  91.633333  0.833787   0.08046      0.007282
859    경기도  김포시    장기동  91.633333  0.833787   0.08046      0.008617
860    경기도  김포시    구래동  91.633333  0.833787   0.08046      0.008256
861    경기도  김포시    마산동  91.633333  0.833787   0.08046      0.000626
862    경기도  김포시    운양동  91.633333  0.833787   0.08046      0.003188

[863 rows x 7 columns]

In [269]:
df_merge_score['최종'] = (
    df_merge_score['예방접종_가중치'] +
    df_merge_score['소아청소년과_가중치점수']
)

       시도명 시군구명    행정동    예방접종_원값  예방접종_정규화  예방접종_가중치  소아청소년과_가중치점수        최종
0    서울특별시  종로구  청운효자동  81.433333  0.000000   0.00000      0.003845  0.003845
1    서울특별시  종로구    사직동  81.433333  0.000000   0.00000      0.011274  0.011274
2    서울특별시  종로구    삼청동  81.433333  0.000000   0.00000      0.000000  0.000000
3    서울특별시  종로구    부암동  81.433333  0.000000   0.00000      0.000000  0.000000
4    서울특별시  종로구    평창동  81.433333  0.000000   0.00000      0.000000  0.000000
..     ...  ...    ...        ...       ...       ...           ...       ...
858    경기도  김포시    풍무동  91.633333  0.833787   0.08046      0.007282  0.087743
859    경기도  김포시    장기동  91.633333  0.833787   0.08046      0.008617  0.089078
860    경기도  김포시    구래동  91.633333  0.833787   0.08046      0.008256  0.088717
861    경기도  김포시    마산동  91.633333  0.833787   0.08046      0.000626  0.081086
862    경기도  김포시    운양동  91.633333  0.833787   0.08046      0.003188  0.083648

[863 rows x 8 columns]

In [271]:
df_merge_score.to_excel('[건강]최종.xlsx')

In [274]:
df_gun = pd.read_excel('drive-download-20260329T122757Z-1-001/[건강]최종_진짜마지막.xlsx')
df_go = pd.read_csv('drive-download-20260329T122757Z-1-001/[교육] 가중치합산.csv')
df_bok = pd.read_excel('drive-download-20260329T122757Z-1-001/[복지]문화시설최종.xlsx')
df_ana = pd.read_excel('drive-download-20260329T122757Z-1-001/[안전]가중치합산.xlsx')
df_hawn = pd.read_csv('drive-download-20260329T122757Z-1-001/[환경] 가중치합산.csv', encoding='cp949')

In [320]:
df_chong = pd.read_excel('[최종] 동별전체합계 - 순위 포함.xlsx')

In [290]:
df_gun = df_gun[['시군구', '행정동', '최종']]
df_gun = df_gun.rename(columns={'최종':'건강_지수'})

In [298]:
df_gun

     시군구    행정동     건강_지수
0    종로구  청운효자동  0.003845
1    종로구    사직동  0.011274
2    종로구    삼청동  0.000000
3    종로구    부암동  0.000000
4    종로구    평창동  0.000000
..   ...    ...       ...
858  김포시    풍무동  0.087743
859  김포시    장기동  0.089078
860  김포시    구래동  0.088717
861  김포시    마산동  0.081086
862  김포시    운양동  0.083648

[863 rows x 3 columns]

In [293]:
df_go = df_go[['시군구', '행정동', '가중치_합산']]
df_go = df_go.rename(columns={'가중치_합산':'교육_지수'})

In [329]:
df_go

      시군구       행정동     교육_지수
0     송파구      가락1동  0.040232
1     송파구      가락2동  0.041110
2     송파구      가락본동  0.035820
3     구로구      가리봉동  0.027878
4     금천구       가산동  0.034550
..    ...       ...       ...
854   하남시       춘궁동  0.000000
855   광명시       학온동  0.010832
856   강화군       화도면  0.013273
857  남양주시  화도읍남부출장소  0.000000
858  남양주시  화도읍동부출장소  0.000000

[859 rows x 3 columns]

In [ ]:
df_go = df_go[['시군구', '행정동', '가중치_합산']]
df_go = df_go.rename(columns={'가중치_합산':'교육_지수'})

In [318]:
df_hawn.head()

     시도명  시군구    행정동  PM10_평균  PM10_정규화  미세먼지_지수값  여가환경_가중치      환경지수
0  서울특별시  종로구  청운효자동    38.69  0.673167  0.068596  0.002320  0.070916
1  서울특별시  종로구    사직동    38.69  0.673167  0.068596  0.003845  0.072441
2  서울특별시  종로구    삼청동    38.69  0.673167  0.068596  0.027691  0.096287
3  서울특별시  종로구    부암동    38.69  0.673167  0.068596  0.000017  0.068613
4  서울특별시  종로구    평창동    38.69  0.673167  0.068596  0.000208  0.068804

In [330]:
df_f = df_chong[['시군구', '행정동', '복지_지수', '안전영역점수.1', '교육_지수', '환경지수']]

In [337]:
df_chong

,시군구,행정동,복지_지수,교육_지수,안전영역점수.1,환경지수,건강_인프라지수,최종지수,100점 환산,순위
0,연수구,송도2동,0.000993,0.053170,0.261407,0.124219,0.485839,0.925629,92.562897,1
1,연수구,송도1동,0.000510,0.060113,0.261407,0.087210,0.490693,0.899933,89.993283,2
2,동구,송림2동,0.080400,0.090221,0.177781,0.083398,0.456403,0.888203,88.820283,3
3,서구,가좌2동,0.004758,0.036773,0.250350,0.055803,0.540294,0.887977,88.797731,4
4,연수구,동춘2동,0.000564,0.047372,0.261407,0.072056,0.505201,0.886600,88.660022,5
...,...,...,...,...,...,...,...,...,...,...
858,종로구,무악동,0.004044,0.033293,0.071460,0.068713,0.002049,0.179559,17.955884,859
859,종로구,창신3동,0.009584,0.027326,0.071460,0.068661,0.000000,0.177031,17.703110,860
860,종로구,숭인1동,0.000000,0.005348,0.071460,0.069593,0.011768,0.158168,15.816777,861
861,종로구,평창동,0.003279,0.001072,0.071460,0.068804,0.000000,0.144615,14.461498,862
862,종로구,숭인2동,0.000903,0.003465,0.071460,0.068698,0.000000,0.144525,14.452500,863

In [331]:
df_f

     시군구   행정동     복지_지수  안전영역점수.1     교육_지수      환경지수
0    연수구  송도2동  0.000993  0.261407  0.053170  0.124219
1    연수구  송도1동  0.000510  0.261407  0.060113  0.087210
2     동구  송림2동  0.080400  0.177781  0.090221  0.083398
3     서구  가좌2동  0.004758  0.250350  0.036773  0.055803
4    연수구  동춘2동  0.000564  0.261407  0.047372  0.072056
..   ...   ...       ...       ...       ...       ...
858  종로구   무악동  0.004044  0.071460  0.033293  0.068713
859  종로구  창신3동  0.009584  0.071460  0.027326  0.068661
860  종로구  숭인1동  0.000000  0.071460  0.005348  0.069593
861  종로구   평창동  0.003279  0.071460  0.001072  0.068804
862  종로구  숭인2동  0.000903  0.071460  0.003465  0.068698

[863 rows x 6 columns]

In [332]:
df_f = df_f.merge(
    df_gun[['시군구', '행정동', '건강_지수']],
    on=['시군구', '행정동'],
    how='left'
)

     시군구   행정동     복지_지수  안전영역점수.1     교육_지수      환경지수     건강_지수        총점
0    연수구  송도2동  0.000993  0.261407  0.053170  0.124219  0.109911  0.549702
1    연수구  송도1동  0.000510  0.261407  0.060113  0.087210  0.093345  0.502585
2     동구  송림2동  0.080400  0.177781  0.090221  0.083398  0.088086  0.519885
3     서구  가좌2동  0.004758  0.250350  0.036773  0.055803  0.096500  0.444184
4    연수구  동춘2동  0.000564  0.261407  0.047372  0.072056  0.108181  0.489580
..   ...   ...       ...       ...       ...       ...       ...       ...
858  종로구   무악동  0.004044  0.071460  0.033293  0.068713  0.004231  0.181741
859  종로구  창신3동  0.009584  0.071460  0.027326  0.068661  0.000000  0.177031
860  종로구  숭인1동  0.000000  0.071460  0.005348  0.069593  0.000000  0.146400
861  종로구   평창동  0.003279  0.071460  0.001072  0.068804  0.000000  0.144615
862  종로구  숭인2동  0.000903  0.071460  0.003465  0.068698  0.011353  0.155878

[863 rows x 8 columns]

In [334]:
df_f['총점'] = df_f[
    ['복지_지수', '안전영역점수.1', '교육_지수', '환경지수', '건강_지수']
].sum(axis=1)

In [339]:
df_f = df_f.rename(columns={'안전영역점수.1':'안전_지수', '환경지수':'환경_지수'})

In [340]:
df_f

     시군구   행정동     복지_지수     안전_지수     교육_지수     환경_지수     건강_지수        총점
0    연수구  송도2동  0.000993  0.261407  0.053170  0.124219  0.109911  0.549702
1    연수구  송도1동  0.000510  0.261407  0.060113  0.087210  0.093345  0.502585
2     동구  송림2동  0.080400  0.177781  0.090221  0.083398  0.088086  0.519885
3     서구  가좌2동  0.004758  0.250350  0.036773  0.055803  0.096500  0.444184
4    연수구  동춘2동  0.000564  0.261407  0.047372  0.072056  0.108181  0.489580
..   ...   ...       ...       ...       ...       ...       ...       ...
858  종로구   무악동  0.004044  0.071460  0.033293  0.068713  0.004231  0.181741
859  종로구  창신3동  0.009584  0.071460  0.027326  0.068661  0.000000  0.177031
860  종로구  숭인1동  0.000000  0.071460  0.005348  0.069593  0.000000  0.146400
861  종로구   평창동  0.003279  0.071460  0.001072  0.068804  0.000000  0.144615
862  종로구  숭인2동  0.000903  0.071460  0.003465  0.068698  0.011353  0.155878

[863 rows x 8 columns]

In [343]:
min_val = df_f['총점'].min()
max_val = df_f['총점'].max()

df_f['100점환산'] = df_f['총점']* 100

In [12]:
df.to_excel('[최종]진짜최종_final.xlsx')

In [1]:
import pandas as pd
df = pd.read_excel('[최종]진짜최종_final.xlsx')
df

,Unnamed: 0.1,Unnamed: 0,시군구,행정동,복지_지수,안전_지수,교육_지수,환경_지수,건강_지수,총점,100점환산
0,0,0,연수구,송도2동,0.000993,0.261407,0.053170,0.124219,0.109911,0.549702,86.892974
1,1,1,연수구,송도1동,0.000510,0.261407,0.060113,0.087210,0.093345,0.502585,80.539463
2,2,2,동구,송림2동,0.080400,0.177781,0.090221,0.083398,0.088086,0.519885,83.108930
3,3,3,서구,가좌2동,0.004758,0.250350,0.036773,0.055803,0.096500,0.444184,69.769589
4,4,4,연수구,동춘2동,0.000564,0.261407,0.047372,0.072056,0.108181,0.489580,78.419938
...,...,...,...,...,...,...,...,...,...,...,...
858,858,858,종로구,무악동,0.004044,0.071460,0.033293,0.068713,0.004231,0.181741,14.330923
859,859,859,종로구,창신3동,0.009584,0.071460,0.027326,0.068661,0.000000,0.177031,13.762285
860,860,860,종로구,숭인1동,0.000000,0.071460,0.005348,0.069593,0.000000,0.146400,10.512950
861,861,861,종로구,평창동,0.003279,0.071460,0.001072,0.068804,0.000000,0.144615,10.346193
862,862,862,종로구,숭인2동,0.000903,0.071460,0.003465,0.068698,0.011353,0.155878,11.438586

In [4]:
df = df.rename(columns={'100점환산':'100점 환산'})

In [9]:
import numpy as np

df['100점환산'] = 100 / (1 + np.exp(-10*(df['총점'] - df['총점'].mean())))

In [5]:
df

,Unnamed: 0.1,Unnamed: 0,시군구,행정동,복지_지수,안전_지수,교육_지수,환경_지수,건강_지수,총점,100점 환산
0,0,0,연수구,송도2동,0.000993,0.261407,0.053170,0.124219,0.109911,0.549702,86.892974
1,1,1,연수구,송도1동,0.000510,0.261407,0.060113,0.087210,0.093345,0.502585,80.539463
2,2,2,동구,송림2동,0.080400,0.177781,0.090221,0.083398,0.088086,0.519885,83.108930
3,3,3,서구,가좌2동,0.004758,0.250350,0.036773,0.055803,0.096500,0.444184,69.769589
4,4,4,연수구,동춘2동,0.000564,0.261407,0.047372,0.072056,0.108181,0.489580,78.419938
...,...,...,...,...,...,...,...,...,...,...,...
858,858,858,종로구,무악동,0.004044,0.071460,0.033293,0.068713,0.004231,0.181741,14.330923
859,859,859,종로구,창신3동,0.009584,0.071460,0.027326,0.068661,0.000000,0.177031,13.762285
860,860,860,종로구,숭인1동,0.000000,0.071460,0.005348,0.069593,0.000000,0.146400,10.512950
861,861,861,종로구,평창동,0.003279,0.071460,0.001072,0.068804,0.000000,0.144615,10.346193
862,862,862,종로구,숭인2동,0.000903,0.071460,0.003465,0.068698,0.011353,0.155878,11.438586

In [15]:
df[df['총점'].isna()]

Empty DataFrame
Columns: [Unnamed: 0, 시군구, 행정동, 복지_지수, 안전_지수, 교육_지수, 환경_지수, 건강_지수, 총점, 100점환산]
Index: []

In [7]:
df.to_excel('[최종]진짜최종_final.xlsx')

In [57]:
import pandas as pd

df_vac = pd.read_csv("[건강]예방접종_동별지수.csv")
df_ped = pd.read_excel("[건강]소아과.xlsx")

df_ped = df_ped.drop(columns=["Unnamed: 0"], errors="ignore")
df_ped = df_ped.rename(columns={"읍면동명": "행정동"})

In [58]:
# 같은 시도 내에서 행정동이 하나의 시군구에만 속하는 경우만 남김
dong_map = (
    df_ped.groupby(["시도명", "행정동"])["시군구명"]
    .nunique()
    .reset_index(name="시군구개수")
)

# 유일한 동만 추출
unique_dong = dong_map[dong_map["시군구개수"] == 1][["시도명", "행정동"]]

# 유일한 동에 대한 시군구명 매핑표 만들기
unique_map = df_ped.merge(unique_dong, on=["시도명", "행정동"], how="inner")
unique_map = unique_map[["시도명", "행정동", "시군구명"]].drop_duplicates()

In [59]:
df_vac_fix = df_vac.merge(
    unique_map,
    on=["시도명", "행정동"],
    how="left",
    suffixes=("", "_보정")
)

# 보정값이 있으면 그걸 쓰고, 없으면 원래 값 유지
df_vac_fix["시군구명"] = df_vac_fix["시군구명_보정"].fillna(df_vac_fix["시군구명"])
df_vac_fix = df_vac_fix.drop(columns=["시군구명_보정"])

In [60]:
df_vac_use = df_vac_fix[["시도명", "시군구명", "행정동", "예방접종_가중치"]].copy()
df_ped_use = df_ped[["시도명", "시군구명", "행정동", "소아청소년과_가중치점수"]].copy()

df_merge = pd.merge(
    df_vac_use,
    df_ped_use,
    on=["시도명", "시군구명", "행정동"],
    how="left"
)

In [61]:
df_merge["최종"] = (
    df_merge["예방접종_가중치"].fillna(0)
    + df_merge["소아청소년과_가중치점수"].fillna(0)
)

In [62]:
df_merge

       시도명 시군구명    행정동  예방접종_가중치  소아청소년과_가중치점수        최종
0    서울특별시  종로구  청운효자동   0.00000      0.003845  0.003845
1    서울특별시  종로구    사직동   0.00000      0.011274  0.011274
2    서울특별시  종로구    삼청동   0.00000      0.000000  0.000000
3    서울특별시  종로구    부암동   0.00000      0.000000  0.000000
4    서울특별시  종로구    평창동   0.00000      0.000000  0.000000
..     ...  ...    ...       ...           ...       ...
858    경기도  김포시    풍무동   0.08046      0.007282  0.087743
859    경기도  김포시    장기동   0.08046      0.008617  0.089078
860    경기도  김포시    구래동   0.08046      0.008256  0.088717
861    경기도  김포시    마산동   0.08046      0.000626  0.081086
862    경기도  김포시    운양동   0.08046      0.003188  0.083648

[863 rows x 6 columns]

In [63]:
check_null = df_merge[df_merge["소아청소년과_가중치점수"].isna()]
print(check_null[["시도명", "시군구명", "행정동"]].drop_duplicates())
print("매칭 안 된 개수:", len(check_null))

       시도명  시군구명  행정동
198  서울특별시  서대문구  홍1동
199  서울특별시  서대문구  홍3동
200  서울특별시  서대문구  홍2동
602    경기도   성남시  위례동
603    경기도   성남시  신촌동
607    경기도   성남시  중앙동
635    경기도   성남시  금곡동
668    경기도   안양시  신촌동
817    경기도   용인시  중앙동
매칭 안 된 개수: 9

In [64]:
unmatched = df_merge[df_merge["소아청소년과_가중치점수"].isna()][["시도명", "시군구명", "행정동"]].drop_duplicates()
print(unmatched)

       시도명  시군구명  행정동
198  서울특별시  서대문구  홍1동
199  서울특별시  서대문구  홍3동
200  서울특별시  서대문구  홍2동
602    경기도   성남시  위례동
603    경기도   성남시  신촌동
607    경기도   성남시  중앙동
635    경기도   성남시  금곡동
668    경기도   안양시  신촌동
817    경기도   용인시  중앙동

In [73]:
a = pd.read_csv('[건강]예방접종_동별지수.csv', encoding='cp949', sep='\t')
a

,시도명,시군구명,행정동,예방접종_원값,예방접종_정규화,예방접종_가중치,시도명.1,시군구명.1,행정동.1,아동인구수,과목별 전문의수,소아청소년과_접근성,소아청소년과_정규화,소아청소년과_가중치점수
0,서울특별시,종로구,청운효자동,81.433333,0.000000,0.00000,서울특별시,종로구,청운효자동,1258,1,0.794913,0.030154,0.003845
1,서울특별시,종로구,사직동,81.433333,0.000000,0.00000,서울특별시,종로구,사직동,858,2,2.331002,0.088423,0.011274
2,서울특별시,종로구,삼청동,81.433333,0.000000,0.00000,서울특별시,종로구,삼청동,181,0,0.000000,0.000000,0.000000
3,서울특별시,종로구,부암동,81.433333,0.000000,0.00000,서울특별시,종로구,부암동,881,0,0.000000,0.000000,0.000000
4,서울특별시,종로구,평창동,81.433333,0.000000,0.00000,서울특별시,종로구,평창동,2039,0,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
858,경기도,김포시,풍무동,91.633333,0.833787,0.08046,경기도,김포시,풍무동,9962,15,1.505722,0.057117,0.007282
859,경기도,김포시,장기동,91.633333,0.833787,0.08046,경기도,김포시,장기동,8419,15,1.781684,0.067585,0.008617
860,경기도,김포시,구래동,91.633333,0.833787,0.08046,경기도,김포시,구래동,8787,15,1.707067,0.064755,0.008256
861,경기도,김포시,마산동,91.633333,0.833787,0.08046,경기도,김포시,마산동,7726,1,0.129433,0.004910,0.000626
862,경기도,김포시,운양동,91.633333,0.833787,0.08046,경기도,김포시,운양동,10621,7,0.659072,0.025001,0.003188

In [74]:
a['합계'] = a['예방접종_가중치'] + a['소아청소년과_가중치점수']

In [76]:
a = a[['시도명.1', '시군구명.1', '행정동.1','합계']]
a = a.rename(columns={'시도명.1':'시도명', '시군구명.1':'시군구', '행정동.1':'행정동'})

In [77]:
a

       시도명  시군구    행정동        합계
0    서울특별시  종로구  청운효자동  0.003845
1    서울특별시  종로구    사직동  0.011274
2    서울특별시  종로구    삼청동  0.000000
3    서울특별시  종로구    부암동  0.000000
4    서울특별시  종로구    평창동  0.000000
..     ...  ...    ...       ...
858    경기도  김포시    풍무동  0.087743
859    경기도  김포시    장기동  0.089078
860    경기도  김포시    구래동  0.088717
861    경기도  김포시    마산동  0.081086
862    경기도  김포시    운양동  0.083648

[863 rows x 4 columns]

In [78]:
b=pd.read_excel('[최종]진짜최종_final.xlsx')
b

,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,시군구,행정동,복지_지수,안전_지수,교육_지수,환경_지수,건강_지수,총점,100점 환산
0,0,0,0,연수구,송도2동,0.000993,0.261407,0.053170,0.124219,0.109911,0.549702,86.892974
1,1,1,1,연수구,송도1동,0.000510,0.261407,0.060113,0.087210,0.093345,0.502585,80.539463
2,2,2,2,동구,송림2동,0.080400,0.177781,0.090221,0.083398,0.088086,0.519885,83.108930
3,3,3,3,서구,가좌2동,0.004758,0.250350,0.036773,0.055803,0.096500,0.444184,69.769589
4,4,4,4,연수구,동춘2동,0.000564,0.261407,0.047372,0.072056,0.108181,0.489580,78.419938
...,...,...,...,...,...,...,...,...,...,...,...,...
858,858,858,858,종로구,무악동,0.004044,0.071460,0.033293,0.068713,0.004231,0.181741,14.330923
859,859,859,859,종로구,창신3동,0.009584,0.071460,0.027326,0.068661,0.000000,0.177031,13.762285
860,860,860,860,종로구,숭인1동,0.000000,0.071460,0.005348,0.069593,0.000000,0.146400,10.512950
861,861,861,861,종로구,평창동,0.003279,0.071460,0.001072,0.068804,0.000000,0.144615,10.346193
862,862,862,862,종로구,숭인2동,0.000903,0.071460,0.003465,0.068698,0.011353,0.155878,11.438586

In [80]:
b = b.drop(columns=['Unnamed: 0.2', 'Unnamed: 0.1', 'Unnamed: 0'])

In [81]:
b

,시군구,행정동,복지_지수,안전_지수,교육_지수,환경_지수,건강_지수,총점,100점 환산
0,연수구,송도2동,0.000993,0.261407,0.053170,0.124219,0.109911,0.549702,86.892974
1,연수구,송도1동,0.000510,0.261407,0.060113,0.087210,0.093345,0.502585,80.539463
2,동구,송림2동,0.080400,0.177781,0.090221,0.083398,0.088086,0.519885,83.108930
3,서구,가좌2동,0.004758,0.250350,0.036773,0.055803,0.096500,0.444184,69.769589
4,연수구,동춘2동,0.000564,0.261407,0.047372,0.072056,0.108181,0.489580,78.419938
...,...,...,...,...,...,...,...,...,...
858,종로구,무악동,0.004044,0.071460,0.033293,0.068713,0.004231,0.181741,14.330923
859,종로구,창신3동,0.009584,0.071460,0.027326,0.068661,0.000000,0.177031,13.762285
860,종로구,숭인1동,0.000000,0.071460,0.005348,0.069593,0.000000,0.146400,10.512950
861,종로구,평창동,0.003279,0.071460,0.001072,0.068804,0.000000,0.144615,10.346193
862,종로구,숭인2동,0.000903,0.071460,0.003465,0.068698,0.011353,0.155878,11.438586

In [84]:
# 1. merge
df = b.merge(
    a[['시군구', '행정동', '합계']],
    on=['시군구', '행정동'],
    how='left'
)

In [86]:
df.tail(30)

,시군구,행정동,복지_지수,안전_지수,교육_지수,환경_지수,건강_지수,총점,100점 환산,합계
833,강화군,양도면,0.000000,0.125852,0.016737,0.076956,0.033920,0.253465,25.524372,0.033920
834,강화군,송해면,0.002922,0.125852,0.013478,0.076956,0.033920,0.253128,25.460323,0.033920
835,용산구,서빙고동,0.000763,0.150205,0.032579,0.049669,0.030501,0.263718,27.521784,0.030501
836,용산구,원효로2동,0.000695,0.150205,0.029970,0.049124,0.034019,0.264012,27.580451,0.034019
837,용산구,원효로1동,0.000545,0.150205,0.026722,0.049241,0.036128,0.262842,27.347478,0.036128
838,용산구,이태원2동,0.000000,0.150205,0.025407,0.049179,0.030501,0.255292,25.873328,0.030501
839,강화군,양사면,0.000000,0.125852,0.007722,0.076956,0.033920,0.244450,23.848717,0.033920
840,용산구,남영동,0.019553,0.150205,0.008022,0.049191,0.030501,0.257472,26.293502,0.030501
841,강화군,교동면,0.000000,0.125852,0.006296,0.076956,0.033920,0.243024,23.590853,0.033920
842,강화군,서도면,0.000000,0.125852,0.002340,0.076956,0.033920,0.239068,22.885140,0.033920
843,강화군,서도면볼음출장소,0.000000,0.125852,0.000000,0.076956,0.033920,0.236728,22.474827,0.033920
844,용산구,이태원1동,0.001590,0.150205,0.006589,0.049149,0.044049,0.251582,25.168097,0.044049
845,용산구,이촌2동,0.000000,0.150205,0.003465,0.049107,0.030501,0.233278,21.879498,0.030501
846,안양시 동안구,비산2동,0.000000,0.234837,0.044148,0.000025,NaN,0.279010,30.674465,0.123232
847,종로구,삼청동,0.044200,0.071460,0.034881,0.096287,0.000000,0.246828,24.283297,0.000000
848,종로구,종로1.2.3.4가동,0.020952,0.071460,0.058787,0.078202,0.015354,0.244755,23.904189,0.015354
849,종로구,창신2동,0.061214,0.071460,0.006308,0.068607,0.000000,0.207589,17.805272,0.000000
850,종로구,종로5.6가동,0.037236,0.071460,0.037254,0.068936,0.000000,0.214886,18.898405,0.000000
851,종로구,교남동,0.001968,0.071460,0.034750,0.068810,0.008108,0.185095,14.747621,0.008108
852,종로구,혜화동,0.002360,0.071460,0.031314,0.070244,0.004064,0.179442,14.050870,0.004064
853,종로구,가회동,0.015488,0.071460,0.044219,0.068941,0.000000,0.200109,16.736744,0.000000
854,종로구,창신1동,0.027568,0.071460,0.031655,0.068596,0.000000,0.199278,16.621339,0.000000
855,종로구,사직동,0.012499,0.071460,0.035307,0.072441,0.011274,0.202980,17.140787,0.011274
856,종로구,청운효자동,0.003432,0.071460,0.035358,0.070916,0.003845,0.185010,14.736878,0.003845
857,종로구,부암동,0.006252,0.071460,0.036287,0.068613,0.000000,0.182612,14.438150,0.000000
858,종로구,무악동,0.004044,0.071460,0.033293,0.068713,0.004231,0.181741,14.330923,0.004231
859,종로구,창신3동,0.009584,0.071460,0.027326,0.068661,0.000000,0.177031,13.762285,0.000000
860,종로구,숭인1동,0.000000,0.071460,0.005348,0.069593,0.000000,0.146400,10.512950,0.000000
861,종로구,평창동,0.003279,0.071460,0.001072,0.068804,0.000000,0.144615,10.346193,0.000000
862,종로구,숭인2동,0.000903,0.071460,0.003465,0.068698,0.011353,0.155878,11.438586,0.011353

In [87]:

# 2. 건강_지수 덮어쓰기
df['건강_지수'] = df['합계']

# 3. 필요없는 컬럼 제거
df = df.drop(columns=['합계'])

In [89]:
df['총점'] = df[['복지_지수', '안전_지수', '교육_지수', '환경_지수', '건강_지수']].sum(axis=1)

In [90]:
df

,시군구,행정동,복지_지수,안전_지수,교육_지수,환경_지수,건강_지수,총점,100점 환산
0,연수구,송도2동,0.000993,0.261407,0.053170,0.124219,0.109911,0.549702,86.892974
1,연수구,송도1동,0.000510,0.261407,0.060113,0.087210,0.093345,0.502585,80.539463
2,동구,송림2동,0.080400,0.177781,0.090221,0.083398,0.088086,0.519885,83.108930
3,서구,가좌2동,0.004758,0.250350,0.036773,0.055803,0.096500,0.444184,69.769589
4,연수구,동춘2동,0.000564,0.261407,0.047372,0.072056,0.108181,0.489580,78.419938
...,...,...,...,...,...,...,...,...,...
858,종로구,무악동,0.004044,0.071460,0.033293,0.068713,0.004231,0.181741,14.330923
859,종로구,창신3동,0.009584,0.071460,0.027326,0.068661,0.000000,0.177031,13.762285
860,종로구,숭인1동,0.000000,0.071460,0.005348,0.069593,0.000000,0.146400,10.512950
861,종로구,평창동,0.003279,0.071460,0.001072,0.068804,0.000000,0.144615,10.346193
862,종로구,숭인2동,0.000903,0.071460,0.003465,0.068698,0.011353,0.155878,11.438586

In [ ]:
import numpy as np

df['100점 환산'] = 100 / (1 + np.exp(-10*(df['총점'] - df['총점'].mean())))

In [109]:
import numpy as np

df['100점 환산'] = 100 / (1 + np.exp(-10*(df['총점'] - df['총점'].mean())))

In [111]:
df.to_excel('[최종]진짜마지막최종_final.xlsx')