In [20]:
import geopandas as gpd

# geojson 불러오기
gdf = gpd.read_file("HangJeongDong_ver20260201.geojson")

In [21]:
gdf

,adm_nm,adm_cd2,sgg,sido,sidonm,sggnm,adm_cd,geometry
0,서울특별시 종로구 사직동,1111053000,11110,11,서울특별시,종로구,11010530,"MULTIPOLYGON (((126.97689 37.57565, 126.97703 ..."
1,서울특별시 종로구 삼청동,1111054000,11110,11,서울특별시,종로구,11010540,"MULTIPOLYGON (((126.98269 37.59507, 126.98337 ..."
2,서울특별시 종로구 부암동,1111055000,11110,11,서울특별시,종로구,11010550,"MULTIPOLYGON (((126.97585 37.59656, 126.97359 ..."
3,서울특별시 종로구 평창동,1111056000,11110,11,서울특별시,종로구,11010560,"MULTIPOLYGON (((126.97507 37.63139, 126.97649 ..."
4,서울특별시 종로구 무악동,1111057000,11110,11,서울특별시,종로구,11010570,"MULTIPOLYGON (((126.96067 37.5808, 126.96281 3..."
...,...,...,...,...,...,...,...,...
3553,인천광역시 서구 검암경서동,2826051500,28260,28,인천광역시,서구,23080510,"MULTIPOLYGON (((126.63275 37.56981, 126.64602 ..."
3554,인천광역시 중구 영종1동,2811062200,28110,28,인천광역시,중구,23010681,"MULTIPOLYGON (((126.55342 37.49647, 126.55456 ..."
3555,인천광역시 중구 영종2동,2811062300,28110,28,인천광역시,중구,23010691,"MULTIPOLYGON (((126.5708 37.48492, 126.56552 3..."
3556,경기도 과천시 갈현동,4129052000,41290,41,경기도,과천시,31110521,"MULTIPOLYGON (((126.97077 37.41631, 126.9737 3..."
3557,경기도 과천시 원문동,4129051500,41290,41,경기도,과천시,31110522,"MULTIPOLYGON (((126.99141 37.41776, 126.98794 ..."

In [22]:

# 1. 서울 + 인천 + 경기 전체
gdf_filtered = gdf[
    gdf["adm_cd"].astype(str).str.startswith(("11", "23", "31"))
]

In [24]:
gdf_filtered.to_file("dong.geojson", driver="GeoJSON", encoding="utf-8")

In [1]:
import geopandas as gpd
import pandas as pd
df_1 = gpd.read_file('dong.geojson')

In [21]:
df_2 = pd.read_csv('경기도행정기관코드.csv', encoding='cp949')

In [6]:
df_1.head()

,adm_nm,adm_cd2,sgg,sido,sidonm,sggnm,adm_cd,geometry
0,서울특별시 종로구 사직동,1111053000,11110,11,서울특별시,종로구,11010530,"MULTIPOLYGON (((126.97689 37.57565, 126.97703 ..."
1,서울특별시 종로구 삼청동,1111054000,11110,11,서울특별시,종로구,11010540,"MULTIPOLYGON (((126.98269 37.59507, 126.98337 ..."
2,서울특별시 종로구 부암동,1111055000,11110,11,서울특별시,종로구,11010550,"MULTIPOLYGON (((126.97585 37.59656, 126.97359 ..."
3,서울특별시 종로구 평창동,1111056000,11110,11,서울특별시,종로구,11010560,"MULTIPOLYGON (((126.97507 37.63139, 126.97649 ..."
4,서울특별시 종로구 무악동,1111057000,11110,11,서울특별시,종로구,11010570,"MULTIPOLYGON (((126.96067 37.5808, 126.96281 3..."

In [65]:
df_2.head()

        행정동코드  시도명     시군구명 읍면동명       법정동코드     동리명      생성일자
0  4100000000  경기도      NaN  NaN  4100000000     경기도  19880423
1  4111000000  경기도      수원시  NaN  4111000000     수원시  19880423
2  4111100000  경기도  수원시 장안구  NaN  4111100000  수원시장안구  19880701
3  4111156000  경기도  수원시 장안구  파장동  4111112900     파장동  20031124
4  4111156000  경기도  수원시 장안구  파장동  4111113100     이목동  20031124

In [23]:
target_cities = [
    "성남", "고양", "부천", "광명", "하남",
    "남양주", "용인", "김포", "구리", "안양"
]

In [24]:

df_gi2 = df_2[df_2['시군구명'].str.contains('|'.join(target_cities), na=False)]

In [25]:
df_gi2 = df_gi2.dropna(subset=['읍면동명'])

In [30]:
df_gi2.head()

         행정동코드  시도명    시군구명  읍면동명       법정동코드  동리명      생성일자
82  4113151000  경기도  성남시수정구  신흥1동  4113110100  신흥동  19890501
83  4113152000  경기도  성남시수정구  신흥2동  4113110100  신흥동  19890501
84  4113153000  경기도  성남시수정구  신흥3동  4113110100  신흥동  19890501
85  4113154000  경기도  성남시수정구  태평1동  4113110200  태평동  19890501
86  4113155000  경기도  성남시수정구  태평2동  4113110200  태평동  19890501

In [76]:
df_1.head()

,adm_nm,adm_cd2,sgg,sido,sidonm,sggnm,adm_cd,geometry,동이름,key
0,서울특별시 종로구 사직동,1111053000,11110,11,서울특별시,종로구,11010530,"MULTIPOLYGON (((126.97689 37.57565, 126.97703 ...",사직동,종로구 사직동
1,서울특별시 종로구 삼청동,1111054000,11110,11,서울특별시,종로구,11010540,"MULTIPOLYGON (((126.98269 37.59507, 126.98337 ...",삼청동,종로구 삼청동
2,서울특별시 종로구 부암동,1111055000,11110,11,서울특별시,종로구,11010550,"MULTIPOLYGON (((126.97585 37.59656, 126.97359 ...",부암동,종로구 부암동
3,서울특별시 종로구 평창동,1111056000,11110,11,서울특별시,종로구,11010560,"MULTIPOLYGON (((126.97507 37.63139, 126.97649 ...",평창동,종로구 평창동
4,서울특별시 종로구 무악동,1111057000,11110,11,서울특별시,종로구,11010570,"MULTIPOLYGON (((126.96067 37.5808, 126.96281 3...",무악동,종로구 무악동

In [27]:
df_gi2['시군구명'] = df_gi2['시군구명'].str.replace(" ", "")

In [14]:
df_1['동이름'] = df_1['adm_nm'].str.split().str[-1]

In [48]:
a = df_gi2[['시군구명','읍면동명']]

In [61]:
a.columns[0]

'시군구명'

In [73]:
df_1['key'] = df_1['sggnm'] + ' ' + df_1['동이름']
df_gi2['key'] = df_gi2['시군구명'] + ' ' + df_gi2['읍면동명']

df_final = df_1[
    (df_1['key'].isin(df_gi2['key'])) |
    (df_1['sido'].isin(['11', '28']))
]

In [77]:
df_final.to_file("fianl.geojson", driver="GeoJSON", encoding="utf-8")

In [6]:
gdf_filtered

,BASE_DATE,ADM_CD,ADM_NM,geometry
0,20250630,11010530,사직동,"POLYGON ((126.97399 37.57823, 126.974 37.57809..."
1,20250630,11010540,삼청동,"POLYGON ((126.97714 37.59768, 126.9773 37.5976..."
2,20250630,11010550,부암동,"POLYGON ((126.96173 37.60714, 126.96182 37.607..."
3,20250630,11010560,평창동,"POLYGON ((126.97508 37.63118, 126.97488 37.630..."
4,20250630,11010570,무악동,"POLYGON ((126.95975 37.58001, 126.96006 37.579..."
...,...,...,...,...
421,20250630,11250730,천호2동,"POLYGON ((127.11633 37.55005, 127.11642 37.550..."
422,20250630,11250740,길동,"POLYGON ((127.14844 37.54544, 127.14843 37.545..."
423,20250630,11250750,강일동,"POLYGON ((127.17669 37.57907, 127.17662 37.579..."
424,20250630,11250760,상일1동,"POLYGON ((127.17387 37.54591, 127.1739 37.5457..."
425,20250630,11250770,상일2동,"POLYGON ((127.18162 37.55837, 127.18162 37.558..."

In [7]:
gdf

,BASE_DATE,ADM_CD,ADM_NM,geometry
0,20250630,11010530,사직동,"POLYGON ((126.97399 37.57823, 126.974 37.57809..."
1,20250630,11010540,삼청동,"POLYGON ((126.97714 37.59768, 126.9773 37.5976..."
2,20250630,11010550,부암동,"POLYGON ((126.96173 37.60714, 126.96182 37.607..."
3,20250630,11010560,평창동,"POLYGON ((126.97508 37.63118, 126.97488 37.630..."
4,20250630,11010570,무악동,"POLYGON ((126.95975 37.58001, 126.96006 37.579..."
...,...,...,...,...
421,20250630,11250730,천호2동,"POLYGON ((127.11633 37.55005, 127.11642 37.550..."
422,20250630,11250740,길동,"POLYGON ((127.14844 37.54544, 127.14843 37.545..."
423,20250630,11250750,강일동,"POLYGON ((127.17669 37.57907, 127.17662 37.579..."
424,20250630,11250760,상일1동,"POLYGON ((127.17387 37.54591, 127.1739 37.5457..."
425,20250630,11250770,상일2동,"POLYGON ((127.18162 37.55837, 127.18162 37.558..."

In [5]:
target_cities = [
    "성남", "고양", "부천", "광명", "하남",
    "남양주", "용인", "김포", "구리", "안양"
]

In [4]:
import pandas as pd
df_gi = pd.read_csv('경기도행정기관코드.csv', encoding='cp949')
df_gi

           행정동코드  시도명     시군구명 읍면동명       법정동코드     동리명      생성일자
0     4100000000  경기도      NaN  NaN  4100000000     경기도  19880423
1     4111000000  경기도      수원시  NaN  4111000000     수원시  19880423
2     4111100000  경기도  수원시 장안구  NaN  4111100000  수원시장안구  19880701
3     4111156000  경기도  수원시 장안구  파장동  4111112900     파장동  20031124
4     4111156000  경기도  수원시 장안구  파장동  4111113100     이목동  20031124
...          ...  ...      ...  ...         ...     ...       ...
2491  4183041000  경기도      양평군  개군면  4183041024     석장리  19880423
2492  4183041000  경기도      양평군  개군면  4183041023     앙덕리  19880423
2493  4183041000  경기도      양평군  개군면  4183041022     구미리  19880423
2494  4183041000  경기도      양평군  개군면  4183041021    하자포리  19880423
2495  4183041000  경기도      양평군  개군면  4183041027      부리  19880423

[2496 rows x 7 columns]

In [6]:

df_gi2 = df_gi[df_gi['시군구명'].str.contains('|'.join(target_cities), na=False)]

In [8]:
df_gi2 = df_gi2.dropna(subset=['읍면동명'])

In [9]:
df_gi2

           행정동코드  시도명     시군구명  읍면동명       법정동코드  동리명      생성일자
82    4113151000  경기도  성남시 수정구  신흥1동  4113110100  신흥동  19890501
83    4113152000  경기도  성남시 수정구  신흥2동  4113110100  신흥동  19890501
84    4113153000  경기도  성남시 수정구  신흥3동  4113110100  신흥동  19890501
85    4113154000  경기도  성남시 수정구  태평1동  4113110200  태평동  19890501
86    4113155000  경기도  성남시 수정구  태평2동  4113110200  태평동  19890501
...          ...  ...      ...   ...         ...  ...       ...
1563  4157056000  경기도      김포시   장기동  4157010400  장기동  20120924
1564  4157056000  경기도      김포시   장기동  4157010500  감정동  20120924
1565  4157057000  경기도      김포시   구래동  4157010900  구래동  20131028
1566  4157057500  경기도      김포시   마산동  4157010800  마산동  20190923
1567  4157058000  경기도      김포시   운양동  4157010300  운양동  20150202

[571 rows x 7 columns]

In [12]:
df_gi2[df_gi2['읍면동명']=='금곡동']

          행정동코드  시도명     시군구명 읍면동명       법정동코드  동리명      생성일자
145  4113566200  경기도  성남시 분당구  금곡동  4113511100  금곡동  20080922
146  4113566200  경기도  성남시 분당구  금곡동  4113511200  궁내동  20080922
697  4136053000  경기도     남양주시  금곡동  4136010300  금곡동  19950101

In [54]:
dong = df_gi2['읍면동명'].unique()

gdf_filtered = gdf_seoul[
    (gdf_seoul["ADM_CD"].astype(str).str.startswith(("11", "23"))) |
    (gdf_seoul["ADM_NM"].isin(dong))
]

In [56]:
gdf_filtered.to_file('final_edge.geojson', driver="GeoJSON", encoding="utf-8")

In [ ]:
import pandas as pd
import folium
from math import radians, sin, cos, sqrt, atan2

# 데이터
df_mart = pd.DataFrame({
    '마트명': ['마트A', '마트B', '마트C', '마트D'],
    '위도': [37.5660, 37.5700, 37.5600, 37.5900],
    '경도': [126.9780, 126.9900, 126.9750, 127.0300]
})

# 거리 함수
def haversine(lat1, lon1, lat2, lon2):
    R = 6371000
    lat1, lon1, lat2, lon2 = map(radians, [lat1, lon1, lat2, lon2])

    dlat = lat2 - lat1
    dlon = lon2 - lon1

    a = sin(dlat / 2)**2 + cos(lat1) * cos(lat2) * sin(dlon / 2)**2
    c = 2 * atan2(sqrt(a), sqrt(1 - a))

    return R * c

# 👉 클릭 좌표 (여기만 바꾸면 됨)
click_lat = 37.5665
click_lng = 126.9780

# 거리 계산
df_mart['거리(m)'] = df_mart.apply(
    lambda row: haversine(click_lat, click_lng, row['위도'], row['경도']),
    axis=1
)

df_1km = df_mart[df_mart['거리(m)'] <= 1000]

print("1km 내 마트 수:", len(df_1km))

# 지도 생성
m = folium.Map(location=[click_lat, click_lng], zoom_start=14)

# 기준 위치
folium.Marker(
    [click_lat, click_lng],
    popup='선택 위치'
).add_to(m)

# 1km 원
folium.Circle(
    [click_lat, click_lng],
    radius=1000,
    color='blue',
    fill=True,
    fill_opacity=0.2
).add_to(m)

# 마트 표시
for _, row in df_1km.iterrows():
    folium.Marker(
        [row['위도'], row['경도']],
        popup=f"{row['마트명']} ({row['거리(m)']:.0f}m)"
    ).add_to(m)

m

In [ ]:
import pandas as pd

q = pd.read_csv('final/data_education/어린이집.csv', encoding='cp949')
q

,시도,추출시군구,어린이집명,주소,위도,경도
0,인천광역시,중구,장미어린이집,인천광역시 중구 참외전로174번길 12-1,37.471945,126.634784
1,인천광역시,중구,금산어린이집,인천광역시 중구 백운로351번길 3 (운북동),37.505831,126.519962
2,인천광역시,중구,효성어린이집,인천광역시 중구 백운로 34 (중산동),37.501012,126.552623
3,인천광역시,중구,비둘기어린이집,인천광역시 중구 자유공원서로29번길 3-19,37.476661,126.619777
4,인천광역시,중구,인천신광초등학교어린이집,인천광역시 중구 신흥동3가 인중로 63 인천신광초등학교어린이집,37.464355,126.634530
...,...,...,...,...,...,...
8861,서울특별시,NaN,아기랑놀이랑어린이집,"서울특별시 강동구 명일로 293 505-101(길동, 삼익파크아파트)",NaN,NaN
8862,서울특별시,NaN,구립명일사랑어린이집,서울특별시 강동구 상암로 224 9-106,NaN,NaN
8863,서울특별시,NaN,구립토리어린이집,"서울특별시 강동구 상일로 74 323-102(상일동, 고덕리엔파크아파트 3단지)",NaN,NaN
8864,서울특별시,NaN,새아어린이집,"서울특별시 강동구 아리수로50길 50 119-203(고덕동, 래미안힐스테이트A)",NaN,NaN
8865,서울특별시,NaN,구립강동한별어린이집,서울특별시 강동구 천중로53길 19 1~4층,NaN,NaN

In [ ]:


from math import radians, sin, cos, sqrt, atan2
import pandas as pd
import requests

KAKAO_API_KEY = "YOUR_KAKAO_API_KEY"

def haversine(lat1, lon1, lat2, lon2):
    R = 6371000
    φ1, φ2 = radians(lat1), radians(lat2)
    Δφ = radians(lat2 - lat1)
    Δλ = radians(lon2 - lon1)
    a = sin(Δφ/2)**2 + cos(φ1)*cos(φ2)*sin(Δλ/2)**2
    return R * 2 * atan2(sqrt(a), sqrt(1-a))

def get_coord(address):
    url = "https://dapi.kakao.com/v2/local/search/address.json"
    headers = {"Authorization": f"KakaoAK {KAKAO_API_KEY}"}
    res = requests.get(url, headers=headers, params={"query": address})
    docs = res.json().get("documents", [])
    if docs:
        return float(docs[0]['y']), float(docs[0]['x'])
    return None, None

def get_access_score(my_lat, my_lng, df, lat_col, lng_col, radius):
    df = df.copy()
    df['거리'] = df.apply(
        lambda row: haversine(my_lat, my_lng, row[lat_col], row[lng_col]), axis=1
    )
    df_filtered = df[df['거리'] <= radius]
    if len(df_filtered) == 0:
        return 0
    return (1 / df_filtered['거리']).sum()

def count_within(my_lat, my_lng, df, lat_col, lng_col, radius):
    df = df.copy()
    df['거리'] = df.apply(
        lambda row: haversine(my_lat, my_lng, row[lat_col], row[lng_col]), axis=1
    )
    return int((df['거리'] <= radius).sum())

def normalize(value, v_min, v_max, reverse=False):
    value = max(v_min, min(v_max, value))
    norm = (value - v_min) / (v_max - v_min)
    return round(1 - norm if reverse else norm, 4)

# 정규화 기준값
HOSPITAL_MAX = 0.03  # 소아과 접근성 최고점
WELFARE_MAX  = 0.01  # 아동센터 접근성 최고점

# 데이터 로드
df_hospital = pd.read_excel('data/(의료)주변소아과.xlsx')
df_welfare  = pd.read_excel('data/(복지)통합아동지원센터.xlsx')

# 주소 입력
address = input("주소를 입력하세요: ")
my_lat, my_lng = get_coord(address)

if my_lat is None:
    print("주소를 찾을 수 없어요!")
else:
    # 소아과 1km
    s_hospital = get_access_score(my_lat, my_lng, df_hospital, '좌표(Y)', '좌표(X)', 2000)
    n_hospital = count_within(my_lat, my_lng, df_hospital, '좌표(Y)', '좌표(X)', 2000)

    # 아동센터 1km
    s_welfare = get_access_score(my_lat, my_lng, df_welfare, 'Y좌표값', 'X좌표값', 2000)
    n_welfare = count_within(my_lat, my_lng, df_welfare, 'Y좌표값', 'X좌표값', 2000)

    # 정규화
    v1 = normalize(s_hospital, 0, HOSPITAL_MAX)
    v2 = normalize(s_welfare,  0, WELFARE_MAX)

    # 점수 계산
    score = round((v1 + v2) / 2 * 100, 2)

    # 결과 출력
    print(f"\n📍 {address}")
    print(f"   좌표: ({my_lat}, {my_lng})")
    print()
    print(f"소아과 개수 (2km):             {n_hospital}개")
    print(f"소아과 접근성 (2km):           {s_hospital:.4f}  → V1: {v1:.4f}")
    print(f"통합아동지원센터 개수 (2km):   {n_welfare}개")
    print(f"통합아동지원센터 접근성 (2km): {s_welfare:.4f}  → V2: {v2:.4f}")
    print()
    print(f"의료·복지 점수 = (V1+V2)/2 × 100")
    print(f"              = {score}점")

In [1]:
import pandas as pd

In [2]:
df = pd.read_excel('streamlit\의료복지\[복지]_문화시설_총합_최종.xlsx')

In [12]:
df = df[~df['이름'].str.contains('도서관')]

In [13]:
df.to_excel('[복지]_문화시설_총합_최종.xlsx')