In [1]:
import pandas as pd

In [119]:
from pathlib import Path
import pandas as pd

base_path = Path(r"final/in_gi")

# 매매
sale_files = list((base_path / "매매").glob("*.xlsx"))

sale_dfs = []
for file in sale_files:
    print("매매 읽는 중:", file)
    df = pd.read_excel(file)
    sale_dfs.append(df)

df_sale = pd.concat(sale_dfs, ignore_index=True)


# 전월세
rent_files = list((base_path / "전월세").glob("*.xlsx"))

rent_dfs = []
for file in rent_files:
    try:
        print("전월세 읽는 중:", file)
        df = pd.read_excel(file)
        rent_dfs.append(df)
    except Exception as e:
        print("❌ 문제 파일:", file)
        print(e)

df_rent = pd.concat(rent_dfs, ignore_index=True)


print("매매 shape:", df_sale.shape)
print("전월세 shape:", df_rent.shape)

매매 읽는 중: final\in_gi\매매\경기_고양_덕양구_매매.xlsx
매매 읽는 중: final\in_gi\매매\경기_고양_일산동구_매매.xlsx

c:\Users\asia\miniconda3\envs\ai4_p2\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

매매 읽는 중: final\in_gi\매매\경기_고양_일산서구_매매.xlsx

c:\Users\asia\miniconda3\envs\ai4_p2\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

매매 읽는 중: final\in_gi\매매\경기_광명_매매.xlsx

c:\Users\asia\miniconda3\envs\ai4_p2\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

매매 읽는 중: final\in_gi\매매\경기_구리_매매.xlsx

c:\Users\asia\miniconda3\envs\ai4_p2\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

매매 읽는 중: final\in_gi\매매\경기_김포_매매.xlsx

c:\Users\asia\miniconda3\envs\ai4_p2\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

매매 읽는 중: final\in_gi\매매\경기_남양주시_매매.xlsx

c:\Users\asia\miniconda3\envs\ai4_p2\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

매매 읽는 중: final\in_gi\매매\경기_부천_소사구_매매.xlsx

c:\Users\asia\miniconda3\envs\ai4_p2\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

매매 읽는 중: final\in_gi\매매\경기_부천_오정구_매매.xlsx
매매 읽는 중: final\in_gi\매매\경기_부천_원미구_매매.xlsx

c:\Users\asia\miniconda3\envs\ai4_p2\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\asia\miniconda3\envs\ai4_p2\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

매매 읽는 중: final\in_gi\매매\경기_성남_분당구_매매.xlsx

c:\Users\asia\miniconda3\envs\ai4_p2\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

매매 읽는 중: final\in_gi\매매\경기_성남_수정구_매매.xlsx

c:\Users\asia\miniconda3\envs\ai4_p2\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

매매 읽는 중: final\in_gi\매매\경기_성남_중원구_매매.xlsx

c:\Users\asia\miniconda3\envs\ai4_p2\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

매매 읽는 중: final\in_gi\매매\경기_안양_동안구_매매.xlsx

c:\Users\asia\miniconda3\envs\ai4_p2\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

매매 읽는 중: final\in_gi\매매\경기_안양_만안구_매매.xlsx

c:\Users\asia\miniconda3\envs\ai4_p2\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

매매 읽는 중: final\in_gi\매매\경기_용인_기흥구_매매.xlsx

c:\Users\asia\miniconda3\envs\ai4_p2\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

매매 읽는 중: final\in_gi\매매\경기_용인_수지구_매매.xlsx

c:\Users\asia\miniconda3\envs\ai4_p2\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

매매 읽는 중: final\in_gi\매매\경기_용인_처인구_매매.xlsx

c:\Users\asia\miniconda3\envs\ai4_p2\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

매매 읽는 중: final\in_gi\매매\경기_하남_매매.xlsx

c:\Users\asia\miniconda3\envs\ai4_p2\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

전월세 읽는 중: final\in_gi\전월세\경기_고양_덕양구_전월세.xlsx

c:\Users\asia\miniconda3\envs\ai4_p2\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

전월세 읽는 중: final\in_gi\전월세\경기_고양_일산동구_전월세.xlsx

c:\Users\asia\miniconda3\envs\ai4_p2\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

전월세 읽는 중: final\in_gi\전월세\경기_고양_일산서구_전월세.xlsx

c:\Users\asia\miniconda3\envs\ai4_p2\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

전월세 읽는 중: final\in_gi\전월세\경기_광명_전월세.xlsx

c:\Users\asia\miniconda3\envs\ai4_p2\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

전월세 읽는 중: final\in_gi\전월세\경기_구리_전월세.xlsx

c:\Users\asia\miniconda3\envs\ai4_p2\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

전월세 읽는 중: final\in_gi\전월세\경기_김포_전월세.xlsx

c:\Users\asia\miniconda3\envs\ai4_p2\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

전월세 읽는 중: final\in_gi\전월세\경기_남양주_전월세.xlsx

c:\Users\asia\miniconda3\envs\ai4_p2\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

전월세 읽는 중: final\in_gi\전월세\경기_부천_소사구_전월세.xlsx

c:\Users\asia\miniconda3\envs\ai4_p2\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

전월세 읽는 중: final\in_gi\전월세\경기_부천_오정구_전월세.xlsx

c:\Users\asia\miniconda3\envs\ai4_p2\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

전월세 읽는 중: final\in_gi\전월세\경기_부천_원미구_전월세.xlsx

c:\Users\asia\miniconda3\envs\ai4_p2\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

전월세 읽는 중: final\in_gi\전월세\경기_성남_분당구_전월세.xlsx

c:\Users\asia\miniconda3\envs\ai4_p2\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

전월세 읽는 중: final\in_gi\전월세\경기_성남_수정구_전월세.xlsx

c:\Users\asia\miniconda3\envs\ai4_p2\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

전월세 읽는 중: final\in_gi\전월세\경기_성남_중원구_전월세.xlsx

c:\Users\asia\miniconda3\envs\ai4_p2\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

전월세 읽는 중: final\in_gi\전월세\경기_안양_동안구_전월세.xlsx

c:\Users\asia\miniconda3\envs\ai4_p2\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

전월세 읽는 중: final\in_gi\전월세\경기_안양_만안구_전월세.xlsx

c:\Users\asia\miniconda3\envs\ai4_p2\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

전월세 읽는 중: final\in_gi\전월세\경기_용인_기흥구_전월세.xlsx

c:\Users\asia\miniconda3\envs\ai4_p2\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

전월세 읽는 중: final\in_gi\전월세\경기_용인_수지구_전월세.xlsx

c:\Users\asia\miniconda3\envs\ai4_p2\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

전월세 읽는 중: final\in_gi\전월세\경기_용인_처인구_전월세.xlsx

c:\Users\asia\miniconda3\envs\ai4_p2\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

전월세 읽는 중: final\in_gi\전월세\경기_하남_전월세.xlsx

c:\Users\asia\miniconda3\envs\ai4_p2\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

매매 shape: (77771, 42)
전월세 shape: (173720, 21)

In [ ]:
from pathlib import Path
import pandas as pd

base_path = Path(r"final/in_gi")

# 매매
sale_files = list((base_path / "매매").glob("*.xlsx"))
df_sale = pd.concat([pd.read_excel(file) for file in sale_files], ignore_index=True)

# 전월세
rent_files = list((base_path / "전월세").glob("*.xlsx"))
df_rent = pd.concat([pd.read_excel(file, index_col=['']) for file, print in rent_files], ignore_index=True)


print("매매 shape:", df_sale.shape)
print("전월세 shape:", df_rent.shape)

SyntaxError: cannot assign to function call (1672840391.py, line 12)

In [120]:
df_group2 = df_rent.apply(auto)

KeyError: "None of [Index(['시군구', '단지명', '도로명', '주택유형', '거래금액(만원)'], dtype='object')] are in the [index]"

In [27]:
df_rent.columns = df_rent.iloc[11]

In [32]:
df_rent = df_rent.iloc[12:]

In [34]:
df_sale.columns = df_sale.iloc[11]
df_sale = df_sale.iloc[12:]

In [39]:
df_sale = df_sale[['시군구', '단지명', '도로명', '주택유형', '거래금액(만원)']]

In [45]:
df_sale['거래금액(만원)'] = df_sale['거래금액(만원)'].str.replace(',', '')

C:\Users\asia\AppData\Local\Temp\ipykernel_18556\3084095270.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_sale['거래금액(만원)'] = df_sale['거래금액(만원)'].str.replace(',', '')

In [47]:
df_sale['거래금액(만원)'] = df_sale['거래금액(만원)'].astype(str).str.replace(r'[^0-9]', '', regex=True)

C:\Users\asia\AppData\Local\Temp\ipykernel_18556\1757181944.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_sale['거래금액(만원)'] = df_sale['거래금액(만원)'].astype(str).str.replace(r'[^0-9]', '', regex=True)

In [48]:
df_sale['거래금액(만원)'] = pd.to_numeric(df_sale['거래금액(만원)'])

C:\Users\asia\AppData\Local\Temp\ipykernel_18556\1546128702.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_sale['거래금액(만원)'] = pd.to_numeric(df_sale['거래금액(만원)'])

In [50]:
df_sale = df_sale.dropna(subset=['거래금액(만원)'])

In [108]:
df_group = df_sale.groupby('도로명', as_index=False).agg({
    '거래금액(만원)': 'mean',
    '단지명': 'first',
    '시군구': 'first',
    '주택유형' : 'first'
})

In [111]:
df_group = df_group.rename(columns={'거래금액(만원)': '평균금액'})

In [112]:
df_group['평균금액'] = df_group['평균금액'].round(0).astype(int) * 10000

In [122]:
df_group.to_csv('경기_아파트_매매.csv',encoding='utf-8')

In [175]:
def auto(df):
    df.columns = df.iloc[11]
    df = df.iloc[12:]
    
    df = df[['시군구', '단지명', '도로명', '주택유형', '거래금액(만원)']]
    
    df['거래금액(만원)'] = df['거래금액(만원)'].astype(str).str.replace(',', '')
    df['거래금액(만원)'] = df['거래금액(만원)'].str.replace(r'[^0-9]', '', regex=True)
    df['거래금액(만원)'] = pd.to_numeric(df['거래금액(만원)'], errors='coerce')
    
    df = df.dropna(subset=['거래금액(만원)'])

    df = df.groupby('도로명', as_index=False).agg({
        '거래금액(만원)': 'mean',
        '단지명': 'first',
        '시군구': 'first',
        '주택유형': 'first'
    })

    df = df.rename(columns={'거래금액(만원)': '평균금액'})
    df['평균금액'] = df['평균금액'].round(0).astype(int) * 10000

    return df

In [129]:
df_rent.columns = df_rent.iloc[11]

In [133]:
df_rent = df_rent.iloc[12:]

In [137]:
df_rent = df_rent[df_rent['전월세구분']=='전세']

In [141]:
df_rent = df_rent[['시군구', '단지명', '도로명', '주택유형', '보증금(만원)']]

In [143]:
df_rent['보증금(만원)'] = df_rent['보증금(만원)'].astype(str).str.replace(',', '')

C:\Users\asia\AppData\Local\Temp\ipykernel_18556\2173361601.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_rent['보증금(만원)'] = df_rent['보증금(만원)'].astype(str).str.replace(',', '')

In [144]:
df_rent['보증금(만원)'] = df_rent['보증금(만원)'].str.replace(r'[^0-9]', '', regex=True)
df_rent['보증금(만원)'] = pd.to_numeric(df_rent['보증금(만원)'], errors='coerce')

C:\Users\asia\AppData\Local\Temp\ipykernel_18556\1804846879.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_rent['보증금(만원)'] = df_rent['보증금(만원)'].str.replace(r'[^0-9]', '', regex=True)
C:\Users\asia\AppData\Local\Temp\ipykernel_18556\1804846879.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_rent['보증금(만원)'] = pd.to_numeric(df_rent['보증금(만원)'], errors='coerce')

In [148]:
df_rent = df_rent.dropna(subset=['보증금(만원)'])

In [151]:
df_rent = df_rent.groupby('도로명', as_index=False).agg({
    '보증금(만원)': 'mean',
    '단지명': 'first',
    '시군구': 'first',
    '주택유형': 'first'
})

In [157]:
df_rent = df_rent.rename(columns={'보증금(만원)': '평균금액'})

In [159]:
df_rent['평균금액'] = df_rent['평균금액'].round(0).astype(int) * 10000

In [168]:
df_rent.loc[df_rent['단지명'] == '아크로베스티뉴', '도로명'] = '시민대로 124'

In [170]:
df_rent.to_csv('경기_아파트_전세.csv', encoding='utf-8')

In [171]:
df_rent

11              도로명       평균금액           단지명               시군구 주택유형
0          시민대로 124  471350000       아크로베스티뉴   경기도 안양시 동안구 호계동  아파트
1            가림로 38  222780000           주공5       경기도 광명시 하안동  아파트
2          가림일로 101  294960000     도덕파크타운2단지       경기도 광명시 철산동  아파트
3           가림일로 55  268500000       하안현대아파트       경기도 광명시 하안동  아파트
4           가림일로 61  245000000       광명현대아파트       경기도 광명시 하안동  아파트
...             ...        ...           ...               ...  ...
3229        희망로 412  358270000            단남   경기도 성남시 중원구 금광동  아파트
3230        희망로 415  511990000          롯데캐슬   경기도 성남시 중원구 중앙동  아파트
3231        희망로 531  510260000  산성역자이푸르지오3단지   경기도 성남시 수정구 신흥동  아파트
3232  희망로380번길 12-5  370000000         태영파크뷰  경기도 성남시 중원구 상대원동  아파트
3233    희망로506번길 13  224000000            희망   경기도 성남시 수정구 단대동  아파트

[3234 rows x 5 columns]

In [172]:
from pathlib import Path
import pandas as pd

base_path = Path(r"final/in_gi/경기_연립_다세대")

# 매매
sale_files = list((base_path / "매매").glob("*.xlsx"))

sale_dfs = []
for file in sale_files:
    print("매매 읽는 중:", file)
    df = pd.read_excel(file)
    sale_dfs.append(df)

df_sale = pd.concat(sale_dfs, ignore_index=True)


# 전월세
rent_files = list((base_path / "전월세").glob("*.xlsx"))

rent_dfs = []
for file in rent_files:
    try:
        print("전월세 읽는 중:", file)
        df = pd.read_excel(file)
        rent_dfs.append(df)
    except Exception as e:
        print("❌ 문제 파일:", file)
        print(e)

df_rent = pd.concat(rent_dfs, ignore_index=True)


print("매매 shape:", df_sale.shape)
print("전월세 shape:", df_rent.shape)

매매 읽는 중: final\in_gi\경기_연립_다세대\매매\경기_고양_덕양구_매매.xlsx

c:\Users\asia\miniconda3\envs\ai4_p2\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

매매 읽는 중: final\in_gi\경기_연립_다세대\매매\경기_고양_일산동구_매매.xlsx
매매 읽는 중: final\in_gi\경기_연립_다세대\매매\경기_고양_일산서구_매매.xlsx
매매 읽는 중: final\in_gi\경기_연립_다세대\매매\경기_광명_매매.xlsx

c:\Users\asia\miniconda3\envs\ai4_p2\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\asia\miniconda3\envs\ai4_p2\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\asia\miniconda3\envs\ai4_p2\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

매매 읽는 중: final\in_gi\경기_연립_다세대\매매\경기_구리_매매.xlsx
매매 읽는 중: final\in_gi\경기_연립_다세대\매매\경기_김포_매매.xlsx

c:\Users\asia\miniconda3\envs\ai4_p2\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\asia\miniconda3\envs\ai4_p2\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

매매 읽는 중: final\in_gi\경기_연립_다세대\매매\경기_남양주_매매.xlsx

c:\Users\asia\miniconda3\envs\ai4_p2\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

매매 읽는 중: final\in_gi\경기_연립_다세대\매매\경기_부천_소사구_매매.xlsx
매매 읽는 중: final\in_gi\경기_연립_다세대\매매\경기_부천_오정구_매매.xlsx

c:\Users\asia\miniconda3\envs\ai4_p2\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\asia\miniconda3\envs\ai4_p2\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

매매 읽는 중: final\in_gi\경기_연립_다세대\매매\경기_부천_원미구_매매.xlsx

c:\Users\asia\miniconda3\envs\ai4_p2\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

매매 읽는 중: final\in_gi\경기_연립_다세대\매매\경기_성남_분당구_매매.xlsx
매매 읽는 중: final\in_gi\경기_연립_다세대\매매\경기_성남_수정구_매매.xlsx

c:\Users\asia\miniconda3\envs\ai4_p2\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\asia\miniconda3\envs\ai4_p2\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

매매 읽는 중: final\in_gi\경기_연립_다세대\매매\경기_성남_중원구_매매.xlsx

c:\Users\asia\miniconda3\envs\ai4_p2\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

매매 읽는 중: final\in_gi\경기_연립_다세대\매매\경기_안양_동안구_매매.xlsx
매매 읽는 중: final\in_gi\경기_연립_다세대\매매\경기_안양_만안구_매매.xlsx

c:\Users\asia\miniconda3\envs\ai4_p2\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\asia\miniconda3\envs\ai4_p2\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

매매 읽는 중: final\in_gi\경기_연립_다세대\매매\경기_용인_기흥구_매매.xlsx
매매 읽는 중: final\in_gi\경기_연립_다세대\매매\경기_용인_수지구_매매.xlsx
매매 읽는 중: final\in_gi\경기_연립_다세대\매매\경기_용인_처인구_매매.xlsx

c:\Users\asia\miniconda3\envs\ai4_p2\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\asia\miniconda3\envs\ai4_p2\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\asia\miniconda3\envs\ai4_p2\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

매매 읽는 중: final\in_gi\경기_연립_다세대\매매\경기_하남_매매.xlsx
전월세 읽는 중: final\in_gi\경기_연립_다세대\전월세\경기_고양_덕양구_전월세.xlsx

c:\Users\asia\miniconda3\envs\ai4_p2\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\asia\miniconda3\envs\ai4_p2\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

전월세 읽는 중: final\in_gi\경기_연립_다세대\전월세\경기_고양_일산동구_전월세.xlsx
전월세 읽는 중: final\in_gi\경기_연립_다세대\전월세\경기_고양_일산서구_전월세.xlsx

c:\Users\asia\miniconda3\envs\ai4_p2\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\asia\miniconda3\envs\ai4_p2\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

전월세 읽는 중: final\in_gi\경기_연립_다세대\전월세\경기_광명_전월세.xlsx

c:\Users\asia\miniconda3\envs\ai4_p2\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

전월세 읽는 중: final\in_gi\경기_연립_다세대\전월세\경기_구리_전월세.xlsx

c:\Users\asia\miniconda3\envs\ai4_p2\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

전월세 읽는 중: final\in_gi\경기_연립_다세대\전월세\경기_김포_전월세.xlsx

c:\Users\asia\miniconda3\envs\ai4_p2\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

전월세 읽는 중: final\in_gi\경기_연립_다세대\전월세\경기_남양주_전월세.xlsx

c:\Users\asia\miniconda3\envs\ai4_p2\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

전월세 읽는 중: final\in_gi\경기_연립_다세대\전월세\경기_부천_소사구_전월세.xlsx

c:\Users\asia\miniconda3\envs\ai4_p2\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

전월세 읽는 중: final\in_gi\경기_연립_다세대\전월세\경기_부천_오정구_전월세.xlsx

c:\Users\asia\miniconda3\envs\ai4_p2\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

전월세 읽는 중: final\in_gi\경기_연립_다세대\전월세\경기_부천_원미구_전월세.xlsx

c:\Users\asia\miniconda3\envs\ai4_p2\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

전월세 읽는 중: final\in_gi\경기_연립_다세대\전월세\경기_성남_분당구_전월세.xlsx

c:\Users\asia\miniconda3\envs\ai4_p2\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

전월세 읽는 중: final\in_gi\경기_연립_다세대\전월세\경기_성남_수정구_전월세.xlsx

c:\Users\asia\miniconda3\envs\ai4_p2\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

전월세 읽는 중: final\in_gi\경기_연립_다세대\전월세\경기_성남_중원구_전월세.xlsx

c:\Users\asia\miniconda3\envs\ai4_p2\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

전월세 읽는 중: final\in_gi\경기_연립_다세대\전월세\경기_안양_동안구_전월세.xlsx

c:\Users\asia\miniconda3\envs\ai4_p2\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

전월세 읽는 중: final\in_gi\경기_연립_다세대\전월세\경기_안양_만안구_전월세.xlsx

c:\Users\asia\miniconda3\envs\ai4_p2\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

전월세 읽는 중: final\in_gi\경기_연립_다세대\전월세\경기_용인_기흥구_전월세.xlsx

c:\Users\asia\miniconda3\envs\ai4_p2\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

전월세 읽는 중: final\in_gi\경기_연립_다세대\전월세\경기_용인_수지구_전월세.xlsx

c:\Users\asia\miniconda3\envs\ai4_p2\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

전월세 읽는 중: final\in_gi\경기_연립_다세대\전월세\경기_용인_처인구_전월세.xlsx

c:\Users\asia\miniconda3\envs\ai4_p2\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

전월세 읽는 중: final\in_gi\경기_연립_다세대\전월세\경기_하남_전월세.xlsx
매매 shape: (12291, 21)
전월세 shape: (27816, 21)

c:\Users\asia\miniconda3\envs\ai4_p2\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [182]:
df_sale.columns = df_sale.iloc[11]

In [183]:
df_sale = df_sale[12:]

In [188]:
def auto(df):

    
    df['거래금액(만원)'] = df['거래금액(만원)'].astype(str).str.replace(',', '')
    df['거래금액(만원)'] = df['거래금액(만원)'].str.replace(r'[^0-9]', '', regex=True)
    df['거래금액(만원)'] = pd.to_numeric(df['거래금액(만원)'], errors='coerce')
    
    df = df.dropna(subset=['거래금액(만원)'])

    df = df.groupby('도로명', as_index=False).agg({
        '거래금액(만원)': 'mean',
        '단지명': 'first',
        '시군구': 'first',
        '주택유형': 'first'
    })

    df = df.rename(columns={'거래금액(만원)': '평균금액'})
    df['평균금액'] = df['평균금액'].round(0).astype(int) * 10000

    return df

In [187]:
df_sale = df_sale[['시군구', '건물명', '도로명', '주택유형', '거래금액(만원)']]

In [190]:
df_sale['거래금액(만원)'] = df_sale['거래금액(만원)'].astype(str).str.replace(',', '')

C:\Users\asia\AppData\Local\Temp\ipykernel_18556\1180929731.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_sale['거래금액(만원)'] = df_sale['거래금액(만원)'].astype(str).str.replace(',', '')

In [191]:
df_sale['거래금액(만원)'] = df_sale['거래금액(만원)'].str.replace(r'[^0-9]', '', regex=True)

C:\Users\asia\AppData\Local\Temp\ipykernel_18556\2293590394.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_sale['거래금액(만원)'] = df_sale['거래금액(만원)'].str.replace(r'[^0-9]', '', regex=True)

In [192]:
df_sale['거래금액(만원)'] = pd.to_numeric(df_sale['거래금액(만원)'], errors='coerce')

C:\Users\asia\AppData\Local\Temp\ipykernel_18556\93132688.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_sale['거래금액(만원)'] = pd.to_numeric(df_sale['거래금액(만원)'], errors='coerce')

In [193]:
df_sale = df_sale.dropna(subset=['거래금액(만원)'])

In [195]:
df_sale = df_sale.groupby('도로명', as_index=False).agg({
        '거래금액(만원)': 'mean',
        '건물명': 'first',
        '시군구': 'first',
        '주택유형': 'first'
    })

In [196]:
df_sale = df_sale.rename(columns={'거래금액(만원)': '평균금액'})
df_sale['평균금액'] = df_sale['평균금액'].round(0).astype(int) * 10000

In [198]:
df_sale.to_csv('경기_연립_다세대_매매.csv', encoding='utf-8')

In [201]:
df_rent.columns = df_rent.iloc[11]

In [206]:
df_rent = df_rent.iloc[12:]

In [ ]:
def auto(df):

    
    df['거래금액(만원)'] = df['거래금액(만원)'].astype(str).str.replace(',', '')
    df['거래금액(만원)'] = df['거래금액(만원)'].str.replace(r'[^0-9]', '', regex=True)
    df['거래금액(만원)'] = pd.to_numeric(df['거래금액(만원)'], errors='coerce')
    
    df = df.dropna(subset=['거래금액(만원)'])

    df = df.groupby('도로명', as_index=False).agg({
        '거래금액(만원)': 'mean',
        '단지명': 'first',
        '시군구': 'first',
        '주택유형': 'first'
    })

    df = df.rename(columns={'거래금액(만원)': '평균금액'})
    df['평균금액'] = df['평균금액'].round(0).astype(int) * 10000

    return df

11,NO,시군구,번지,본번,부번,건물명,전월세구분,전용면적(㎡),계약년월,계약일,...,월세금(만원),층,건축년도,도로명,계약기간,계약구분,갱신요구권 사용,종전계약 보증금(만원),종전계약 월세(만원),주택유형
12,1,경기도 고양시 덕양구 관산동,687-42,0687,0042,광장맨션101,전세,58.1500,202603,24,...,0,3,2003,동헌로1번길 41,202605~202805,신규,-,NaN,NaN,다세대
13,2,경기도 고양시 덕양구 내유동,105-2,0105,0002,동화빌라102동,월세,59.9400,202603,23,...,50,4,2009,내유길131번길 13,202603~202803,신규,-,NaN,NaN,다세대
14,3,경기도 고양시 덕양구 관산동,118,0118,0000,NS타운,월세,30.8000,202603,21,...,45,4,2014,통일로742번길 63-7,202603~202803,신규,-,NaN,NaN,다세대
15,4,경기도 고양시 덕양구 행신동,641-19,0641,0019,한미가든빌라3동,전세,36.1800,202603,20,...,0,2,1990,충장로103번길 166-7,202604~202804,신규,-,NaN,NaN,다세대
16,5,경기도 고양시 덕양구 행신동,1093,1093,0000,휴먼시티,월세,17.1000,202603,20,...,58,4,2019,서정로 11-12,202603~202703,갱신,사용,500,55,다세대
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27811,476,경기도 하남시 신장동,427-189,0427,0189,더프레스티지,월세,49.8400,202503,27,...,2,8,2022,신장1로21번길 76,202505~202705,갱신,-,"27,000",0,다세대
27812,477,경기도 하남시 미사동,462-2,0462,0002,강변라움빌,전세,25.5000,202503,27,...,0,2,2019,미사동로40번길 49-9,202505~202705,신규,-,NaN,NaN,다세대
27813,478,경기도 하남시 초이동,234-78,0234,0078,라움하우스,전세,48.8500,202503,27,...,0,2,2021,초이로92번길 16-46,202506~202706,신규,-,NaN,NaN,다세대
27814,479,경기도 하남시 초이동,234-78,0234,0078,라움하우스,전세,48.8500,202503,27,...,0,2,2021,초이로92번길 16-46,202506~202706,신규,-,NaN,NaN,다세대
27815,480,경기도 하남시 덕풍동,326-48,0326,0048,푸른빌,월세,57.6400,202503,26,...,4,2,2017,수리북로34번길 5-1,202504~202704,갱신,사용,"22,000",0,다세대

In [208]:
df_rent = df_rent[['시군구', '건물명', '도로명', '주택유형', '보증금(만원)']]

In [210]:
df_rent['보증금(만원)'] = df_rent['보증금(만원)'].astype(str).str.replace(',', '')
df_rent['보증금(만원)'] = df_rent['보증금(만원)'].str.replace(r'[^0-9]', '', regex=True)
df_rent['보증금(만원)'] = pd.to_numeric(df_rent['보증금(만원)'], errors='coerce')

C:\Users\asia\AppData\Local\Temp\ipykernel_18556\4019994621.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_rent['보증금(만원)'] = df_rent['보증금(만원)'].astype(str).str.replace(',', '')
C:\Users\asia\AppData\Local\Temp\ipykernel_18556\4019994621.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_rent['보증금(만원)'] = df_rent['보증금(만원)'].str.replace(r'[^0-9]', '', regex=True)
C:\Users\asia\AppData\Local\Temp\ipykernel_18556\4019994621.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_rent['보증금(만원)'] = pd.to_numeric(df_rent['보증금(만원)'], errors='coerce')

In [212]:
df_rent = df_rent.dropna(subset=['보증금(만원)'])

df_rent = df_rent.groupby('도로명', as_index=False).agg({
    '보증금(만원)': 'mean',
    '건물명': 'first',
    '시군구': 'first',
    '주택유형': 'first'
})

df_rent = df_rent.rename(columns={'보증금(만원)': '평균금액'})
df_rent['평균금액'] = df_rent['평균금액'].round(0).astype(int) * 10000

In [214]:
df_rent = df_rent[1:]

In [216]:
df_rent.to_csv('경기_연립_다세대_전세.csv', encoding='utf-8')

In [217]:
df_1 = pd.read_excel('final/in_gi/경기_단독_다가구/매매/경기_전체_매매.xlsx')
df_2 = pd.read_excel('final/in_gi/경기_단독_다가구/전월세/경기_전체_전월세.xlsx')

c:\Users\asia\miniconda3\envs\ai4_p2\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\asia\miniconda3\envs\ai4_p2\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [224]:
df_1.columns = df_1.iloc[11]

In [228]:
df_1 = df_1.iloc[12:]

In [230]:
df_2.columns = df_2.iloc[11]

In [231]:
df_2 = df_2.iloc[12:]

In [235]:
df_1 = df_1[['시군구', '주택유형', '도로명', '거래금액(만원)']]

In [237]:
df2 = df_2[df_2['전월세구분']=='전세']

In [238]:
df_2 = df_2[['시군구', '주택유형', '도로명', '보증금(만원)']]

In [239]:
df_2

11                      시군구 주택유형         도로명 보증금(만원)
12          경기도 수원시 장안구 연무동  다가구   경수대로754번길     500
13      경기도 용인시 처인구 모현읍 매산리   단독     이일로61번길     200
14          경기도 수원시 장안구 영화동  다가구    수성로276번길   1,000
15          경기도 수원시 권선구 서둔동   단독         상탑로  12,000
16      경기도 용인시 처인구 모현읍 왕산리  다가구  백옥대로2332번길   1,000
...                     ...  ...         ...     ...
139411          경기도 광명시 철산동   단독     연서일로9번길     100
139412          경기도 광명시 소하동  다가구    소하일로52번길   3,000
139413      경기도 고양시 덕양구 토당동  다가구     토당로12번길     500
139414      경기도 고양시 덕양구 토당동  다가구     능곡로45번길     200
139415         경기도 의정부시 가능동  다가구   호국로1051번길   8,000

[139404 rows x 4 columns]

In [240]:
cities = ['성남시', '고양시', '부천시', '광명시', '하남시', '남양주시', '용인시', '김포시', '구리시', '안양시']

df_me = df_1[df_1['시군구'].str.contains('|'.join(cities), na=False)]

In [242]:
df_me['거래금액(만원)'] = df_me['거래금액(만원)'].astype(str).str.replace(',', '')
df_me['거래금액(만원)'] = df_me['거래금액(만원)'].str.replace(r'[^0-9]', '', regex=True)
df_me['거래금액(만원)'] = pd.to_numeric(df_me['거래금액(만원)'], errors='coerce')

df_me = df_me.dropna(subset=['거래금액(만원)'])

C:\Users\asia\AppData\Local\Temp\ipykernel_18556\2086742822.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_me['거래금액(만원)'] = df_me['거래금액(만원)'].astype(str).str.replace(',', '')
C:\Users\asia\AppData\Local\Temp\ipykernel_18556\2086742822.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_me['거래금액(만원)'] = df_me['거래금액(만원)'].str.replace(r'[^0-9]', '', regex=True)
C:\Users\asia\AppData\Local\Temp\ipykernel_18556\2086742822.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_me['거래금액(만원)'] = pd.to_numeric(df_me['거래금액(만원)'], errors='coerce')

In [246]:
df_me = df_me.groupby('도로명', as_index=False).agg({
    '거래금액(만원)': 'mean',
    '시군구': 'first',
    '주택유형': 'first'
})

In [248]:
df_me = df_me.rename(columns={'거래금액(만원)': '평균금액'})
df_me['평균금액'] = df_me['평균금액'].round(0).astype(int) * 10000

In [251]:
df_me.to_csv('경기_단독_다가구_매매.csv', encoding='utf-8')

In [252]:
cities = ['성남시', '고양시', '부천시', '광명시', '하남시', '남양주시', '용인시', '김포시', '구리시', '안양시']

df_jon = df_2[df_2['시군구'].str.contains('|'.join(cities), na=False)]

In [254]:
df_jon['보증금(만원)'] = df_jon['보증금(만원)'].astype(str).str.replace(',', '')
df_jon['보증금(만원)'] = df_jon['보증금(만원)'].str.replace(r'[^0-9]', '', regex=True)
df_jon['보증금(만원)'] = pd.to_numeric(df_jon['보증금(만원)'], errors='coerce')

df_jon = df_jon.dropna(subset=['보증금(만원)'])

C:\Users\asia\AppData\Local\Temp\ipykernel_18556\345735437.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_jon['보증금(만원)'] = df_jon['보증금(만원)'].astype(str).str.replace(',', '')
C:\Users\asia\AppData\Local\Temp\ipykernel_18556\345735437.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_jon['보증금(만원)'] = df_jon['보증금(만원)'].str.replace(r'[^0-9]', '', regex=True)
C:\Users\asia\AppData\Local\Temp\ipykernel_18556\345735437.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_jon['보증금(만원)'] = pd.to_numeric(df_jon['보증금(만원)'], errors='coerce')

In [255]:
df_jon

11                      시군구 주택유형         도로명  보증금(만원)
13      경기도 용인시 처인구 모현읍 매산리   단독     이일로61번길      200
16      경기도 용인시 처인구 모현읍 왕산리  다가구  백옥대로2332번길     1000
18          경기도 성남시 수정구 태평동   단독     태평로64번길     7000
19          경기도 성남시 수정구 신흥동   단독   산성대로283번길    15000
20          경기도 성남시 수정구 태평동   단독    남문로131번길     6000
...                     ...  ...         ...      ...
139410      경기도 고양시 덕양구 화정동  다가구     은빛로77번길     4000
139411          경기도 광명시 철산동   단독     연서일로9번길      100
139412          경기도 광명시 소하동  다가구    소하일로52번길     3000
139413      경기도 고양시 덕양구 토당동  다가구     토당로12번길      500
139414      경기도 고양시 덕양구 토당동  다가구     능곡로45번길      200

[59271 rows x 4 columns]

In [256]:
df_jon = df_jon.groupby('도로명', as_index=False).agg({
    '보증금(만원)': 'mean',
    '시군구': 'first',
    '주택유형': 'first'
})

In [257]:
df_jon = df_jon.rename(columns={'보증금(만원)': '평균금액'})
df_jon['평균금액'] = df_jon['평균금액'].round(0).astype(int) * 10000

In [312]:
import requests
import pandas as pd
import time

url = "https://dapi.kakao.com/v2/local/search/address.json"
headers = {"Authorization": "KakaoAK YOUR_KAKAO_API_KEY"}

def get_address(address):
    try:
        params = {'query' : address}
        res = requests.get(url, headers=headers, params=params, timeout=5)
        a = res.json()
        lat = a['documents'][0]['y']   # 위도
        lon = a['documents'][0]['x']   # 경도
        return pd.Series([lat, lon])
        
    except Exception as e:
        print(f"주소 변환 실패: {address} / 에러: {e}")
        return pd.Series([None, None])

In [260]:
df_jon[['위도', '경도']] = df_jon['도로명'].apply(get_address).values

In [262]:
df_me[['위도', '경도']] = df_me['도로명'].apply(get_address).values

In [264]:
df_jon.to_csv('경기_단독_다가구_전세.csv', encoding='utf-8')

In [266]:
df_me.to_csv('경기_단독_다가구_매매.csv', encoding='utf-8')

In [267]:
df=pd.read_csv('경기_아파트_매매.csv')

In [269]:
df[['위도', '경도']] = df['도로명'].apply(get_address).values

주소 변환 실패: 분당수서로 472 / 에러: list index out of range
주소 변환 실패: 소사로835번길 835 / 에러: list index out of range

In [278]:
df[df['위도'].isna()]

      Unnamed: 0      도로명       평균금액   단지명              시군구 주택유형    위도    경도
1737        1737  소사로 835  415800000  동문1차  경기도 부천시 오정구 원종동  아파트  None  None

In [ ]:
df.loc[df['도로명'] == '희망로 472', ['위도', '경도']] = '37.4470676074685','127.155817316664'

In [ ]:
df.loc[df['도로명'] == '희망로 472']

,Unnamed: 0,도로명,평균금액,단지명,시군구,주택유형,위도,경도
1737,1737,소사로 835,415800000,동문1차,경기도 부천시 오정구 원종동,아파트,37.5300190774874,126.803792117305

In [285]:
df.to_csv('경기_아파트_매매.csv')

In [286]:
df=pd.read_csv('경기_아파트_전세.csv', encoding='utf-8')

In [288]:
df[['위도', '경도']] = df['도로명'].apply(get_address).values

주소 변환 실패: 분당수서로 472 / 에러: list index out of range
주소 변환 실패: 분당수서로 486 / 에러: list index out of range
주소 변환 실패: 소사로835번길 835 / 에러: list index out of range

In [299]:
df[df['위도'].isna()]

Empty DataFrame
Columns: [Unnamed: 0, 도로명, 평균금액, 단지명, 시군구, 주택유형, 위도, 경도]
Index: []

In [297]:
df.loc[df['도로명'] == '분당수서로 486', ['위도', '경도']] = '37.4478136532649','127.15464592374'

In [298]:
df.loc[df['도로명'] == '분당수서로 486', '도로명'] = '희망로 486'

In [300]:
df.to_csv('경기_아파트_전세.csv', encoding='utf-8')

In [301]:
df=pd.read_csv('경기_연립_다세대_매매.csv', encoding='utf-8')

In [303]:
df[['위도', '경도']] = df['도로명'].apply(get_address).values

주소 변환 실패: 둔촌대로371번길 6 / 에러: list index out of range
주소 변환 실패: 삼작로268번길 14 / 에러: list index out of range
주소 변환 실패: 삼작로268번길 16 / 에러: list index out of range
주소 변환 실패: 성오로 143 / 에러: list index out of range
주소 변환 실패: 성오로117번길 33-1 / 에러: list index out of range
주소 변환 실패: 원종로94번길 35 / 에러: list index out of range
주소 변환 실패: 원종로94번길 37 / 에러: list index out of range
주소 변환 실패: 은성로98번길 52 / 에러: list index out of range

In [308]:
df = df[df['위도'].notna()]

In [309]:
df.to_csv('경기_연립_다세대_매매.csv', encoding='utf-8')

In [310]:
df=pd.read_csv('경기_연립_다세대_전세.csv', encoding='utf-8')

In [313]:
df[['위도', '경도']] = df['도로명'].apply(get_address).values

주소 변환 실패: 성결대학로64번길 9-1 / 에러: list index out of range
주소 변환 실패: 원종로94번길 35 / 에러: list index out of range

In [314]:
df = df[df['위도'].notna()]

In [316]:
df.to_csv('경기_연립_다세대_전세.csv', encoding='utf-8')