In [1]:
# %matplotlib notebook

import pandas as pd
import matplotlib.pyplot as plt
from matplotlib import font_manager, rc

# 한글깨짐처리
font_loc = "c:/Windows/Fonts/malgun.ttf"
font_name=font_manager.FontProperties(fname=font_loc).get_name()
rc('font', family=font_name)

In [5]:
df = pd.read_csv('어린이집정제.csv', usecols=[0,1,2,4,5],encoding='cp949')
df

         시도  시군구         어린이집명   행정동  0~5인구
0     인천광역시   중구        장미어린이집  동인천동     50
1     인천광역시   중구        금산어린이집   영종동   1241
2     인천광역시   중구        효성어린이집   영종동   1241
3     인천광역시   중구       비둘기어린이집   개항동     52
4     인천광역시   중구  인천신광초등학교어린이집   신흥동    396
...     ...  ...           ...   ...    ...
8861  서울특별시  강동구    아기랑놀이랑어린이집  명일1동   1050
8862  서울특별시  강동구    구립명일사랑어린이집  명일1동   1050
8863  서울특별시  강동구      구립토리어린이집  상일2동    637
8864  서울특별시  강동구        새아어린이집  고덕1동    671
8865  서울특별시  강동구    구립강동한별어린이집    길동   1297

[8866 rows x 5 columns]

In [6]:
result = (df.groupby(['시군구', '행정동'], as_index=False).agg(어린이집수=('어린이집명', 'count'),유아인구합계=('0~5인구', 'first')))
result

     시군구   행정동  어린이집수  유아인구합계
0    강남구  개포1동      4    1031
1    강남구  개포2동      8    2024
2    강남구  개포3동      6     486
3    강남구  개포4동      9     817
4    강남구  논현1동      2     289
..   ...   ...    ...     ...
926  하남시  신장1동      3     134
927  하남시  신장2동     30    1652
928  하남시   위례동     21    2642
929  하남시   천현동      4      81
930  하남시   초이동      2      66

[931 rows x 4 columns]

In [7]:
result.to_csv('어린이집합계.csv', index=False, encoding='utf-8-sig')

In [8]:
dup = result['행정동'].value_counts()
dup[dup >= 2]

행정동
중앙동     4
신촌동     3
위례동     3
신흥동     3
기흥동     2
       ..
중동      2
심곡1동    2
논현1동    2
논현2동    2
신사동     2
Name: count, Length: 96, dtype: int64

In [9]:
dup[dup >= 2].to_string()

'행정동\n중앙동      4\n신촌동      3\n위례동      3\n신흥동      3\n기흥동      2\n동백2동     2\n동백3동     2\n동천동      2\n마북동      2\n모현읍      2\n보라동      2\n보정동      2\n삼가동      2\n상현3동     2\n서농동      2\n성복동      2\n신갈동      2\n신봉동      2\n양지읍      2\n역북동      2\n영덕1동     2\n영덕2동     2\n유림1동     2\n유림2동     2\n이동읍      2\n죽전1동     2\n죽전3동     2\n포곡읍      2\n풍덕천1동    2\n남사읍      2\n안양5동     2\n구성동      2\n연희동      2\n금곡동      2\n관양동      2\n달안동      2\n박달동      2\n부림동      2\n부흥동      2\n비산1동     2\n비산2동     2\n비산3동     2\n석수1동     2\n석수2동     2\n안양1동     2\n안양2동     2\n안양3동     2\n안양4동     2\n안양6동     2\n안양7동     2\n안양8동     2\n안양9동     2\n인덕원동     2\n충훈동      2\n호계1동     2\n호계2동     2\n호계3동     2\n호현동      2\n구갈동      2\n동백1동     2\n중1동      2\n춘의동      2\n고강1동     2\n고강본동     2\n괴안동      2\n도당동      2\n범박동      2\n상1동      2\n중4동      2\n상2동      2\n상3동      2\n상동       2\n성곡동      2\n소사동      2\n소사본1동    2\n소사본동     2\n송내1동     2\n송내2동     2\n심곡본1동    2\n심곡본동     2\n중3동      2\n약대동      2\n역곡1동     2\n역곡2동     2\n역곡3동     2\n오정동      2\n옥길동      2\n원미1동     2\n원종1동     2\n원종2동     2\n중2동      2\n중동       2\n심곡1동     2\n논현1동     2\n논현2동     2\n신사동      2'

In [10]:
result = (df.groupby('행정동', as_index=False).agg(어린이집수=('어린이집명', 'count'),유아인구합계=('0~5인구', 'first')))
result

      행정동  어린이집수  유아인구합계
0    가락1동     14    1520
1    가락2동     14     868
2    가락본동     11     705
3    가리봉동      2      94
4     가산동      9     364
..    ...    ...     ...
825   후암동      5     292
826  휘경1동      6     661
827  휘경2동     12     441
828   흑석동     15    1102
829   흥도동     17    1123

[830 rows x 3 columns]

In [11]:
result.to_csv('어린이집합계2.csv', index=False, encoding='utf-8-sig')

In [13]:
df = pd.read_csv('어린이집합계2.csv', encoding='cp949')
df

      행정동  어린이집수  유아인구합계  시군구
0    가락1동     14    1520  NaN
1    가락2동     14     868  NaN
2    가락본동     11     705  NaN
3    가리봉동      2      94  NaN
4     가산동      9     364  NaN
..    ...    ...     ...  ...
837   후암동      5     292  NaN
838  휘경1동      6     661  NaN
839  휘경2동     12     441  NaN
840   흑석동     15    1102  NaN
841   흥도동     17    1123  NaN

[842 rows x 4 columns]

In [15]:
df2 = pd.read_csv('유아인구통합.csv', encoding='utf-8-sig')
df2

       시도명 시군구명      읍면동명  유아인구
0    서울특별시  종로구     청운효자동   250
1    서울특별시  종로구       사직동   189
2    서울특별시  종로구       삼청동    34
3    서울특별시  종로구       부암동   151
4    서울특별시  종로구       평창동   459
..     ...  ...       ...   ...
858  인천광역시  옹진군       덕적면    12
859  인천광역시  옹진군       영흥면    98
860  인천광역시  옹진군       자월면    10
861  인천광역시  옹진군  자월면이작출장소     2
862  인천광역시  옹진군       연평면    35

[863 rows x 4 columns]

In [16]:
df = df.merge(
    df2[['시군구명', '읍면동명']],
    left_on='행정동',
    right_on='읍면동명',
    how='left'
)

df['시군구'] = df['시군구명']
df.drop(columns=['시군구명', '읍면동명'], inplace=True)

df

      행정동  어린이집수  유아인구합계      시군구
0    가락1동     14    1520      송파구
1    가락2동     14     868      송파구
2    가락본동     11     705      송파구
3    가리봉동      2      94      구로구
4     가산동      9     364      금천구
..    ...    ...     ...      ...
867   후암동      5     292      용산구
868  휘경1동      6     661     동대문구
869  휘경2동     12     441     동대문구
870   흑석동     15    1102      동작구
871   흥도동     17    1123  고양시 덕양구

[872 rows x 4 columns]

In [18]:
df.to_csv('어린이집합계3.csv', index=False, encoding='utf-8-sig')

In [19]:
df

      행정동  어린이집수  유아인구합계      시군구
0    가락1동     14    1520      송파구
1    가락2동     14     868      송파구
2    가락본동     11     705      송파구
3    가리봉동      2      94      구로구
4     가산동      9     364      금천구
..    ...    ...     ...      ...
867   후암동      5     292      용산구
868  휘경1동      6     661     동대문구
869  휘경2동     12     441     동대문구
870   흑석동     15    1102      동작구
871   흥도동     17    1123  고양시 덕양구

[872 rows x 4 columns]

In [21]:
df = pd.read_csv('어린이집합계3.csv', encoding='cp949')
df

         시군구   행정동  어린이집수  유아인구합계
0        송파구  가락1동     14    1520
1        송파구  가락2동     14     868
2        송파구  가락본동     11     705
3        구로구  가리봉동      2      94
4        금천구   가산동      9     364
..       ...   ...    ...     ...
837      용산구   후암동      5     292
838     동대문구  휘경1동      6     661
839     동대문구  휘경2동     12     441
840      동작구   흑석동     15    1102
841  고양시 덕양구   흥도동     17    1123

[842 rows x 4 columns]

In [22]:
df['유아천명당시설수'] = df['어린이집수'] / df['유아인구합계'] * 1000
df

         시군구   행정동  어린이집수  유아인구합계   유아천명당시설수
0        송파구  가락1동     14    1520   9.210526
1        송파구  가락2동     14     868  16.129032
2        송파구  가락본동     11     705  15.602837
3        구로구  가리봉동      2      94  21.276596
4        금천구   가산동      9     364  24.725275
..       ...   ...    ...     ...        ...
837      용산구   후암동      5     292  17.123288
838     동대문구  휘경1동      6     661   9.077156
839     동대문구  휘경2동     12     441  27.210884
840      동작구   흑석동     15    1102  13.611615
841  고양시 덕양구   흥도동     17    1123  15.138023

[842 rows x 5 columns]

In [24]:
df.to_csv('어린이집합계3.csv', index=False, encoding='utf-8-sig')

In [25]:
min_val = df['유아천명당시설수'].min()
max_val = df['유아천명당시설수'].max()

df['정규화값'] = (df['유아천명당시설수'] - min_val) / (max_val - min_val)
df

         시군구   행정동  어린이집수  유아인구합계   유아천명당시설수      정규화값
0        송파구  가락1동     14    1520   9.210526  0.027632
1        송파구  가락2동     14     868  16.129032  0.048387
2        송파구  가락본동     11     705  15.602837  0.046809
3        구로구  가리봉동      2      94  21.276596  0.063830
4        금천구   가산동      9     364  24.725275  0.074176
..       ...   ...    ...     ...        ...       ...
837      용산구   후암동      5     292  17.123288  0.051370
838     동대문구  휘경1동      6     661   9.077156  0.027231
839     동대문구  휘경2동     12     441  27.210884  0.081633
840      동작구   흑석동     15    1102  13.611615  0.040835
841  고양시 덕양구   흥도동     17    1123  15.138023  0.045414

[842 rows x 6 columns]

In [26]:
df['가중치적용값'] = df['정규화값'] * 0.0820
df

         시군구   행정동  어린이집수  유아인구합계   유아천명당시설수      정규화값    가중치적용값
0        송파구  가락1동     14    1520   9.210526  0.027632  0.002266
1        송파구  가락2동     14     868  16.129032  0.048387  0.003968
2        송파구  가락본동     11     705  15.602837  0.046809  0.003838
3        구로구  가리봉동      2      94  21.276596  0.063830  0.005234
4        금천구   가산동      9     364  24.725275  0.074176  0.006082
..       ...   ...    ...     ...        ...       ...       ...
837      용산구   후암동      5     292  17.123288  0.051370  0.004212
838     동대문구  휘경1동      6     661   9.077156  0.027231  0.002233
839     동대문구  휘경2동     12     441  27.210884  0.081633  0.006694
840      동작구   흑석동     15    1102  13.611615  0.040835  0.003348
841  고양시 덕양구   흥도동     17    1123  15.138023  0.045414  0.003724

[842 rows x 7 columns]

In [28]:
df.to_csv('어린이집합계3.csv', index=False, encoding='utf-8-sig')

In [30]:
df = pd.read_csv('최종2_서울학급당학생수.csv', encoding='utf-8-sig')
df

,시군구,행정동,학생수(계)_초,학급수(계)_초,학생수(계)_중,학급수(계)_중,총학생수,총학급수,학급당학생수
0,송파구,가락1동,1833,84,853,30,2686,114,23.561404
1,송파구,가락2동,1409,66,896,34,2305,100,23.050000
2,송파구,가락본동,693,42,736,30,1429,72,19.847222
3,구로구,가리봉동,267,19,0,0,267,19,14.052632
4,금천구,가산동,265,15,0,0,265,15,17.666667
...,...,...,...,...,...,...,...,...,...
424,관악구,신림동,0,0,0,0,0,0,0.000000
425,종로구,창신2동,0,0,0,0,0,0,0.000000
426,서대문구,북가좌2동,0,0,0,0,0,0,0.000000
427,성동구,성수1가2동,0,0,0,0,0,0,0.000000
428,중랑구,중화2동,0,0,0,0,0,0,0.000000

In [31]:
min_val = df['학급당학생수'].min()
max_val = df['학급당학생수'].max()

df['정규화값'] = (df['학급당학생수'] - min_val) / (max_val - min_val)
df

,시군구,행정동,학생수(계)_초,학급수(계)_초,학생수(계)_중,학급수(계)_중,총학생수,총학급수,학급당학생수,정규화값
0,송파구,가락1동,1833,84,853,30,2686,114,23.561404,0.721794
1,송파구,가락2동,1409,66,896,34,2305,100,23.050000,0.706127
2,송파구,가락본동,693,42,736,30,1429,72,19.847222,0.608011
3,구로구,가리봉동,267,19,0,0,267,19,14.052632,0.430496
4,금천구,가산동,265,15,0,0,265,15,17.666667,0.541211
...,...,...,...,...,...,...,...,...,...,...
424,관악구,신림동,0,0,0,0,0,0,0.000000,0.000000
425,종로구,창신2동,0,0,0,0,0,0,0.000000,0.000000
426,서대문구,북가좌2동,0,0,0,0,0,0,0.000000,0.000000
427,성동구,성수1가2동,0,0,0,0,0,0,0.000000,0.000000
428,중랑구,중화2동,0,0,0,0,0,0,0.000000,0.000000

In [32]:
df['가중치적용값'] = df['정규화값'] * 0.0820
df

,시군구,행정동,학생수(계)_초,학급수(계)_초,학생수(계)_중,학급수(계)_중,총학생수,총학급수,학급당학생수,정규화값,가중치적용값
0,송파구,가락1동,1833,84,853,30,2686,114,23.561404,0.721794,0.059187
1,송파구,가락2동,1409,66,896,34,2305,100,23.050000,0.706127,0.057902
2,송파구,가락본동,693,42,736,30,1429,72,19.847222,0.608011,0.049857
3,구로구,가리봉동,267,19,0,0,267,19,14.052632,0.430496,0.035301
4,금천구,가산동,265,15,0,0,265,15,17.666667,0.541211,0.044379
...,...,...,...,...,...,...,...,...,...,...,...
424,관악구,신림동,0,0,0,0,0,0,0.000000,0.000000,0.000000
425,종로구,창신2동,0,0,0,0,0,0,0.000000,0.000000,0.000000
426,서대문구,북가좌2동,0,0,0,0,0,0,0.000000,0.000000,0.000000
427,성동구,성수1가2동,0,0,0,0,0,0,0.000000,0.000000,0.000000
428,중랑구,중화2동,0,0,0,0,0,0,0.000000,0.000000,0.000000

In [33]:
df.to_csv('최종2_서울학급당학생수.csv', index=False, encoding='utf-8-sig')

In [34]:
df = pd.read_csv('최종2_인천학급당학생수.csv', encoding='utf-8-sig')
df

,행정동,학생수(계)_초,학급수(계)_초,학생수(계)_중,학급수(계)_중,총학생수,총학급수,학급당학생수,시군구
0,가정1동,1558,66,910,30,2468,96,25.708333,서구
1,가정2동,1216,51,0,0,1216,51,23.843137,서구
2,가정3동,209,13,0,0,209,13,16.076923,서구
3,가좌1동,298,20,0,0,298,20,14.900000,서구
4,가좌2동,582,33,0,0,582,33,17.636364,서구
...,...,...,...,...,...,...,...,...,...
157,계양3동,0,0,0,0,0,0,0.000000,계양구
158,서도면볼음출장소,0,0,0,0,0,0,0.000000,강화군
159,북도면장봉출장소,0,0,0,0,0,0,0.000000,옹진군
160,대청면소청출장소,0,0,0,0,0,0,0.000000,옹진군
161,자월면이작출장소,0,0,0,0,0,0,0.000000,옹진군

In [35]:
min_val = df['학급당학생수'].min()
max_val = df['학급당학생수'].max()

df['정규화값'] = (df['학급당학생수'] - min_val) / (max_val - min_val)
df

,행정동,학생수(계)_초,학급수(계)_초,학생수(계)_중,학급수(계)_중,총학생수,총학급수,학급당학생수,시군구,정규화값
0,가정1동,1558,66,910,30,2468,96,25.708333,서구,0.914887
1,가정2동,1216,51,0,0,1216,51,23.843137,서구,0.848510
2,가정3동,209,13,0,0,209,13,16.076923,서구,0.572132
3,가좌1동,298,20,0,0,298,20,14.900000,서구,0.530249
4,가좌2동,582,33,0,0,582,33,17.636364,서구,0.627629
...,...,...,...,...,...,...,...,...,...,...
157,계양3동,0,0,0,0,0,0,0.000000,계양구,0.000000
158,서도면볼음출장소,0,0,0,0,0,0,0.000000,강화군,0.000000
159,북도면장봉출장소,0,0,0,0,0,0,0.000000,옹진군,0.000000
160,대청면소청출장소,0,0,0,0,0,0,0.000000,옹진군,0.000000
161,자월면이작출장소,0,0,0,0,0,0,0.000000,옹진군,0.000000

In [36]:
df['가중치적용값'] = df['정규화값'] * 0.0820
df

,행정동,학생수(계)_초,학급수(계)_초,학생수(계)_중,학급수(계)_중,총학생수,총학급수,학급당학생수,시군구,정규화값,가중치적용값
0,가정1동,1558,66,910,30,2468,96,25.708333,서구,0.914887,0.075021
1,가정2동,1216,51,0,0,1216,51,23.843137,서구,0.848510,0.069578
2,가정3동,209,13,0,0,209,13,16.076923,서구,0.572132,0.046915
3,가좌1동,298,20,0,0,298,20,14.900000,서구,0.530249,0.043480
4,가좌2동,582,33,0,0,582,33,17.636364,서구,0.627629,0.051466
...,...,...,...,...,...,...,...,...,...,...,...
157,계양3동,0,0,0,0,0,0,0.000000,계양구,0.000000,0.000000
158,서도면볼음출장소,0,0,0,0,0,0,0.000000,강화군,0.000000,0.000000
159,북도면장봉출장소,0,0,0,0,0,0,0.000000,옹진군,0.000000,0.000000
160,대청면소청출장소,0,0,0,0,0,0,0.000000,옹진군,0.000000,0.000000
161,자월면이작출장소,0,0,0,0,0,0,0.000000,옹진군,0.000000,0.000000

In [38]:
cols = ['시군구'] + [col for col in df.columns if col != '시군구']
df = df[cols]
df

,시군구,행정동,학생수(계)_초,학급수(계)_초,학생수(계)_중,학급수(계)_중,총학생수,총학급수,학급당학생수,정규화값,가중치적용값
0,서구,가정1동,1558,66,910,30,2468,96,25.708333,0.914887,0.075021
1,서구,가정2동,1216,51,0,0,1216,51,23.843137,0.848510,0.069578
2,서구,가정3동,209,13,0,0,209,13,16.076923,0.572132,0.046915
3,서구,가좌1동,298,20,0,0,298,20,14.900000,0.530249,0.043480
4,서구,가좌2동,582,33,0,0,582,33,17.636364,0.627629,0.051466
...,...,...,...,...,...,...,...,...,...,...,...
157,계양구,계양3동,0,0,0,0,0,0,0.000000,0.000000,0.000000
158,강화군,서도면볼음출장소,0,0,0,0,0,0,0.000000,0.000000,0.000000
159,옹진군,북도면장봉출장소,0,0,0,0,0,0,0.000000,0.000000,0.000000
160,옹진군,대청면소청출장소,0,0,0,0,0,0,0.000000,0.000000,0.000000
161,옹진군,자월면이작출장소,0,0,0,0,0,0,0.000000,0.000000,0.000000

In [39]:
df.to_csv('최종2_인천학급당학생수.csv', index=False, encoding='utf-8-sig')

In [41]:
df = pd.read_csv('최종2_경기학급당학생수.csv', encoding='cp949')
df

    시군구\t행정동\t학생수(계)_초\t학급수(계)_초\t학생수(계)_중\t학급수(계)_중\t총학생수\t총학급수
0            고양시 일산서구\t가좌동\t762\t38\t613\t24\t1375\t62
1             구리시\t갈매동\t2420\t102\t1010\t34\t3430\t136
2          안양시 동안구\t갈산동\t1695\t69\t1135\t38\t2830\t107
3                         하남시\t감북동\t84\t8\t0\t0\t84\t8
4             하남시\t감일동\t3684\t156\t1261\t48\t4945\t204
..                                                 ...
269                   남양주시\t화도읍남부출장소\t0\t0\t0\t0\t0\t0
270                        남양주시\t양정동\t0\t0\t0\t0\t0\t0
271                        하남시\t신장1동\t0\t0\t0\t0\t0\t0
272                         하남시\t춘궁동\t0\t0\t0\t0\t0\t0
273                         하남시\t초이동\t0\t0\t0\t0\t0\t0

[274 rows x 1 columns]

In [42]:
df = pd.read_csv('최종2_경기학급당학생수.csv', encoding='cp949')
df

          시군구       행정동  학생수(계)_초  학급수(계)_초  학생수(계)_중  학급수(계)_중  총학생수  총학급수
0    고양시 일산서구       가좌동       762        38       613        24  1375    62
1         구리시       갈매동      2420       102      1010        34  3430   136
2     안양시 동안구       갈산동      1695        69      1135        38  2830   107
3         하남시       감북동        84         8         0         0    84     8
4         하남시       감일동      3684       156      1261        48  4945   204
..        ...       ...       ...       ...       ...       ...   ...   ...
269      남양주시  화도읍남부출장소         0         0         0         0     0     0
270      남양주시       양정동         0         0         0         0     0     0
271       하남시      신장1동         0         0         0         0     0     0
272       하남시       춘궁동         0         0         0         0     0     0
273       하남시       초이동         0         0         0         0     0     0

[274 rows x 8 columns]

In [43]:
df['전체_학급당학생수'] = df['총학생수'] / df['총학급수']
df

,시군구,행정동,학생수(계)_초,학급수(계)_초,학생수(계)_중,학급수(계)_중,총학생수,총학급수,전체_학급당학생수
0,고양시 일산서구,가좌동,762,38,613,24,1375,62,22.177419
1,구리시,갈매동,2420,102,1010,34,3430,136,25.220588
2,안양시 동안구,갈산동,1695,69,1135,38,2830,107,26.448598
3,하남시,감북동,84,8,0,0,84,8,10.500000
4,하남시,감일동,3684,156,1261,48,4945,204,24.240196
...,...,...,...,...,...,...,...,...,...
269,남양주시,화도읍남부출장소,0,0,0,0,0,0,NaN
270,남양주시,양정동,0,0,0,0,0,0,NaN
271,하남시,신장1동,0,0,0,0,0,0,NaN
272,하남시,춘궁동,0,0,0,0,0,0,NaN
273,하남시,초이동,0,0,0,0,0,0,NaN

In [44]:
df = df.fillna(0)

In [45]:
df

,시군구,행정동,학생수(계)_초,학급수(계)_초,학생수(계)_중,학급수(계)_중,총학생수,총학급수,전체_학급당학생수
0,고양시 일산서구,가좌동,762,38,613,24,1375,62,22.177419
1,구리시,갈매동,2420,102,1010,34,3430,136,25.220588
2,안양시 동안구,갈산동,1695,69,1135,38,2830,107,26.448598
3,하남시,감북동,84,8,0,0,84,8,10.500000
4,하남시,감일동,3684,156,1261,48,4945,204,24.240196
...,...,...,...,...,...,...,...,...,...
269,남양주시,화도읍남부출장소,0,0,0,0,0,0,0.000000
270,남양주시,양정동,0,0,0,0,0,0,0.000000
271,하남시,신장1동,0,0,0,0,0,0,0.000000
272,하남시,춘궁동,0,0,0,0,0,0,0.000000
273,하남시,초이동,0,0,0,0,0,0,0.000000

In [46]:
min_val = df['전체_학급당학생수'].min()
max_val = df['전체_학급당학생수'].max()

df['정규화값'] = (df['전체_학급당학생수'] - min_val) / (max_val - min_val)
df

,시군구,행정동,학생수(계)_초,학급수(계)_초,학생수(계)_중,학급수(계)_중,총학생수,총학급수,전체_학급당학생수,정규화값
0,고양시 일산서구,가좌동,762,38,613,24,1375,62,22.177419,0.779739
1,구리시,갈매동,2420,102,1010,34,3430,136,25.220588,0.886734
2,안양시 동안구,갈산동,1695,69,1135,38,2830,107,26.448598,0.929910
3,하남시,감북동,84,8,0,0,84,8,10.500000,0.369171
4,하남시,감일동,3684,156,1261,48,4945,204,24.240196,0.852264
...,...,...,...,...,...,...,...,...,...,...
269,남양주시,화도읍남부출장소,0,0,0,0,0,0,0.000000,0.000000
270,남양주시,양정동,0,0,0,0,0,0,0.000000,0.000000
271,하남시,신장1동,0,0,0,0,0,0,0.000000,0.000000
272,하남시,춘궁동,0,0,0,0,0,0,0.000000,0.000000
273,하남시,초이동,0,0,0,0,0,0,0.000000,0.000000

In [47]:
df['가중치적용값'] = df['정규화값'] * 0.0526
df

,시군구,행정동,학생수(계)_초,학급수(계)_초,학생수(계)_중,학급수(계)_중,총학생수,총학급수,전체_학급당학생수,정규화값,가중치적용값
0,고양시 일산서구,가좌동,762,38,613,24,1375,62,22.177419,0.779739,0.041014
1,구리시,갈매동,2420,102,1010,34,3430,136,25.220588,0.886734,0.046642
2,안양시 동안구,갈산동,1695,69,1135,38,2830,107,26.448598,0.929910,0.048913
3,하남시,감북동,84,8,0,0,84,8,10.500000,0.369171,0.019418
4,하남시,감일동,3684,156,1261,48,4945,204,24.240196,0.852264,0.044829
...,...,...,...,...,...,...,...,...,...,...,...
269,남양주시,화도읍남부출장소,0,0,0,0,0,0,0.000000,0.000000,0.000000
270,남양주시,양정동,0,0,0,0,0,0,0.000000,0.000000,0.000000
271,하남시,신장1동,0,0,0,0,0,0,0.000000,0.000000,0.000000
272,하남시,춘궁동,0,0,0,0,0,0,0.000000,0.000000,0.000000
273,하남시,초이동,0,0,0,0,0,0,0.000000,0.000000,0.000000

In [49]:
df.to_csv('최종2_경기학급당학생수.csv', index=False, encoding='utf-8-sig')

In [51]:
df = pd.read_csv('최종2_서울학급당학생수.csv', encoding='utf-8-sig')
df

,시군구,행정동,학생수(계)_초,학급수(계)_초,학생수(계)_중,학급수(계)_중,총학생수,총학급수,학급당학생수,정규화값,가중치적용값
0,송파구,가락1동,1833,84,853,30,2686,114,23.561404,0.721794,0.059187
1,송파구,가락2동,1409,66,896,34,2305,100,23.050000,0.706127,0.057902
2,송파구,가락본동,693,42,736,30,1429,72,19.847222,0.608011,0.049857
3,구로구,가리봉동,267,19,0,0,267,19,14.052632,0.430496,0.035301
4,금천구,가산동,265,15,0,0,265,15,17.666667,0.541211,0.044379
...,...,...,...,...,...,...,...,...,...,...,...
424,관악구,신림동,0,0,0,0,0,0,0.000000,0.000000,0.000000
425,종로구,창신2동,0,0,0,0,0,0,0.000000,0.000000,0.000000
426,서대문구,북가좌2동,0,0,0,0,0,0,0.000000,0.000000,0.000000
427,성동구,성수1가2동,0,0,0,0,0,0,0.000000,0.000000,0.000000
428,중랑구,중화2동,0,0,0,0,0,0,0.000000,0.000000,0.000000

In [52]:
df['가중치적용값'] = df['정규화값'] * 0.0526
df

,시군구,행정동,학생수(계)_초,학급수(계)_초,학생수(계)_중,학급수(계)_중,총학생수,총학급수,학급당학생수,정규화값,가중치적용값
0,송파구,가락1동,1833,84,853,30,2686,114,23.561404,0.721794,0.037966
1,송파구,가락2동,1409,66,896,34,2305,100,23.050000,0.706127,0.037142
2,송파구,가락본동,693,42,736,30,1429,72,19.847222,0.608011,0.031981
3,구로구,가리봉동,267,19,0,0,267,19,14.052632,0.430496,0.022644
4,금천구,가산동,265,15,0,0,265,15,17.666667,0.541211,0.028468
...,...,...,...,...,...,...,...,...,...,...,...
424,관악구,신림동,0,0,0,0,0,0,0.000000,0.000000,0.000000
425,종로구,창신2동,0,0,0,0,0,0,0.000000,0.000000,0.000000
426,서대문구,북가좌2동,0,0,0,0,0,0,0.000000,0.000000,0.000000
427,성동구,성수1가2동,0,0,0,0,0,0,0.000000,0.000000,0.000000
428,중랑구,중화2동,0,0,0,0,0,0,0.000000,0.000000,0.000000

In [53]:
df.to_csv('최종2_서울학급당학생수.csv', index=False, encoding='utf-8-sig')

In [54]:
df = pd.read_csv('최종2_인천학급당학생수.csv', encoding='utf-8-sig')
df

,시군구,행정동,학생수(계)_초,학급수(계)_초,학생수(계)_중,학급수(계)_중,총학생수,총학급수,학급당학생수,정규화값,가중치적용값
0,서구,가정1동,1558,66,910,30,2468,96,25.708333,0.914887,0.075021
1,서구,가정2동,1216,51,0,0,1216,51,23.843137,0.848510,0.069578
2,서구,가정3동,209,13,0,0,209,13,16.076923,0.572132,0.046915
3,서구,가좌1동,298,20,0,0,298,20,14.900000,0.530249,0.043480
4,서구,가좌2동,582,33,0,0,582,33,17.636364,0.627629,0.051466
...,...,...,...,...,...,...,...,...,...,...,...
157,계양구,계양3동,0,0,0,0,0,0,0.000000,0.000000,0.000000
158,강화군,서도면볼음출장소,0,0,0,0,0,0,0.000000,0.000000,0.000000
159,옹진군,북도면장봉출장소,0,0,0,0,0,0,0.000000,0.000000,0.000000
160,옹진군,대청면소청출장소,0,0,0,0,0,0,0.000000,0.000000,0.000000
161,옹진군,자월면이작출장소,0,0,0,0,0,0,0.000000,0.000000,0.000000

In [55]:
df['가중치적용값'] = df['정규화값'] * 0.0526
df

,시군구,행정동,학생수(계)_초,학급수(계)_초,학생수(계)_중,학급수(계)_중,총학생수,총학급수,학급당학생수,정규화값,가중치적용값
0,서구,가정1동,1558,66,910,30,2468,96,25.708333,0.914887,0.048123
1,서구,가정2동,1216,51,0,0,1216,51,23.843137,0.848510,0.044632
2,서구,가정3동,209,13,0,0,209,13,16.076923,0.572132,0.030094
3,서구,가좌1동,298,20,0,0,298,20,14.900000,0.530249,0.027891
4,서구,가좌2동,582,33,0,0,582,33,17.636364,0.627629,0.033013
...,...,...,...,...,...,...,...,...,...,...,...
157,계양구,계양3동,0,0,0,0,0,0,0.000000,0.000000,0.000000
158,강화군,서도면볼음출장소,0,0,0,0,0,0,0.000000,0.000000,0.000000
159,옹진군,북도면장봉출장소,0,0,0,0,0,0,0.000000,0.000000,0.000000
160,옹진군,대청면소청출장소,0,0,0,0,0,0,0.000000,0.000000,0.000000
161,옹진군,자월면이작출장소,0,0,0,0,0,0,0.000000,0.000000,0.000000

In [56]:
df.to_csv('최종2_인천학급당학생수.csv', index=False, encoding='utf-8-sig')

In [58]:
df = pd.read_csv('최종-학급당학생수.csv', encoding='cp949')
df

,시군구,행정동,학생수(계)_초,학급수(계)_초,학생수(계)_중,학급수(계)_중,총학생수,총학급수,학급당학생수,정규화값,가중치적용값
0,송파구,가락1동,1833,84,853,30,2686,114,23.561404,0.721794,0.037966
1,송파구,가락2동,1409,66,896,34,2305,100,23.050000,0.706127,0.037142
2,송파구,가락본동,693,42,736,30,1429,72,19.847222,0.608011,0.031981
3,구로구,가리봉동,267,19,0,0,267,19,14.052632,0.430496,0.022644
4,금천구,가산동,265,15,0,0,265,15,17.666667,0.541211,0.028468
...,...,...,...,...,...,...,...,...,...,...,...
860,계양구,계양3동,0,0,0,0,0,0,0.000000,0.000000,0.000000
861,강화군,서도면볼음출장소,0,0,0,0,0,0,0.000000,0.000000,0.000000
862,옹진군,북도면장봉출장소,0,0,0,0,0,0,0.000000,0.000000,0.000000
863,옹진군,대청면소청출장소,0,0,0,0,0,0,0.000000,0.000000,0.000000
864,옹진군,자월면이작출장소,0,0,0,0,0,0,0.000000,0.000000,0.000000

In [59]:
df['행정동'].value_counts()[df['행정동'].value_counts() >= 2]

행정동
신사동     4
신촌동     3
위례동     3
중앙동     3
논현1동    2
연희동     2
금곡동     2
신흥동     2
논현2동    2
Name: count, dtype: int64

In [67]:
df = pd.read_csv('유아인구통합.csv', encoding='utf-8-sig')
df

       시도명 시군구명      읍면동명  유아인구
0    서울특별시  종로구     청운효자동   250
1    서울특별시  종로구       사직동   189
2    서울특별시  종로구       삼청동    34
3    서울특별시  종로구       부암동   151
4    서울특별시  종로구       평창동   459
..     ...  ...       ...   ...
858  인천광역시  옹진군       덕적면    12
859  인천광역시  옹진군       영흥면    98
860  인천광역시  옹진군       자월면    10
861  인천광역시  옹진군  자월면이작출장소     2
862  인천광역시  옹진군       연평면    35

[863 rows x 4 columns]

In [68]:
df2 = pd.read_csv('어린이집합계3.csv', encoding='utf-8-sig')
df2

         시군구   행정동  어린이집수  유아인구합계   유아천명당시설수      정규화값    가중치적용값
0        송파구  가락1동     14    1520   9.210526  0.027632  0.002266
1        송파구  가락2동     14     868  16.129032  0.048387  0.003968
2        송파구  가락본동     11     705  15.602837  0.046809  0.003838
3        구로구  가리봉동      2      94  21.276596  0.063830  0.005234
4        금천구   가산동      9     364  24.725275  0.074176  0.006082
..       ...   ...    ...     ...        ...       ...       ...
837      용산구   후암동      5     292  17.123288  0.051370  0.004212
838     동대문구  휘경1동      6     661   9.077156  0.027231  0.002233
839     동대문구  휘경2동     12     441  27.210884  0.081633  0.006694
840      동작구   흑석동     15    1102  13.611615  0.040835  0.003348
841  고양시 덕양구   흥도동     17    1123  15.138023  0.045414  0.003724

[842 rows x 7 columns]

In [71]:
set(df['읍면동명'])-set(df2['행정동'])

{'감북동',
 '교동면',
 '내가면',
 '노량진2동',
 '대청면소청출장소',
 '반포본동',
 '북도면장봉출장소',
 '서도면',
 '서도면볼음출장소',
 '송해면',
 '양도면',
 '양사면',
 '용유동',
 '율목동',
 '자월면이작출장소',
 '잠실7동',
 '춘궁동',
 '학온동',
 '화도면',
 '화도읍남부출장소',
 '화도읍동부출장소'}