In [1]:
# %matplotlib notebook

import pandas as pd
import matplotlib.pyplot as plt
from matplotlib import font_manager, rc

# 한글깨짐처리
font_loc = "c:/Windows/Fonts/malgun.ttf"
font_name=font_manager.FontProperties(fname=font_loc).get_name()
rc('font', family=font_name)

In [4]:
df = pd.read_csv(
    'clean_elementary_gg.csv')
df

,학교명,주소내역,상세주소내역,학교도로명 주소,학교도로명 상세주소,위도,경도,동읍면
0,가평마장초등학교,경기도 가평군 가평읍,357번지.,경기도 가평군 가평읍 각담말길 15,(가평읍),37.860340,127.514300,가평읍
1,가평초등학교,경기도 가평군 가평읍,읍내리557.,경기도 가평군 가평읍 향교로 23,(가평읍),37.800000,127.500000,가평읍
2,대성초등학교,경기도 가평군 청평면 대성리,399-16.,경기도 가평군 청평면 경춘로 75,"(청평면, 대성초등학교)",37.683060,127.377648,청평면
3,목동초등학교,경기도 가평군 북면 이곡리,13-45.,경기도 가평군 북면 석장모루길 13,", 목동초등학교 (북면)",37.879224,127.548063,목동
4,목동초등학교명지분교장,경기도 가평군 북면 적목리,162번지.,경기도 가평군 북면 가화로 2680,(북면),37.971046,127.454358,북면
...,...,...,...,...,...,...,...,...
1406,모담초등학교,경기도 김포시 운양동 1295-2,.,경기도 김포시 운양로 158,(운양동),37.656730,126.674743,운양동
1407,평택화양초등학교,경기도 평택시 안중읍 현화리,.,경기도 평택시 현덕면 화양현화2로 10,NaN,36.984942,126.905424,NaN
1408,평택연화초등학교,경기도 평택시 현덕면 운정리 5-13,.,경기도 평택시 현덕면 운정화양1로 95,NaN,36.973650,126.907344,NaN
1409,이천중리초등학교,경기도 이천시 증일동 115,.,경기도 이천시 시청중앙로 10,"(증일동,이천중리초등학교)",NaN,NaN,증일동
1410,위례해솔초등학교,경기도 성남시 수정구 복정동 156,.,경기도 성남시 수정구 남위례로 131,위례해솔초등학교,NaN,NaN,NaN

In [5]:
cities = ['성남', '고양', '부천', '광명', '하남', '남양주', '용인', '김포', '구리', '안양']

pattern = '|'.join(cities)

df_filtered = df[df['학교도로명 주소'].str.contains(pattern, na=False)]

In [6]:
df_filtered.head()

,학교명,주소내역,상세주소내역,학교도로명 주소,학교도로명 상세주소,위도,경도,동읍면
16,가람초등학교,경기도 고양시 덕양구 행신3동,926.,경기도 고양시 덕양구 행신로311번길 78,"(행신동,가람초등학교)",37.623714,126.842197,행신동
17,강선초등학교,경기도 고양시 일산서구 주엽동,64번지.,경기도 고양시 일산서구 강선로 77,", 강선초등학교 (주엽동)",37.671247,126.765011,주엽동
18,고봉초등학교,경기도 고양시 일산동구 중산동,1554-1.,경기도 고양시 일산동구 중산로 280,", 고봉초등학교 (중산동)",37.696200,126.782200,중산동
19,고양백석초등학교,NaN,.,경기도 고양시 일산동구 강촌로 140,"(백석동,고양백석초등학교)",37.652148,126.789045,백석동
20,고양신일초등학교,경기도 고양시 일산서구 일산3동,1075번지.,경기도 고양시 일산서구 강선로 183,", 고양신일초등학교 (일산동)",37.679495,126.770888,일산동

In [9]:
df.to_csv('clean_elementary_gg.csv', index=False, encoding='utf-8-sig')

In [10]:
df = pd.read_csv(
    'clean_elementary_gg.csv')
df

,학교명,주소내역,상세주소내역,학교도로명 주소,학교도로명 상세주소,위도,경도,동읍면
0,가평마장초등학교,경기도 가평군 가평읍,357번지.,경기도 가평군 가평읍 각담말길 15,(가평읍),37.860340,127.514300,가평읍
1,가평초등학교,경기도 가평군 가평읍,읍내리557.,경기도 가평군 가평읍 향교로 23,(가평읍),37.800000,127.500000,가평읍
2,대성초등학교,경기도 가평군 청평면 대성리,399-16.,경기도 가평군 청평면 경춘로 75,"(청평면, 대성초등학교)",37.683060,127.377648,청평면
3,목동초등학교,경기도 가평군 북면 이곡리,13-45.,경기도 가평군 북면 석장모루길 13,", 목동초등학교 (북면)",37.879224,127.548063,목동
4,목동초등학교명지분교장,경기도 가평군 북면 적목리,162번지.,경기도 가평군 북면 가화로 2680,(북면),37.971046,127.454358,북면
...,...,...,...,...,...,...,...,...
1406,모담초등학교,경기도 김포시 운양동 1295-2,.,경기도 김포시 운양로 158,(운양동),37.656730,126.674743,운양동
1407,평택화양초등학교,경기도 평택시 안중읍 현화리,.,경기도 평택시 현덕면 화양현화2로 10,NaN,36.984942,126.905424,NaN
1408,평택연화초등학교,경기도 평택시 현덕면 운정리 5-13,.,경기도 평택시 현덕면 운정화양1로 95,NaN,36.973650,126.907344,NaN
1409,이천중리초등학교,경기도 이천시 증일동 115,.,경기도 이천시 시청중앙로 10,"(증일동,이천중리초등학교)",NaN,NaN,증일동
1410,위례해솔초등학교,경기도 성남시 수정구 복정동 156,.,경기도 성남시 수정구 남위례로 131,위례해솔초등학교,NaN,NaN,NaN

In [11]:
cities = ['성남', '고양', '부천', '광명', '하남', '남양주', '용인', '김포', '구리', '안양']

pattern = '|'.join(cities)

df_filtered = df[df['학교도로명 주소'].str.contains(pattern, na=False)]

In [13]:
df_filtered.to_csv('clean_elementary_gg.csv', index=False, encoding='utf-8-sig')
df_filtered.head()

,학교명,주소내역,상세주소내역,학교도로명 주소,학교도로명 상세주소,위도,경도,동읍면
16,가람초등학교,경기도 고양시 덕양구 행신3동,926.,경기도 고양시 덕양구 행신로311번길 78,"(행신동,가람초등학교)",37.623714,126.842197,행신동
17,강선초등학교,경기도 고양시 일산서구 주엽동,64번지.,경기도 고양시 일산서구 강선로 77,", 강선초등학교 (주엽동)",37.671247,126.765011,주엽동
18,고봉초등학교,경기도 고양시 일산동구 중산동,1554-1.,경기도 고양시 일산동구 중산로 280,", 고봉초등학교 (중산동)",37.696200,126.782200,중산동
19,고양백석초등학교,NaN,.,경기도 고양시 일산동구 강촌로 140,"(백석동,고양백석초등학교)",37.652148,126.789045,백석동
20,고양신일초등학교,경기도 고양시 일산서구 일산3동,1075번지.,경기도 고양시 일산서구 강선로 183,", 고양신일초등학교 (일산동)",37.679495,126.770888,일산동

In [14]:
df_filtered.to_csv('clean_elementary_gg.csv', index=False, encoding='utf-8-sig')

In [16]:
REST_API_KEY = "YOUR_KAKAO_API_KEY"

def get_addr_info(address):
    url = 'https://dapi.kakao.com/v2/local/search/address.json'
    headers = {"Authorization": f"KakaoAK {REST_API_KEY}"}
    params = {'query': address}
    
    try:
        response = requests.get(url, headers=headers, params=params)
        if response.status_code == 200:
            result = response.json()
            if result['documents']:
                addr_data = result['documents'][0]['address']
                lat = addr_data['y']  # 위도
                lon = addr_data['x']  # 경도
                b_dong = addr_data['region_3depth_name']  # 법정동
                
                return lat, lon, b_dong
        return None, None, None
    except:
        return None, None, None

# ✅ 3. CSV 불러오기 (네 파일)
df = pd.read_csv('clean_elementary_seoul.csv', encoding='utf-8-sig')

# ✅ 4. API 적용 (주소 컬럼 기준)
print("좌표 변환 중...")
info_list = []

for addr in df['학교도로명 주소']:
    info = get_addr_info(addr)
    info_list.append(info)
    time.sleep(0.2)  # ⭐ API 제한 방지 (중요)

# ✅ 5. 컬럼 추가
df['위도'], df['경도'], df['법정동'] = zip(*info_list)

# ✅ 6. 저장
df.to_csv('clean_elementary_seoul_with_coord.csv', index=False, encoding='utf-8-sig')

print("완료!")
df.head()

좌표 변환 중...
완료!

,학교명,주소내역,상세주소내역,학교도로명 주소,학교도로명 상세주소,위도,경도,동읍면,법정동
0,가람초등학교,경기도 고양시 덕양구 행신3동,926.,경기도 고양시 덕양구 행신로311번길 78,"(행신동,가람초등학교)",37.6237194495748,126.842224411918,행신동,행신동
1,강선초등학교,경기도 고양시 일산서구 주엽동,64번지.,경기도 고양시 일산서구 강선로 77,", 강선초등학교 (주엽동)",37.67122822894,126.764625731644,주엽동,주엽동
2,고봉초등학교,경기도 고양시 일산동구 중산동,1554-1.,경기도 고양시 일산동구 중산로 280,", 고봉초등학교 (중산동)",37.6961394442868,126.782620493164,중산동,중산동
3,고양백석초등학교,NaN,.,경기도 고양시 일산동구 강촌로 140,"(백석동,고양백석초등학교)",37.6521391747615,126.78905766637,백석동,백석동
4,고양신일초등학교,경기도 고양시 일산서구 일산3동,1075번지.,경기도 고양시 일산서구 강선로 183,", 고양신일초등학교 (일산동)",37.6795496217272,126.770830238317,일산동,일산동

In [17]:
df = pd.read_csv(
    'clean_elementary_seoul.csv')
df

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc7 in position 0: invalid continuation byte

In [18]:
df = pd.read_csv(
    'project/elementary_seoul.csv')
df

,시도교육청,교육지원청,지역,정보공시 학교코드,학교명,학교급코드,설립구분,학교특성,분교여부,설립유형,...,학교도로명 상세주소,위도,경도,전화번호,팩스번호,홈페이지 주소,남녀공학 구분,폐교여부,폐교일자,휴교여부
0,교육부,서울특별시강남서초교육지원청,서울특별시 서초구,S000003511,서울교육대학교부설초등학교,2,국립,NaN,N,부설,...,"(서초동,서울교대초등학교)",37.490739,127.015424,02-6009-6000,02-6009-6090,http://snueps.sen.es.kr/,남녀공학,N,NaN,N
1,교육부,교육부,서울특별시 종로구,S000003563,서울대학교사범대학부설초등학교,2,국립,NaN,N,부설,...,"(동숭동,서울사대부설초등학교)",37.577791,127.002875,02-768-1500,02-766-4085,http://snu.sen.es.kr,남녀공학,N,NaN,N
2,서울특별시교육청,서울특별시강남서초교육지원청,서울특별시 강남구,S010000737,서울개원초등학교,2,공립,NaN,N,단설,...,"(개포동,개원초등학교)",37.481618,127.058738,02-2138-1940,02-2138-1945,https://gaewon.sen.es.kr,남녀공학,N,NaN,N
3,서울특별시교육청,서울특별시강남서초교육지원청,서울특별시 강남구,S010000738,서울개일초등학교,2,공립,NaN,N,단설,...,", 개일초등학교 (개포동,개일초등학교)",37.486214,127.057742,02-571-8320,02-571-8325,http://gaeil.sen.es.kr,남녀공학,N,NaN,N
4,서울특별시교육청,서울특별시강남서초교육지원청,서울특별시 강남구,S010000739,서울개포초등학교,2,공립,NaN,N,단설,...,"(개포동, 개포초등학교)",37.486805,127.069977,02-6952-4092,02-6952-4903,https://gaepo.sen.es.kr/,남녀공학,N,NaN,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,서울특별시교육청,서울특별시남부교육지원청,서울특별시 구로구,S010006432,서울항동초등학교,2,공립,NaN,N,단설,...,(항동),37.476731,126.823929,02-480-3600,02-3666-9841,http://hangdong.sen.es.kr,남녀공학,N,NaN,N
610,서울특별시교육청,서울특별시강동송파교육지원청,서울특별시 송파구,S010006433,서울해누리초등학교,2,공립,NaN,N,단설,...,(가락동),37.498364,127.101956,02-3469-6800,02-3469-6800,http://haenuri.sen.es.kr,남녀공학,N,NaN,N
611,서울특별시교육청,서울특별시동부교육지원청,서울특별시 중랑구,S010006476,서울양원숲초등학교,2,공립,NaN,N,단설,...,"(망우동, 서울양원숲초등학교)",37.608890,127.105540,02-493-9701,02-493-9497,https://yangwonsoop.sen.es.kr/index.do,남녀공학,N,NaN,N
612,서울특별시교육청,서울특별시강남서초교육지원청,서울특별시 강남구,S010006510,서울개현초등학교,2,공립,NaN,N,병설,...,"(개포동, 서울개현초등학교)",37.481026,127.062043,02-2138-1937,02-2138-1938,https://gaehyeon.sen.es.kr,남녀공학,N,NaN,N
613,서울특별시교육청,서울특별시강동송파교육지원청,서울특별시 강동구,S010006543,서울강빛초등학교,2,공립,NaN,N,단설,...,"(강일동, 강빛초중통합학교)",37.574172,127.170940,02-6951-3963,02-6951-3966,http://gbe.sen.es.kr,남녀공학,N,NaN,N

In [19]:
df2 = pd.read_csv(
    'project/elementary_seoul.csv',
    usecols=[4, 18, 19, 20, 21]
)
df2

,학교명,학교도로명 주소,학교도로명 상세주소,위도,경도
0,서울교육대학교부설초등학교,서울특별시 서초구 서초중앙로 96,"(서초동,서울교대초등학교)",37.490739,127.015424
1,서울대학교사범대학부설초등학교,서울특별시 종로구 대학로 64,"(동숭동,서울사대부설초등학교)",37.577791,127.002875
2,서울개원초등학교,서울특별시 강남구 선릉로 29,"(개포동,개원초등학교)",37.481618,127.058738
3,서울개일초등학교,서울특별시 강남구 개포로 401,", 개일초등학교 (개포동,개일초등학교)",37.486214,127.057742
4,서울개포초등학교,서울특별시 강남구 삼성로4길 30,"(개포동, 개포초등학교)",37.486805,127.069977
...,...,...,...,...,...
609,서울항동초등학교,서울특별시 구로구 연동로 178,(항동),37.476731,126.823929
610,서울해누리초등학교,서울특별시 송파구 송파대로37길 95,(가락동),37.498364,127.101956
611,서울양원숲초등학교,서울특별시 중랑구 양원역로 95,"(망우동, 서울양원숲초등학교)",37.608890,127.105540
612,서울개현초등학교,서울특별시 강남구 선릉로 15,"(개포동, 서울개현초등학교)",37.481026,127.062043
613,서울강빛초등학교,서울특별시 강동구 아리수로93다길 1,"(강일동, 강빛초중통합학교)",37.574172,127.170940

In [21]:
df2.to_csv('clean_elementary_seoul.csv', index=False, encoding='utf-8-sig')

In [22]:
REST_API_KEY = "YOUR_KAKAO_API_KEY"

def get_addr_info(address):
    url = 'https://dapi.kakao.com/v2/local/search/address.json'
    headers = {"Authorization": f"KakaoAK {REST_API_KEY}"}
    params = {'query': address}
    
    try:
        response = requests.get(url, headers=headers, params=params)
        if response.status_code == 200:
            result = response.json()
            if result['documents']:
                addr_data = result['documents'][0]['address']
                lat = addr_data['y']  # 위도
                lon = addr_data['x']  # 경도
                b_dong = addr_data['region_3depth_name']  # 법정동
                
                return lat, lon, b_dong
        return None, None, None
    except:
        return None, None, None

# ✅ 3. CSV 불러오기 (네 파일)
df = pd.read_csv('clean_elementary_seoul.csv', encoding='utf-8-sig')

# ✅ 4. API 적용 (주소 컬럼 기준)
print("좌표 변환 중...")
info_list = []

for addr in df['학교도로명 주소']:
    info = get_addr_info(addr)
    info_list.append(info)
    time.sleep(0.2)  # ⭐ API 제한 방지 (중요)

# ✅ 5. 컬럼 추가
df['위도'], df['경도'], df['법정동'] = zip(*info_list)

# ✅ 6. 저장
df.to_csv('clean_elementary_seoul_with_coord.csv', index=False, encoding='utf-8-sig')

print("완료!")
df.head()

좌표 변환 중...
완료!

,학교명,학교도로명 주소,학교도로명 상세주소,위도,경도,법정동
0,서울교육대학교부설초등학교,서울특별시 서초구 서초중앙로 96,"(서초동,서울교대초등학교)",37.4907404857731,127.015424537648,서초동
1,서울대학교사범대학부설초등학교,서울특별시 종로구 대학로 64,"(동숭동,서울사대부설초등학교)",37.5775997032467,127.004295521787,이화동
2,서울개원초등학교,서울특별시 강남구 선릉로 29,"(개포동,개원초등학교)",37.4816986136485,127.059450501428,개포동
3,서울개일초등학교,서울특별시 강남구 개포로 401,", 개일초등학교 (개포동,개일초등학교)",37.4862353839469,127.057790853452,개포동
4,서울개포초등학교,서울특별시 강남구 삼성로4길 30,"(개포동, 개포초등학교)",37.4863349159759,127.070310042973,개포동

In [25]:
df = pd.read_csv(
    'project/acad.csv',
    usecols=[1,2,5,20,21])
df

,시도교육청명,행정구역명,학원명,도로명주소,도로명상세주소
0,경기도교육청,남양주시,1교시독서논술교습소,경기도 남양주시 별내5로 81,", 102호 (별내동, 남양주 별내 스위첸 아파트)"
1,경기도교육청,남양주시,CS수학교습소,경기도 남양주시 별내3로 340,", 404호 일부 (별내동)"
2,경기도교육청,남양주시,DMT수학교습소,경기도 남양주시 화도읍 수레로1233번길 10,", 204호 (화도읍)"
3,경기도교육청,남양주시,ECN영어교습소,경기도 남양주시 다산중앙로146번길 12-19,", 702호 (다산동)"
4,경기도교육청,남양주시,EY수학교습소,경기도 남양주시 두물로11번길 40-20,", 2층 일부 (별내동)"
...,...,...,...,...,...
2038,경기도교육청,남양주시,황소학원,경기도 남양주시 별내면 청학로92번길 35-6,", 1층 일부 (별내면, 청송빌딩)"
2039,경기도교육청,남양주시,후마드원클래스원격학원,경기도 남양주시 진접읍 해밀예당1로 220,707호 일부
2040,경기도교육청,남양주시,힐링댄스스포츠학원,경기도 남양주시 다산중앙로123번길 21-3,", 605호 (다산동)"
2041,경기도교육청,남양주시,힐즈잉글리쉬학원,경기도 남양주시 다산순환로 430,(다산동) 404호
2042,경기도교육청,남양주시,힘학원,경기도 남양주시 도농로 49,", 301호, 302호 (다산동, 부영사랑으로아파트 상가)"

In [27]:
df.to_csv('clean_acad_n.csv', index=False, encoding='utf-8-sig')

In [29]:
# ✅ 1. 카카오 REST API 키 넣기 (여기!!)
REST_API_KEY = "YOUR_KAKAO_API_KEY"

# ✅ 2. 주소 → (위도, 경도, 법정동) 변환 함수
def get_addr_info(address):
    url = 'https://dapi.kakao.com/v2/local/search/address.json'
    headers = {"Authorization": f"KakaoAK {REST_API_KEY}"}
    params = {'query': address}
    
    try:
        response = requests.get(url, headers=headers, params=params)
        if response.status_code == 200:
            result = response.json()
            if result['documents']:
                addr_data = result['documents'][0]['address']
                lat = addr_data['y']  # 위도
                lon = addr_data['x']  # 경도
                b_dong = addr_data['region_3depth_name']  # 법정동
                
                return lat, lon, b_dong
        return None, None, None
    except:
        return None, None, None

# ✅ 3. CSV 불러오기 (네 파일)
df = pd.read_csv('clean_acad_n.csv', encoding='utf-8-sig')

# ✅ 4. API 적용 (주소 컬럼 기준)
print("좌표 변환 중...")
info_list = []

for addr in df['도로명주소']:
    info = get_addr_info(addr)
    info_list.append(info)
    time.sleep(0.2)  # ⭐ API 제한 방지 (중요)

# ✅ 5. 컬럼 추가
df['위도'], df['경도'], df['법정동'] = zip(*info_list)

# ✅ 6. 저장
df.to_csv('clean_acad_index.csv', index=False, encoding='utf-8-sig')

print("완료!")
df.head()

좌표 변환 중...
완료!

,시도교육청명,행정구역명,학원명,도로명주소,도로명상세주소,위도,경도,법정동
0,경기도교육청,남양주시,1교시독서논술교습소,경기도 남양주시 별내5로 81,", 102호 (별내동, 남양주 별내 스위첸 아파트)",37.6574314086709,127.116795681766,별내동
1,경기도교육청,남양주시,CS수학교습소,경기도 남양주시 별내3로 340,", 404호 일부 (별내동)",37.6676939167694,127.11663709946,별내동
2,경기도교육청,남양주시,DMT수학교습소,경기도 남양주시 화도읍 수레로1233번길 10,", 204호 (화도읍)",37.6473228083987,127.301144925654,화도읍 창현리
3,경기도교육청,남양주시,ECN영어교습소,경기도 남양주시 다산중앙로146번길 12-19,", 702호 (다산동)",37.625606410577,127.154831476468,다산동
4,경기도교육청,남양주시,EY수학교습소,경기도 남양주시 두물로11번길 40-20,", 2층 일부 (별내동)",37.6573864488721,127.125058117978,별내동

In [30]:
df = pd.read_csv(
    'hanam.csv')
df

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc7 in position 0: invalid continuation byte

In [35]:
df = pd.read_csv(
    'project/mid_student_seoul.csv', usecols=[4,24,25])
df

                  학교명  학급수(계)  학생수(계)
0      서울대학교사범대학부설중학교      25     573
1    서울대학교사범대학부설여자중학교      19     336
2               개원중학교      31     940
3               개포중학교      36    1014
4               경원중학교      35    1047
..                ...     ...     ...
383             신길중학교      29     711
384           마곡하늬중학교      30     795
385            해누리중학교      30     853
386             강빛중학교      15     340
387    아현중학교부설방송통신중학교      18     259

[388 rows x 3 columns]

In [38]:
df.to_csv('clean_mid_student_seoul.csv', index=False, encoding='utf-8-sig')

In [40]:
df = pd.read_csv(
    'project/ele_student_seoul.csv', usecols=[4,33,34])
df

                 학교명  학급수(계)  학생수(계)
0      서울교육대학교부설초등학교      28     611
1    서울대학교사범대학부설초등학교      31     570
2           서울개원초등학교      44    1006
3           서울개일초등학교      33     834
4           서울개포초등학교      43     886
..               ...     ...     ...
601         서울항동초등학교      70    1478
602        서울해누리초등학교      32     700
603        서울양원숲초등학교      36     779
604         서울개현초등학교      34     800
605         서울강빛초등학교      37     978

[606 rows x 3 columns]

In [41]:
df.to_csv('clean_ele_student_seoul.csv', index=False, encoding='utf-8-sig')

In [44]:
df2 = pd.read_csv(
    'clean_elementary_seoul_with_coord.csv')
df2

,학교명,학교도로명 주소,학교도로명 상세주소,위도,경도,법정동
0,서울교육대학교부설초등학교,서울특별시 서초구 서초중앙로 96,"(서초동,서울교대초등학교)",37.490740,127.015425,서초동
1,서울대학교사범대학부설초등학교,서울특별시 종로구 대학로 64,"(동숭동,서울사대부설초등학교)",37.577600,127.004296,이화동
2,서울개원초등학교,서울특별시 강남구 선릉로 29,"(개포동,개원초등학교)",37.481699,127.059451,개포동
3,서울개일초등학교,서울특별시 강남구 개포로 401,", 개일초등학교 (개포동,개일초등학교)",37.486235,127.057791,개포동
4,서울개포초등학교,서울특별시 강남구 삼성로4길 30,"(개포동, 개포초등학교)",37.486335,127.070310,개포동
...,...,...,...,...,...,...
609,서울항동초등학교,서울특별시 구로구 연동로 178,(항동),37.477092,126.824189,항동
610,서울해누리초등학교,서울특별시 송파구 송파대로37길 95,(가락동),37.498412,127.102124,가락동
611,서울양원숲초등학교,서울특별시 중랑구 양원역로 95,"(망우동, 서울양원숲초등학교)",37.609050,127.105434,망우동
612,서울개현초등학교,서울특별시 강남구 선릉로 15,"(개포동, 서울개현초등학교)",37.481026,127.062043,개포동
613,서울강빛초등학교,서울특별시 강동구 아리수로93다길 1,"(강일동, 강빛초중통합학교)",37.574343,127.170775,강일동

In [45]:
result = pd.merge(df, df2, on='학교명', how='left')
result.head()

,학교명,학급수(계),학생수(계),학교도로명 주소,학교도로명 상세주소,위도,경도,법정동
0,서울교육대학교부설초등학교,28,611,서울특별시 서초구 서초중앙로 96,"(서초동,서울교대초등학교)",37.490740,127.015425,서초동
1,서울대학교사범대학부설초등학교,31,570,서울특별시 종로구 대학로 64,"(동숭동,서울사대부설초등학교)",37.577600,127.004296,이화동
2,서울개원초등학교,44,1006,서울특별시 강남구 선릉로 29,"(개포동,개원초등학교)",37.481699,127.059451,개포동
3,서울개일초등학교,33,834,서울특별시 강남구 개포로 401,", 개일초등학교 (개포동,개일초등학교)",37.486235,127.057791,개포동
4,서울개포초등학교,43,886,서울특별시 강남구 삼성로4길 30,"(개포동, 개포초등학교)",37.486335,127.070310,개포동

In [46]:
result.to_csv('clean_ele_student_seoul.csv', index=False, encoding='utf-8-sig')

In [49]:
df = pd.read_csv(
    'clean_mid_student_seoul.csv')
df

                  학교명  학급수(계)  학생수(계)
0      서울대학교사범대학부설중학교      25     573
1    서울대학교사범대학부설여자중학교      19     336
2               개원중학교      31     940
3               개포중학교      36    1014
4               경원중학교      35    1047
..                ...     ...     ...
383             신길중학교      29     711
384           마곡하늬중학교      30     795
385            해누리중학교      30     853
386             강빛중학교      15     340
387    아현중학교부설방송통신중학교      18     259

[388 rows x 3 columns]

In [53]:
df2 = pd.read_csv(
    'clean_middle_seoul.csv')
df2

,학교명,주소내역,상세주소내역,학교도로명 주소,학교도로명 상세주소,위도,경도,동읍면
0,서울대학교사범대학부설중학교,서울특별시 성북구 종암2동,7-10.,서울특별시 성북구 월곡로 36,(종암동),37.596201,127.039164,종암동
1,서울대학교사범대학부설여자중학교,서울특별시 종로구 이화동,199번지.,서울특별시 종로구 대학로 64,", 서울대학교사범대학부설여자중학교 (이화동)",37.577928,127.003899,이화동
2,개원중학교,서울 강남구 개포3동,184번지.,서울특별시 강남구 영동대로 101,", 개원중학교 (개포동,개원중학교)",37.491641,127.071415,개포동
3,개포중학교,서울특별시 강남구 개포1동,660-37.,서울특별시 강남구 선릉로 9,"(개포동,개포중학교)",37.480664,127.061744,개포동
4,경원중학교,서울특별시 서초구 잠원동,66-1.,서울특별시 서초구 신반포로33길 39,"(잠원동,경원중학교)",37.510997,127.008879,잠원동
...,...,...,...,...,...,...,...,...
387,항동중학교,서울특별시 구로구 항동,.,서울특별시 구로구 연동로 239-2,"(항동, 항동중학교)",37.482748,126.820242,항동
388,신길중학교,NaN,.,서울특별시 영등포구 신길로28길 43,"(신길동, 신길중학교)",37.501890,126.915523,신길동
389,마곡하늬중학교,서울특별시 강서구 마곡동,.,서울특별시 강서구 마곡서1로 16,(마곡동),37.558007,126.820861,마곡동
390,해누리중학교,NaN,.,서울특별시 송파구 송파대로37길 95,", 해누리중학교 (가락동)",37.498364,127.101956,가락동
391,강빛중학교,서울특별시 강동구 강일동,.,서울특별시 강동구 아리수로93다길 1,"(강일동, 강빛초중통합학교)",37.573938,127.170899,강일동

In [54]:
result = pd.merge(df, df2, on='학교명', how='left')
result.head()

,학교명,학급수(계),학생수(계),주소내역,상세주소내역,학교도로명 주소,학교도로명 상세주소,위도,경도,동읍면
0,서울대학교사범대학부설중학교,25,573,서울특별시 성북구 종암2동,7-10.,서울특별시 성북구 월곡로 36,(종암동),37.596201,127.039164,종암동
1,서울대학교사범대학부설여자중학교,19,336,서울특별시 종로구 이화동,199번지.,서울특별시 종로구 대학로 64,", 서울대학교사범대학부설여자중학교 (이화동)",37.577928,127.003899,이화동
2,개원중학교,31,940,서울 강남구 개포3동,184번지.,서울특별시 강남구 영동대로 101,", 개원중학교 (개포동,개원중학교)",37.491641,127.071415,개포동
3,개포중학교,36,1014,서울특별시 강남구 개포1동,660-37.,서울특별시 강남구 선릉로 9,"(개포동,개포중학교)",37.480664,127.061744,개포동
4,경원중학교,35,1047,서울특별시 서초구 잠원동,66-1.,서울특별시 서초구 신반포로33길 39,"(잠원동,경원중학교)",37.510997,127.008879,잠원동

In [56]:
result.to_csv('clean_mid_student_seoul2.csv', index=False, encoding='utf-8-sig')

In [60]:
df = pd.read_csv('초등(서울)학생수.csv', encoding='cp949')
df

,학교명,학급수(계),학생수(계),도로명주소,위도,경도,법정동
0,서울교육대학교부설초등학교,28,611,"서울특별시 서초구 서초중앙로 96 (서초동,서울교대초등학교)",37.490740,127.015424,서초동
1,서울대학교사범대학부설초등학교,31,570,"서울특별시 종로구 대학로 64 (동숭동,서울사대부설초등학교)",37.577600,127.004295,이화동
2,서울개원초등학교,44,1006,"서울특별시 강남구 선릉로 29 (개포동,개원초등학교)",37.481699,127.059450,개포동
3,서울개일초등학교,33,834,"서울특별시 강남구 개포로 401 , 개일초등학교 (개포동,개일초등학교)",37.486235,127.057791,개포동
4,서울개포초등학교,43,886,"서울특별시 강남구 삼성로4길 30 (개포동, 개포초등학교)",37.486335,127.070310,개포동
...,...,...,...,...,...,...,...
601,서울항동초등학교,70,1478,서울특별시 구로구 연동로 178 (항동),37.477092,126.824190,항동
602,서울해누리초등학교,32,700,서울특별시 송파구 송파대로37길 95 (가락동),37.498412,127.102124,가락동
603,서울양원숲초등학교,36,779,"서울특별시 중랑구 양원역로 95 (망우동, 서울양원숲초등학교)",37.609050,127.105434,망우동
604,서울개현초등학교,34,800,"서울특별시 강남구 선릉로 15 (개포동, 서울개현초등학교)",37.481026,127.062043,개포동
605,서울강빛초등학교,37,978,"서울특별시 강동구 아리수로93다길 1 (강일동, 강빛초중통합학교)",37.574343,127.170775,강일동

In [63]:
result = df.groupby('법정동')[['학생수(계)', '학급수(계)']].sum()
result

      학생수(계)  학급수(계)
법정동
가락동     3935     192
가리봉동     267      19
가양동      792      51
가회동      153      10
갈현동     1252      56
...      ...     ...
효제동      166      13
효창동      567      30
후암동      566      34
휘경동      852      45
흑석동     1989      98

[215 rows x 2 columns]

In [65]:
result = df.groupby('법정동', as_index=False)[['학생수(계)', '학급수(계)']].sum()
result

      법정동  학생수(계)  학급수(계)
0     가락동    3935     192
1    가리봉동     267      19
2     가양동     792      51
3     가회동     153      10
4     갈현동    1252      56
..    ...     ...     ...
210   효제동     166      13
211   효창동     567      30
212   후암동     566      34
213   휘경동     852      45
214   흑석동    1989      98

[215 rows x 3 columns]

In [66]:
result.to_csv('sum_ele)seoul.csv', index=False, encoding='utf-8-sig')

In [67]:
df = pd.read_csv('중등(서울)학생.csv', encoding='cp949')
df

,학교명,학급수(계),학생수(계),도로명주소,위도,경도,동읍면
0,서울대학교사범대학부설중학교,25,573,서울특별시 성북구 월곡로 36 (종암동),37.596201,127.039164,종암동
1,서울대학교사범대학부설여자중학교,19,336,"서울특별시 종로구 대학로 64 , 서울대학교사범대학부설여자중학교 (이화동)",37.577928,127.003899,이화동
2,개원중학교,31,940,"서울특별시 강남구 영동대로 101 , 개원중학교 (개포동,개원중학교)",37.491641,127.071415,개포동
3,개포중학교,36,1014,"서울특별시 강남구 선릉로 9 (개포동,개포중학교)",37.480664,127.061744,개포동
4,경원중학교,35,1047,"서울특별시 서초구 신반포로33길 39 (잠원동,경원중학교)",37.510997,127.008879,잠원동
...,...,...,...,...,...,...,...
383,신길중학교,29,711,"서울특별시 영등포구 신길로28길 43 (신길동, 신길중학교)",37.501890,126.915523,신길동
384,마곡하늬중학교,30,795,서울특별시 강서구 마곡서1로 16 (마곡동),37.558007,126.820861,마곡동
385,해누리중학교,30,853,"서울특별시 송파구 송파대로37길 95 , 해누리중학교 (가락동)",37.498364,127.101956,가락동
386,강빛중학교,15,340,"서울특별시 강동구 아리수로93다길 1 (강일동, 강빛초중통합학교)",37.573938,127.170899,강일동
387,아현중학교부설방송통신중학교,18,259,NaN,NaN,NaN,NaN

In [69]:
result = df.groupby('동읍면', as_index=False)[['학생수(계)', '학급수(계)']].sum()
result

     동읍면  학생수(계)  학급수(계)
0    가락동    2485      94
1    가양동     432      22
2    갈현동    1252      64
3     강동     525      22
4    강일동    1061      44
..   ...     ...     ...
167  화곡동     590      23
168  화양동     427      19
169  회기동     847      38
170  휘경동    1188      50
171  흑석동    1013      41

[172 rows x 3 columns]

In [70]:
result.to_csv('sum_mid_seoul.csv', index=False, encoding='utf-8-sig')

In [72]:
# ✅ 1. 카카오 REST API 키 넣기 (여기!!)
REST_API_KEY = "YOUR_KAKAO_API_KEY"

# ✅ 2. 주소 → (위도, 경도, 법정동) 변환 함수
def get_addr_info(address):
    url = 'https://dapi.kakao.com/v2/local/search/address.json'
    headers = {"Authorization": f"KakaoAK {REST_API_KEY}"}
    params = {'query': address}
    
    try:
        response = requests.get(url, headers=headers, params=params)
        if response.status_code == 200:
            result = response.json()
            if result['documents']:
                addr_data = result['documents'][0]['address']
                lat = addr_data['y']  # 위도
                lon = addr_data['x']  # 경도
                b_dong = addr_data['region_3depth_name']  # 법정동
                
                return lat, lon, b_dong
        return None, None, None
    except:
        return None, None, None

# ✅ 3. CSV 불러오기 (네 파일)
df = pd.read_csv('중등(서울)학생.csv', encoding='cp949')

# ✅ 4. API 적용 (주소 컬럼 기준)
print("좌표 변환 중...")
info_list = []

for addr in df['도로명주소']:
    info = get_addr_info(addr)
    info_list.append(info)
    time.sleep(0.2)  # ⭐ API 제한 방지 (중요)

# ✅ 5. 컬럼 추가
df['위도'], df['경도'], df['법정동'] = zip(*info_list)

# ✅ 6. 저장
df.to_csv('clean_mid_seoul.csv', index=False, encoding='utf-8-sig')

print("완료!")
df.head()

좌표 변환 중...
완료!

,학교명,학급수(계),학생수(계),도로명주소,위도,경도,동읍면,법정동
0,서울대학교사범대학부설중학교,25,573,서울특별시 성북구 월곡로 36 (종암동),37.5958358987959,127.039066241267,종암동,종암동
1,서울대학교사범대학부설여자중학교,19,336,"서울특별시 종로구 대학로 64 , 서울대학교사범대학부설여자중학교 (이화동)",37.5775997032467,127.004295521787,이화동,이화동
2,개원중학교,31,940,"서울특별시 강남구 영동대로 101 , 개원중학교 (개포동,개원중학교)",37.4915905275033,127.071900307455,개포동,개포동
3,개포중학교,36,1014,"서울특별시 강남구 선릉로 9 (개포동,개포중학교)",37.4804473919149,127.062402866859,개포동,개포동
4,경원중학교,35,1047,"서울특별시 서초구 신반포로33길 39 (잠원동,경원중학교)",37.5115815961934,127.009018254738,잠원동,잠원동

In [74]:
df = pd.read_csv('clean_mid_seoul.csv', encoding='cp949')
df

,학교명,학급수(계),학생수(계),도로명주소,위도,경도,법정동
0,서울대학교사범대학부설중학교,25,573,서울특별시 성북구 월곡로 36 (종암동),37.595836,127.039066,종암동
1,서울대학교사범대학부설여자중학교,19,336,"서울특별시 종로구 대학로 64 , 서울대학교사범대학부설여자중학교 (이화동)",37.577600,127.004295,이화동
2,개원중학교,31,940,"서울특별시 강남구 영동대로 101 , 개원중학교 (개포동,개원중학교)",37.491591,127.071900,개포동
3,개포중학교,36,1014,"서울특별시 강남구 선릉로 9 (개포동,개포중학교)",37.480447,127.062403,개포동
4,경원중학교,35,1047,"서울특별시 서초구 신반포로33길 39 (잠원동,경원중학교)",37.511582,127.009018,잠원동
...,...,...,...,...,...,...,...
383,신길중학교,29,711,"서울특별시 영등포구 신길로28길 43 (신길동, 신길중학교)",37.502035,126.915436,신길동
384,마곡하늬중학교,30,795,서울특별시 강서구 마곡서1로 16 (마곡동),37.558168,126.820985,마곡동
385,해누리중학교,30,853,"서울특별시 송파구 송파대로37길 95 , 해누리중학교 (가락동)",37.498412,127.102124,가락동
386,강빛중학교,15,340,"서울특별시 강동구 아리수로93다길 1 (강일동, 강빛초중통합학교)",37.574343,127.170775,강일동
387,아현중학교부설방송통신중학교,18,259,서울 마포구 마포대로 247,37.556401,126.956500,아현동

In [75]:
result = df.groupby('법정동', as_index=False)[['학생수(계)', '학급수(계)']].sum()
result

     법정동  학생수(계)  학급수(계)
0    가락동    2485      94
1    가양동     432      22
2    갈현동    1252      64
3    강일동     865      37
4    개봉동    1457      62
..   ...     ...     ...
165  화곡동     986      40
166  화양동     427      19
167  회기동     847      38
168  휘경동    1188      50
169  흑석동    1013      41

[170 rows x 3 columns]

In [76]:
result.to_csv('sum_mid_seoul.csv', index=False, encoding='utf-8-sig')

In [78]:
ele_df = pd.read_csv('sum_ele)seoul.csv', encoding='utf-8-sig')
ele_df

      법정동  학생수(계)  학급수(계)
0     가락동    3935     192
1    가리봉동     267      19
2     가양동     792      51
3     가회동     153      10
4     갈현동    1252      56
..    ...     ...     ...
210   효제동     166      13
211   효창동     567      30
212   후암동     566      34
213   휘경동     852      45
214   흑석동    1989      98

[215 rows x 3 columns]

In [79]:
mid_df = pd.read_csv('sum_mid_seoul.csv', encoding='utf-8-sig')
mid_df

     법정동  학생수(계)  학급수(계)
0    가락동    2485      94
1    가양동     432      22
2    갈현동    1252      64
3    강일동     865      37
4    개봉동    1457      62
..   ...     ...     ...
165  화곡동     986      40
166  화양동     427      19
167  회기동     847      38
168  휘경동    1188      50
169  흑석동    1013      41

[170 rows x 3 columns]

In [80]:
result = pd.merge(
    ele_df, mid_df,
    on='법정동',
    how='outer',
    suffixes=('_초', '_중')
)
result

      법정동  학생수(계)_초  학급수(계)_초  학생수(계)_중  학급수(계)_중
0     가락동    3935.0     192.0    2485.0      94.0
1    가리봉동     267.0      19.0       NaN       NaN
2     가양동     792.0      51.0     432.0      22.0
3     가회동     153.0      10.0       NaN       NaN
4     갈현동    1252.0      56.0    1252.0      64.0
..    ...       ...       ...       ...       ...
226   효제동     166.0      13.0       NaN       NaN
227   효창동     567.0      30.0       NaN       NaN
228   후암동     566.0      34.0       NaN       NaN
229   휘경동     852.0      45.0    1188.0      50.0
230   흑석동    1989.0      98.0    1013.0      41.0

[231 rows x 5 columns]

In [81]:
result = result.fillna(0)

In [82]:
cols = ['학생수(계)_초','학생수(계)_중','학급수(계)_초','학급수(계)_중']
result[cols] = result[cols].astype(int)

In [83]:
result

      법정동  학생수(계)_초  학급수(계)_초  학생수(계)_중  학급수(계)_중
0     가락동      3935       192      2485        94
1    가리봉동       267        19         0         0
2     가양동       792        51       432        22
3     가회동       153        10         0         0
4     갈현동      1252        56      1252        64
..    ...       ...       ...       ...       ...
226   효제동       166        13         0         0
227   효창동       567        30         0         0
228   후암동       566        34         0         0
229   휘경동       852        45      1188        50
230   흑석동      1989        98      1013        41

[231 rows x 5 columns]

In [85]:
result.to_csv('result_seoul_st.csv', index=False, encoding='utf-8-sig')

In [86]:
result['총학생수'] = result['학생수(계)_초'] + result['학생수(계)_중']
result['총학급수'] = result['학급수(계)_초'] + result['학급수(계)_중']

result['학급당학생수'] = result['총학생수'] / result['총학급수']
result

      법정동  학생수(계)_초  학급수(계)_초  학생수(계)_중  학급수(계)_중  총학생수  총학급수     학급당학생수
0     가락동      3935       192      2485        94  6420   286  22.447552
1    가리봉동       267        19         0         0   267    19  14.052632
2     가양동       792        51       432        22  1224    73  16.767123
3     가회동       153        10         0         0   153    10  15.300000
4     갈현동      1252        56      1252        64  2504   120  20.866667
..    ...       ...       ...       ...       ...   ...   ...        ...
226   효제동       166        13         0         0   166    13  12.769231
227   효창동       567        30         0         0   567    30  18.900000
228   후암동       566        34         0         0   566    34  16.647059
229   휘경동       852        45      1188        50  2040    95  21.473684
230   흑석동      1989        98      1013        41  3002   139  21.597122

[231 rows x 8 columns]

In [87]:
result.to_csv('result_seoul_st.csv', index=False, encoding='utf-8-sig')

In [100]:
df = pd.read_csv('mid_icn.csv', encoding='cp949')
df

,학교명,도로명주소,위도,경도,읍면동
0,강남중학교,"인천광역시 강화군 길상면 강화남로 62-2 (길상면, 강남중학교)",37.643852,126.479128,길상면
1,강서중학교,"인천광역시 강화군 하점면 강화서로 909-19 (하점면, 강서중학교)",37.773146,126.388083,하점면
2,강화여자중학교,인천광역시 강화군 강화읍 갑룡길 11 (강화읍),37.744093,126.494610,강화읍
3,강화중학교,"인천광역시 강화군 강화읍 동문로 53 , 강화중학교 (강화읍)",37.774983,126.490496,강화읍
4,교동중학교,인천광역시 강화군 교동면 교동남로 77 (교동면),37.778463,126.284317,교동면
...,...,...,...,...,...
143,인천현송중학교,"인천광역시 연수구 아카데미로312번길 84 (송도동, 인천현송중학교)",37.393036,126.619645,송도동
144,인천루원중학교,"인천광역시 서구 염곡로 517 (가정동, 인천루원중학교)",37.531285,126.668653,가정동
145,인천청호중학교,인천광역시 서구 청라한울로 44 (청라동),37.538836,126.641344,청라동
146,인천운서중학교,인천광역시 중구 하늘초롱길 73 (운서동),37.491219,126.505117,운서동
147,인천은송중학교,인천광역시 연수구 센트럴로 464 (송도동),37.415994,126.629670,송도동

In [90]:
# ✅ 1. 카카오 REST API 키 넣기 (여기!!)
REST_API_KEY = "YOUR_KAKAO_API_KEY"

# ✅ 2. 주소 → (위도, 경도, 법정동) 변환 함수
def get_addr_info(address):
    url = 'https://dapi.kakao.com/v2/local/search/address.json'
    headers = {"Authorization": f"KakaoAK {REST_API_KEY}"}
    params = {'query': address}
    
    try:
        response = requests.get(url, headers=headers, params=params)
        if response.status_code == 200:
            result = response.json()
            if result['documents']:
                addr_data = result['documents'][0]['address']
                lat = addr_data['y']  # 위도
                lon = addr_data['x']  # 경도
                b_dong = addr_data['region_3depth_name']  # 법정동
                
                return lat, lon, b_dong
        return None, None, None
    except:
        return None, None, None

# ✅ 3. CSV 불러오기 (네 파일)
df = pd.read_csv('mid_icn.csv', encoding='cp949')

# ✅ 4. API 적용 (주소 컬럼 기준)
print("좌표 변환 중...")
info_list = []

for addr in df['도로명주소']:
    info = get_addr_info(addr)
    info_list.append(info)
    time.sleep(0.2)  # ⭐ API 제한 방지 (중요)

# ✅ 5. 컬럼 추가
df['위도'], df['경도'], df['법정동'] = zip(*info_list)

# ✅ 6. 저장
df.to_csv('clean_mid_seoul.csv', index=False, encoding='utf-8-sig')

print("완료!")
df.head()

좌표 변환 중...
완료!

,학교명,도로명주소,위도,경도,읍면동,법정동
0,강남중학교,"인천광역시 강화군 길상면 강화남로 62-2 (길상면, 강남중학교)",37.643841359022,126.479099830853,길상면,길상면 온수리
1,강서중학교,"인천광역시 강화군 하점면 강화서로 909-19 (하점면, 강서중학교)",37.7731109281637,126.388107646894,하점면,하점면 이강리
2,강화여자중학교,인천광역시 강화군 강화읍 갑룡길 11 (강화읍),37.7442963095585,126.495025276909,강화읍,강화읍 갑곳리
3,강화중학교,"인천광역시 강화군 강화읍 동문로 53 , 강화중학교 (강화읍)",37.7504037329271,126.491024632395,강화읍,강화읍 관청리
4,교동중학교,인천광역시 강화군 교동면 교동남로 77 (교동면),37.7784626831111,126.284316914567,교동면,교동면 대룡리

In [93]:
df.to_csv('mid_icn_st.csv', index=False, encoding='utf-8-sig')

In [102]:
df = pd.read_csv('mid_icn_student.csv', encoding='cp949')
df

,학교명,도로명주소,위도,경도,법정동
0,강남중학교,"인천광역시 강화군 길상면 강화남로 62-2 (길상면, 강남중학교)",37.643841,126.479100,길상면
1,강서중학교,"인천광역시 강화군 하점면 강화서로 909-19 (하점면, 강서중학교)",37.773111,126.388108,하점면
2,강화여자중학교,인천광역시 강화군 강화읍 갑룡길 11 (강화읍),37.744296,126.495025,강화읍
3,강화중학교,"인천광역시 강화군 강화읍 동문로 53 , 강화중학교 (강화읍)",37.750404,126.491025,강화읍
4,교동중학교,인천광역시 강화군 교동면 교동남로 77 (교동면),37.778463,126.284317,교동면
...,...,...,...,...,...
143,인천현송중학교,"인천광역시 연수구 아카데미로312번길 84 (송도동, 인천현송중학교)",37.393109,126.619598,송도동
144,인천루원중학교,"인천광역시 서구 염곡로 517 (가정동, 인천루원중학교)",37.531285,126.668653,가정동
145,인천청호중학교,인천광역시 서구 청라한울로 44 (청라동),37.538645,126.641516,청라동
146,인천운서중학교,인천광역시 중구 하늘초롱길 73 (운서동),37.491219,126.505117,운서동
147,인천은송중학교,인천광역시 연수구 센트럴로 464 (송도동),37.415994,126.629670,송도동

In [104]:
df.to_csv('mid_icn_student.csv', index=False, encoding='utf-8-sig')

In [105]:
df = pd.read_csv('ele_icn_student.csv', encoding='cp949')
df

,학교명,도로명주소,위도,경도,동읍면
0,경인교육대학교부설초등학교,인천광역시 계양구 안남로 612 (효성동),37.538018,126.712233,효성동
1,서도초등학교볼음분교장,인천광역시 강화군 서도면 볼음도길 248 (서도면),37.671368,126.189456,서도면
2,갑룡초등학교,"인천광역시 강화군 강화읍 갑룡길 88 , 갑룡초등학교 (강화읍,갑룡초등학교)",37.743320,126.503669,강화읍
3,강화초등학교,"인천광역시 강화군 강화읍 북문길 36 (강화읍,강화초등학교)",37.750431,126.486170,강화읍
4,교동초등학교,"인천광역시 강화군 교동면 대룡안길 29 , 교동초등학교 (교동면, 교동초등학교)",37.783695,126.281711,교동
...,...,...,...,...,...
277,인천경연초등학교,인천광역시 서구 차오름로 64 (청라동),37.538497,126.626236,청라동
278,인천별빛초등학교,"인천광역시 중구 은하수로 402 , 인천별빛초등학교 (운남동)",37.490839,126.550346,운남동
279,인천송담초등학교,"인천광역시 연수구 아카데미로 627 (송도동, 인천송담초등학교)",37.410277,126.614920,송도동
280,인천청호초등학교,인천광역시 서구 청라한울로 44 (청라동),37.538634,126.641374,청라동
281,인천신검단초등학교,"인천광역시 서구 불로동 , 247-49 일원 (불로동)",37.609144,126.700470,불로동

In [106]:
df = pd.read_csv('ele_icn_student.csv', encoding='cp949')
df

,학교명,도로명주소,위도,경도,동읍면
0,경인교육대학교부설초등학교,인천광역시 계양구 안남로 612 (효성동),37.538018,126.712233,효성동
1,서도초등학교볼음분교장,인천광역시 강화군 서도면 볼음도길 248 (서도면),37.671368,126.189456,서도면
2,갑룡초등학교,"인천광역시 강화군 강화읍 갑룡길 88 , 갑룡초등학교 (강화읍,갑룡초등학교)",37.743320,126.503669,강화읍
3,강화초등학교,"인천광역시 강화군 강화읍 북문길 36 (강화읍,강화초등학교)",37.750431,126.486170,강화읍
4,교동초등학교,"인천광역시 강화군 교동면 대룡안길 29 , 교동초등학교 (교동면, 교동초등학교)",37.783695,126.281711,교동
...,...,...,...,...,...
277,인천경연초등학교,인천광역시 서구 차오름로 64 (청라동),37.538497,126.626236,청라동
278,인천별빛초등학교,"인천광역시 중구 은하수로 402 , 인천별빛초등학교 (운남동)",37.490839,126.550346,운남동
279,인천송담초등학교,"인천광역시 연수구 아카데미로 627 (송도동, 인천송담초등학교)",37.410277,126.614920,송도동
280,인천청호초등학교,인천광역시 서구 청라한울로 44 (청라동),37.538634,126.641374,청라동
281,인천신검단초등학교,"인천광역시 서구 불로동 , 247-49 일원 (불로동)",37.609144,126.700470,불로동

In [107]:
df = pd.read_csv('ele_icn_student.csv', encoding='cp949')
df

,학교명,도로명주소,위도,경도,법정동
0,경인교육대학교부설초등학교,인천광역시 계양구 안남로 612 (효성동),37.538018,126.712233,효성동
1,서도초등학교볼음분교장,인천광역시 강화군 서도면 볼음도길 248 (서도면),37.671368,126.189456,서도면
2,갑룡초등학교,"인천광역시 강화군 강화읍 갑룡길 88 , 갑룡초등학교 (강화읍,갑룡초등학교)",37.743320,126.503669,강화읍
3,강화초등학교,"인천광역시 강화군 강화읍 북문길 36 (강화읍,강화초등학교)",37.750431,126.486170,강화읍
4,교동초등학교,"인천광역시 강화군 교동면 대룡안길 29 , 교동초등학교 (교동면, 교동초등학교)",37.783695,126.281711,교동
...,...,...,...,...,...
277,인천경연초등학교,인천광역시 서구 차오름로 64 (청라동),37.538497,126.626236,청라동
278,인천별빛초등학교,"인천광역시 중구 은하수로 402 , 인천별빛초등학교 (운남동)",37.490839,126.550346,운남동
279,인천송담초등학교,"인천광역시 연수구 아카데미로 627 (송도동, 인천송담초등학교)",37.410277,126.614920,송도동
280,인천청호초등학교,인천광역시 서구 청라한울로 44 (청라동),37.538634,126.641374,청라동
281,인천신검단초등학교,"인천광역시 서구 불로동 , 247-49 일원 (불로동)",37.609144,126.700470,불로동

In [108]:
df.to_csv('ele_icn_student.csv', index=False, encoding='utf-8-sig')

In [110]:
df = pd.read_csv(
    '인천중학생수.csv')
df

,시도교육청,교육지원청,지역,정보공시 학교코드,학교명,학교급코드,설립구분,제외여부,제외사유,1학년 학급수,...,특수학급 학생수,특수학급 학급당 학생수,순회학급 학급수,순회학급 학생수,순회학급 학급당 학생수,학급수(계),학생수(계),학급당 학생수(계),교사수,수업교원 1인당 학생수
0,인천광역시교육청,인천광역시강화교육지원청,인천광역시 강화군,S040000317,강남중학교,3,공립,N,NaN,2,...,5,5.0,0,0,0,7,129,18.4,16,8.1
1,인천광역시교육청,인천광역시강화교육지원청,인천광역시 강화군,S040000318,강서중학교,3,공립,N,NaN,1,...,2,2.0,0,0,0,4,23,5.8,12,1.9
2,인천광역시교육청,인천광역시강화교육지원청,인천광역시 강화군,S040000320,강화여자중학교,3,공립,N,NaN,6,...,4,4.0,0,0,0,19,479,25.2,33,14.5
3,인천광역시교육청,인천광역시강화교육지원청,인천광역시 강화군,S040000321,강화중학교,3,공립,N,NaN,6,...,13,4.3,0,0,0,21,461,22.0,33,14.0
4,인천광역시교육청,인천광역시강화교육지원청,인천광역시 강화군,S040000322,교동중학교,3,공립,N,NaN,1,...,2,2.0,0,0,0,4,19,4.8,7,2.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
141,인천광역시교육청,인천광역시서부교육지원청,인천광역시 서구,S040002330,인천루원중학교,3,공립,N,NaN,9,...,9,9.0,0,0,0,30,910,30.3,48,19.0
142,인천광역시교육청,인천광역시서부교육지원청,인천광역시 서구,S040002336,인천청호중학교,3,공립,N,NaN,5,...,6,6.0,0,0,0,16,504,31.5,25,20.2
143,인천광역시교육청,인천광역시남부교육지원청,인천광역시 중구,S040002350,인천운서중학교,3,공립,N,NaN,9,...,5,5.0,0,0,0,17,401,23.6,29,13.8
144,인천광역시교육청,인천광역시동부교육지원청,인천광역시 연수구,S040002356,인천은송중학교,3,공립,N,NaN,10,...,2,2.0,0,0,0,18,536,29.8,31,17.3
145,인천광역시교육청,인천광역시동부교육지원청,인천광역시 남동구,S040002270,구월여자중학교부설방송통신중학교,25,공립,N,NaN,2,...,0,0.0,0,0,0,6,142,23.7,24,5.9

In [111]:
df = pd.read_csv(
    '인천중학생수.csv', usecols=[4,24,25])
df

                  학교명  학급수(계)  학생수(계)
0               강남중학교       7     129
1               강서중학교       4      23
2             강화여자중학교      19     479
3               강화중학교      21     461
4               교동중학교       4      19
..                ...     ...     ...
141           인천루원중학교      30     910
142           인천청호중학교      16     504
143           인천운서중학교      17     401
144           인천은송중학교      18     536
145  구월여자중학교부설방송통신중학교       6     142

[146 rows x 3 columns]

In [112]:
df.to_csv('인천중학생수.csv', index=False, encoding='utf-8-sig')

In [113]:
df = pd.read_csv(
    '인천초등학생수.csv', usecols=[4,33,34])
df

               학교명  학급수(계)  학생수(계)
0    경인교육대학교부설초등학교      25     560
1           갑룡초등학교      24     485
2           강화초등학교      14     209
3           교동초등학교       7      18
4           길상초등학교      11     140
..             ...     ...     ...
266       인천중산초등학교      63    1582
267       인천경연초등학교      44    1017
268       인천별빛초등학교      53    1359
269       인천송담초등학교      38     913
270       인천청호초등학교      20     433

[271 rows x 3 columns]

In [114]:
df.to_csv('인천초등학생수.csv', index=False, encoding='utf-8-sig')

In [115]:
df2 = pd.read_csv(
    'ele_icn_student.csv')
df2

,학교명,도로명주소,위도,경도,법정동
0,경인교육대학교부설초등학교,인천광역시 계양구 안남로 612 (효성동),37.538018,126.712233,효성동
1,서도초등학교볼음분교장,인천광역시 강화군 서도면 볼음도길 248 (서도면),37.671368,126.189456,서도면
2,갑룡초등학교,"인천광역시 강화군 강화읍 갑룡길 88 , 갑룡초등학교 (강화읍,갑룡초등학교)",37.743320,126.503669,강화읍
3,강화초등학교,"인천광역시 강화군 강화읍 북문길 36 (강화읍,강화초등학교)",37.750431,126.486170,강화읍
4,교동초등학교,"인천광역시 강화군 교동면 대룡안길 29 , 교동초등학교 (교동면, 교동초등학교)",37.783695,126.281711,교동
...,...,...,...,...,...
277,인천경연초등학교,인천광역시 서구 차오름로 64 (청라동),37.538497,126.626236,청라동
278,인천별빛초등학교,"인천광역시 중구 은하수로 402 , 인천별빛초등학교 (운남동)",37.490839,126.550346,운남동
279,인천송담초등학교,"인천광역시 연수구 아카데미로 627 (송도동, 인천송담초등학교)",37.410277,126.614920,송도동
280,인천청호초등학교,인천광역시 서구 청라한울로 44 (청라동),37.538634,126.641374,청라동
281,인천신검단초등학교,"인천광역시 서구 불로동 , 247-49 일원 (불로동)",37.609144,126.700470,불로동

In [116]:
result = pd.merge(df, df2, on='학교명', how='left')
result.head()

,학교명,학급수(계),학생수(계),도로명주소,위도,경도,법정동
0,경인교육대학교부설초등학교,25,560,인천광역시 계양구 안남로 612 (효성동),37.538018,126.712233,효성동
1,갑룡초등학교,24,485,"인천광역시 강화군 강화읍 갑룡길 88 , 갑룡초등학교 (강화읍,갑룡초등학교)",37.743320,126.503669,강화읍
2,강화초등학교,14,209,"인천광역시 강화군 강화읍 북문길 36 (강화읍,강화초등학교)",37.750431,126.486170,강화읍
3,교동초등학교,7,18,"인천광역시 강화군 교동면 대룡안길 29 , 교동초등학교 (교동면, 교동초등학교)",37.783695,126.281711,교동
4,길상초등학교,11,140,"인천광역시 강화군 길상면 삼랑성길 22 , 길상초등학교 (길상면, 길상초등학교)",37.637793,126.490646,길상면

In [117]:
result.to_csv('인천초등학생수_합계.csv', index=False, encoding='utf-8-sig')

In [119]:
df = pd.read_csv('인천초등학생수_합계.csv', encoding='utf-8-sig')
df

,학교명,학급수(계),학생수(계),도로명주소,위도,경도,법정동
0,경인교육대학교부설초등학교,25,560,인천광역시 계양구 안남로 612 (효성동),37.538018,126.712233,효성동
1,갑룡초등학교,24,485,"인천광역시 강화군 강화읍 갑룡길 88 , 갑룡초등학교 (강화읍,갑룡초등학교)",37.743320,126.503669,강화읍
2,강화초등학교,14,209,"인천광역시 강화군 강화읍 북문길 36 (강화읍,강화초등학교)",37.750431,126.486170,강화읍
3,교동초등학교,7,18,"인천광역시 강화군 교동면 대룡안길 29 , 교동초등학교 (교동면, 교동초등학교)",37.783695,126.281711,교동
4,길상초등학교,11,140,"인천광역시 강화군 길상면 삼랑성길 22 , 길상초등학교 (길상면, 길상초등학교)",37.637793,126.490646,길상면
...,...,...,...,...,...,...,...
266,인천중산초등학교,63,1582,"인천광역시 중구 두미포로 100, 인천중산 초등학교",37.495165,126.565532,중산동
267,인천경연초등학교,44,1017,인천광역시 서구 차오름로 64 (청라동),37.538497,126.626236,청라동
268,인천별빛초등학교,53,1359,"인천광역시 중구 은하수로 402 , 인천별빛초등학교 (운남동)",37.490839,126.550346,운남동
269,인천송담초등학교,38,913,"인천광역시 연수구 아카데미로 627 (송도동, 인천송담초등학교)",37.410277,126.614920,송도동
270,인천청호초등학교,20,433,인천광역시 서구 청라한울로 44 (청라동),37.538634,126.641374,청라동

In [120]:
result = df.groupby('법정동', as_index=False)[['학생수(계)', '학급수(계)']].sum()
result

     법정동  학생수(계)  학급수(계)
0    가정동    4137     182
1    가좌동    1753      95
2    간석동    2647     134
3    갈산동     946      55
4    강화읍     932      59
..   ...     ...     ...
88   학익동    2290     117
89  항동7가     104      10
90   화도면      41       7
91   화수동     263      16
92   효성동    2483     128

[93 rows x 3 columns]

In [121]:
result.to_csv('인천초등학교_동합계.csv', index=False, encoding='utf-8-sig')

In [122]:
df2 = pd.read_csv(
    'mid_icn_student.csv')
df2

,학교명,도로명주소,위도,경도,법정동
0,강남중학교,"인천광역시 강화군 길상면 강화남로 62-2 (길상면, 강남중학교)",37.643841,126.479100,길상면
1,강서중학교,"인천광역시 강화군 하점면 강화서로 909-19 (하점면, 강서중학교)",37.773111,126.388108,하점면
2,강화여자중학교,인천광역시 강화군 강화읍 갑룡길 11 (강화읍),37.744296,126.495025,강화읍
3,강화중학교,"인천광역시 강화군 강화읍 동문로 53 , 강화중학교 (강화읍)",37.750404,126.491025,강화읍
4,교동중학교,인천광역시 강화군 교동면 교동남로 77 (교동면),37.778463,126.284317,교동면
...,...,...,...,...,...
143,인천현송중학교,"인천광역시 연수구 아카데미로312번길 84 (송도동, 인천현송중학교)",37.393109,126.619598,송도동
144,인천루원중학교,"인천광역시 서구 염곡로 517 (가정동, 인천루원중학교)",37.531285,126.668653,가정동
145,인천청호중학교,인천광역시 서구 청라한울로 44 (청라동),37.538645,126.641516,청라동
146,인천운서중학교,인천광역시 중구 하늘초롱길 73 (운서동),37.491219,126.505117,운서동
147,인천은송중학교,인천광역시 연수구 센트럴로 464 (송도동),37.415994,126.629670,송도동

In [123]:
df = pd.read_csv(
    '인천중학생수.csv')
df

                  학교명  학급수(계)  학생수(계)
0               강남중학교       7     129
1               강서중학교       4      23
2             강화여자중학교      19     479
3               강화중학교      21     461
4               교동중학교       4      19
..                ...     ...     ...
141           인천루원중학교      30     910
142           인천청호중학교      16     504
143           인천운서중학교      17     401
144           인천은송중학교      18     536
145  구월여자중학교부설방송통신중학교       6     142

[146 rows x 3 columns]

In [124]:
result = pd.merge(df, df2, on='학교명', how='left')
result.head()

,학교명,학급수(계),학생수(계),도로명주소,위도,경도,법정동
0,강남중학교,7,129,"인천광역시 강화군 길상면 강화남로 62-2 (길상면, 강남중학교)",37.643841,126.479100,길상면
1,강서중학교,4,23,"인천광역시 강화군 하점면 강화서로 909-19 (하점면, 강서중학교)",37.773111,126.388108,하점면
2,강화여자중학교,19,479,인천광역시 강화군 강화읍 갑룡길 11 (강화읍),37.744296,126.495025,강화읍
3,강화중학교,21,461,"인천광역시 강화군 강화읍 동문로 53 , 강화중학교 (강화읍)",37.750404,126.491025,강화읍
4,교동중학교,4,19,인천광역시 강화군 교동면 교동남로 77 (교동면),37.778463,126.284317,교동면

In [125]:
result

,학교명,학급수(계),학생수(계),도로명주소,위도,경도,법정동
0,강남중학교,7,129,"인천광역시 강화군 길상면 강화남로 62-2 (길상면, 강남중학교)",37.643841,126.479100,길상면
1,강서중학교,4,23,"인천광역시 강화군 하점면 강화서로 909-19 (하점면, 강서중학교)",37.773111,126.388108,하점면
2,강화여자중학교,19,479,인천광역시 강화군 강화읍 갑룡길 11 (강화읍),37.744296,126.495025,강화읍
3,강화중학교,21,461,"인천광역시 강화군 강화읍 동문로 53 , 강화중학교 (강화읍)",37.750404,126.491025,강화읍
4,교동중학교,4,19,인천광역시 강화군 교동면 교동남로 77 (교동면),37.778463,126.284317,교동면
...,...,...,...,...,...,...,...
141,인천루원중학교,30,910,"인천광역시 서구 염곡로 517 (가정동, 인천루원중학교)",37.531285,126.668653,가정동
142,인천청호중학교,16,504,인천광역시 서구 청라한울로 44 (청라동),37.538645,126.641516,청라동
143,인천운서중학교,17,401,인천광역시 중구 하늘초롱길 73 (운서동),37.491219,126.505117,운서동
144,인천은송중학교,18,536,인천광역시 연수구 센트럴로 464 (송도동),37.415994,126.629670,송도동
145,구월여자중학교부설방송통신중학교,6,142,NaN,NaN,NaN,NaN

In [127]:
result2 = result.groupby('법정동', as_index=False)[['학생수(계)', '학급수(계)']].sum()
result2

    법정동  학생수(계)  학급수(계)
0   가정동     910      30
1   가좌동    1345      61
2   간석동    1859      76
3   갈산동     379      18
4   강화읍     940      40
..  ...     ...     ...
62  하점면      23       4
63  학익동    1721      60
64  화도면      37       4
65  화수동     354      18
66  효성동    1307      54

[67 rows x 3 columns]

In [128]:
result2.to_csv('인천중학교_동합계.csv', index=False, encoding='utf-8-sig')

In [129]:
ele_df = pd.read_csv('인천초등학교_동합계.csv', encoding='utf-8-sig')
ele_df

     법정동  학생수(계)  학급수(계)
0    가정동    4137     182
1    가좌동    1753      95
2    간석동    2647     134
3    갈산동     946      55
4    강화읍     932      59
..   ...     ...     ...
88   학익동    2290     117
89  항동7가     104      10
90   화도면      41       7
91   화수동     263      16
92   효성동    2483     128

[93 rows x 3 columns]

In [130]:
mid_df = pd.read_csv('인천중학교_동합계.csv', encoding='utf-8-sig')
mid_df

    법정동  학생수(계)  학급수(계)
0   가정동     910      30
1   가좌동    1345      61
2   간석동    1859      76
3   갈산동     379      18
4   강화읍     940      40
..  ...     ...     ...
62  하점면      23       4
63  학익동    1721      60
64  화도면      37       4
65  화수동     354      18
66  효성동    1307      54

[67 rows x 3 columns]

In [131]:
result = pd.merge(
    ele_df, mid_df,
    on='법정동',
    how='outer',
    suffixes=('_초', '_중')
)
result

     법정동  학생수(계)_초  학급수(계)_초  학생수(계)_중  학급수(계)_중
0    가정동    4137.0     182.0     910.0      30.0
1    가좌동    1753.0      95.0    1345.0      61.0
2    간석동    2647.0     134.0    1859.0      76.0
3    갈산동     946.0      55.0     379.0      18.0
4    강화읍     932.0      59.0     940.0      40.0
..   ...       ...       ...       ...       ...
91   학익동    2290.0     117.0    1721.0      60.0
92  항동7가     104.0      10.0       NaN       NaN
93   화도면      41.0       7.0      37.0       4.0
94   화수동     263.0      16.0     354.0      18.0
95   효성동    2483.0     128.0    1307.0      54.0

[96 rows x 5 columns]

In [132]:
result = result.fillna(0)

In [133]:
cols = ['학생수(계)_초','학생수(계)_중','학급수(계)_초','학급수(계)_중']
result[cols] = result[cols].astype(int)
result

     법정동  학생수(계)_초  학급수(계)_초  학생수(계)_중  학급수(계)_중
0    가정동      4137       182       910        30
1    가좌동      1753        95      1345        61
2    간석동      2647       134      1859        76
3    갈산동       946        55       379        18
4    강화읍       932        59       940        40
..   ...       ...       ...       ...       ...
91   학익동      2290       117      1721        60
92  항동7가       104        10         0         0
93   화도면        41         7        37         4
94   화수동       263        16       354        18
95   효성동      2483       128      1307        54

[96 rows x 5 columns]

In [134]:
result.to_csv('result_icn_st.csv', index=False, encoding='utf-8-sig')

In [135]:
result['총학생수'] = result['학생수(계)_초'] + result['학생수(계)_중']
result['총학급수'] = result['학급수(계)_초'] + result['학급수(계)_중']

In [136]:
result['학급당학생수'] = result['총학생수'] / result['총학급수']
result

     법정동  학생수(계)_초  학급수(계)_초  학생수(계)_중  학급수(계)_중  총학생수  총학급수     학급당학생수
0    가정동      4137       182       910        30  5047   212  23.806604
1    가좌동      1753        95      1345        61  3098   156  19.858974
2    간석동      2647       134      1859        76  4506   210  21.457143
3    갈산동       946        55       379        18  1325    73  18.150685
4    강화읍       932        59       940        40  1872    99  18.909091
..   ...       ...       ...       ...       ...   ...   ...        ...
91   학익동      2290       117      1721        60  4011   177  22.661017
92  항동7가       104        10         0         0   104    10  10.400000
93   화도면        41         7        37         4    78    11   7.090909
94   화수동       263        16       354        18   617    34  18.147059
95   효성동      2483       128      1307        54  3790   182  20.824176

[96 rows x 8 columns]

In [138]:
result.to_csv('result_icn_st.csv', index=False, encoding='utf-8-sig')

In [140]:
df = pd.read_csv(
    '경기_초등학교.csv',encoding='cp949')
df

,학교명,도로명주소,위도,경도,읍면동
0,가람초등학교,"경기도 고양시 덕양구 행신로311번길 78 (행신동,가람초등학교)",37.623719,126.842224,행신동
1,강선초등학교,"경기도 고양시 일산서구 강선로 77 , 강선초등학교 (주엽동)",37.671228,126.764626,주엽동
2,고봉초등학교,"경기도 고양시 일산동구 중산로 280 , 고봉초등학교 (중산동)",37.696139,126.782620,중산동
3,고양백석초등학교,"경기도 고양시 일산동구 강촌로 140 (백석동,고양백석초등학교)",37.652139,126.789058,백석동
4,고양신일초등학교,"경기도 고양시 일산서구 강선로 183 , 고양신일초등학교 (일산동)",37.679550,126.770830,일산동
...,...,...,...,...,...
558,도현초등학교,경기도 용인시 처인구 모현읍 왕산로 15 도현초등학교,37.346183,127.256954,모현읍
559,처인초등학교,경기도 용인시 처인구 남사읍 한숲로57번길 17 처인초등학교,37.154096,127.168567,남사읍
560,용인솔빛초등학교,경기도 용인시 처인구 낙은로 100-5 (역북동),37.244666,127.193263,역북동
561,모담초등학교,경기도 김포시 운양로 158 (운양동),37.656730,126.674743,운양동
562,위례해솔초등학교,경기도 성남시 수정구 남위례로 131 위례해솔초등학교,37.460354,127.139264,복정동

In [142]:
df.rename(columns={'읍면동': '법정동'}, inplace=True)
df

,학교명,도로명주소,위도,경도,법정동,법정동
0,가람초등학교,"경기도 고양시 덕양구 행신로311번길 78 (행신동,가람초등학교)",37.6237194495748,126.842224411918,행신동,행신동
1,강선초등학교,"경기도 고양시 일산서구 강선로 77 , 강선초등학교 (주엽동)",37.67122822894,126.764625731644,주엽동,주엽동
2,고봉초등학교,"경기도 고양시 일산동구 중산로 280 , 고봉초등학교 (중산동)",37.6961394442868,126.782620493164,중산동,중산동
3,고양백석초등학교,"경기도 고양시 일산동구 강촌로 140 (백석동,고양백석초등학교)",37.6521391747615,126.78905766637,백석동,백석동
4,고양신일초등학교,"경기도 고양시 일산서구 강선로 183 , 고양신일초등학교 (일산동)",37.6795496217272,126.770830238317,일산동,일산동
...,...,...,...,...,...,...
558,도현초등학교,경기도 용인시 처인구 모현읍 왕산로 15 도현초등학교,37.3461830568516,127.256953804892,모현읍,모현읍 왕산리
559,처인초등학교,경기도 용인시 처인구 남사읍 한숲로57번길 17 처인초등학교,37.1540955255544,127.168566626366,남사읍,남사읍 아곡리
560,용인솔빛초등학교,경기도 용인시 처인구 낙은로 100-5 (역북동),37.2446656786154,127.193262483638,역북동,역북동
561,모담초등학교,경기도 김포시 운양로 158 (운양동),37.656730157341,126.674743025505,운양동,운양동
562,위례해솔초등학교,경기도 성남시 수정구 남위례로 131 위례해솔초등학교,37.4603536084894,127.139263749552,복정동,복정동

,학교명,도로명주소,위도,경도,법정동,법정동
0,가람초등학교,"경기도 고양시 덕양구 행신로311번길 78 (행신동,가람초등학교)",37.6237194495748,126.842224411918,행신동,행신동
1,강선초등학교,"경기도 고양시 일산서구 강선로 77 , 강선초등학교 (주엽동)",37.67122822894,126.764625731644,주엽동,주엽동
2,고봉초등학교,"경기도 고양시 일산동구 중산로 280 , 고봉초등학교 (중산동)",37.6961394442868,126.782620493164,중산동,중산동
3,고양백석초등학교,"경기도 고양시 일산동구 강촌로 140 (백석동,고양백석초등학교)",37.6521391747615,126.78905766637,백석동,백석동
4,고양신일초등학교,"경기도 고양시 일산서구 강선로 183 , 고양신일초등학교 (일산동)",37.6795496217272,126.770830238317,일산동,일산동
...,...,...,...,...,...,...
558,도현초등학교,경기도 용인시 처인구 모현읍 왕산로 15 도현초등학교,37.3461830568516,127.256953804892,모현읍,모현읍 왕산리
559,처인초등학교,경기도 용인시 처인구 남사읍 한숲로57번길 17 처인초등학교,37.1540955255544,127.168566626366,남사읍,남사읍 아곡리
560,용인솔빛초등학교,경기도 용인시 처인구 낙은로 100-5 (역북동),37.2446656786154,127.193262483638,역북동,역북동
561,모담초등학교,경기도 김포시 운양로 158 (운양동),37.656730157341,126.674743025505,운양동,운양동
562,위례해솔초등학교,경기도 성남시 수정구 남위례로 131 위례해솔초등학교,37.4603536084894,127.139263749552,복정동,복정동

In [144]:
df2 = pd.read_csv(
    '경기_중학교.csv',encoding='cp949')
df2

         학교명                                도로명주소         위도          경도  읍면동
0      가람중학교       경기도 고양시 덕양구 화신로 122(행신동,가람중학교)  37.623392  126.841112  행신동
1      고양중학교              경기도 고양시 덕양구 동세로 82(삼송동)  37.649668  126.884581  삼송동
2      능곡중학교          경기도 고양시 덕양구 행당로11번길 48(토당동)  37.622823  126.826338  토당동
3      대화중학교     경기도 고양시 일산서구 고양대로 348(대화동,대화중학교)  37.673760  126.744560  대화동
4      덕양중학교      경기도 고양시 덕양구 중앙로176번길 18-29(화전동)  37.604562  126.871721  화전동
..       ...                                  ...        ...         ...  ...
305  옥길새길중학교  경기도 부천시 소사구 양지로166번길 45옥길새길중학교(옥길동)  37.467734  126.818591  옥길동
306    한홀중학교          경기도 하남시 조정대로 115 한홀중학교(풍산동)  37.554453  127.191572  풍산동
307    처인중학교     경기도 용인시 처인구 남사읍 한숲로57번길 17 처인중학교  37.154096  127.168567  남사읍
308    도현중학교               경기도 용인시 처인구 모현읍 왕산로 15  37.346183  127.256954  모현읍
309  용인솔빛중학교              경기도 용인시 처인구 낙은로 98(역북동)  37.244766  127.195100  역북동

[310 rows x 5 columns]

In [145]:
df2.rename(columns={'읍면동': '법정동'}, inplace=True)
df2

         학교명                                도로명주소         위도          경도  법정동
0      가람중학교       경기도 고양시 덕양구 화신로 122(행신동,가람중학교)  37.623392  126.841112  행신동
1      고양중학교              경기도 고양시 덕양구 동세로 82(삼송동)  37.649668  126.884581  삼송동
2      능곡중학교          경기도 고양시 덕양구 행당로11번길 48(토당동)  37.622823  126.826338  토당동
3      대화중학교     경기도 고양시 일산서구 고양대로 348(대화동,대화중학교)  37.673760  126.744560  대화동
4      덕양중학교      경기도 고양시 덕양구 중앙로176번길 18-29(화전동)  37.604562  126.871721  화전동
..       ...                                  ...        ...         ...  ...
305  옥길새길중학교  경기도 부천시 소사구 양지로166번길 45옥길새길중학교(옥길동)  37.467734  126.818591  옥길동
306    한홀중학교          경기도 하남시 조정대로 115 한홀중학교(풍산동)  37.554453  127.191572  풍산동
307    처인중학교     경기도 용인시 처인구 남사읍 한숲로57번길 17 처인중학교  37.154096  127.168567  남사읍
308    도현중학교               경기도 용인시 처인구 모현읍 왕산로 15  37.346183  127.256954  모현읍
309  용인솔빛중학교              경기도 용인시 처인구 낙은로 98(역북동)  37.244766  127.195100  역북동

[310 rows x 5 columns]

In [146]:
df = pd.read_csv(
    '경기_중학교_학생수.csv', usecols=[4,24,25])
df

                  학교명  학급수(계)  학생수(계)
0               가평중학교      23     551
1              가평북중학교       4      38
2               설악중학교       8     171
3               조종중학교      10     222
4               청평중학교      10     185
..                ...     ...     ...
679             도현중학교      11     195
680    호원중학교부설방송통신중학교       9     204
681  수원제일중학교부설방송통신중학교       7     159
682    광명중학교부설방송통신중학교       9     185
683    삼평중학교부설방송통신중학교       9     181

[684 rows x 3 columns]

In [147]:
df2 = pd.read_csv(
    '경기_초등학교_학생수.csv', usecols=[4,33,34])
df2

              학교명  학급수(계)  학생수(계)
0        가평마장초등학교       7      52
1          가평초등학교      30     680
2          대성초등학교       7      64
3          목동초등학교       7      40
4     목동초등학교명지분교장       1       1
...           ...     ...     ...
1361     과천율목초등학교      23     460
1362      푸른샘초등학교      26     563
1363       매교초등학교      38     884
1364       규장초등학교      14     262
1365       모담초등학교       6      47

[1366 rows x 3 columns]

In [148]:
df2 = pd.read_csv(
    '경기_중학교.csv',encoding='cp949')
df2

         학교명                                도로명주소         위도          경도  읍면동
0      가람중학교       경기도 고양시 덕양구 화신로 122(행신동,가람중학교)  37.623392  126.841112  행신동
1      고양중학교              경기도 고양시 덕양구 동세로 82(삼송동)  37.649668  126.884581  삼송동
2      능곡중학교          경기도 고양시 덕양구 행당로11번길 48(토당동)  37.622823  126.826338  토당동
3      대화중학교     경기도 고양시 일산서구 고양대로 348(대화동,대화중학교)  37.673760  126.744560  대화동
4      덕양중학교      경기도 고양시 덕양구 중앙로176번길 18-29(화전동)  37.604562  126.871721  화전동
..       ...                                  ...        ...         ...  ...
305  옥길새길중학교  경기도 부천시 소사구 양지로166번길 45옥길새길중학교(옥길동)  37.467734  126.818591  옥길동
306    한홀중학교          경기도 하남시 조정대로 115 한홀중학교(풍산동)  37.554453  127.191572  풍산동
307    처인중학교     경기도 용인시 처인구 남사읍 한숲로57번길 17 처인중학교  37.154096  127.168567  남사읍
308    도현중학교               경기도 용인시 처인구 모현읍 왕산로 15  37.346183  127.256954  모현읍
309  용인솔빛중학교              경기도 용인시 처인구 낙은로 98(역북동)  37.244766  127.195100  역북동

[310 rows x 5 columns]

In [150]:
result = pd.merge(df, df2, on='학교명', how='inner')
result.head()

,학교명,학급수(계),학생수(계),도로명주소,위도,경도,읍면동
0,가람중학교,16,378,"경기도 고양시 덕양구 화신로 122(행신동,가람중학교)",37.623392,126.841112,행신동
1,고양중학교,32,823,경기도 고양시 덕양구 동세로 82(삼송동),37.649668,126.884581,삼송동
2,능곡중학교,19,411,경기도 고양시 덕양구 행당로11번길 48(토당동),37.622823,126.826338,토당동
3,대화중학교,19,509,"경기도 고양시 일산서구 고양대로 348(대화동,대화중학교)",37.673760,126.744560,대화동
4,덕양중학교,10,175,경기도 고양시 덕양구 중앙로176번길 18-29(화전동),37.604562,126.871721,화전동

In [152]:
result.rename(columns={'읍면동': '법정동'}, inplace=True)
result

,학교명,학급수(계),학생수(계),도로명주소,위도,경도,법정동
0,가람중학교,16,378,"경기도 고양시 덕양구 화신로 122(행신동,가람중학교)",37.623392,126.841112,행신동
1,고양중학교,32,823,경기도 고양시 덕양구 동세로 82(삼송동),37.649668,126.884581,삼송동
2,능곡중학교,19,411,경기도 고양시 덕양구 행당로11번길 48(토당동),37.622823,126.826338,토당동
3,대화중학교,19,509,"경기도 고양시 일산서구 고양대로 348(대화동,대화중학교)",37.673760,126.744560,대화동
4,덕양중학교,10,175,경기도 고양시 덕양구 중앙로176번길 18-29(화전동),37.604562,126.871721,화전동
...,...,...,...,...,...,...,...
294,판교대장중학교,15,412,"경기도 성남시 분당구 판교대장로5길 71, 판교대장중학교 (대장동)",37.368289,127.069778,대장동
295,과천율목중학교,13,341,경기도 과천시 과천대로2길 37(갈현동),37.407571,126.982604,갈현동
296,옥길새길중학교,7,146,경기도 부천시 소사구 양지로166번길 45옥길새길중학교(옥길동),37.467734,126.818591,옥길동
297,처인중학교,4,90,경기도 용인시 처인구 남사읍 한숲로57번길 17 처인중학교,37.154096,127.168567,남사읍
298,도현중학교,11,195,경기도 용인시 처인구 모현읍 왕산로 15,37.346183,127.256954,모현읍

In [153]:
result2 = result.groupby('법정동', as_index=False)[['학생수(계)', '학급수(계)']].sum()
result2

     법정동  학생수(계)  학급수(계)
0    가운동     241      14
1    가좌동     613      24
2    갈매동    1010      34
3    갈현동     341      13
4    감이동     700      26
..   ...     ...     ...
152  호계동    4086     143
153  호평동    2041      74
154  화도읍    3590     119
155  화전동     175      10
156  화정동    2227      89

[157 rows x 3 columns]

In [154]:
result2.to_csv('경기중학교_동합계.csv', index=False, encoding='utf-8-sig')

In [156]:

# ✅ 1. 카카오 REST API 키 넣기 (여기!!)
REST_API_KEY = "YOUR_KAKAO_API_KEY"

# ✅ 2. 주소 → (위도, 경도, 법정동) 변환 함수
def get_addr_info(address):
    url = 'https://dapi.kakao.com/v2/local/search/address.json'
    headers = {"Authorization": f"KakaoAK {REST_API_KEY}"}
    params = {'query': address}
    
    try:
        response = requests.get(url, headers=headers, params=params)
        if response.status_code == 200:
            result = response.json()
            if result['documents']:
                addr_data = result['documents'][0]['address']
                lat = addr_data['y']  # 위도
                lon = addr_data['x']  # 경도
                b_dong = addr_data['region_3depth_name']  # 법정동
                
                return lat, lon, b_dong
        return None, None, None
    except:
        return None, None, None

# ✅ 3. CSV 불러오기 (네 파일)
df = pd.read_csv('경기_중학교.csv', encoding='cp949')

# ✅ 4. API 적용 (주소 컬럼 기준)
print("좌표 변환 중...")
info_list = []

for addr in df['도로명주소']:
    info = get_addr_info(addr)
    info_list.append(info)
    time.sleep(0.2)  # ⭐ API 제한 방지 (중요)

# ✅ 5. 컬럼 추가
df['위도'], df['경도'], df['법정동'] = zip(*info_list)

# ✅ 6. 저장
df.to_csv('경기중학교_법정동.csv', index=False, encoding='utf-8-sig')

print("완료!")
df.head()

좌표 변환 중...
완료!

,학교명,도로명주소,위도,경도,읍면동,법정동
0,가람중학교,"경기도 고양시 덕양구 화신로 122(행신동,가람중학교)",37.6236599713119,126.841207087385,행신동,행신동
1,고양중학교,경기도 고양시 덕양구 동세로 82(삼송동),37.649668189667,126.884581142849,삼송동,삼송동
2,능곡중학교,경기도 고양시 덕양구 행당로11번길 48(토당동),37.622922016434,126.826641887462,토당동,토당동
3,대화중학교,"경기도 고양시 일산서구 고양대로 348(대화동,대화중학교)",37.6738435519202,126.744476855032,대화동,대화동
4,덕양중학교,경기도 고양시 덕양구 중앙로176번길 18-29(화전동),37.6046541593841,126.87171545085,화전동,화전동

In [157]:
# ✅ 1. 카카오 REST API 키 넣기 (여기!!)
REST_API_KEY = "YOUR_KAKAO_API_KEY"

# ✅ 2. 주소 → (위도, 경도, 법정동) 변환 함수
def get_addr_info(address):
    url = 'https://dapi.kakao.com/v2/local/search/address.json'
    headers = {"Authorization": f"KakaoAK {REST_API_KEY}"}
    params = {'query': address}
    
    try:
        response = requests.get(url, headers=headers, params=params)
        if response.status_code == 200:
            result = response.json()
            if result['documents']:
                addr_data = result['documents'][0]['address']
                lat = addr_data['y']  # 위도
                lon = addr_data['x']  # 경도
                b_dong = addr_data['region_3depth_name']  # 법정동
                
                return lat, lon, b_dong
        return None, None, None
    except:
        return None, None, None

# ✅ 3. CSV 불러오기 (네 파일)
df = pd.read_csv('경기_초등학교.csv', encoding='cp949')

# ✅ 4. API 적용 (주소 컬럼 기준)
print("좌표 변환 중...")
info_list = []

for addr in df['도로명주소']:
    info = get_addr_info(addr)
    info_list.append(info)
    time.sleep(0.2)  # ⭐ API 제한 방지 (중요)

# ✅ 5. 컬럼 추가
df['위도'], df['경도'], df['법정동'] = zip(*info_list)

# ✅ 6. 저장
df.to_csv('경기초등학교_법정동.csv', index=False, encoding='utf-8-sig')

print("완료!")
df.head()

좌표 변환 중...
완료!

,학교명,도로명주소,위도,경도,읍면동,법정동
0,가람초등학교,"경기도 고양시 덕양구 행신로311번길 78 (행신동,가람초등학교)",37.6237194495748,126.842224411918,행신동,행신동
1,강선초등학교,"경기도 고양시 일산서구 강선로 77 , 강선초등학교 (주엽동)",37.67122822894,126.764625731644,주엽동,주엽동
2,고봉초등학교,"경기도 고양시 일산동구 중산로 280 , 고봉초등학교 (중산동)",37.6961394442868,126.782620493164,중산동,중산동
3,고양백석초등학교,"경기도 고양시 일산동구 강촌로 140 (백석동,고양백석초등학교)",37.6521391747615,126.78905766637,백석동,백석동
4,고양신일초등학교,"경기도 고양시 일산서구 강선로 183 , 고양신일초등학교 (일산동)",37.6795496217272,126.770830238317,일산동,일산동

In [158]:
df = pd.read_csv(
    '경기중학교_법정동.csv',encoding='cp949')
df

         학교명                                도로명주소         위도          경도  법정동
0      가람중학교       경기도 고양시 덕양구 화신로 122(행신동,가람중학교)  37.623660  126.841207  행신동
1      고양중학교              경기도 고양시 덕양구 동세로 82(삼송동)  37.649668  126.884581  삼송동
2      능곡중학교          경기도 고양시 덕양구 행당로11번길 48(토당동)  37.622922  126.826642  토당동
3      대화중학교     경기도 고양시 일산서구 고양대로 348(대화동,대화중학교)  37.673844  126.744477  대화동
4      덕양중학교      경기도 고양시 덕양구 중앙로176번길 18-29(화전동)  37.604654  126.871715  화전동
..       ...                                  ...        ...         ...  ...
304  옥길새길중학교  경기도 부천시 소사구 양지로166번길 45옥길새길중학교(옥길동)  37.467734  126.818591  옥길동
305    한홀중학교          경기도 하남시 조정대로 115 한홀중학교(풍산동)  37.554453  127.191572  풍산동
306    처인중학교     경기도 용인시 처인구 남사읍 한숲로57번길 17 처인중학교  37.154096  127.168567  남사읍
307    도현중학교               경기도 용인시 처인구 모현읍 왕산로 15  37.346183  127.256954  모현읍
308  용인솔빛중학교              경기도 용인시 처인구 낙은로 98(역북동)  37.244766  127.195100  역북동

[309 rows x 5 columns]

In [159]:
df2 = pd.read_csv(
    '경기_중학교_학생수.csv', usecols=[4,24,25])
df2

                  학교명  학급수(계)  학생수(계)
0               가평중학교      23     551
1              가평북중학교       4      38
2               설악중학교       8     171
3               조종중학교      10     222
4               청평중학교      10     185
..                ...     ...     ...
679             도현중학교      11     195
680    호원중학교부설방송통신중학교       9     204
681  수원제일중학교부설방송통신중학교       7     159
682    광명중학교부설방송통신중학교       9     185
683    삼평중학교부설방송통신중학교       9     181

[684 rows x 3 columns]

In [160]:
result = pd.merge(df2, df, on='학교명', how='inner')
result.head()

,학교명,학급수(계),학생수(계),도로명주소,위도,경도,법정동
0,가람중학교,16,378,"경기도 고양시 덕양구 화신로 122(행신동,가람중학교)",37.623660,126.841207,행신동
1,고양중학교,32,823,경기도 고양시 덕양구 동세로 82(삼송동),37.649668,126.884581,삼송동
2,능곡중학교,19,411,경기도 고양시 덕양구 행당로11번길 48(토당동),37.622922,126.826642,토당동
3,대화중학교,19,509,"경기도 고양시 일산서구 고양대로 348(대화동,대화중학교)",37.673844,126.744477,대화동
4,덕양중학교,10,175,경기도 고양시 덕양구 중앙로176번길 18-29(화전동),37.604654,126.871715,화전동

In [161]:
df3 = pd.read_csv(
    '경기초등학교_법정동.csv',encoding='cp949')
df3

,학교명,도로명주소,위도,경도,법정동
0,가람초등학교,"경기도 고양시 덕양구 행신로311번길 78 (행신동,가람초등학교)",37.623719,126.842224,행신동
1,강선초등학교,"경기도 고양시 일산서구 강선로 77 , 강선초등학교 (주엽동)",37.671228,126.764626,주엽동
2,고봉초등학교,"경기도 고양시 일산동구 중산로 280 , 고봉초등학교 (중산동)",37.696139,126.782620,중산동
3,고양백석초등학교,"경기도 고양시 일산동구 강촌로 140 (백석동,고양백석초등학교)",37.652139,126.789058,백석동
4,고양신일초등학교,"경기도 고양시 일산서구 강선로 183 , 고양신일초등학교 (일산동)",37.679550,126.770830,일산동
...,...,...,...,...,...
558,도현초등학교,경기도 용인시 처인구 모현읍 왕산로 15 도현초등학교,37.346183,127.256954,모현읍
559,처인초등학교,경기도 용인시 처인구 남사읍 한숲로57번길 17 처인초등학교,37.154096,127.168567,남사읍
560,용인솔빛초등학교,경기도 용인시 처인구 낙은로 100-5 (역북동),37.244666,127.193263,역북동
561,모담초등학교,경기도 김포시 운양로 158 (운양동),37.656730,126.674743,운양동
562,위례해솔초등학교,경기도 성남시 수정구 남위례로 131 위례해솔초등학교,37.460354,127.139264,복정동

In [162]:
df4 = pd.read_csv(
    '경기_초등학교_학생수.csv', usecols=[4,33,34])
df4

              학교명  학급수(계)  학생수(계)
0        가평마장초등학교       7      52
1          가평초등학교      30     680
2          대성초등학교       7      64
3          목동초등학교       7      40
4     목동초등학교명지분교장       1       1
...           ...     ...     ...
1361     과천율목초등학교      23     460
1362      푸른샘초등학교      26     563
1363       매교초등학교      38     884
1364       규장초등학교      14     262
1365       모담초등학교       6      47

[1366 rows x 3 columns]

In [163]:
result2 = pd.merge(df4, df3, on='학교명', how='inner')
result2.head()

,학교명,학급수(계),학생수(계),도로명주소,위도,경도,법정동
0,가람초등학교,17,309,"경기도 고양시 덕양구 행신로311번길 78 (행신동,가람초등학교)",37.623719,126.842224,행신동
1,강선초등학교,22,507,"경기도 고양시 일산서구 강선로 77 , 강선초등학교 (주엽동)",37.671228,126.764626,주엽동
2,고봉초등학교,17,323,"경기도 고양시 일산동구 중산로 280 , 고봉초등학교 (중산동)",37.696139,126.782620,중산동
3,고양백석초등학교,20,452,"경기도 고양시 일산동구 강촌로 140 (백석동,고양백석초등학교)",37.652139,126.789058,백석동
4,고양신일초등학교,35,831,"경기도 고양시 일산서구 강선로 183 , 고양신일초등학교 (일산동)",37.679550,126.770830,일산동

In [164]:
result3 = result.groupby('법정동', as_index=False)[['학생수(계)', '학급수(계)']].sum()
result

,학교명,학급수(계),학생수(계),도로명주소,위도,경도,법정동
0,가람중학교,16,378,"경기도 고양시 덕양구 화신로 122(행신동,가람중학교)",37.623660,126.841207,행신동
1,고양중학교,32,823,경기도 고양시 덕양구 동세로 82(삼송동),37.649668,126.884581,삼송동
2,능곡중학교,19,411,경기도 고양시 덕양구 행당로11번길 48(토당동),37.622922,126.826642,토당동
3,대화중학교,19,509,"경기도 고양시 일산서구 고양대로 348(대화동,대화중학교)",37.673844,126.744477,대화동
4,덕양중학교,10,175,경기도 고양시 덕양구 중앙로176번길 18-29(화전동),37.604654,126.871715,화전동
...,...,...,...,...,...,...,...
294,판교대장중학교,15,412,"경기도 성남시 분당구 판교대장로5길 71, 판교대장중학교 (대장동)",37.368570,127.069678,대장동
295,과천율목중학교,13,341,경기도 과천시 과천대로2길 37(갈현동),37.407571,126.982604,갈현동
296,옥길새길중학교,7,146,경기도 부천시 소사구 양지로166번길 45옥길새길중학교(옥길동),37.467734,126.818591,옥길동
297,처인중학교,4,90,경기도 용인시 처인구 남사읍 한숲로57번길 17 처인중학교,37.154096,127.168567,남사읍
298,도현중학교,11,195,경기도 용인시 처인구 모현읍 왕산로 15,37.346183,127.256954,모현읍

In [166]:
result3 = result.groupby('법정동', as_index=False)[['학생수(계)', '학급수(계)']].sum()
result3

     법정동  학생수(계)  학급수(계)
0    가좌동     613      24
1    갈매동    1010      34
2    갈현동     341      13
3    감이동     700      26
4    감일동     561      22
..   ...     ...     ...
148  호계동    4086     143
149  호평동    2041      74
150  화도읍    3590     119
151  화전동     175      10
152  화정동    2227      89

[153 rows x 3 columns]

In [167]:
result4 = result2.groupby('법정동', as_index=False)[['학생수(계)', '학급수(계)']].sum()
result4

     법정동  학생수(계)  학급수(계)
0    가좌동     762      38
1    가학동      44       7
2    갈매동    2420     102
3    감이동    2200      94
4    감일동    1568      70
..   ...     ...     ...
171  호계동    5931     253
172  호평동    3433     152
173  화도읍    5779     276
174  화전동     179      12
175  화정동    2498     117

[176 rows x 3 columns]

In [168]:
result3.to_csv('경기중학교_동합계.csv', index=False, encoding='utf-8-sig')

In [169]:
result4.to_csv('경기초등학교_동합계.csv', index=False, encoding='utf-8-sig')

In [170]:
ele_df = pd.read_csv('경기중학교_동합계.csv', encoding='utf-8-sig')
ele_df

     법정동  학생수(계)  학급수(계)
0    가좌동     613      24
1    갈매동    1010      34
2    갈현동     341      13
3    감이동     700      26
4    감일동     561      22
..   ...     ...     ...
148  호계동    4086     143
149  호평동    2041      74
150  화도읍    3590     119
151  화전동     175      10
152  화정동    2227      89

[153 rows x 3 columns]

In [171]:
mid_df = pd.read_csv('경기초등학교_동합계.csv', encoding='utf-8-sig')
mid_df

     법정동  학생수(계)  학급수(계)
0    가좌동     762      38
1    가학동      44       7
2    갈매동    2420     102
3    감이동    2200      94
4    감일동    1568      70
..   ...     ...     ...
171  호계동    5931     253
172  호평동    3433     152
173  화도읍    5779     276
174  화전동     179      12
175  화정동    2498     117

[176 rows x 3 columns]

In [172]:
result = pd.merge(
    ele_df, mid_df,
    on='법정동',
    how='outer',
    suffixes=('_초', '_중')
)
result

     법정동  학생수(계)_초  학급수(계)_초  학생수(계)_중  학급수(계)_중
0    가좌동     613.0      24.0     762.0      38.0
1    가학동       NaN       NaN      44.0       7.0
2    갈매동    1010.0      34.0    2420.0     102.0
3    갈현동     341.0      13.0       NaN       NaN
4    감이동     700.0      26.0    2200.0      94.0
..   ...       ...       ...       ...       ...
182  호계동    4086.0     143.0    5931.0     253.0
183  호평동    2041.0      74.0    3433.0     152.0
184  화도읍    3590.0     119.0    5779.0     276.0
185  화전동     175.0      10.0     179.0      12.0
186  화정동    2227.0      89.0    2498.0     117.0

[187 rows x 5 columns]

In [173]:
result = result.fillna(0)

In [174]:
cols = ['학생수(계)_초','학생수(계)_중','학급수(계)_초','학급수(계)_중']
result[cols] = result[cols].astype(int)
result

     법정동  학생수(계)_초  학급수(계)_초  학생수(계)_중  학급수(계)_중
0    가좌동       613        24       762        38
1    가학동         0         0        44         7
2    갈매동      1010        34      2420       102
3    갈현동       341        13         0         0
4    감이동       700        26      2200        94
..   ...       ...       ...       ...       ...
182  호계동      4086       143      5931       253
183  호평동      2041        74      3433       152
184  화도읍      3590       119      5779       276
185  화전동       175        10       179        12
186  화정동      2227        89      2498       117

[187 rows x 5 columns]

In [175]:
result.to_csv('result_gg_st.csv', index=False, encoding='utf-8-sig')

In [176]:
result['총학생수'] = result['학생수(계)_초'] + result['학생수(계)_중']
result['총학급수'] = result['학급수(계)_초'] + result['학급수(계)_중']

In [177]:
result['학급당학생수'] = result['총학생수'] / result['총학급수']
result

     법정동  학생수(계)_초  학급수(계)_초  학생수(계)_중  학급수(계)_중   총학생수  총학급수     학급당학생수
0    가좌동       613        24       762        38   1375    62  22.177419
1    가학동         0         0        44         7     44     7   6.285714
2    갈매동      1010        34      2420       102   3430   136  25.220588
3    갈현동       341        13         0         0    341    13  26.230769
4    감이동       700        26      2200        94   2900   120  24.166667
..   ...       ...       ...       ...       ...    ...   ...        ...
182  호계동      4086       143      5931       253  10017   396  25.295455
183  호평동      2041        74      3433       152   5474   226  24.221239
184  화도읍      3590       119      5779       276   9369   395  23.718987
185  화전동       175        10       179        12    354    22  16.090909
186  화정동      2227        89      2498       117   4725   206  22.936893

[187 rows x 8 columns]

In [178]:
result.to_csv('result_gg_st.csv', index=False, encoding='utf-8-sig')

In [179]:
result

     법정동  학생수(계)_초  학급수(계)_초  학생수(계)_중  학급수(계)_중   총학생수  총학급수     학급당학생수
0    가좌동       613        24       762        38   1375    62  22.177419
1    가학동         0         0        44         7     44     7   6.285714
2    갈매동      1010        34      2420       102   3430   136  25.220588
3    갈현동       341        13         0         0    341    13  26.230769
4    감이동       700        26      2200        94   2900   120  24.166667
..   ...       ...       ...       ...       ...    ...   ...        ...
182  호계동      4086       143      5931       253  10017   396  25.295455
183  호평동      2041        74      3433       152   5474   226  24.221239
184  화도읍      3590       119      5779       276   9369   395  23.718987
185  화전동       175        10       179        12    354    22  16.090909
186  화정동      2227        89      2498       117   4725   206  22.936893

[187 rows x 8 columns]

In [183]:
df = pd.read_csv(
    '인구통계.csv', usecols=[0,1,2,5,6,7,8,9,10,24,25,26,27,28,29], encoding='cp949')
df

,시도명,시군구명,읍면동명,0세남자,1세남자,2세남자,3세남자,4세남자,5세남자,0세여자,1세여자,2세여자,3세여자,4세여자,5세여자
0,서울특별시,종로구,청운효자동,17,21,21,20,20,29,18,23,15,22,23,21
1,서울특별시,종로구,사직동,6,19,11,21,22,15,10,17,13,16,23,16
2,서울특별시,종로구,삼청동,5,3,1,3,4,2,3,2,3,3,3,2
3,서울특별시,종로구,부암동,15,16,14,15,12,12,9,7,11,15,14,11
4,서울특별시,종로구,평창동,36,37,42,26,51,47,35,30,26,36,41,52
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
858,경기도,김포시,풍무동,168,173,195,213,231,226,159,178,169,175,200,232
859,경기도,김포시,장기동,106,98,131,139,178,172,90,125,101,150,155,154
860,경기도,김포시,구래동,169,165,168,196,177,239,174,147,142,180,190,205
861,경기도,김포시,마산동,153,153,149,184,207,185,130,116,139,175,149,183
862,경기도,김포시,운양동,135,148,142,210,203,250,130,133,135,183,179,223

In [184]:
cols = [
    '0세남자','1세남자','2세남자','3세남자','4세남자','5세남자',
    '0세여자','1세여자','2세여자','3세여자','4세여자','5세여자'
]

df['유아인구'] = df[cols].sum(axis=1)
df

,시도명,시군구명,읍면동명,0세남자,1세남자,2세남자,3세남자,4세남자,5세남자,0세여자,1세여자,2세여자,3세여자,4세여자,5세여자,유아인구
0,서울특별시,종로구,청운효자동,17,21,21,20,20,29,18,23,15,22,23,21,250
1,서울특별시,종로구,사직동,6,19,11,21,22,15,10,17,13,16,23,16,189
2,서울특별시,종로구,삼청동,5,3,1,3,4,2,3,2,3,3,3,2,34
3,서울특별시,종로구,부암동,15,16,14,15,12,12,9,7,11,15,14,11,151
4,서울특별시,종로구,평창동,36,37,42,26,51,47,35,30,26,36,41,52,459
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
858,경기도,김포시,풍무동,168,173,195,213,231,226,159,178,169,175,200,232,2319
859,경기도,김포시,장기동,106,98,131,139,178,172,90,125,101,150,155,154,1599
860,경기도,김포시,구래동,169,165,168,196,177,239,174,147,142,180,190,205,2152
861,경기도,김포시,마산동,153,153,149,184,207,185,130,116,139,175,149,183,1923
862,경기도,김포시,운양동,135,148,142,210,203,250,130,133,135,183,179,223,2071

In [186]:
df = df[['시도명','시군구명','읍면동명','유아인구']]

In [187]:
df

       시도명 시군구명   읍면동명  유아인구
0    서울특별시  종로구  청운효자동   250
1    서울특별시  종로구    사직동   189
2    서울특별시  종로구    삼청동    34
3    서울특별시  종로구    부암동   151
4    서울특별시  종로구    평창동   459
..     ...  ...    ...   ...
858    경기도  김포시    풍무동  2319
859    경기도  김포시    장기동  1599
860    경기도  김포시    구래동  2152
861    경기도  김포시    마산동  1923
862    경기도  김포시    운양동  2071

[863 rows x 4 columns]

In [188]:
kgs = pd.read_csv(
    '서울어린이집.csv', encoding='cp949')
kgs

,시도,시군구,어린이집명,어린이집유형구분,운영현황,우편번호,주소,어린이집전화번호,어린이집팩스번호,보육실수,...,정원수,현원수,위도,경도,통학차량운영여부,홈페이지주소,인가일자,휴지시작일자,휴지종료일자,폐지일자
0,서울특별시,종로구,삼청어린이집,국공립,정상,3049,서울특별시 종로구 삼청로7길 26 (팔판동),02-723-0155,02-723-0155,3,...,32,12,37.584006,126.980487,미운영,http://cafe.naver.com/samchung1004,1999-09-01,NaN,NaN,NaN
1,서울특별시,종로구,창신어린이집,사회복지법인,정상,3105,서울특별시 종로구 창신5길 22 (창신동),02-743-6302,02-743-6302,4,...,77,20,37.573605,127.012017,미운영,http://changsin.ukid.kr,1978-12-01,NaN,NaN,NaN
2,서울특별시,종로구,아동회관어린이집,국공립,정상,3094,서울특별시 종로구 지봉로13길 14 아동회관어린이집,02-763-6038,050-5845-6038,6,...,65,35,37.578307,127.011810,미운영,NaN,1988-10-01,NaN,NaN,NaN
3,서울특별시,종로구,부암어린이집,국공립,정상,3019,서울특별시 종로구 세검정로6다길 10-7,02-396-6226,02-396-6227,5,...,92,80,37.601522,126.963073,미운영,https://buarm.kidsnote.ac,1998-07-29,NaN,NaN,NaN
4,서울특별시,종로구,낙산어린이집,국공립,정상,3091,서울특별시 종로구 창신길 210-11 낙산어린이집 (창신동),02-765-1268,02-765-1268,5,...,52,16,37.579530,127.010167,미운영,http://children.seoul.go.kr,1981-10-13,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4071,서울특별시,강동구,구립그란츠리버키즈어린이집,국공립,정상,5379,서울특별시 강동구 천호대로 1050 101동 1~2층,02-471-7178,--,3,...,30,21,37.536249,127.128045,미운영,NaN,2025-03-31,NaN,NaN,NaN
4072,서울특별시,강동구,구립둔촌1동어린이집,국공립,정상,5409,서울특별시 강동구 양재대로 1342 1층,02-486-1342,02-487-1342,6,...,85,63,37.525860,127.136388,미운영,NaN,2025-03-27,NaN,NaN,NaN
4073,서울특별시,강동구,구립온빛어린이집,국공립,정상,5206,서울특별시 강동구 아리수로 385 1층(고덕동),02-426-0701,02-426-0702,5,...,51,20,37.563331,127.172392,미운영,NaN,2025-04-29,NaN,NaN,NaN
4074,서울특별시,강동구,구립더샵강동센트럴시티어린이집,국공립,정상,5335,서울특별시 강동구 진황도로 14 102동,02-478-2888,02-478-3888,8,...,63,0,37.566470,126.977963,NaN,NaN,2025-12-16,NaN,NaN,NaN
4075,서울특별시,강동구,구립강동프레스티지원어린이집,국공립,정상,5327,서울특별시 강동구 올림픽로78길 37 104동,010-6393-4400,--,8,...,55,0,37.566470,126.977963,NaN,NaN,2025-12-23,NaN,NaN,NaN

In [189]:
kgs.columns

Index(['시도', '시군구', '어린이집명', '어린이집유형구분', '운영현황', '우편번호', '주소', '어린이집전화번호',
       '어린이집팩스번호', '보육실수', '보육실면적', '놀이터수', 'CCTV설치수', '보육교직원수', '정원수', '현원수',
       '위도', '경도', '통학차량운영여부', '홈페이지주소', '인가일자', '휴지시작일자', '휴지종료일자', '폐지일자'],
      dtype='object')

In [191]:
kgs = pd.read_csv(
    '서울어린이집.csv', usecols=[0,1,2,3,6,16,17],encoding='cp949')
kgs

,시도,시군구,어린이집명,어린이집유형구분,주소,위도,경도
0,서울특별시,종로구,삼청어린이집,국공립,서울특별시 종로구 삼청로7길 26 (팔판동),37.584006,126.980487
1,서울특별시,종로구,창신어린이집,사회복지법인,서울특별시 종로구 창신5길 22 (창신동),37.573605,127.012017
2,서울특별시,종로구,아동회관어린이집,국공립,서울특별시 종로구 지봉로13길 14 아동회관어린이집,37.578307,127.011810
3,서울특별시,종로구,부암어린이집,국공립,서울특별시 종로구 세검정로6다길 10-7,37.601522,126.963073
4,서울특별시,종로구,낙산어린이집,국공립,서울특별시 종로구 창신길 210-11 낙산어린이집 (창신동),37.579530,127.010167
...,...,...,...,...,...,...,...
4071,서울특별시,강동구,구립그란츠리버키즈어린이집,국공립,서울특별시 강동구 천호대로 1050 101동 1~2층,37.536249,127.128045
4072,서울특별시,강동구,구립둔촌1동어린이집,국공립,서울특별시 강동구 양재대로 1342 1층,37.525860,127.136388
4073,서울특별시,강동구,구립온빛어린이집,국공립,서울특별시 강동구 아리수로 385 1층(고덕동),37.563331,127.172392
4074,서울특별시,강동구,구립더샵강동센트럴시티어린이집,국공립,서울특별시 강동구 진황도로 14 102동,37.566470,126.977963
4075,서울특별시,강동구,구립강동프레스티지원어린이집,국공립,서울특별시 강동구 올림픽로78길 37 104동,37.566470,126.977963

In [192]:
kgs.to_csv('서울어린이집.csv', index=False, encoding='utf-8-sig')

In [194]:
# ✅ 1. 카카오 REST API 키 넣기 (여기!!)
REST_API_KEY = "YOUR_KAKAO_API_KEY"

# ✅ 2. 주소 → (위도, 경도, 법정동) 변환 함수
def get_addr_info(address):
    url = 'https://dapi.kakao.com/v2/local/search/address.json'
    headers = {"Authorization": f"KakaoAK {REST_API_KEY}"}
    params = {'query': address}
    
    try:
        response = requests.get(url, headers=headers, params=params)
        if response.status_code == 200:
            result = response.json()
            if result['documents']:
                addr_data = result['documents'][0]['address']
                lat = addr_data['y']  # 위도
                lon = addr_data['x']  # 경도
                b_dong = addr_data['region_3depth_name']  # 법정동
                
                return lat, lon, b_dong
        return None, None, None
    except:
        return None, None, None

# ✅ 3. CSV 불러오기 (네 파일)
df = pd.read_csv('서울어린이집.csv', encoding='utf-8-sig')

# ✅ 4. API 적용 (주소 컬럼 기준)
print("좌표 변환 중...")
info_list = []

for addr in df['주소']:
    info = get_addr_info(addr)
    info_list.append(info)
    time.sleep(0.2)  # ⭐ API 제한 방지 (중요)

# ✅ 5. 컬럼 추가
df['위도'], df['경도'], df['법정동'] = zip(*info_list)

# ✅ 6. 저장
df.to_csv('서울어린이집_법정동.csv', index=False, encoding='utf-8-sig')

print("완료!")
df.head()

좌표 변환 중...
완료!

,시도,시군구,어린이집명,어린이집유형구분,주소,위도,경도,법정동
0,서울특별시,종로구,삼청어린이집,국공립,서울특별시 종로구 삼청로7길 26 (팔판동),37.5840321640655,126.980481002242,팔판동
1,서울특별시,종로구,창신어린이집,사회복지법인,서울특별시 종로구 창신5길 22 (창신동),37.5736477680085,127.012017293871,창신동
2,서울특별시,종로구,아동회관어린이집,국공립,서울특별시 종로구 지봉로13길 14 아동회관어린이집,37.5789483137908,127.014467533898,창신동
3,서울특별시,종로구,부암어린이집,국공립,서울특별시 종로구 세검정로6다길 10-7,37.601604649771,126.963099123923,신영동
4,서울특별시,종로구,낙산어린이집,국공립,서울특별시 종로구 창신길 210-11 낙산어린이집 (창신동),37.5795467508656,127.010182884217,창신동

In [195]:
# ✅ 1. 카카오 REST API 키 넣기 (여기!!)
REST_API_KEY = "YOUR_KAKAO_API_KEY"

# ✅ 2. 주소 → (위도, 경도, 법정동) 변환 함수
def get_addr_info(address):
    url = 'https://dapi.kakao.com/v2/local/search/address.json'
    headers = {"Authorization": f"KakaoAK {REST_API_KEY}"}
    params = {'query': address}
    
    try:
        response = requests.get(url, headers=headers, params=params)
        if response.status_code == 200:
            result = response.json()
            if result['documents']:
                addr_data = result['documents'][0]['address']
                lat = addr_data['y']  # 위도
                lon = addr_data['x']  # 경도
                b_dong = addr_data['region_3depth_name']  # 법정동
                
                return lat, lon, b_dong
        return None, None, None
    except:
        return None, None, None

# ✅ 3. CSV 불러오기 (네 파일)
df = pd.read_csv('인천어린이집_법정동.csv', encoding='utf-8-sig')

# ✅ 4. API 적용 (주소 컬럼 기준)
print("좌표 변환 중...")
info_list = []

for addr in df['주소']:
    info = get_addr_info(addr)
    info_list.append(info)
    time.sleep(0.2)  # ⭐ API 제한 방지 (중요)

# ✅ 5. 컬럼 추가
df['위도'], df['경도'], df['법정동'] = zip(*info_list)

# ✅ 6. 저장
df.to_csv('인천어린이집_법정동.csv', index=False, encoding='utf-8-sig')

print("완료!")
df.head()

좌표 변환 중...
완료!

,시도,시군구,어린이집명,어린이집유형구분,주소,위도,경도,법정동
0,인천광역시,중구,장미어린이집,국공립,인천광역시 중구 참외전로174번길 12-1,37.471945263384,126.634784259158,경동
1,인천광역시,중구,금산어린이집,국공립,인천광역시 중구 백운로351번길 3 (운북동),37.5058305883434,126.519962026481,운북동
2,인천광역시,중구,효성어린이집,사회복지법인,인천광역시 중구 백운로 34 (중산동),37.5010123199487,126.55262267154,중산동
3,인천광역시,중구,찬솔어린이집,국공립,"인천광역시 중구 축항대로86번길 47 3동 101호(항동7가, 라이프아파트)",37.4517673879313,126.60497770554,항동7가
4,인천광역시,중구,비둘기어린이집,국공립,인천광역시 중구 자유공원서로29번길 3-19,37.4766609983658,126.619777159028,북성동3가

In [196]:
kgg = pd.read_csv(
    '경기어린이집.csv', usecols=[0,1,2,3,6,16,17],encoding='cp949')
kgg

,시도,시군구,어린이집명,어린이집유형구분,주소,위도,경도
0,경기도,고양시일산서구,미소어린이집,가정,"경기도 고양시 일산서구 대산로 249 106동 102호(대화동, 성저마을동익1단지아파트)",37.679185,126.750311
1,경기도,고양시덕양구,신임마누엘어린이집,민간,경기도 고양시 덕양구 혜음로13번길 34 (고양동),37.702042,126.899583
2,경기도,고양시일산동구,고양시립저현어린이집,국공립,경기도 고양시 일산동구 위시티2로11번길 22-21,37.677383,126.813707
3,경기도,고양시일산동구,동심어린이집,민간,"경기도 고양시 일산동구 강촌로 191 (마두동,백마마을4단지 내)",37.656121,126.792563
4,경기도,고양시일산동구,안젤라어린이집,사회복지법인,경기도 고양시 일산동구 강송로225번길 39 (마두동),37.657403,126.779241
...,...,...,...,...,...,...,...
3989,경기도,김포시,양우늘푸른어린이집,민간,경기도 김포시 고촌읍 신곡로 75 양우내안애 관리동,37.606140,126.771224
3990,경기도,김포시,시립아이월드어린이집,국공립,경기도 김포시 풍무로69번길 47 (당곡마을 월드메르디앙아파트),37.603274,126.717022
3991,경기도,김포시,시립운양래미안어린이집,국공립,"경기도 김포시 김포한강11로 227 (운양동, 풍경마을 래미안 한강2차)",37.566470,126.977963
3992,경기도,김포시,시립다예린어린이집,국공립,"경기도 김포시 김포한강5로 417 (구래동, 한가람마을 우미린)",37.648258,126.625498
3993,경기도,김포시,서광노리숲어린이집,민간,경기도 김포시 김포대로926번길 15 신안서광아파트 관리동,37.626382,126.713972

In [197]:
kgg.to_csv('경기어린이집_법정동.csv', index=False, encoding='utf-8-sig')

In [198]:
kgg

,시도,시군구,어린이집명,어린이집유형구분,주소,위도,경도
0,경기도,고양시일산서구,미소어린이집,가정,"경기도 고양시 일산서구 대산로 249 106동 102호(대화동, 성저마을동익1단지아파트)",37.679185,126.750311
1,경기도,고양시덕양구,신임마누엘어린이집,민간,경기도 고양시 덕양구 혜음로13번길 34 (고양동),37.702042,126.899583
2,경기도,고양시일산동구,고양시립저현어린이집,국공립,경기도 고양시 일산동구 위시티2로11번길 22-21,37.677383,126.813707
3,경기도,고양시일산동구,동심어린이집,민간,"경기도 고양시 일산동구 강촌로 191 (마두동,백마마을4단지 내)",37.656121,126.792563
4,경기도,고양시일산동구,안젤라어린이집,사회복지법인,경기도 고양시 일산동구 강송로225번길 39 (마두동),37.657403,126.779241
...,...,...,...,...,...,...,...
3989,경기도,김포시,양우늘푸른어린이집,민간,경기도 김포시 고촌읍 신곡로 75 양우내안애 관리동,37.606140,126.771224
3990,경기도,김포시,시립아이월드어린이집,국공립,경기도 김포시 풍무로69번길 47 (당곡마을 월드메르디앙아파트),37.603274,126.717022
3991,경기도,김포시,시립운양래미안어린이집,국공립,"경기도 김포시 김포한강11로 227 (운양동, 풍경마을 래미안 한강2차)",37.566470,126.977963
3992,경기도,김포시,시립다예린어린이집,국공립,"경기도 김포시 김포한강5로 417 (구래동, 한가람마을 우미린)",37.648258,126.625498
3993,경기도,김포시,서광노리숲어린이집,민간,경기도 김포시 김포대로926번길 15 신안서광아파트 관리동,37.626382,126.713972

In [199]:
# ✅ 1. 카카오 REST API 키 넣기 (여기!!)
REST_API_KEY = "YOUR_KAKAO_API_KEY"

# ✅ 2. 주소 → (위도, 경도, 법정동) 변환 함수
def get_addr_info(address):
    url = 'https://dapi.kakao.com/v2/local/search/address.json'
    headers = {"Authorization": f"KakaoAK {REST_API_KEY}"}
    params = {'query': address}
    
    try:
        response = requests.get(url, headers=headers, params=params)
        if response.status_code == 200:
            result = response.json()
            if result['documents']:
                addr_data = result['documents'][0]['address']
                lat = addr_data['y']  # 위도
                lon = addr_data['x']  # 경도
                b_dong = addr_data['region_3depth_name']  # 법정동
                
                return lat, lon, b_dong
        return None, None, None
    except:
        return None, None, None

# ✅ 3. CSV 불러오기 (네 파일)
df = pd.read_csv('경기어린이집_법정동.csv', encoding='utf-8-sig')

# ✅ 4. API 적용 (주소 컬럼 기준)
print("좌표 변환 중...")
info_list = []

for addr in df['주소']:
    info = get_addr_info(addr)
    info_list.append(info)
    time.sleep(0.2)  # ⭐ API 제한 방지 (중요)

# ✅ 5. 컬럼 추가
df['위도'], df['경도'], df['법정동'] = zip(*info_list)

# ✅ 6. 저장
df.to_csv('경기어린이집_법정동.csv', index=False, encoding='utf-8-sig')

print("완료!")
df.head()

좌표 변환 중...
완료!

,시도,시군구,어린이집명,어린이집유형구분,주소,위도,경도,법정동
0,경기도,고양시일산서구,미소어린이집,가정,"경기도 고양시 일산서구 대산로 249 106동 102호(대화동, 성저마을동익1단지아파트)",37.679564287656,126.751468068203,대화동
1,경기도,고양시덕양구,신임마누엘어린이집,민간,경기도 고양시 덕양구 혜음로13번길 34 (고양동),37.7020663256629,126.899653714746,고양동
2,경기도,고양시일산동구,고양시립저현어린이집,국공립,경기도 고양시 일산동구 위시티2로11번길 22-21,37.6773412572031,126.81370871157,식사동
3,경기도,고양시일산동구,동심어린이집,민간,"경기도 고양시 일산동구 강촌로 191 (마두동,백마마을4단지 내)",37.6553426282362,126.794735459959,마두동
4,경기도,고양시일산동구,안젤라어린이집,사회복지법인,경기도 고양시 일산동구 강송로225번길 39 (마두동),37.6574425350477,126.779214197105,마두동

In [200]:
# ✅ 1. 카카오 REST API 키 넣기 (여기!!)
REST_API_KEY = "YOUR_KAKAO_API_KEY"

# ✅ 2. 주소 → (위도, 경도, 법정동) 변환 함수
def get_addr_info(address):
    url = 'https://dapi.kakao.com/v2/local/search/address.json'
    headers = {"Authorization": f"KakaoAK {REST_API_KEY}"}
    params = {'query': address}
    
    try:
        response = requests.get(url, headers=headers, params=params)
        if response.status_code == 200:
            result = response.json()
            if result['documents']:
                addr_data = result['documents'][0]['address']
                lat = addr_data['y']  # 위도
                lon = addr_data['x']  # 경도
                b_dong = addr_data['region_3depth_h_name']  # 법정동
                
                return lat, lon, b_dong
        return None, None, None
    except:
        return None, None, None

# ✅ 3. CSV 불러오기 (네 파일)
df = pd.read_csv('경기어린이집_법정동.csv', encoding='utf-8-sig')

# ✅ 4. API 적용 (주소 컬럼 기준)
print("좌표 변환 중...")
info_list = []

for addr in df['주소']:
    info = get_addr_info(addr)
    info_list.append(info)
    time.sleep(0.2)  # ⭐ API 제한 방지 (중요)

# ✅ 5. 컬럼 추가
df['위도'], df['경도'], df['법정동'] = zip(*info_list)

# ✅ 6. 저장
df.to_csv('경기어린이집_법정동.csv', index=False, encoding='utf-8-sig')

print("완료!")
df.head()

좌표 변환 중...
완료!

,시도,시군구,어린이집명,어린이집유형구분,주소,위도,경도,법정동
0,경기도,고양시일산서구,미소어린이집,가정,"경기도 고양시 일산서구 대산로 249 106동 102호(대화동, 성저마을동익1단지아파트)",37.679564287656,126.751468068203,대화동
1,경기도,고양시덕양구,신임마누엘어린이집,민간,경기도 고양시 덕양구 혜음로13번길 34 (고양동),37.7020663256629,126.899653714746,고양동
2,경기도,고양시일산동구,고양시립저현어린이집,국공립,경기도 고양시 일산동구 위시티2로11번길 22-21,37.6773412572031,126.81370871157,식사동
3,경기도,고양시일산동구,동심어린이집,민간,"경기도 고양시 일산동구 강촌로 191 (마두동,백마마을4단지 내)",37.6553426282362,126.794735459959,마두1동
4,경기도,고양시일산동구,안젤라어린이집,사회복지법인,경기도 고양시 일산동구 강송로225번길 39 (마두동),37.6574425350477,126.779214197105,마두1동

In [201]:
# ✅ 1. 카카오 REST API 키 넣기 (여기!!)
REST_API_KEY = "YOUR_KAKAO_API_KEY"

# ✅ 2. 주소 → (위도, 경도, 법정동) 변환 함수
def get_addr_info(address):
    url = 'https://dapi.kakao.com/v2/local/search/address.json'
    headers = {"Authorization": f"KakaoAK {REST_API_KEY}"}
    params = {'query': address}
    
    try:
        response = requests.get(url, headers=headers, params=params)
        if response.status_code == 200:
            result = response.json()
            if result['documents']:
                addr_data = result['documents'][0]['address']
                lat = addr_data['y']  # 위도
                lon = addr_data['x']  # 경도
                b_dong = addr_data['region_3depth_h_name']  # 법정동
                
                return lat, lon, b_dong
        return None, None, None
    except:
        return None, None, None

# ✅ 3. CSV 불러오기 (네 파일)
df = pd.read_csv('인천어린이집_법정동.csv', encoding='utf-8-sig')

# ✅ 4. API 적용 (주소 컬럼 기준)
print("좌표 변환 중...")
info_list = []

for addr in df['주소']:
    info = get_addr_info(addr)
    info_list.append(info)
    time.sleep(0.2)  # ⭐ API 제한 방지 (중요)

# ✅ 5. 컬럼 추가
df['위도'], df['경도'], df['법정동'] = zip(*info_list)

# ✅ 6. 저장
df.to_csv('인천어린이집_법정동.csv', index=False, encoding='utf-8-sig')

print("완료!")
df.head()

좌표 변환 중...
완료!

,시도,시군구,어린이집명,어린이집유형구분,주소,위도,경도,법정동
0,인천광역시,중구,장미어린이집,국공립,인천광역시 중구 참외전로174번길 12-1,37.471945263384,126.634784259158,동인천동
1,인천광역시,중구,금산어린이집,국공립,인천광역시 중구 백운로351번길 3 (운북동),37.5058305883434,126.519962026481,영종동
2,인천광역시,중구,효성어린이집,사회복지법인,인천광역시 중구 백운로 34 (중산동),37.5010123199487,126.55262267154,영종동
3,인천광역시,중구,찬솔어린이집,국공립,"인천광역시 중구 축항대로86번길 47 3동 101호(항동7가, 라이프아파트)",37.4517673879313,126.60497770554,연안동
4,인천광역시,중구,비둘기어린이집,국공립,인천광역시 중구 자유공원서로29번길 3-19,37.4766609983658,126.619777159028,개항동

In [12]:
# ✅ 1. 카카오 REST API 키 넣기 (여기!!)
REST_API_KEY = "YOUR_KAKAO_API_KEY"

# ✅ 2. 주소 → (위도, 경도, 법정동) 변환 함수
def get_addr_info(address):
    url = 'https://dapi.kakao.com/v2/local/search/address.json'
    headers = {"Authorization": f"KakaoAK {REST_API_KEY}"}
    params = {'query': address}
    
    try:
        response = requests.get(url, headers=headers, params=params)
        if response.status_code == 200:
            result = response.json()
            if result['documents']:
                addr_data = result['documents'][0]['address']
                lat = addr_data['y']  # 위도
                lon = addr_data['x']  # 경도
                b_dong = addr_data['region_3depth_h_name']  # 법정동
                
                return lat, lon, b_dong
        return None, None, None
    except:
        return None, None, None

# ✅ 3. CSV 불러오기 (네 파일)
df = pd.read_csv('서울어린이집.csv', encoding='utf-8-sig')

# ✅ 4. API 적용 (주소 컬럼 기준)
print("좌표 변환 중...")
info_list = []

for addr in df['주소']:
    info = get_addr_info(addr)
    info_list.append(info)
    time.sleep(0.2)  # ⭐ API 제한 방지 (중요)

# ✅ 5. 컬럼 추가
df['위도'], df['경도'], df['법정동'] = zip(*info_list)

# ✅ 6. 저장
df.to_csv('서울어린이집_법정동.csv', index=False, encoding='utf-8-sig')

print("완료!")
df.head()

좌표 변환 중...
완료!

,시도,시군구,어린이집명,어린이집유형구분,주소,위도,경도,법정동
0,서울특별시,종로구,삼청어린이집,국공립,서울특별시 종로구 삼청로7길 26 (팔판동),37.5840321640655,126.980481002242,삼청동
1,서울특별시,종로구,창신어린이집,사회복지법인,서울특별시 종로구 창신5길 22 (창신동),37.5736477680085,127.012017293871,창신1동
2,서울특별시,종로구,아동회관어린이집,국공립,서울특별시 종로구 지봉로13길 14 아동회관어린이집,37.5789483137908,127.014467533898,창신3동
3,서울특별시,종로구,부암어린이집,국공립,서울특별시 종로구 세검정로6다길 10-7,37.601604649771,126.963099123923,부암동
4,서울특별시,종로구,낙산어린이집,국공립,서울특별시 종로구 창신길 210-11 낙산어린이집 (창신동),37.5795467508656,127.010182884217,창신2동

In [13]:
df = pd.read_csv('서울_유아인구.csv', encoding='cp949')
df

,행정동,학생수(계)_초,학급수(계)_초,학생수(계)_중,학급수(계)_중,총학생수,총학급수,학급당학생수,행정동_정제
0,가좌동,762,38,613,24,1375,62,22.177419,가좌동
1,갈매동,2420,102,1010,34,3430,136,25.220588,갈매동
2,갈산동,1695,69,1135,38,2830,107,26.448598,갈산동
3,감북동,84,8,0,0,84,8,10.500000,감북동
4,감일동,3684,156,1261,48,4945,204,24.240196,감일동
...,...,...,...,...,...,...,...,...,...
242,화전동,2142,96,825,37,2967,133,22.308271,화전동
243,화정1동,886,46,738,31,1624,77,21.090909,화정1동
244,화정2동,1612,71,1489,58,3101,129,24.038760,화정2동
245,효자동,2096,90,850,31,2946,121,24.347107,효자동
246,흥도동,1847,81,1175,44,3022,125,24.176000,흥도동

In [14]:
df = pd.read_csv('서울_유아인구.csv', encoding='cp949')
df

       시도명 시군구명   읍면동명  유아인구
0    서울특별시  종로구  청운효자동   250
1    서울특별시  종로구    사직동   189
2    서울특별시  종로구    삼청동    34
3    서울특별시  종로구    부암동   151
4    서울특별시  종로구    평창동   459
..     ...  ...    ...   ...
422  서울특별시  강동구  성내제2동   488
423  서울특별시  강동구  성내제3동   448
424  서울특별시  강동구     길동  1297
425  서울특별시  강동구  둔촌제1동  1986
426  서울특별시  강동구  둔촌제2동   949

[427 rows x 4 columns]

In [15]:
df['읍면동명'] = df['읍면동명'].str.replace(r'제+(?=\d)', '', regex=True)
df

       시도명 시군구명   읍면동명  유아인구
0    서울특별시  종로구  청운효자동   250
1    서울특별시  종로구    사직동   189
2    서울특별시  종로구    삼청동    34
3    서울특별시  종로구    부암동   151
4    서울특별시  종로구    평창동   459
..     ...  ...    ...   ...
422  서울특별시  강동구   성내2동   488
423  서울특별시  강동구   성내3동   448
424  서울특별시  강동구     길동  1297
425  서울특별시  강동구   둔촌1동  1986
426  서울특별시  강동구   둔촌2동   949

[427 rows x 4 columns]

In [50]:
df.to_csv('서울_유아인구.csv', index=False, encoding='utf-8-sig')

In [41]:
df = pd.read_csv('서울_유아인구.csv', encoding='cp949')
df

      시도명\t시군구명\t읍면동명\t유아인구
0    서울특별시\t종로구\t청운효자동\t250
1      서울특별시\t종로구\t사직동\t189
2       서울특별시\t종로구\t삼청동\t34
3      서울특별시\t종로구\t부암동\t151
4      서울특별시\t종로구\t평창동\t459
..                      ...
422   서울특별시\t강동구\t성내2동\t488
423   서울특별시\t강동구\t성내3동\t448
424    서울특별시\t강동구\t길동\t1297
425  서울특별시\t강동구\t둔촌1동\t1986
426   서울특별시\t강동구\t둔촌2동\t949

[427 rows x 1 columns]

In [42]:
df2 = pd.read_csv('최종-서울학급당학생수.csv', encoding='utf-8-sig')
df2

      행정동  학생수(계)_초  학급수(계)_초  학생수(계)_중  학급수(계)_중  총학생수  총학급수     학급당학생수
0    가락1동      1833        84       853        30  2686   114  23.561404
1    가락2동      1409        66       896        34  2305   100  23.050000
2    가락본동       693        42       736        30  1429    72  19.847222
3    가리봉동       267        19         0         0   267    19  14.052632
4     가산동       265        15         0         0   265    15  17.666667
..    ...       ...       ...       ...       ...   ...   ...        ...
384   회기동      1957        88       847        38  2804   126  22.253968
385   효창동       567        30         0         0   567    30  18.900000
386   후암동       566        34         0         0   566    34  16.647059
387  휘경2동       852        45       712        32  1564    77  20.311688
388   흑석동      1989        98       658        26  2647   124  21.346774

[389 rows x 8 columns]

In [43]:
len(set(df['읍면동명']) - set(df2['행정동']))

KeyError: '읍면동명'

In [45]:
df = pd.read_csv('서울어린이집_법정동행정동.csv', encoding='utf-8-sig')
df

,시도,시군구,어린이집명,어린이집유형구분,주소,위도,경도,법정동,행정동
0,서울특별시,종로구,삼청어린이집,국공립,서울특별시 종로구 삼청로7길 26 (팔판동),37.584032,126.980481,팔판동,삼청동
1,서울특별시,종로구,창신어린이집,사회복지법인,서울특별시 종로구 창신5길 22 (창신동),37.573648,127.012017,창신동,창신1동
2,서울특별시,종로구,아동회관어린이집,국공립,서울특별시 종로구 지봉로13길 14 아동회관어린이집,37.578948,127.014468,창신동,창신3동
3,서울특별시,종로구,부암어린이집,국공립,서울특별시 종로구 세검정로6다길 10-7,37.601605,126.963099,신영동,부암동
4,서울특별시,종로구,낙산어린이집,국공립,서울특별시 종로구 창신길 210-11 낙산어린이집 (창신동),37.579547,127.010183,창신동,창신2동
...,...,...,...,...,...,...,...,...,...
3980,서울특별시,강동구,구립그란츠리버키즈어린이집,국공립,서울특별시 강동구 천호대로 1050 101동 1~2층,37.536712,127.128325,성내동,성내2동
3981,서울특별시,강동구,구립둔촌1동어린이집,국공립,서울특별시 강동구 양재대로 1342 1층,37.525887,127.136436,둔촌동,둔촌1동
3982,서울특별시,강동구,구립온빛어린이집,국공립,서울특별시 강동구 아리수로 385 1층(고덕동),37.562759,127.170832,고덕동,고덕2동
3983,서울특별시,강동구,구립더샵강동센트럴시티어린이집,국공립,서울특별시 강동구 진황도로 14 102동,37.539524,127.128473,천호동,천호3동
3984,서울특별시,강동구,구립강동프레스티지원어린이집,국공립,서울특별시 강동구 올림픽로78길 37 104동,37.542953,127.126261,천호동,천호2동

In [ ]:
df_child = df.groupby('행정동').size().reset_index(name='보육시설수')
df_child

In [47]:
df2 = pd.read_csv('서울_유아인구.csv', encoding='cp949')
df2

      시도명\t시군구명\t읍면동명\t유아인구
0    서울특별시\t종로구\t청운효자동\t250
1      서울특별시\t종로구\t사직동\t189
2       서울특별시\t종로구\t삼청동\t34
3      서울특별시\t종로구\t부암동\t151
4      서울특별시\t종로구\t평창동\t459
..                      ...
422   서울특별시\t강동구\t성내2동\t488
423   서울특별시\t강동구\t성내3동\t448
424    서울특별시\t강동구\t길동\t1297
425  서울특별시\t강동구\t둔촌1동\t1986
426   서울특별시\t강동구\t둔촌2동\t949

[427 rows x 1 columns]

In [48]:
df2.rename(columns={'읍면동명': '행정동'}, inplace=True)
df2

      시도명\t시군구명\t읍면동명\t유아인구
0    서울특별시\t종로구\t청운효자동\t250
1      서울특별시\t종로구\t사직동\t189
2       서울특별시\t종로구\t삼청동\t34
3      서울특별시\t종로구\t부암동\t151
4      서울특별시\t종로구\t평창동\t459
..                      ...
422   서울특별시\t강동구\t성내2동\t488
423   서울특별시\t강동구\t성내3동\t448
424    서울특별시\t강동구\t길동\t1297
425  서울특별시\t강동구\t둔촌1동\t1986
426   서울특별시\t강동구\t둔촌2동\t949

[427 rows x 1 columns]

In [49]:
result = pd.merge(
    df2, df_child,
    on='행정동',
    how='outer')
result

KeyError: '행정동'

In [39]:
result[result.isnull().any(axis=1)]

       시도명  시군구명    행정동   유아인구  보육시설수
57   서울특별시   동작구  노량진2동   57.0    NaN
129  서울특별시   서초구   반포본동    4.0    NaN
337  서울특별시   송파구   잠실7동  259.0    NaN
406  서울특별시  서대문구    홍1동  691.0    NaN
407  서울특별시  서대문구    홍2동  359.0    NaN
408  서울특별시  서대문구    홍3동  522.0    NaN
411    NaN   NaN   홍제1동    NaN   10.0
412    NaN   NaN   홍제2동    NaN    4.0
413    NaN   NaN   홍제3동    NaN    9.0

In [51]:
df2 = pd.read_csv('서울_유아인구.csv', encoding='cp949')
df2

       시도명 시군구명   읍면동명  유아인구
0    서울특별시  종로구  청운효자동   250
1    서울특별시  종로구    사직동   189
2    서울특별시  종로구    삼청동    34
3    서울특별시  종로구    부암동   151
4    서울특별시  종로구    평창동   459
..     ...  ...    ...   ...
422  서울특별시  강동구  성내제2동   488
423  서울특별시  강동구  성내제3동   448
424  서울특별시  강동구     길동  1297
425  서울특별시  강동구  둔촌제1동  1986
426  서울특별시  강동구  둔촌제2동   949

[427 rows x 4 columns]

In [52]:
df2['읍면동명'] = df2['읍면동명'].str.replace(r'제+(?=\d)', '', regex=True)
df2

       시도명 시군구명   읍면동명  유아인구
0    서울특별시  종로구  청운효자동   250
1    서울특별시  종로구    사직동   189
2    서울특별시  종로구    삼청동    34
3    서울특별시  종로구    부암동   151
4    서울특별시  종로구    평창동   459
..     ...  ...    ...   ...
422  서울특별시  강동구   성내2동   488
423  서울특별시  강동구   성내3동   448
424  서울특별시  강동구     길동  1297
425  서울특별시  강동구   둔촌1동  1986
426  서울특별시  강동구   둔촌2동   949

[427 rows x 4 columns]

In [53]:
df2.to_csv('서울_유아인구.csv', index=False, encoding='utf-8-sig')

In [54]:
df = pd.read_csv('서울_유아인구.csv', encoding='cp949')
df

      시도명\t시군구명\t읍면동명\t유아인구
0    서울특별시\t종로구\t청운효자동\t250
1      서울특별시\t종로구\t사직동\t189
2       서울특별시\t종로구\t삼청동\t34
3      서울특별시\t종로구\t부암동\t151
4      서울특별시\t종로구\t평창동\t459
..                      ...
422   서울특별시\t강동구\t성내2동\t488
423   서울특별시\t강동구\t성내3동\t448
424    서울특별시\t강동구\t길동\t1297
425  서울특별시\t강동구\t둔촌1동\t1986
426   서울특별시\t강동구\t둔촌2동\t949

[427 rows x 1 columns]

In [55]:
df = pd.read_csv('어린이집정제.csv', encoding='cp949')
df

,시도,시군구,어린이집명,주소,행정동,0~5인구,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,인천광역시,중구,장미어린이집,인천광역시 중구 참외전로174번길 12-1,동인천동,50,2,40.000000,333.333333,2.188184,0.114185,0.009363,0.936317
1,인천광역시,중구,금산어린이집,인천광역시 중구 백운로351번길 3 (운북동),영종동,1241,17,13.698630,333.333333,2.188184,0.034760,0.002850,0.285028
2,인천광역시,중구,효성어린이집,인천광역시 중구 백운로 34 (중산동),영종동,1241,17,13.698630,333.333333,2.188184,0.034760,0.002850,0.285028
3,인천광역시,중구,비둘기어린이집,인천광역시 중구 자유공원서로29번길 3-19,개항동,52,1,19.230769,333.333333,2.188184,0.051466,0.004220,0.422018
4,인천광역시,중구,인천신광초등학교어린이집,인천광역시 중구 신흥동3가 인중로 63 인천신광초등학교어린이집,신흥동,396,15,37.878788,333.333333,2.188184,0.107779,0.008838,0.883791
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8861,서울특별시,강동구,아기랑놀이랑어린이집,"서울특별시 강동구 명일로 293 505-101(길동, 삼익파크아파트)",명일1동,1050,13,12.380952,333.333333,2.188184,0.030780,0.002524,0.252399
8862,서울특별시,강동구,구립명일사랑어린이집,서울특별시 강동구 상암로 224 9-106,명일1동,1050,13,12.380952,333.333333,2.188184,0.030780,0.002524,0.252399
8863,서울특별시,강동구,구립토리어린이집,"서울특별시 강동구 상일로 74 323-102(상일동, 고덕리엔파크아파트 3단지)",상일2동,637,14,21.978022,333.333333,2.188184,0.059762,0.004900,0.490047
8864,서울특별시,강동구,새아어린이집,"서울특별시 강동구 아리수로50길 50 119-203(고덕동, 래미안힐스테이트A)",고덕1동,671,8,11.922504,333.333333,2.188184,0.029396,0.002410,0.241047
8865,서울특별시,강동구,구립강동한별어린이집,서울특별시 강동구 천중로53길 19 1~4층,길동,1297,14,10.794140,333.333333,2.188184,0.025988,0.002131,0.213105

In [56]:
result = df.groupby('행정동').agg({
    '어린이집명': 'count',   
    '0~5인구': 'sum'      
}).reset_index()
result

      행정동  어린이집명  0~5인구
0    가락1동     14  21280
1    가락2동     14  12152
2    가락본동     11   7755
3    가리봉동      2    188
4     가산동      9   3276
..    ...    ...    ...
825   후암동      5   1460
826  휘경1동      6   3966
827  휘경2동     12   5292
828   흑석동     15  16530
829   흥도동     17  19091

[830 rows x 3 columns]

In [57]:
result['유아천명당보육시설수'] = (result['어린이집명'] / result['0~5인구']) * 1000

In [58]:
result

      행정동  어린이집명  0~5인구  유아천명당보육시설수
0    가락1동     14  21280    0.657895
1    가락2동     14  12152    1.152074
2    가락본동     11   7755    1.418440
3    가리봉동      2    188   10.638298
4     가산동      9   3276    2.747253
..    ...    ...    ...         ...
825   후암동      5   1460    3.424658
826  휘경1동      6   3966    1.512859
827  휘경2동     12   5292    2.267574
828   흑석동     15  16530    0.907441
829   흥도동     17  19091    0.890472

[830 rows x 4 columns]

In [61]:
df.groupby('행정동')['0~5인구'].nunique()

행정동
가락1동    1
가락2동    1
가락본동    1
가리봉동    1
가산동     1
       ..
후암동     1
휘경1동    1
휘경2동    1
흑석동     1
흥도동     1
Name: 0~5인구, Length: 830, dtype: int64

In [62]:
result = df.groupby('행정동').agg({
    '어린이집명': 'count',   
    '0~5인구': 'first'      
}).reset_index()
result

      행정동  어린이집명  0~5인구
0    가락1동     14   1520
1    가락2동     14    868
2    가락본동     11    705
3    가리봉동      2     94
4     가산동      9    364
..    ...    ...    ...
825   후암동      5    292
826  휘경1동      6    661
827  휘경2동     12    441
828   흑석동     15   1102
829   흥도동     17   1123

[830 rows x 3 columns]

In [65]:
result.rename(columns={'어린이집명':'어린이집수'},inplace=True)
result

      행정동  어린이집수  0~5인구
0    가락1동     14   1520
1    가락2동     14    868
2    가락본동     11    705
3    가리봉동      2     94
4     가산동      9    364
..    ...    ...    ...
825   후암동      5    292
826  휘경1동      6    661
827  휘경2동     12    441
828   흑석동     15   1102
829   흥도동     17   1123

[830 rows x 3 columns]

In [68]:
result['유아천명당보육시설수'] = (result['어린이집수'] / result['0~5인구']) * 1000

In [69]:
result

      행정동  어린이집수  0~5인구  유아천명당보육시설수
0    가락1동     14   1520    9.210526
1    가락2동     14    868   16.129032
2    가락본동     11    705   15.602837
3    가리봉동      2     94   21.276596
4     가산동      9    364   24.725275
..    ...    ...    ...         ...
825   후암동      5    292   17.123288
826  휘경1동      6    661    9.077156
827  휘경2동     12    441   27.210884
828   흑석동     15   1102   13.611615
829   흥도동     17   1123   15.138023

[830 rows x 4 columns]

In [70]:
result.to_csv('천명당보육시설수.csv', index=False, encoding='utf-8-sig')

In [72]:
df = pd.read_csv('문화시설.csv', encoding='utf-8-sig')
df

,Unnamed: 0,시도,시군구,이름,주소,법정동,행정동
0,0,서울,서초구,국립중앙도서관,서울특별시 서초구 반포대로 201 (반포동),반포동,반포4동
1,1,서울,영등포구,국회도서관,서울특별시 영등포구 의사당대로 1 (여의도동),여의도동,여의동
2,2,서울,서초구,국립장애인도서관,서울특별시 서초구 반포대로 201 (반포동),반포동,반포4동
3,3,경기,고양시,법원도서관,경기도 고양시 일산동구 호수로 550 (장항동),장항동,장항2동
4,4,서울,강남구,서울특별시교육청강남도서관,서울특별시 강남구 선릉로116길 45 (삼성동) 서울특별시교육청강남도서관,삼성동,삼성2동
...,...,...,...,...,...,...,...
864,895,인천광역시,부평구,부평구문화재단,인천광역시 부평구 아트센터로 166,십정동,부평3동
865,896,인천광역시,연수구,연수문화재단,인천광역시 연수구 비류대로 299(청학동) 청학아트센터 2층,청학동,청학동
866,897,인천광역시,서구,인천서구문화재단,인천광역시 서구 서달로 190,가정동,가정3동
867,898,인천광역시,중구,인천중구문화재단,인천광역시 중구 신포로27번길 83-1,중앙동1가,신포동
868,899,인천광역시,남동구,남동문화재단,"인천광역시 남동구 아암대로1437번길 32(논현동, 소래아트홀)",논현동,논현고잔동

In [5]:
df = pd.read_csv('서울_유아인구.csv', encoding='cp949')
df

       시도명 시군구명   읍면동명  유아인구
0    서울특별시  종로구  청운효자동   250
1    서울특별시  종로구    사직동   189
2    서울특별시  종로구    삼청동    34
3    서울특별시  종로구    부암동   151
4    서울특별시  종로구    평창동   459
..     ...  ...    ...   ...
422  서울특별시  강동구  성내제2동   488
423  서울특별시  강동구  성내제3동   448
424  서울특별시  강동구     길동  1297
425  서울특별시  강동구  둔촌제1동  1986
426  서울특별시  강동구  둔촌제2동   949

[427 rows x 4 columns]

In [7]:
df['읍면동명'] = df['읍면동명'].str.replace(r'제+(?=\d)', '', regex=True)
df

       시도명 시군구명   읍면동명  유아인구
0    서울특별시  종로구  청운효자동   250
1    서울특별시  종로구    사직동   189
2    서울특별시  종로구    삼청동    34
3    서울특별시  종로구    부암동   151
4    서울특별시  종로구    평창동   459
..     ...  ...    ...   ...
422  서울특별시  강동구   성내2동   488
423  서울특별시  강동구   성내3동   448
424  서울특별시  강동구     길동  1297
425  서울특별시  강동구   둔촌1동  1986
426  서울특별시  강동구   둔촌2동   949

[427 rows x 4 columns]

In [11]:
df.to_csv('서울_유아인구.csv', index=False, encoding='cp949')

In [12]:
df = pd.read_csv('서울_유아인구.csv', encoding='cp949')
df

       시도명 시군구명   읍면동명  유아인구
0    서울특별시  종로구  청운효자동   250
1    서울특별시  종로구    사직동   189
2    서울특별시  종로구    삼청동    34
3    서울특별시  종로구    부암동   151
4    서울특별시  종로구    평창동   459
..     ...  ...    ...   ...
422  서울특별시  강동구   성내2동   488
423  서울특별시  강동구   성내3동   448
424  서울특별시  강동구     길동  1297
425  서울특별시  강동구   둔촌1동  1986
426  서울특별시  강동구   둔촌2동   949

[427 rows x 4 columns]

In [13]:
df.to_csv('서울_유아인구.csv', index=False, encoding='cp949')

In [14]:
df = pd.read_csv('최종-유아인구통합.csv', encoding='cp949')
df

       시도명 시군구명      읍면동명  유아인구
0    서울특별시  종로구     청운효자동   250
1    서울특별시  종로구       사직동   189
2    서울특별시  종로구       삼청동    34
3    서울특별시  종로구       부암동   151
4    서울특별시  종로구       평창동   459
..     ...  ...       ...   ...
746  인천광역시  옹진군       덕적면    12
747  인천광역시  옹진군       영흥면    98
748  인천광역시  옹진군       자월면    10
749  인천광역시  옹진군  자월면이작출장소     2
750  인천광역시  옹진군       연평면    35

[751 rows x 4 columns]

In [15]:
df = pd.read_csv('서울_유아인구.csv', encoding='cp949')
df

       시도명 시군구명   읍면동명  유아인구
0    서울특별시  종로구  청운효자동   250
1    서울특별시  종로구    사직동   189
2    서울특별시  종로구    삼청동    34
3    서울특별시  종로구    부암동   151
4    서울특별시  종로구    평창동   459
..     ...  ...    ...   ...
422  서울특별시  강동구   성내2동   488
423  서울특별시  강동구   성내3동   448
424  서울특별시  강동구     길동  1297
425  서울특별시  강동구   둔촌1동  1986
426  서울특별시  강동구   둔촌2동   949

[427 rows x 4 columns]

In [19]:
df2 = pd.read_csv('경기유아인구.csv', encoding='cp949')
df2

     시도명     시군구명  읍면동명  유아인구
0    경기도  성남시 수정구  신흥1동   123
1    경기도  성남시 수정구  신흥2동  1916
2    경기도  성남시 수정구  신흥3동   142
3    경기도  성남시 수정구  태평1동   151
4    경기도  성남시 수정구  태평2동   204
..   ...      ...   ...   ...
269  경기도      김포시   풍무동  2319
270  경기도      김포시   장기동  1599
271  경기도      김포시   구래동  2152
272  경기도      김포시   마산동  1923
273  경기도      김포시   운양동  2071

[274 rows x 4 columns]

In [20]:
df3 = pd.read_csv('인천유아인구.csv', encoding='cp949')
df3

       시도명 시군구명      읍면동명  유아인구
0    인천광역시   중구       연안동    63
1    인천광역시   중구       신포동    57
2    인천광역시   중구       신흥동   396
3    인천광역시   중구       도원동    24
4    인천광역시   중구       율목동    27
..     ...  ...       ...   ...
157  인천광역시  옹진군       덕적면    12
158  인천광역시  옹진군       영흥면    98
159  인천광역시  옹진군       자월면    10
160  인천광역시  옹진군  자월면이작출장소     2
161  인천광역시  옹진군       연평면    35

[162 rows x 4 columns]

In [21]:
df_all = pd.concat([df, df2, df3], ignore_index=True)
df_all

       시도명 시군구명      읍면동명  유아인구
0    서울특별시  종로구     청운효자동   250
1    서울특별시  종로구       사직동   189
2    서울특별시  종로구       삼청동    34
3    서울특별시  종로구       부암동   151
4    서울특별시  종로구       평창동   459
..     ...  ...       ...   ...
858  인천광역시  옹진군       덕적면    12
859  인천광역시  옹진군       영흥면    98
860  인천광역시  옹진군       자월면    10
861  인천광역시  옹진군  자월면이작출장소     2
862  인천광역시  옹진군       연평면    35

[863 rows x 4 columns]

In [23]:
df_all.to_csv('유아인구통합.csv', index=False, encoding='utf-8-sig')

In [24]:
df = pd.read_csv('유아인구통합.csv')
df

       시도명 시군구명      읍면동명  유아인구
0    서울특별시  종로구     청운효자동   250
1    서울특별시  종로구       사직동   189
2    서울특별시  종로구       삼청동    34
3    서울특별시  종로구       부암동   151
4    서울특별시  종로구       평창동   459
..     ...  ...       ...   ...
858  인천광역시  옹진군       덕적면    12
859  인천광역시  옹진군       영흥면    98
860  인천광역시  옹진군       자월면    10
861  인천광역시  옹진군  자월면이작출장소     2
862  인천광역시  옹진군       연평면    35

[863 rows x 4 columns]

In [25]:
df2 = pd.read_csv('천명당보육시설수.csv')
df2

      행정동  어린이집수  0~5인구  유아천명당보육시설수
0    가락1동     14   1520    9.210526
1    가락2동     14    868   16.129032
2    가락본동     11    705   15.602837
3    가리봉동      2     94   21.276596
4     가산동      9    364   24.725275
..    ...    ...    ...         ...
825   후암동      5    292   17.123288
826  휘경1동      6    661    9.077156
827  휘경2동     12    441   27.210884
828   흑석동     15   1102   13.611615
829   흥도동     17   1123   15.138023

[830 rows x 4 columns]

In [27]:
len(set(df['읍면동명']) - set(df2['행정동']))

21

In [28]:
unmatched = df[~df['읍면동명'].isin(df2['행정동'])]
unmatched

       시도명  시군구명      읍면동명  유아인구
306  서울특별시   동작구     노량진2동    57
346  서울특별시   서초구      반포본동     4
407  서울특별시   송파구      잠실7동   259
563    경기도   광명시       학온동    18
619    경기도  남양주시  화도읍동부출장소   450
620    경기도  남양주시  화도읍남부출장소  1053
640    경기도   하남시       감북동    85
643    경기도   하남시       춘궁동    10
705  인천광역시    중구       율목동    27
711  인천광역시    중구       용유동    15
843  인천광역시   강화군       화도면    71
844  인천광역시   강화군       양도면    64
845  인천광역시   강화군       내가면    61
847  인천광역시   강화군       양사면    38
848  인천광역시   강화군       송해면    60
849  인천광역시   강화군       교동면    26
851  인천광역시   강화군       서도면     4
852  인천광역시   강화군  서도면볼음출장소     2
854  인천광역시   옹진군  북도면장봉출장소     3
857  인천광역시   옹진군  대청면소청출장소     2
861  인천광역시   옹진군  자월면이작출장소     2

In [29]:
sorted(set(df['읍면동명']) - set(df2['행정동']))

['감북동',
 '교동면',
 '내가면',
 '노량진2동',
 '대청면소청출장소',
 '반포본동',
 '북도면장봉출장소',
 '서도면',
 '서도면볼음출장소',
 '송해면',
 '양도면',
 '양사면',
 '용유동',
 '율목동',
 '자월면이작출장소',
 '잠실7동',
 '춘궁동',
 '학온동',
 '화도면',
 '화도읍남부출장소',
 '화도읍동부출장소']

In [33]:
df = pd.read_csv('어린이집정제.csv', encoding='cp949')
df

,시도,시군구,어린이집명,주소,행정동,0~5인구,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,인천광역시,중구,장미어린이집,인천광역시 중구 참외전로174번길 12-1,동인천동,50,2,40.000000,333.333333,2.188184,0.114185,0.009363,0.936317
1,인천광역시,중구,금산어린이집,인천광역시 중구 백운로351번길 3 (운북동),영종동,1241,17,13.698630,333.333333,2.188184,0.034760,0.002850,0.285028
2,인천광역시,중구,효성어린이집,인천광역시 중구 백운로 34 (중산동),영종동,1241,17,13.698630,333.333333,2.188184,0.034760,0.002850,0.285028
3,인천광역시,중구,비둘기어린이집,인천광역시 중구 자유공원서로29번길 3-19,개항동,52,1,19.230769,333.333333,2.188184,0.051466,0.004220,0.422018
4,인천광역시,중구,인천신광초등학교어린이집,인천광역시 중구 신흥동3가 인중로 63 인천신광초등학교어린이집,신흥동,396,15,37.878788,333.333333,2.188184,0.107779,0.008838,0.883791
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8861,서울특별시,강동구,아기랑놀이랑어린이집,"서울특별시 강동구 명일로 293 505-101(길동, 삼익파크아파트)",명일1동,1050,13,12.380952,333.333333,2.188184,0.030780,0.002524,0.252399
8862,서울특별시,강동구,구립명일사랑어린이집,서울특별시 강동구 상암로 224 9-106,명일1동,1050,13,12.380952,333.333333,2.188184,0.030780,0.002524,0.252399
8863,서울특별시,강동구,구립토리어린이집,"서울특별시 강동구 상일로 74 323-102(상일동, 고덕리엔파크아파트 3단지)",상일2동,637,14,21.978022,333.333333,2.188184,0.059762,0.004900,0.490047
8864,서울특별시,강동구,새아어린이집,"서울특별시 강동구 아리수로50길 50 119-203(고덕동, 래미안힐스테이트A)",고덕1동,671,8,11.922504,333.333333,2.188184,0.029396,0.002410,0.241047
8865,서울특별시,강동구,구립강동한별어린이집,서울특별시 강동구 천중로53길 19 1~4층,길동,1297,14,10.794140,333.333333,2.188184,0.025988,0.002131,0.213105

In [34]:
df = pd.read_csv('어린이집정제.csv', usecols=[1,2,4,5], encoding='cp949')
df

      시군구         어린이집명   행정동  0~5인구
0      중구        장미어린이집  동인천동     50
1      중구        금산어린이집   영종동   1241
2      중구        효성어린이집   영종동   1241
3      중구       비둘기어린이집   개항동     52
4      중구  인천신광초등학교어린이집   신흥동    396
...   ...           ...   ...    ...
8861  강동구    아기랑놀이랑어린이집  명일1동   1050
8862  강동구    구립명일사랑어린이집  명일1동   1050
8863  강동구      구립토리어린이집  상일2동    637
8864  강동구        새아어린이집  고덕1동    671
8865  강동구    구립강동한별어린이집    길동   1297

[8866 rows x 4 columns]

In [36]:
result = (
    df.groupby(['시군구', '행정동'], as_index=False).agg(어린이집수=('어린이집명', 'count'),유아인구수=('0~5인구', 'first')))
result

     시군구   행정동  어린이집수  유아인구수
0    강남구  개포1동      4   1031
1    강남구  개포2동      8   2024
2    강남구  개포3동      6    486
3    강남구  개포4동      9    817
4    강남구  논현1동      2    289
..   ...   ...    ...    ...
926  하남시  신장1동      3    134
927  하남시  신장2동     30   1652
928  하남시   위례동     21   2642
929  하남시   천현동      4     81
930  하남시   초이동      2     66

[931 rows x 4 columns]

In [37]:
dup_check = (
    df.groupby('행정동')['시군구']
      .nunique()
      .reset_index(name='시군구개수')
      .sort_values('시군구개수', ascending=False)
)

dup_check[dup_check['시군구개수'] > 1]

      행정동  시군구개수
707   중앙동      4
491   신흥동      3
602   위례동      3
485   신촌동      3
613   이동읍      2
..    ...    ...
49   고강1동      2
50   고강본동      2
194   마북동      2
278   부림동      2
273   보정동      2

[96 rows x 2 columns]