In [3]:
# %matplotlib notebook

import pandas as pd
import matplotlib.pyplot as plt
from matplotlib import font_manager, rc

# 한글깨짐처리
font_loc = "c:/Windows/Fonts/malgun.ttf"
font_name=font_manager.FontProperties(fname=font_loc).get_name()
rc('font', family=font_name)

In [5]:
df = pd.read_csv('최종-경기학급당학생수.csv', encoding='utf-8-sig')
df

      행정동  학생수(계)_초  학급수(계)_초  학생수(계)_중  학급수(계)_중  총학생수  총학급수     학급당학생수
0     가좌동       762        38       613        24  1375    62  22.177419
1     갈매동      2420       102      1010        34  3430   136  25.220588
2     갈산동      1695        69      1135        38  2830   107  26.448598
3     감북동        84         8         0         0    84     8  10.500000
4     감일동      3684       156      1261        48  4945   204  24.240196
..    ...       ...       ...       ...       ...   ...   ...        ...
242   화전동      2142        96       825        37  2967   133  22.308271
243  화정1동       886        46       738        31  1624    77  21.090909
244  화정2동      1612        71      1489        58  3101   129  24.038760
245   효자동      2096        90       850        31  2946   121  24.347107
246   흥도동      1847        81      1175        44  3022   125  24.176000

[247 rows x 8 columns]

In [7]:
df2 = pd.read_csv('경기유아인구.csv', encoding='cp949')
df2

     시도명     시군구명  읍면동명  유아인구
0    경기도  성남시 수정구  신흥1동   123
1    경기도  성남시 수정구  신흥2동  1916
2    경기도  성남시 수정구  신흥3동   142
3    경기도  성남시 수정구  태평1동   151
4    경기도  성남시 수정구  태평2동   204
..   ...      ...   ...   ...
269  경기도      김포시   풍무동  2319
270  경기도      김포시   장기동  1599
271  경기도      김포시   구래동  2152
272  경기도      김포시   마산동  1923
273  경기도      김포시   운양동  2071

[274 rows x 4 columns]

In [8]:
set(df2['읍면동명']) - set(df['행정동'])

{'광명1동',
 '광명2동',
 '광명4동',
 '박달동',
 '상대원2동',
 '수진1동',
 '수택2동',
 '시흥동',
 '신장1동',
 '신흥1동',
 '신흥3동',
 '심곡1동',
 '안양4동',
 '양정동',
 '원미2동',
 '철산4동',
 '초이동',
 '춘궁동',
 '춘의동',
 '태평2동',
 '호계1동',
 '화도읍남부출장소',
 '화도읍동부출장소'}

In [9]:
df = pd.read_csv('최종-서울학급당학생수.csv', encoding='utf-8-sig')
df

      행정동  학생수(계)_초  학급수(계)_초  학생수(계)_중  학급수(계)_중  총학생수  총학급수     학급당학생수
0    가락1동      1833        84       853        30  2686   114  23.561404
1    가락2동      1409        66       896        34  2305   100  23.050000
2    가락본동       693        42       736        30  1429    72  19.847222
3    가리봉동       267        19         0         0   267    19  14.052632
4     가산동       265        15         0         0   265    15  17.666667
..    ...       ...       ...       ...       ...   ...   ...        ...
384   회기동      1957        88       847        38  2804   126  22.253968
385   효창동       567        30         0         0   567    30  18.900000
386   후암동       566        34         0         0   566    34  16.647059
387  휘경2동       852        45       712        32  1564    77  20.311688
388   흑석동      1989        98       658        26  2647   124  21.346774

[389 rows x 8 columns]

In [11]:
df2 = pd.read_csv('서울_유아인구.csv', encoding='cp949')
df2

       시도명 시군구명   읍면동명  유아인구
0    서울특별시  종로구  청운효자동   250
1    서울특별시  종로구    사직동   189
2    서울특별시  종로구    삼청동    34
3    서울특별시  종로구    부암동   151
4    서울특별시  종로구    평창동   459
..     ...  ...    ...   ...
422  서울특별시  강동구   성내2동   488
423  서울특별시  강동구   성내3동   448
424  서울특별시  강동구     길동  1297
425  서울특별시  강동구   둔촌1동  1986
426  서울특별시  강동구   둔촌2동   949

[427 rows x 4 columns]

In [14]:
len(set(df2['읍면동명']) - set(df['행정동']))

37

In [15]:
missing = set(df2['읍면동명']) - set(df['행정동'])

In [16]:
missing_df = pd.DataFrame({'행정동': list(missing)})
for col in df.columns:
    if col != '행정동':
        missing_df[col] = 0
df_final = pd.concat([df, missing_df], ignore_index=True)
df_final

        행정동  학생수(계)_초  학급수(계)_초  학생수(계)_중  학급수(계)_중  총학생수  총학급수     학급당학생수
0      가락1동      1833        84       853        30  2686   114  23.561404
1      가락2동      1409        66       896        34  2305   100  23.050000
2      가락본동       693        42       736        30  1429    72  19.847222
3      가리봉동       267        19         0         0   267    19  14.052632
4       가산동       265        15         0         0   265    15  17.666667
..      ...       ...       ...       ...       ...   ...   ...        ...
421     신림동         0         0         0         0     0     0   0.000000
422    창신2동         0         0         0         0     0     0   0.000000
423   북가좌2동         0         0         0         0     0     0   0.000000
424  성수1가2동         0         0         0         0     0     0   0.000000
425    중화2동         0         0         0         0     0     0   0.000000

[426 rows x 8 columns]

In [19]:
df_final.to_csv('최종2_서울학급당학생수.csv', index=False, encoding='utf-8-sig')

In [21]:
df2=pd.read_csv('최종2_서울학급당학생수.csv', encoding='utf-8-sig')
df2

        행정동  학생수(계)_초  학급수(계)_초  학생수(계)_중  학급수(계)_중  총학생수  총학급수     학급당학생수
0      가락1동      1833        84       853        30  2686   114  23.561404
1      가락2동      1409        66       896        34  2305   100  23.050000
2      가락본동       693        42       736        30  1429    72  19.847222
3      가리봉동       267        19         0         0   267    19  14.052632
4       가산동       265        15         0         0   265    15  17.666667
..      ...       ...       ...       ...       ...   ...   ...        ...
421     신림동         0         0         0         0     0     0   0.000000
422    창신2동         0         0         0         0     0     0   0.000000
423   북가좌2동         0         0         0         0     0     0   0.000000
424  성수1가2동         0         0         0         0     0     0   0.000000
425    중화2동         0         0         0         0     0     0   0.000000

[426 rows x 8 columns]

In [28]:
df2 = pd.read_csv('서울_유아인구.csv', encoding='cp949')
df2

       시도명 시군구명   읍면동명  유아인구
0    서울특별시  종로구  청운효자동   250
1    서울특별시  종로구    사직동   189
2    서울특별시  종로구    삼청동    34
3    서울특별시  종로구    부암동   151
4    서울특별시  종로구    평창동   459
..     ...  ...    ...   ...
422  서울특별시  강동구   성내2동   488
423  서울특별시  강동구   성내3동   448
424  서울특별시  강동구     길동  1297
425  서울특별시  강동구   둔촌1동  1986
426  서울특별시  강동구   둔촌2동   949

[427 rows x 4 columns]

In [29]:
set(df2['행정동']) - set(df['읍면동명'])

KeyError: '행정동'

In [30]:
df = pd.read_csv('최종-서울학급당학생수.csv', encoding='cp949')
df

,시군구,행정동,학생수(계)_초,학급수(계)_초,학생수(계)_중,학급수(계)_중,총학생수,총학급수,학급당학생수
0,NaN,가락1동,1833,84,853,30,2686,114,23.561404
1,NaN,가락2동,1409,66,896,34,2305,100,23.050000
2,NaN,가락본동,693,42,736,30,1429,72,19.847222
3,NaN,가리봉동,267,19,0,0,267,19,14.052632
4,NaN,가산동,265,15,0,0,265,15,17.666667
...,...,...,...,...,...,...,...,...,...
422,NaN,신림동,0,0,0,0,0,0,0.000000
423,NaN,창신2동,0,0,0,0,0,0,0.000000
424,NaN,북가좌2동,0,0,0,0,0,0,0.000000
425,NaN,성수1가2동,0,0,0,0,0,0,0.000000
426,NaN,중화2동,0,0,0,0,0,0,0.000000

In [31]:
df = df.merge(
    df2[['시군구명', '읍면동명']],
    left_on='행정동',
    right_on='읍면동명',
    how='left'
)

df['시군구'] = df['시군구명']
df = df.drop(columns=['시군구명', '읍면동명'])
df

,시군구,행정동,학생수(계)_초,학급수(계)_초,학생수(계)_중,학급수(계)_중,총학생수,총학급수,학급당학생수
0,송파구,가락1동,1833,84,853,30,2686,114,23.561404
1,송파구,가락2동,1409,66,896,34,2305,100,23.050000
2,송파구,가락본동,693,42,736,30,1429,72,19.847222
3,구로구,가리봉동,267,19,0,0,267,19,14.052632
4,금천구,가산동,265,15,0,0,265,15,17.666667
...,...,...,...,...,...,...,...,...,...
424,관악구,신림동,0,0,0,0,0,0,0.000000
425,종로구,창신2동,0,0,0,0,0,0,0.000000
426,서대문구,북가좌2동,0,0,0,0,0,0,0.000000
427,성동구,성수1가2동,0,0,0,0,0,0,0.000000
428,중랑구,중화2동,0,0,0,0,0,0,0.000000

In [32]:
df.to_csv('최종2_서울학급당학생수.csv', index=False, encoding='utf-8-sig')

In [34]:
df['행정동'] = df['행정동'].str.replace(r'제+(?=\d)', '', regex=True)
df

,시군구,행정동,학생수(계)_초,학급수(계)_초,학생수(계)_중,학급수(계)_중,총학생수,총학급수,학급당학생수
0,송파구,가락1동,1833,84,853,30,2686,114,23.561404
1,송파구,가락2동,1409,66,896,34,2305,100,23.050000
2,송파구,가락본동,693,42,736,30,1429,72,19.847222
3,구로구,가리봉동,267,19,0,0,267,19,14.052632
4,금천구,가산동,265,15,0,0,265,15,17.666667
...,...,...,...,...,...,...,...,...,...
424,관악구,신림동,0,0,0,0,0,0,0.000000
425,종로구,창신2동,0,0,0,0,0,0,0.000000
426,서대문구,북가좌2동,0,0,0,0,0,0,0.000000
427,성동구,성수1가2동,0,0,0,0,0,0,0.000000
428,중랑구,중화2동,0,0,0,0,0,0,0.000000

In [35]:
df.to_csv('최종2_서울학급당학생수.csv', index=False, encoding='utf-8-sig')

In [37]:
df = pd.read_csv('최종-인천학급당학생수.csv', encoding='utf-8-sig')
df

      행정동  학생수(계)_초  학급수(계)_초  학생수(계)_중  학급수(계)_중  총학생수  총학급수     학급당학생수
0    가정1동      1558        66       910        30  2468    96  25.708333
1    가정2동      1216        51         0         0  1216    51  23.843137
2    가정3동       209        13         0         0   209    13  16.076923
3    가좌1동       298        20         0         0   298    20  14.900000
4    가좌2동       582        33         0         0   582    33  17.636364
..    ...       ...       ...       ...       ...   ...   ...        ...
136  학익2동       789        42       782        27  1571    69  22.768116
137   화도면        41         7        37         4    78    11   7.090909
138  화수2동       610        33       354        18   964    51  18.901961
139  효성1동      2142       109       895        38  3037   147  20.659864
140  효성2동       341        19       412        16   753    35  21.514286

[141 rows x 8 columns]

In [39]:
df2 = pd.read_csv('인천유아인구.csv', encoding='cp949')
df2

       시도명 시군구명      읍면동명  유아인구
0    인천광역시   중구       연안동    63
1    인천광역시   중구       신포동    57
2    인천광역시   중구       신흥동   396
3    인천광역시   중구       도원동    24
4    인천광역시   중구       율목동    27
..     ...  ...       ...   ...
157  인천광역시  옹진군       덕적면    12
158  인천광역시  옹진군       영흥면    98
159  인천광역시  옹진군       자월면    10
160  인천광역시  옹진군  자월면이작출장소     2
161  인천광역시  옹진군       연평면    35

[162 rows x 4 columns]

In [40]:
len(set(df2['읍면동명']) - set(df['행정동']))

21

In [41]:
df = df.merge(
    df2[['시군구명', '읍면동명']],
    left_on='행정동',
    right_on='읍면동명',
    how='left'
)

df['시군구'] = df['시군구명']
df = df.drop(columns=['시군구명', '읍면동명'])
df

      행정동  학생수(계)_초  학급수(계)_초  학생수(계)_중  학급수(계)_중  총학생수  총학급수     학급당학생수   시군구
0    가정1동      1558        66       910        30  2468    96  25.708333    서구
1    가정2동      1216        51         0         0  1216    51  23.843137    서구
2    가정3동       209        13         0         0   209    13  16.076923    서구
3    가좌1동       298        20         0         0   298    20  14.900000    서구
4    가좌2동       582        33         0         0   582    33  17.636364    서구
..    ...       ...       ...       ...       ...   ...   ...        ...   ...
136  학익2동       789        42       782        27  1571    69  22.768116  미추홀구
137   화도면        41         7        37         4    78    11   7.090909   강화군
138  화수2동       610        33       354        18   964    51  18.901961    동구
139  효성1동      2142       109       895        38  3037   147  20.659864   계양구
140  효성2동       341        19       412        16   753    35  21.514286   계양구

[141 rows x 9 columns]

In [42]:
missing = set(df2['읍면동명']) - set(df['행정동'])
missing_df = pd.DataFrame({'행정동': list(missing)})
for col in df.columns:
    if col != '행정동':
        missing_df[col] = 0
df_final = pd.concat([df, missing_df], ignore_index=True)
df_final

,행정동,학생수(계)_초,학급수(계)_초,학생수(계)_중,학급수(계)_중,총학생수,총학급수,학급당학생수,시군구
0,가정1동,1558,66,910,30,2468,96,25.708333,서구
1,가정2동,1216,51,0,0,1216,51,23.843137,서구
2,가정3동,209,13,0,0,209,13,16.076923,서구
3,가좌1동,298,20,0,0,298,20,14.900000,서구
4,가좌2동,582,33,0,0,582,33,17.636364,서구
...,...,...,...,...,...,...,...,...,...
157,계양3동,0,0,0,0,0,0,0.000000,0
158,대청면소청출장소,0,0,0,0,0,0,0.000000,0
159,개항동,0,0,0,0,0,0,0.000000,0
160,용현2동,0,0,0,0,0,0,0.000000,0
161,만수5동,0,0,0,0,0,0,0.000000,0

In [44]:
df_final = df_final.merge(
    df2[['시군구명', '읍면동명']],
    left_on='행정동',
    right_on='읍면동명',
    how='left'
)

df_final['시군구'] = df2['시군구명']
df_final = df_final.drop(columns=['시군구명', '읍면동명'])
df_final

KeyError: "['시군구명', '읍면동명'] not found in axis"

In [45]:
df

      행정동  학생수(계)_초  학급수(계)_초  학생수(계)_중  학급수(계)_중  총학생수  총학급수     학급당학생수   시군구
0    가정1동      1558        66       910        30  2468    96  25.708333    서구
1    가정2동      1216        51         0         0  1216    51  23.843137    서구
2    가정3동       209        13         0         0   209    13  16.076923    서구
3    가좌1동       298        20         0         0   298    20  14.900000    서구
4    가좌2동       582        33         0         0   582    33  17.636364    서구
..    ...       ...       ...       ...       ...   ...   ...        ...   ...
136  학익2동       789        42       782        27  1571    69  22.768116  미추홀구
137   화도면        41         7        37         4    78    11   7.090909   강화군
138  화수2동       610        33       354        18   964    51  18.901961    동구
139  효성1동      2142       109       895        38  3037   147  20.659864   계양구
140  효성2동       341        19       412        16   753    35  21.514286   계양구

[141 rows x 9 columns]

In [46]:
df2

       시도명 시군구명      읍면동명  유아인구
0    인천광역시   중구       연안동    63
1    인천광역시   중구       신포동    57
2    인천광역시   중구       신흥동   396
3    인천광역시   중구       도원동    24
4    인천광역시   중구       율목동    27
..     ...  ...       ...   ...
157  인천광역시  옹진군       덕적면    12
158  인천광역시  옹진군       영흥면    98
159  인천광역시  옹진군       자월면    10
160  인천광역시  옹진군  자월면이작출장소     2
161  인천광역시  옹진군       연평면    35

[162 rows x 4 columns]

In [47]:
df = df.merge(
    df2[['시군구명', '읍면동명']],
    left_on='행정동',
    right_on='읍면동명',
    how='left'
)

df['시군구'] = df['시군구명']
df.drop(columns=['시군구명', '읍면동명'], inplace=True)

In [48]:
df

      행정동  학생수(계)_초  학급수(계)_초  학생수(계)_중  학급수(계)_중  총학생수  총학급수     학급당학생수   시군구
0    가정1동      1558        66       910        30  2468    96  25.708333    서구
1    가정2동      1216        51         0         0  1216    51  23.843137    서구
2    가정3동       209        13         0         0   209    13  16.076923    서구
3    가좌1동       298        20         0         0   298    20  14.900000    서구
4    가좌2동       582        33         0         0   582    33  17.636364    서구
..    ...       ...       ...       ...       ...   ...   ...        ...   ...
136  학익2동       789        42       782        27  1571    69  22.768116  미추홀구
137   화도면        41         7        37         4    78    11   7.090909   강화군
138  화수2동       610        33       354        18   964    51  18.901961    동구
139  효성1동      2142       109       895        38  3037   147  20.659864   계양구
140  효성2동       341        19       412        16   753    35  21.514286   계양구

[141 rows x 9 columns]

In [49]:
full = df2[['시군구명', '읍면동명']].drop_duplicates()

df = full.merge(
    df,
    left_on='읍면동명',
    right_on='행정동',
    how='left'
)

In [50]:
for col in df.columns:
    if col not in ['시군구명', '읍면동명', '행정동']:
        df[col] = df[col].fillna(0)

In [51]:
df['행정동'] = df['읍면동명']
df['시군구'] = df['시군구명']

df.drop(columns=['읍면동명', '시군구명'], inplace=True)
df

,행정동,학생수(계)_초,학급수(계)_초,학생수(계)_중,학급수(계)_중,총학생수,총학급수,학급당학생수,시군구
0,연안동,104.0,10.0,0.0,0.0,104.0,10.0,10.400000,중구
1,신포동,811.0,39.0,517.0,26.0,1328.0,65.0,20.430769,중구
2,신흥동,985.0,50.0,823.0,38.0,1808.0,88.0,20.545455,중구
3,도원동,0.0,0.0,311.0,18.0,311.0,18.0,17.277778,중구
4,율목동,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,중구
...,...,...,...,...,...,...,...,...,...
157,덕적면,17.0,5.0,10.0,4.0,27.0,9.0,3.000000,옹진군
158,영흥면,147.0,11.0,118.0,6.0,265.0,17.0,15.588235,옹진군
159,자월면,8.0,4.0,0.0,0.0,8.0,4.0,2.000000,옹진군
160,자월면이작출장소,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,옹진군
161,연평면,26.0,6.0,4.0,3.0,30.0,9.0,3.333333,옹진군

In [52]:
df_final

,행정동,학생수(계)_초,학급수(계)_초,학생수(계)_중,학급수(계)_중,총학생수,총학급수,학급당학생수,시군구,시군구명_x,읍면동명_x,시군구명_y,읍면동명_y
0,가정1동,1558,66,910,30,2468,96,25.708333,중구,서구,가정1동,서구,가정1동
1,가정2동,1216,51,0,0,1216,51,23.843137,중구,서구,가정2동,서구,가정2동
2,가정3동,209,13,0,0,209,13,16.076923,중구,서구,가정3동,서구,가정3동
3,가좌1동,298,20,0,0,298,20,14.900000,중구,서구,가좌1동,서구,가좌1동
4,가좌2동,582,33,0,0,582,33,17.636364,중구,서구,가좌2동,서구,가좌2동
...,...,...,...,...,...,...,...,...,...,...,...,...,...
157,계양3동,0,0,0,0,0,0,0.000000,옹진군,계양구,계양3동,계양구,계양3동
158,대청면소청출장소,0,0,0,0,0,0,0.000000,옹진군,옹진군,대청면소청출장소,옹진군,대청면소청출장소
159,개항동,0,0,0,0,0,0,0.000000,옹진군,중구,개항동,중구,개항동
160,용현2동,0,0,0,0,0,0,0.000000,옹진군,미추홀구,용현2동,미추홀구,용현2동
161,만수5동,0,0,0,0,0,0,0.000000,옹진군,남동구,만수5동,남동구,만수5동

In [53]:
df.to_csv('최종2_인천학급당학생수.csv', index=False, encoding='utf-8-sig')

In [55]:
df = pd.read_csv('최종-인천학급당학생수.csv')
df

      행정동  학생수(계)_초  학급수(계)_초  학생수(계)_중  학급수(계)_중  총학생수  총학급수     학급당학생수
0    가정1동      1558        66       910        30  2468    96  25.708333
1    가정2동      1216        51         0         0  1216    51  23.843137
2    가정3동       209        13         0         0   209    13  16.076923
3    가좌1동       298        20         0         0   298    20  14.900000
4    가좌2동       582        33         0         0   582    33  17.636364
..    ...       ...       ...       ...       ...   ...   ...        ...
136  학익2동       789        42       782        27  1571    69  22.768116
137   화도면        41         7        37         4    78    11   7.090909
138  화수2동       610        33       354        18   964    51  18.901961
139  효성1동      2142       109       895        38  3037   147  20.659864
140  효성2동       341        19       412        16   753    35  21.514286

[141 rows x 8 columns]

In [58]:
df2 = pd.read_csv('인천유아인구.csv',encoding='cp949')
df2

       시도명 시군구명      읍면동명  유아인구
0    인천광역시   중구       연안동    63
1    인천광역시   중구       신포동    57
2    인천광역시   중구       신흥동   396
3    인천광역시   중구       도원동    24
4    인천광역시   중구       율목동    27
..     ...  ...       ...   ...
157  인천광역시  옹진군       덕적면    12
158  인천광역시  옹진군       영흥면    98
159  인천광역시  옹진군       자월면    10
160  인천광역시  옹진군  자월면이작출장소     2
161  인천광역시  옹진군       연평면    35

[162 rows x 4 columns]

In [59]:
missing_dong = set(df2['읍면동명']) - set(df['행정동'])
missing_rows = df2[df2['읍면동명'].isin(missing_dong)][['시군구명', '읍면동명']].drop_duplicates()
missing_df = pd.DataFrame(columns=df.columns)
missing_df['행정동'] = missing_rows['읍면동명'].values
missing_df['시군구'] = missing_rows['시군구명'].values
for col in df.columns:
    if col not in ['행정동', '시군구']:
        missing_df[col] = 0
df_final = pd.concat([df, missing_df], ignore_index=True)
df_final

,행정동,학생수(계)_초,학급수(계)_초,학생수(계)_중,학급수(계)_중,총학생수,총학급수,학급당학생수,시군구
0,가정1동,1558,66,910,30,2468,96,25.708333,NaN
1,가정2동,1216,51,0,0,1216,51,23.843137,NaN
2,가정3동,209,13,0,0,209,13,16.076923,NaN
3,가좌1동,298,20,0,0,298,20,14.900000,NaN
4,가좌2동,582,33,0,0,582,33,17.636364,NaN
...,...,...,...,...,...,...,...,...,...
157,계양3동,0,0,0,0,0,0,0.000000,계양구
158,서도면볼음출장소,0,0,0,0,0,0,0.000000,강화군
159,북도면장봉출장소,0,0,0,0,0,0,0.000000,옹진군
160,대청면소청출장소,0,0,0,0,0,0,0.000000,옹진군
161,자월면이작출장소,0,0,0,0,0,0,0.000000,옹진군

In [60]:
# 1) 없는 동 추가
missing_dong = set(df2['읍면동명']) - set(df['행정동'])
missing_rows = df2[df2['읍면동명'].isin(missing_dong)][['시군구명', '읍면동명']].drop_duplicates()

missing_df = pd.DataFrame(columns=df.columns)
missing_df['행정동'] = missing_rows['읍면동명'].values

for col in df.columns:
    if col != '행정동':
        missing_df[col] = 0

df_final = pd.concat([df, missing_df], ignore_index=True)

# 2) 시군구 매핑표 만들기
dong_map = df2[['시군구명', '읍면동명']].drop_duplicates()

# 3) 전체 행에 대해 시군구 붙이기
df_final = df_final.merge(
    dong_map,
    left_on='행정동',
    right_on='읍면동명',
    how='left'
)

# 4) 컬럼명 정리
df_final['시군구'] = df_final['시군구명']
df_final.drop(columns=['시군구명', '읍면동명'], inplace=True)

df_final

,행정동,학생수(계)_초,학급수(계)_초,학생수(계)_중,학급수(계)_중,총학생수,총학급수,학급당학생수,시군구
0,가정1동,1558,66,910,30,2468,96,25.708333,서구
1,가정2동,1216,51,0,0,1216,51,23.843137,서구
2,가정3동,209,13,0,0,209,13,16.076923,서구
3,가좌1동,298,20,0,0,298,20,14.900000,서구
4,가좌2동,582,33,0,0,582,33,17.636364,서구
...,...,...,...,...,...,...,...,...,...
157,계양3동,0,0,0,0,0,0,0.000000,계양구
158,서도면볼음출장소,0,0,0,0,0,0,0.000000,강화군
159,북도면장봉출장소,0,0,0,0,0,0,0.000000,옹진군
160,대청면소청출장소,0,0,0,0,0,0,0.000000,옹진군
161,자월면이작출장소,0,0,0,0,0,0,0.000000,옹진군

In [62]:
df_final.to_csv('최종2_인천학급당학생수.csv', index=False, encoding='utf-8-sig')

In [64]:
df = pd.read_csv('최종-경기학급당학생수.csv',encoding='utf-8-sig')
df

      행정동  학생수(계)_초  학급수(계)_초  학생수(계)_중  학급수(계)_중  총학생수  총학급수     학급당학생수
0     가좌동       762        38       613        24  1375    62  22.177419
1     갈매동      2420       102      1010        34  3430   136  25.220588
2     갈산동      1695        69      1135        38  2830   107  26.448598
3     감북동        84         8         0         0    84     8  10.500000
4     감일동      3684       156      1261        48  4945   204  24.240196
..    ...       ...       ...       ...       ...   ...   ...        ...
242   화전동      2142        96       825        37  2967   133  22.308271
243  화정1동       886        46       738        31  1624    77  21.090909
244  화정2동      1612        71      1489        58  3101   129  24.038760
245   효자동      2096        90       850        31  2946   121  24.347107
246   흥도동      1847        81      1175        44  3022   125  24.176000

[247 rows x 8 columns]

In [66]:
df2 = pd.read_csv('경기유아인구.csv',encoding='cp949')
df2

     시도명     시군구명  읍면동명  유아인구
0    경기도  성남시 수정구  신흥1동   123
1    경기도  성남시 수정구  신흥2동  1916
2    경기도  성남시 수정구  신흥3동   142
3    경기도  성남시 수정구  태평1동   151
4    경기도  성남시 수정구  태평2동   204
..   ...      ...   ...   ...
269  경기도      김포시   풍무동  2319
270  경기도      김포시   장기동  1599
271  경기도      김포시   구래동  2152
272  경기도      김포시   마산동  1923
273  경기도      김포시   운양동  2071

[274 rows x 4 columns]

In [67]:
missing = set(df2['읍면동명']) - set(df['행정동'])

{'광명1동',
 '광명2동',
 '광명4동',
 '박달동',
 '상대원2동',
 '수진1동',
 '수택2동',
 '시흥동',
 '신장1동',
 '신흥1동',
 '신흥3동',
 '심곡1동',
 '안양4동',
 '양정동',
 '원미2동',
 '철산4동',
 '초이동',
 '춘궁동',
 '춘의동',
 '태평2동',
 '호계1동',
 '화도읍남부출장소',
 '화도읍동부출장소'}

In [68]:
# 1) 없는 동 추가
missing_dong = set(df2['읍면동명']) - set(df['행정동'])
missing_rows = df2[df2['읍면동명'].isin(missing_dong)][['시군구명', '읍면동명']].drop_duplicates()

missing_df = pd.DataFrame(columns=df.columns)
missing_df['행정동'] = missing_rows['읍면동명'].values

for col in df.columns:
    if col != '행정동':
        missing_df[col] = 0

df_final = pd.concat([df, missing_df], ignore_index=True)

# 2) 시군구 매핑표 만들기
dong_map = df2[['시군구명', '읍면동명']].drop_duplicates()

# 3) 전체 행에 대해 시군구 붙이기
df_final = df_final.merge(
    dong_map,
    left_on='행정동',
    right_on='읍면동명',
    how='left'
)

# 4) 컬럼명 정리
df_final['시군구'] = df_final['시군구명']
df_final.drop(columns=['시군구명', '읍면동명'], inplace=True)

df_final

,행정동,학생수(계)_초,학급수(계)_초,학생수(계)_중,학급수(계)_중,총학생수,총학급수,학급당학생수,시군구
0,가좌동,762,38,613,24,1375,62,22.177419,고양시 일산서구
1,갈매동,2420,102,1010,34,3430,136,25.220588,구리시
2,갈산동,1695,69,1135,38,2830,107,26.448598,안양시 동안구
3,감북동,84,8,0,0,84,8,10.500000,하남시
4,감일동,3684,156,1261,48,4945,204,24.240196,하남시
...,...,...,...,...,...,...,...,...,...
269,화도읍남부출장소,0,0,0,0,0,0,0.000000,남양주시
270,양정동,0,0,0,0,0,0,0.000000,남양주시
271,신장1동,0,0,0,0,0,0,0.000000,하남시
272,춘궁동,0,0,0,0,0,0,0.000000,하남시
273,초이동,0,0,0,0,0,0,0.000000,하남시

In [69]:
df_final.to_csv('최종2_경기학급당학생수.csv', index=False, encoding='utf-8-sig')