In [69]:
# %matplotlib notebook

import pandas as pd
import matplotlib.pyplot as plt
from matplotlib import font_manager, rc

# 한글깨짐처리
font_loc = "c:/Windows/Fonts/malgun.ttf"
font_name=font_manager.FontProperties(fname=font_loc).get_name()
rc('font', family=font_name)

In [2]:
df = pd.read_csv(
    '서울방과후.csv', encoding='cp949')
df

         시도   시군구     학교명
0    서울시교육청  동대문구    군자초
1    서울시교육청  동대문구   답십리초
2    서울시교육청  동대문구    동답초
3    서울시교육청   중랑구    동원초
4    서울시교육청   중랑구    망우초
..      ...   ...     ...
599  서울시교육청   성북구     대광초
600  서울시교육청   성북구     매원초
601  서울시교육청   성북구     성신초
602  서울시교육청   강북구     영훈초
603  서울시교육청   성북구     우촌초

[604 rows x 3 columns]

In [3]:
df2 = pd.read_csv(
    '교육 - 초등학교(서울).csv', encoding='cp949')
df2

FileNotFoundError: [Errno 2] No such file or directory: '교육 - 초등학교(서울).csv'

In [ ]:
df2 = pd.read_csv(
    '교육 - 초등학교(인천).csv', encoding='cp949')
df2

In [ ]:
df = pd.read_csv(
    '인천초등학생수.csv', usecols=[4,33,34], encoding='cp949')
df

In [ ]:
df2 = pd.read_csv(
    '최종-인천초등.csv',encoding='cp949')
df2

In [ ]:
result = pd.merge(df2, df, on='학교명', how='outer')
result

In [ ]:
result2 = result.groupby('행정동')[['학생수(계)', '학급수(계)']].sum().reset_index()
result2

In [ ]:
result2.to_csv('인천행정동초등합계.csv', index=False, encoding='utf-8-sig')

In [ ]:
df = pd.read_csv(
    '인천중학생수.csv', usecols=[4,24,25], encoding='cp949')
df

In [ ]:
df2 = pd.read_csv(
    '최종-인천중등.csv',encoding='cp949')
df2

In [ ]:
result = pd.merge(df2, df, on='학교명', how='outer')
result

In [ ]:
result2 = result.groupby('행정동')[['학생수(계)', '학급수(계)']].sum().reset_index()
result2

In [ ]:
result2.to_csv('인천행정동중등합계.csv', index=False, encoding='utf-8-sig')

In [ ]:
ele_df =  pd.read_csv('인천행정동초등합계.csv',encoding='utf-8-sig')
ele_df

In [ ]:
mid_df = pd.read_csv('인천행정동중등합계.csv',encoding='utf-8-sig')

In [ ]:
mid_df

In [ ]:
result = pd.merge(
    ele_df, mid_df,
    on='행정동',
    how='outer',
    suffixes=('_초', '_중')
)
result

In [ ]:
result = result.fillna(0)

In [ ]:
cols = ['학생수(계)_초','학생수(계)_중','학급수(계)_초','학급수(계)_중']
result[cols] = result[cols].astype(int)
result

In [ ]:
result['총학생수'] = result['학생수(계)_초'] + result['학생수(계)_중']
result['총학급수'] = result['학급수(계)_초'] + result['학급수(계)_중']

result['학급당학생수'] = result['총학생수'] / result['총학급수']
result

In [ ]:
result.to_csv('최종-인천학급당학생수.csv', index=False, encoding='utf-8-sig')

In [ ]:
icn = pd.read_csv('인천유아인구.csv',encoding='cp949')
icn

In [ ]:
icn.rename(columns={'읍면동명': '행정동'}, inplace=True)
icn

In [ ]:
set(icn['행정동']) - set(result['행정동'])

In [ ]:
df = pd.read_csv('최종-서울초등.csv',encoding='cp949')
df

In [ ]:
df2 = pd.read_csv(
    '서울초등학생수.csv', usecols=[4,33,34], encoding='cp949')
df2

In [ ]:
result = pd.merge(df, df2, on='학교명', how='outer')
result

In [ ]:
result2 = result.groupby('행정동')[['학생수(계)', '학급수(계)']].sum().reset_index()
result2

In [ ]:
result2.to_csv('서울행정동초등합계.csv', index=False, encoding='utf-8-sig')

In [ ]:
df = pd.read_csv('최종-서울중등.csv',encoding='cp949')
df

In [ ]:
df2 = pd.read_csv(
    '서울중학생수.csv', usecols=[4,24,25], encoding='cp949')
df2

In [ ]:
result = pd.merge(df, df2, on='학교명', how='outer')
result

In [ ]:
result2 = result.groupby('행정동')[['학생수(계)', '학급수(계)']].sum().reset_index()
result2

In [ ]:
result2.to_csv('서울행정동중등합계.csv', index=False, encoding='utf-8-sig')

In [ ]:
ele_df =  pd.read_csv('서울행정동초등합계.csv',encoding='utf-8-sig')
ele_df

In [ ]:
mid_df =  pd.read_csv('서울행정동중등합계.csv',encoding='utf-8-sig')
mid_df

In [ ]:
result = pd.merge(
    ele_df, mid_df,
    on='행정동',
    how='outer',
    suffixes=('_초', '_중')
)
result

In [ ]:
result = result.fillna(0)
cols = ['학생수(계)_초','학생수(계)_중','학급수(계)_초','학급수(계)_중']
result[cols] = result[cols].astype(int)
result

In [ ]:
result['총학생수'] = result['학생수(계)_초'] + result['학생수(계)_중']
result['총학급수'] = result['학급수(계)_초'] + result['학급수(계)_중']

result['학급당학생수'] = result['총학생수'] / result['총학급수']
result

In [ ]:
result.to_csv('최종-서울학급당학생수.csv', index=False, encoding='utf-8-sig')

In [ ]:
df = pd.read_csv('최종-경기초등.csv',encoding='cp949')
df

In [ ]:
df2 = pd.read_csv(
    '경기초등학생수.csv', usecols=[4,33,34], encoding='cp949')
df2

In [ ]:
result = pd.merge(df, df2, on='학교명', how='outer')
result

In [ ]:
result2 = result.groupby('행정동')[['학생수(계)', '학급수(계)']].sum().reset_index()
result2

In [ ]:
result2.to_csv('경기행정동초등합계.csv', index=False, encoding='utf-8-sig')

In [ ]:
df = pd.read_csv('최종-경기중등.csv',encoding='cp949')
df

In [ ]:
df2 = pd.read_csv(
    '경기중학생수.csv', usecols=[4,24,25], encoding='cp949')
df2

In [ ]:
result = pd.merge(df, df2, on='학교명', how='outer')
result

In [ ]:
result2 = result.groupby('행정동')[['학생수(계)', '학급수(계)']].sum().reset_index()
result2

In [ ]:
result2.to_csv('경기행정동중등합계.csv', index=False, encoding='utf-8-sig')

In [ ]:
ele_df =  pd.read_csv('경기행정동초등합계.csv',encoding='utf-8-sig')
ele_df

In [ ]:
mid_df =  pd.read_csv('경기행정동중등합계.csv',encoding='utf-8-sig')
mid_df

In [ ]:
result = pd.merge(
    ele_df, mid_df,
    on='행정동',
    how='outer',
    suffixes=('_초', '_중')
)
result

In [ ]:
result = result.fillna(0)

In [ ]:
cols = ['학생수(계)_초','학생수(계)_중','학급수(계)_초','학급수(계)_중']
result[cols] = result[cols].astype(int)
result

In [ ]:
result['총학생수'] = result['학생수(계)_초'] + result['학생수(계)_중']
result['총학급수'] = result['학급수(계)_초'] + result['학급수(계)_중']

result['학급당학생수'] = result['총학생수'] / result['총학급수']
result

In [4]:
result.to_csv('최종-경기학급당학생수.csv', index=False, encoding='utf-8-sig')

NameError: name 'result' is not defined

In [29]:
df = pd.read_csv('최종-경기초등.csv',encoding='cp949')
df

,학교명,도로명주소,위도,경도,법정동,행정동
0,가람초등학교,"경기도 고양시 덕양구 행신로311번길 78 (행신동,가람초등학교)",37.623719,126.842224,행신동,행신3동
1,강선초등학교,"경기도 고양시 일산서구 강선로 77 , 강선초등학교 (주엽동)",37.671228,126.764626,주엽동,주엽1동
2,고봉초등학교,"경기도 고양시 일산동구 중산로 280 , 고봉초등학교 (중산동)",37.696139,126.782620,중산동,중산1동
3,고양백석초등학교,"경기도 고양시 일산동구 강촌로 140 (백석동,고양백석초등학교)",37.652139,126.789058,백석동,백석1동
4,고양신일초등학교,"경기도 고양시 일산서구 강선로 183 , 고양신일초등학교 (일산동)",37.679550,126.770830,일산동,일산3동
...,...,...,...,...,...,...
556,도현초등학교,경기도 용인시 처인구 모현읍 왕산로 15 도현초등학교,37.346183,127.256954,모현읍 왕산리,모현읍
557,처인초등학교,경기도 용인시 처인구 남사읍 한숲로57번길 17 처인초등학교,37.154096,127.168567,남사읍 아곡리,남사읍
558,용인솔빛초등학교,경기도 용인시 처인구 낙은로 100-5 (역북동),37.244666,127.193263,역북동,역북동
559,모담초등학교,경기도 김포시 운양로 158 (운양동),37.656730,126.674743,운양동,운양동
560,위례해솔초등학교,경기도 성남시 수정구 남위례로 131 위례해솔초등학교,37.460354,127.139264,복정동,복정동

In [30]:
df2 = pd.read_csv(
    '경기초등학생수.csv', usecols=[4,33,34], encoding='cp949')
df2

          학교명  학급수(계)  학생수(계)
0      가람초등학교      17     309
1      강선초등학교      22     507
2      고봉초등학교      17     323
3    고양백석초등학교      20     452
4    고양신일초등학교      35     831
..        ...     ...     ...
557  고양장항초등학교      18     351
558    도현초등학교      20     445
559    처인초등학교      11     181
560  과천율목초등학교      23     460
561    모담초등학교       6      47

[562 rows x 3 columns]

In [32]:
result = pd.merge(df, df2, on='학교명', how='outer')
result

,학교명,도로명주소,위도,경도,법정동,행정동,학급수(계),학생수(계)
0,가곡초등학교,"경기도 남양주시 화도읍 비룡로379번길 3 (화도읍, 가곡초등학교)",37.684372,127.305213,화도읍 가곡리,화도읍,20.0,414.0
1,가람초등학교,"경기도 고양시 덕양구 행신로311번길 78 (행신동,가람초등학교)",37.623719,126.842224,행신동,행신3동,17.0,309.0
2,가림초등학교,"경기도 광명시 금당로 11-7 (하안동, 가림초등학교)",37.458532,126.878838,하안동,하안3동,21.0,410.0
3,가양초등학교,"경기도 남양주시 수동면 비룡로1243번길 7 , 가양초등학교 (수동면)",37.733004,127.293476,수동면 수산리,수동면,6.0,33.0
4,가운초등학교,경기도 남양주시 가운로2길 54 (가운동),37.600570,127.155810,다산동,다산2동,15.0,281.0
...,...,...,...,...,...,...,...,...
564,효자초등학교,경기도 용인시 수지구 성복1로 106-1 (성복동),37.317352,127.067344,성복동,성복동,37.0,924.0
565,흥덕초등학교,"경기도 용인시 기흥구 흥덕1로62번길 26 , 흥덕초등학교 (영덕동)",37.272441,127.071724,영덕동,영덕1동,21.0,474.0
566,흥도초등학교,경기도 고양시 덕양구 도래울1로 83 (도내동),37.627476,126.872069,도내동,흥도동,49.0,1146.0
567,희망대초등학교,"경기도 성남시 수정구 공원로370번길 29 (신흥동,희망대초등학교)",37.447499,127.149115,신흥동,신흥2동,33.0,729.0
568,희성초등학교,"경기도 안양시 동안구 학의로 86 , 희성초등학교 (비산동)",37.398366,126.948710,비산동,달안동,12.0,181.0

In [33]:
result2 = result.groupby('행정동')[['학생수(계)', '학급수(계)']].sum().reset_index()
result2

      행정동  학생수(계)  학급수(계)
0     가좌동   762.0    38.0
1     갈매동  2420.0   102.0
2     갈산동  1695.0    69.0
3     감북동    84.0     8.0
4     감일동  3684.0   156.0
..    ...     ...     ...
238   화전동  2142.0    96.0
239  화정1동   886.0    46.0
240  화정2동  1612.0    71.0
241   효자동  2096.0    90.0
242   흥도동  1847.0    81.0

[243 rows x 3 columns]

In [34]:
result2.to_csv('경기행정동초등합계.csv', index=False, encoding='utf-8-sig')

In [35]:
df = pd.read_csv('최종-경기중등.csv',encoding='cp949')
df

,학교명,도로명주소,위도,경도,법정동,행정동
0,가람중학교,"경기도 고양시 덕양구 화신로 122(행신동,가람중학교)",37.623660,126.841207,행신동,행신3동
1,고양중학교,경기도 고양시 덕양구 동세로 82(삼송동),37.649668,126.884581,삼송동,삼송2동
2,능곡중학교,경기도 고양시 덕양구 행당로11번길 48(토당동),37.622922,126.826642,토당동,행주동
3,대화중학교,"경기도 고양시 일산서구 고양대로 348(대화동,대화중학교)",37.673844,126.744477,대화동,대화동
4,덕양중학교,경기도 고양시 덕양구 중앙로176번길 18-29(화전동),37.604654,126.871715,화전동,화전동
...,...,...,...,...,...,...
299,옥길새길중학교,경기도 부천시 소사구 양지로166번길 45옥길새길중학교(옥길동),37.467734,126.818591,옥길동,옥길동
300,한홀중학교,경기도 하남시 조정대로 115 한홀중학교(풍산동),37.554453,127.191572,풍산동,미사3동
301,처인중학교,경기도 용인시 처인구 남사읍 한숲로57번길 17 처인중학교,37.154096,127.168567,남사읍 아곡리,남사읍
302,도현중학교,경기도 용인시 처인구 모현읍 왕산로 15,37.346183,127.256954,모현읍 왕산리,모현읍
303,용인솔빛중학교,경기도 용인시 처인구 낙은로 98(역북동),37.244766,127.195100,역북동,역북동

In [36]:
df2 = pd.read_csv(
    '경기중학생수.csv', usecols=[4,24,25], encoding='cp949')
df2

                학교명  학급수(계)  학생수(계)
0             가람중학교      16     378
1             고양중학교      32     823
2             능곡중학교      19     411
3             대화중학교      19     509
4             덕양중학교      10     175
..              ...     ...     ...
296         옥길새길중학교       7     146
297           처인중학교       4      90
298           도현중학교      11     195
299  광명중학교부설방송통신중학교       9     185
300  삼평중학교부설방송통신중학교       9     181

[301 rows x 3 columns]

In [37]:
result = pd.merge(df, df2, on='학교명', how='outer')
result

,학교명,도로명주소,위도,경도,법정동,행정동,학급수(계),학생수(계)
0,가람중학교,"경기도 고양시 덕양구 화신로 122(행신동,가람중학교)",37.623660,126.841207,행신동,행신3동,16.0,378.0
1,가림중학교,"경기도 광명시 오리로 616(하안동,가림중학교)",37.457643,126.879674,하안동,하안3동,19.0,469.0
2,가운중학교,"경기도 남양주시 가운로2길 74(가운동,가운중학교)",37.599443,127.156612,다산동,다산2동,14.0,241.0
3,갈매중학교,"경기도 구리시 갈매순환로 121(갈매동, 갈매중학교)",37.630934,127.119781,갈매동,갈매동,34.0,1010.0
4,감일백제중학교,경기도 하남시 감일백제로 210감일동,37.509968,127.151198,감일동,감일동,22.0,561.0
...,...,...,...,...,...,...,...,...
306,화광중학교,"경기도 남양주시 화도읍 경춘로 2226(화도읍,화광중학교)",37.652764,127.334952,화도읍 월산리,화도읍,13.0,404.0
307,화수중학교,"경기도 고양시 덕양구 화수로 47(화정동, 화수중학교)",37.645229,126.834916,화정동,화정1동,31.0,738.0
308,화접중학교,경기도 남양주시 별내4로 26 화접중학교(별내동),37.645854,127.114755,별내동,별내동,20.0,504.0
309,화정중학교,"경기도 고양시 덕양구 화신로 343(화정동, 화정중학교)",37.634911,126.826480,화정동,화정2동,24.0,670.0
310,흥덕중학교,"경기도 용인시 기흥구 흥덕중앙로105번길 10(영덕동,흥덕중학교)",37.276810,127.079374,영덕동,영덕1동,37.0,1039.0

In [38]:
result2 = result.groupby('행정동')[['학생수(계)', '학급수(계)']].sum().reset_index()
result2

      행정동  학생수(계)  학급수(계)
0     가좌동   613.0    24.0
1     갈매동  1010.0    34.0
2     갈산동  1135.0    38.0
3     감일동  1261.0    48.0
4    고강본동   610.0    25.0
..    ...     ...     ...
185   화전동   825.0    37.0
186  화정1동   738.0    31.0
187  화정2동  1489.0    58.0
188   효자동   850.0    31.0
189   흥도동  1175.0    44.0

[190 rows x 3 columns]

In [39]:
result2.to_csv('경기행정동중등합계.csv', index=False, encoding='utf-8-sig')

In [40]:
ele_df =  pd.read_csv('경기행정동초등합계.csv',encoding='utf-8-sig')
mid_df =  pd.read_csv('경기행정동중등합계.csv',encoding='utf-8-sig')

In [41]:
result = pd.merge(
    ele_df, mid_df,
    on='행정동',
    how='outer',
    suffixes=('_초', '_중')
)
result

      행정동  학생수(계)_초  학급수(계)_초  학생수(계)_중  학급수(계)_중
0     가좌동     762.0      38.0     613.0      24.0
1     갈매동    2420.0     102.0    1010.0      34.0
2     갈산동    1695.0      69.0    1135.0      38.0
3     감북동      84.0       8.0       NaN       NaN
4     감일동    3684.0     156.0    1261.0      48.0
..    ...       ...       ...       ...       ...
242   화전동    2142.0      96.0     825.0      37.0
243  화정1동     886.0      46.0     738.0      31.0
244  화정2동    1612.0      71.0    1489.0      58.0
245   효자동    2096.0      90.0     850.0      31.0
246   흥도동    1847.0      81.0    1175.0      44.0

[247 rows x 5 columns]

In [42]:
result = result.fillna(0)

In [43]:
cols = ['학생수(계)_초','학생수(계)_중','학급수(계)_초','학급수(계)_중']
result[cols] = result[cols].astype(int)
result

      행정동  학생수(계)_초  학급수(계)_초  학생수(계)_중  학급수(계)_중
0     가좌동       762        38       613        24
1     갈매동      2420       102      1010        34
2     갈산동      1695        69      1135        38
3     감북동        84         8         0         0
4     감일동      3684       156      1261        48
..    ...       ...       ...       ...       ...
242   화전동      2142        96       825        37
243  화정1동       886        46       738        31
244  화정2동      1612        71      1489        58
245   효자동      2096        90       850        31
246   흥도동      1847        81      1175        44

[247 rows x 5 columns]

In [44]:
result['총학생수'] = result['학생수(계)_초'] + result['학생수(계)_중']
result['총학급수'] = result['학급수(계)_초'] + result['학급수(계)_중']

result['학급당학생수'] = result['총학생수'] / result['총학급수']
result

      행정동  학생수(계)_초  학급수(계)_초  학생수(계)_중  학급수(계)_중  총학생수  총학급수     학급당학생수
0     가좌동       762        38       613        24  1375    62  22.177419
1     갈매동      2420       102      1010        34  3430   136  25.220588
2     갈산동      1695        69      1135        38  2830   107  26.448598
3     감북동        84         8         0         0    84     8  10.500000
4     감일동      3684       156      1261        48  4945   204  24.240196
..    ...       ...       ...       ...       ...   ...   ...        ...
242   화전동      2142        96       825        37  2967   133  22.308271
243  화정1동       886        46       738        31  1624    77  21.090909
244  화정2동      1612        71      1489        58  3101   129  24.038760
245   효자동      2096        90       850        31  2946   121  24.347107
246   흥도동      1847        81      1175        44  3022   125  24.176000

[247 rows x 8 columns]

In [45]:
result.to_csv('최종-경기학급당학생수.csv', index=False, encoding='utf-8-sig')

In [46]:
df =  pd.read_csv('경기유아인구.csv',encoding='cp949')
df

     시도명     시군구명  읍면동명  유아인구
0    경기도  성남시 수정구  신흥1동   123
1    경기도  성남시 수정구  신흥2동  1916
2    경기도  성남시 수정구  신흥3동   142
3    경기도  성남시 수정구  태평1동   151
4    경기도  성남시 수정구  태평2동   204
..   ...      ...   ...   ...
269  경기도      김포시   풍무동  2319
270  경기도      김포시   장기동  1599
271  경기도      김포시   구래동  2152
272  경기도      김포시   마산동  1923
273  경기도      김포시   운양동  2071

[274 rows x 4 columns]

In [47]:
set(df['읍면동명']) - set(result['행정동'])

{'광명1동',
 '광명2동',
 '광명4동',
 '박달동',
 '상대원2동',
 '수진1동',
 '수택2동',
 '시흥동',
 '신장1동',
 '신흥1동',
 '신흥3동',
 '심곡1동',
 '안양4동',
 '양정동',
 '원미2동',
 '철산4동',
 '초이동',
 '춘궁동',
 '춘의동',
 '태평2동',
 '호계1동',
 '화도읍남부출장소',
 '화도읍동부출장소'}

In [48]:
result['행정동'].nunique()

247

In [50]:
df['읍면동명_정제'] = df['읍면동명'].astype(str).str.strip().str.replace(' ', '', regex=False)
result['행정동_정제'] = result['행정동'].astype(str).str.strip().str.replace(' ', '', regex=False)

In [51]:
print('전체 행정동:', df['읍면동명_정제'].nunique())
print('result 행정동:', result['행정동_정제'].nunique())

missing = set(df['읍면동명_정제']) - set(result['행정동_정제'])
print('없는 동 수:', len(missing))
print(sorted(missing))

전체 행정동: 270
result 행정동: 247
없는 동 수: 23
['광명1동', '광명2동', '광명4동', '박달동', '상대원2동', '수진1동', '수택2동', '시흥동', '신장1동', '신흥1동', '신흥3동', '심곡1동', '안양4동', '양정동', '원미2동', '철산4동', '초이동', '춘궁동', '춘의동', '태평2동', '호계1동', '화도읍남부출장소', '화도읍동부출장소']

In [52]:
extra = set(result['행정동_정제']) - set(df['읍면동명_정제'])
print(len(extra))
print(sorted(extra))

0
[]

In [53]:
set(df['읍면동명_정제']) - set(result['행정동_정제'])

{'광명1동',
 '광명2동',
 '광명4동',
 '박달동',
 '상대원2동',
 '수진1동',
 '수택2동',
 '시흥동',
 '신장1동',
 '신흥1동',
 '신흥3동',
 '심곡1동',
 '안양4동',
 '양정동',
 '원미2동',
 '철산4동',
 '초이동',
 '춘궁동',
 '춘의동',
 '태평2동',
 '호계1동',
 '화도읍남부출장소',
 '화도읍동부출장소'}

In [57]:
df = pd.read_csv('서울어린이집_법정동.csv', encoding='cp949')
df

,시도,시군구,어린이집명,어린이집유형구분,주소,위도,경도,법정동
0,서울특별시,종로구,삼청어린이집,국공립,서울특별시 종로구 삼청로7길 26 (팔판동),37.584032,126.980481,팔판동
1,서울특별시,종로구,창신어린이집,사회복지법인,서울특별시 종로구 창신5길 22 (창신동),37.573648,127.012017,창신동
2,서울특별시,종로구,아동회관어린이집,국공립,서울특별시 종로구 지봉로13길 14 아동회관어린이집,37.578948,127.014467,창신동
3,서울특별시,종로구,부암어린이집,국공립,서울특별시 종로구 세검정로6다길 10-7,37.601605,126.963099,신영동
4,서울특별시,종로구,낙산어린이집,국공립,서울특별시 종로구 창신길 210-11 낙산어린이집 (창신동),37.579547,127.010183,창신동
...,...,...,...,...,...,...,...,...
3980,서울특별시,강동구,구립그란츠리버키즈어린이집,국공립,서울특별시 강동구 천호대로 1050 101동 1~2층,37.536712,127.128325,성내동
3981,서울특별시,강동구,구립둔촌1동어린이집,국공립,서울특별시 강동구 양재대로 1342 1층,37.525887,127.136436,둔촌동
3982,서울특별시,강동구,구립온빛어린이집,국공립,서울특별시 강동구 아리수로 385 1층(고덕동),37.562759,127.170832,고덕동
3983,서울특별시,강동구,구립더샵강동센트럴시티어린이집,국공립,서울특별시 강동구 진황도로 14 102동,37.539524,127.128473,천호동
3984,서울특별시,강동구,구립강동프레스티지원어린이집,국공립,서울특별시 강동구 올림픽로78길 37 104동,37.542953,127.126261,천호동

In [66]:
df = pd.read_csv('서울_유아인구.csv', encoding='cp949')
df

       시도명 시군구명   읍면동명  유아인구
0    서울특별시  종로구  청운효자동   250
1    서울특별시  종로구    사직동   189
2    서울특별시  종로구    삼청동    34
3    서울특별시  종로구    부암동   151
4    서울특별시  종로구    평창동   459
..     ...  ...    ...   ...
422  서울특별시  강동구  성내제2동   488
423  서울특별시  강동구  성내제3동   448
424  서울특별시  강동구     길동  1297
425  서울특별시  강동구  둔촌제1동  1986
426  서울특별시  강동구  둔촌제2동   949

[427 rows x 4 columns]

In [67]:
df['읍면동명'] = df['읍면동명'].str.replace(r'제+(?=\d)', '', regex=True)
df

       시도명 시군구명   읍면동명  유아인구
0    서울특별시  종로구  청운효자동   250
1    서울특별시  종로구    사직동   189
2    서울특별시  종로구    삼청동    34
3    서울특별시  종로구    부암동   151
4    서울특별시  종로구    평창동   459
..     ...  ...    ...   ...
422  서울특별시  강동구   성내2동   488
423  서울특별시  강동구   성내3동   448
424  서울특별시  강동구     길동  1297
425  서울특별시  강동구   둔촌1동  1986
426  서울특별시  강동구   둔촌2동   949

[427 rows x 4 columns]

In [68]:
result.to_csv('서울_유아인구.csv', index=False, encoding='cp949')