In [1]:
# %matplotlib notebook

import pandas as pd
import matplotlib.pyplot as plt
from matplotlib import font_manager, rc

# 한글깨짐처리
font_loc = "c:/Windows/Fonts/malgun.ttf"
font_name=font_manager.FontProperties(fname=font_loc).get_name()
rc('font', family=font_name)

In [2]:
df = pd.read_csv(
    '인천어린이집_법정동.csv', encoding='cp949')
df

,시도,시군구,어린이집명,어린이집유형구분,주소,위도,경도,행정동
0,인천광역시,중구,장미어린이집,국공립,인천광역시 중구 참외전로174번길 12-1,37.471945,126.634784,동인천동
1,인천광역시,중구,금산어린이집,국공립,인천광역시 중구 백운로351번길 3 (운북동),37.505831,126.519962,영종동
2,인천광역시,중구,효성어린이집,사회복지법인,인천광역시 중구 백운로 34 (중산동),37.501012,126.552623,영종동
3,인천광역시,중구,찬솔어린이집,국공립,"인천광역시 중구 축항대로86번길 47 3동 101호(항동7가, 라이프아파트)",37.451767,126.604978,연안동
4,인천광역시,중구,비둘기어린이집,국공립,인천광역시 중구 자유공원서로29번길 3-19,37.476661,126.619777,개항동
...,...,...,...,...,...,...,...,...
1543,인천광역시,옹진군,공립자월보듬이나눔이어린이집,국공립,인천광역시 옹진군 자월면 자월서로164번길 23,37.254506,126.308238,자월면
1544,인천광역시,옹진군,영흥 빛누리 어린이집,직장,인천광역시 옹진군 영흥면 영흥남로369번길 22,37.249944,126.454689,영흥면
1545,인천광역시,옹진군,해병대흑룡어린이집,직장,인천광역시 옹진군 백령면 백령로 783 해병대 흑룡어린이집,37.960648,124.668521,백령면
1546,인천광역시,옹진군,공립진촌어린이집,국공립,인천광역시 옹진군 백령면 백령로 359,37.973188,124.709005,백령면
1547,인천광역시,옹진군,공립장봉어린이집,국공립,인천광역시 옹진군 북도면 장봉로 229 공립장봉어린이집,37.531176,126.368617,북도면

In [4]:
df2 = pd.read_csv(
    '유아인구.csv', encoding='utf-8-sig')
df2

       시도명 시군구명   읍면동명  유아인구
0    서울특별시  종로구  청운효자동   250
1    서울특별시  종로구    사직동   189
2    서울특별시  종로구    삼청동    34
3    서울특별시  종로구    부암동   151
4    서울특별시  종로구    평창동   459
..     ...  ...    ...   ...
858    경기도  김포시    풍무동  2319
859    경기도  김포시    장기동  1599
860    경기도  김포시    구래동  2152
861    경기도  김포시    마산동  1923
862    경기도  김포시    운양동  2071

[863 rows x 4 columns]

In [5]:
df2.rename(columns={'읍면동명': '행정동'}, inplace=True)
df2

       시도명 시군구명    행정동  유아인구
0    서울특별시  종로구  청운효자동   250
1    서울특별시  종로구    사직동   189
2    서울특별시  종로구    삼청동    34
3    서울특별시  종로구    부암동   151
4    서울특별시  종로구    평창동   459
..     ...  ...    ...   ...
858    경기도  김포시    풍무동  2319
859    경기도  김포시    장기동  1599
860    경기도  김포시    구래동  2152
861    경기도  김포시    마산동  1923
862    경기도  김포시    운양동  2071

[863 rows x 4 columns]

In [6]:
df.groupby('행정동').size().reset_index(name='어린이집수')

         행정동  어린이집수
0       가정1동     25
1       가정2동      9
2       가정3동      2
3       가좌1동      7
4       가좌2동      7
..       ...    ...
144     학익2동      8
145  화수1.화평동      3
146     화수2동      2
147     효성1동     10
148     효성2동     15

[149 rows x 2 columns]

In [8]:
df2 = pd.read_csv(
    '인천유아인구.csv', encoding='cp949')
df2

       시도명 시군구명      읍면동명  유아인구
0    인천광역시   중구       연안동    63
1    인천광역시   중구       신포동    57
2    인천광역시   중구       신흥동   396
3    인천광역시   중구       도원동    24
4    인천광역시   중구       율목동    27
..     ...  ...       ...   ...
157  인천광역시  옹진군       덕적면    12
158  인천광역시  옹진군       영흥면    98
159  인천광역시  옹진군       자월면    10
160  인천광역시  옹진군  자월면이작출장소     2
161  인천광역시  옹진군       연평면    35

[162 rows x 4 columns]

In [9]:
df2.rename(columns={'읍면동명': '행정동'}, inplace=True)
df2

       시도명 시군구명       행정동  유아인구
0    인천광역시   중구       연안동    63
1    인천광역시   중구       신포동    57
2    인천광역시   중구       신흥동   396
3    인천광역시   중구       도원동    24
4    인천광역시   중구       율목동    27
..     ...  ...       ...   ...
157  인천광역시  옹진군       덕적면    12
158  인천광역시  옹진군       영흥면    98
159  인천광역시  옹진군       자월면    10
160  인천광역시  옹진군  자월면이작출장소     2
161  인천광역시  옹진군       연평면    35

[162 rows x 4 columns]

In [11]:
result = df.groupby('행정동').size().reset_index(name='어린이집수')
result

         행정동  어린이집수
0       가정1동     25
1       가정2동      9
2       가정3동      2
3       가좌1동      7
4       가좌2동      7
..       ...    ...
144     학익2동      8
145  화수1.화평동      3
146     화수2동      2
147     효성1동     10
148     효성2동     15

[149 rows x 2 columns]

In [12]:
result2 = pd.merge(result, df2, on='행정동', how='inner')
result2.head()

    행정동  어린이집수    시도명 시군구명  유아인구
0  가정1동     25  인천광역시   서구  2292
1  가정2동      9  인천광역시   서구  1177
2  가정3동      2  인천광역시   서구   139
3  가좌1동      7  인천광역시   서구   341
4  가좌2동      7  인천광역시   서구   458

In [13]:
result2['천명당보육시설수'] = (result2['어린이집수'] / result2['유아인구']) * 1000
result2

         행정동  어린이집수    시도명  시군구명  유아인구   천명당보육시설수
0       가정1동     25  인천광역시    서구  2292  10.907504
1       가정2동      9  인천광역시    서구  1177   7.646559
2       가정3동      2  인천광역시    서구   139  14.388489
3       가좌1동      7  인천광역시    서구   341  20.527859
4       가좌2동      7  인천광역시    서구   458  15.283843
..       ...    ...    ...   ...   ...        ...
144     학익2동      8  인천광역시  미추홀구   301  26.578073
145  화수1.화평동      3  인천광역시    동구    35  85.714286
146     화수2동      2  인천광역시    동구    54  37.037037
147     효성1동     10  인천광역시   계양구   735  13.605442
148     효성2동     15  인천광역시   계양구   671  22.354694

[149 rows x 6 columns]

In [14]:
result2 = result2[['시도명', '시군구명', '행정동', '어린이집수', '유아인구', '천명당보육시설수']]

In [15]:
result2

       시도명  시군구명      행정동  어린이집수  유아인구   천명당보육시설수
0    인천광역시    서구     가정1동     25  2292  10.907504
1    인천광역시    서구     가정2동      9  1177   7.646559
2    인천광역시    서구     가정3동      2   139  14.388489
3    인천광역시    서구     가좌1동      7   341  20.527859
4    인천광역시    서구     가좌2동      7   458  15.283843
..     ...   ...      ...    ...   ...        ...
144  인천광역시  미추홀구     학익2동      8   301  26.578073
145  인천광역시    동구  화수1.화평동      3    35  85.714286
146  인천광역시    동구     화수2동      2    54  37.037037
147  인천광역시   계양구     효성1동     10   735  13.605442
148  인천광역시   계양구     효성2동     15   671  22.354694

[149 rows x 6 columns]

In [16]:
result2.to_csv('교육 - 천명당보육시설수(인천).csv', index=False, encoding='utf-8-sig')

In [17]:
pop_dongs = set(df2['행정동'])      # 유아인구 데이터 행정동
child_dongs = set(result['행정동'])  # 어린이집 groupby 결과 행정동

missing_dongs = pop_dongs - child_dongs
print(len(missing_dongs))
print(sorted(missing_dongs))

13
['교동면', '내가면', '대청면소청출장소', '북도면장봉출장소', '서도면', '서도면볼음출장소', '송해면', '양도면', '양사면', '용유동', '율목동', '자월면이작출장소', '화도면']

In [18]:
result2 = pd.merge(df2, result, on='행정동', how='left')
result2['어린이집수'] = result2['어린이집수'].fillna(0)
result2['천명당보육시설수'] = (result2['어린이집수'] / result2['유아인구']) * 1000
result2

       시도명 시군구명       행정동  유아인구  어린이집수    천명당보육시설수
0    인천광역시   중구       연안동    63    2.0   31.746032
1    인천광역시   중구       신포동    57    3.0   52.631579
2    인천광역시   중구       신흥동   396   10.0   25.252525
3    인천광역시   중구       도원동    24    3.0  125.000000
4    인천광역시   중구       율목동    27    0.0    0.000000
..     ...  ...       ...   ...    ...         ...
157  인천광역시  옹진군       덕적면    12    1.0   83.333333
158  인천광역시  옹진군       영흥면    98    3.0   30.612245
159  인천광역시  옹진군       자월면    10    2.0  200.000000
160  인천광역시  옹진군  자월면이작출장소     2    0.0    0.000000
161  인천광역시  옹진군       연평면    35    1.0   28.571429

[162 rows x 6 columns]

In [19]:
result2.to_csv('교육 - 천명당보육시설수(인천).csv', index=False, encoding='utf-8-sig')

In [20]:
result2['어린이집수'] = result2['어린이집수'].fillna(0).astype(int)
result2

       시도명 시군구명       행정동  유아인구  어린이집수    천명당보육시설수
0    인천광역시   중구       연안동    63      2   31.746032
1    인천광역시   중구       신포동    57      3   52.631579
2    인천광역시   중구       신흥동   396     10   25.252525
3    인천광역시   중구       도원동    24      3  125.000000
4    인천광역시   중구       율목동    27      0    0.000000
..     ...  ...       ...   ...    ...         ...
157  인천광역시  옹진군       덕적면    12      1   83.333333
158  인천광역시  옹진군       영흥면    98      3   30.612245
159  인천광역시  옹진군       자월면    10      2  200.000000
160  인천광역시  옹진군  자월면이작출장소     2      0    0.000000
161  인천광역시  옹진군       연평면    35      1   28.571429

[162 rows x 6 columns]

In [21]:
result2.to_csv('교육 - 천명당보육시설수(인천).csv', index=False, encoding='utf-8-sig')

In [22]:
df = pd.read_csv(
    '인천어린이집_법정동.csv', encoding='cp949')
df

,시도,시군구,어린이집명,어린이집유형구분,주소,위도,경도,행정동
0,인천광역시,중구,장미어린이집,국공립,인천광역시 중구 참외전로174번길 12-1,37.471945,126.634784,동인천동
1,인천광역시,중구,금산어린이집,국공립,인천광역시 중구 백운로351번길 3 (운북동),37.505831,126.519962,영종동
2,인천광역시,중구,효성어린이집,사회복지법인,인천광역시 중구 백운로 34 (중산동),37.501012,126.552623,영종동
3,인천광역시,중구,찬솔어린이집,국공립,"인천광역시 중구 축항대로86번길 47 3동 101호(항동7가, 라이프아파트)",37.451767,126.604978,연안동
4,인천광역시,중구,비둘기어린이집,국공립,인천광역시 중구 자유공원서로29번길 3-19,37.476661,126.619777,개항동
...,...,...,...,...,...,...,...,...
1543,인천광역시,옹진군,공립자월보듬이나눔이어린이집,국공립,인천광역시 옹진군 자월면 자월서로164번길 23,37.254506,126.308238,자월면
1544,인천광역시,옹진군,영흥 빛누리 어린이집,직장,인천광역시 옹진군 영흥면 영흥남로369번길 22,37.249944,126.454689,영흥면
1545,인천광역시,옹진군,해병대흑룡어린이집,직장,인천광역시 옹진군 백령면 백령로 783 해병대 흑룡어린이집,37.960648,124.668521,백령면
1546,인천광역시,옹진군,공립진촌어린이집,국공립,인천광역시 옹진군 백령면 백령로 359,37.973188,124.709005,백령면
1547,인천광역시,옹진군,공립장봉어린이집,국공립,인천광역시 옹진군 북도면 장봉로 229 공립장봉어린이집,37.531176,126.368617,북도면

In [24]:
df2 = pd.read_csv(
    '인천유아인구.csv', encoding='cp949')
df2

       시도명 시군구명      읍면동명  유아인구
0    인천광역시   중구       연안동    63
1    인천광역시   중구       신포동    57
2    인천광역시   중구       신흥동   396
3    인천광역시   중구       도원동    24
4    인천광역시   중구       율목동    27
..     ...  ...       ...   ...
157  인천광역시  옹진군       덕적면    12
158  인천광역시  옹진군       영흥면    98
159  인천광역시  옹진군       자월면    10
160  인천광역시  옹진군  자월면이작출장소     2
161  인천광역시  옹진군       연평면    35

[162 rows x 4 columns]

In [25]:
result = df.groupby('행정동').size().reset_index(name='어린이집수')
result

         행정동  어린이집수
0       가정1동     25
1       가정2동      9
2       가정3동      2
3       가좌1동      7
4       가좌2동      7
..       ...    ...
144     학익2동      8
145  화수1.화평동      3
146     화수2동      2
147     효성1동     10
148     효성2동     15

[149 rows x 2 columns]

In [27]:
df = pd.read_csv(
    '경기어린이집_법정동.csv', encoding='utf-8-sig')
df

,시도,시군구,어린이집명,어린이집유형구분,주소,위도,경도,법정동
0,경기도,고양시일산서구,미소어린이집,가정,"경기도 고양시 일산서구 대산로 249 106동 102호(대화동, 성저마을동익1단지아파트)",37.679564,126.751468,대화동
1,경기도,고양시덕양구,신임마누엘어린이집,민간,경기도 고양시 덕양구 혜음로13번길 34 (고양동),37.702066,126.899654,고양동
2,경기도,고양시일산동구,고양시립저현어린이집,국공립,경기도 고양시 일산동구 위시티2로11번길 22-21,37.677341,126.813709,식사동
3,경기도,고양시일산동구,동심어린이집,민간,"경기도 고양시 일산동구 강촌로 191 (마두동,백마마을4단지 내)",37.655343,126.794735,마두1동
4,경기도,고양시일산동구,안젤라어린이집,사회복지법인,경기도 고양시 일산동구 강송로225번길 39 (마두동),37.657443,126.779214,마두1동
...,...,...,...,...,...,...,...,...
3989,경기도,김포시,양우늘푸른어린이집,민간,경기도 김포시 고촌읍 신곡로 75 양우내안애 관리동,37.606540,126.771684,고촌읍
3990,경기도,김포시,시립아이월드어린이집,국공립,경기도 김포시 풍무로69번길 47 (당곡마을 월드메르디앙아파트),37.602435,126.718868,풍무동
3991,경기도,김포시,시립운양래미안어린이집,국공립,"경기도 김포시 김포한강11로 227 (운양동, 풍경마을 래미안 한강2차)",37.653289,126.674614,운양동
3992,경기도,김포시,시립다예린어린이집,국공립,"경기도 김포시 김포한강5로 417 (구래동, 한가람마을 우미린)",37.648193,126.625425,구래동
3993,경기도,김포시,서광노리숲어린이집,민간,경기도 김포시 김포대로926번길 15 신안서광아파트 관리동,37.625621,126.714967,김포본동

In [28]:
df2 = pd.read_csv(
    '경기유아인구.csv', encoding='cp949')
df2

     시도명     시군구명  읍면동명  유아인구
0    경기도  성남시 수정구  신흥1동   123
1    경기도  성남시 수정구  신흥2동  1916
2    경기도  성남시 수정구  신흥3동   142
3    경기도  성남시 수정구  태평1동   151
4    경기도  성남시 수정구  태평2동   204
..   ...      ...   ...   ...
269  경기도      김포시   풍무동  2319
270  경기도      김포시   장기동  1599
271  경기도      김포시   구래동  2152
272  경기도      김포시   마산동  1923
273  경기도      김포시   운양동  2071

[274 rows x 4 columns]

In [30]:
df.rename(columns={'법정동': '행정동'}, inplace=True)
df

,시도,시군구,어린이집명,어린이집유형구분,주소,위도,경도,행정동
0,경기도,고양시일산서구,미소어린이집,가정,"경기도 고양시 일산서구 대산로 249 106동 102호(대화동, 성저마을동익1단지아파트)",37.679564,126.751468,대화동
1,경기도,고양시덕양구,신임마누엘어린이집,민간,경기도 고양시 덕양구 혜음로13번길 34 (고양동),37.702066,126.899654,고양동
2,경기도,고양시일산동구,고양시립저현어린이집,국공립,경기도 고양시 일산동구 위시티2로11번길 22-21,37.677341,126.813709,식사동
3,경기도,고양시일산동구,동심어린이집,민간,"경기도 고양시 일산동구 강촌로 191 (마두동,백마마을4단지 내)",37.655343,126.794735,마두1동
4,경기도,고양시일산동구,안젤라어린이집,사회복지법인,경기도 고양시 일산동구 강송로225번길 39 (마두동),37.657443,126.779214,마두1동
...,...,...,...,...,...,...,...,...
3989,경기도,김포시,양우늘푸른어린이집,민간,경기도 김포시 고촌읍 신곡로 75 양우내안애 관리동,37.606540,126.771684,고촌읍
3990,경기도,김포시,시립아이월드어린이집,국공립,경기도 김포시 풍무로69번길 47 (당곡마을 월드메르디앙아파트),37.602435,126.718868,풍무동
3991,경기도,김포시,시립운양래미안어린이집,국공립,"경기도 김포시 김포한강11로 227 (운양동, 풍경마을 래미안 한강2차)",37.653289,126.674614,운양동
3992,경기도,김포시,시립다예린어린이집,국공립,"경기도 김포시 김포한강5로 417 (구래동, 한가람마을 우미린)",37.648193,126.625425,구래동
3993,경기도,김포시,서광노리숲어린이집,민간,경기도 김포시 김포대로926번길 15 신안서광아파트 관리동,37.625621,126.714967,김포본동

In [31]:
df2.rename(columns={'읍면동명': '행정동'}, inplace=True)
df2

     시도명     시군구명   행정동  유아인구
0    경기도  성남시 수정구  신흥1동   123
1    경기도  성남시 수정구  신흥2동  1916
2    경기도  성남시 수정구  신흥3동   142
3    경기도  성남시 수정구  태평1동   151
4    경기도  성남시 수정구  태평2동   204
..   ...      ...   ...   ...
269  경기도      김포시   풍무동  2319
270  경기도      김포시   장기동  1599
271  경기도      김포시   구래동  2152
272  경기도      김포시   마산동  1923
273  경기도      김포시   운양동  2071

[274 rows x 4 columns]

In [32]:
result = df.groupby('행정동').size().reset_index(name='어린이집수')
result

      행정동  어린이집수
0     가좌동     10
1     갈매동     22
2     갈산동      3
3     갈현동     19
4     감일동     38
..    ...    ...
284   화전동     19
285  화정1동     13
286  화정2동     16
287   효자동     15
288   흥도동     17

[289 rows x 2 columns]

In [37]:
result2 = pd.merge(df2, result, on='행정동', how='inner')
result2

     시도명     시군구명   행정동  유아인구  어린이집수
0    경기도  성남시 수정구  신흥1동   123      1
1    경기도  성남시 수정구  신흥2동  1916     14
2    경기도  성남시 수정구  신흥3동   142      2
3    경기도  성남시 수정구  태평1동   151      5
4    경기도  성남시 수정구  태평2동   204      7
..   ...      ...   ...   ...    ...
264  경기도      김포시   풍무동  2319     39
265  경기도      김포시   장기동  1599     29
266  경기도      김포시   구래동  2152     33
267  경기도      김포시   마산동  1923     26
268  경기도      김포시   운양동  2071     39

[269 rows x 5 columns]

In [38]:
set(df2['행정동']) - set(result['행정동'])

{'감북동', '춘궁동', '학온동', '화도읍남부출장소', '화도읍동부출장소'}

In [40]:
set(result['행정동']) - set(df2['행정동'])

{'갈현동',
 '과천동',
 '광탄면',
 '교하동',
 '금촌1동',
 '금촌2동',
 '금촌3동',
 '문산읍',
 '문원동',
 '법원읍',
 '별양동',
 '운정1동',
 '운정2동',
 '운정3동',
 '운정4동',
 '운정5동',
 '운정6동',
 '원문동',
 '월롱면',
 '적성면',
 '조리읍',
 '탄현면',
 '파주읍',
 '파평면'}

In [46]:
df2 = pd.read_csv(
    '경기어린이집.csv', encoding='cp949')
df2.head()

,시도,시군구,어린이집명,어린이집유형구분,운영현황,우편번호,주소,어린이집전화번호,어린이집팩스번호,보육실수,...,정원수,현원수,위도,경도,통학차량운영여부,홈페이지주소,인가일자,휴지시작일자,휴지종료일자,폐지일자
0,경기도,고양시일산서구,미소어린이집,가정,정상,10376,"경기도 고양시 일산서구 대산로 249 106동 102호(대화동, 성저마을동익1단지아파트)",031-814-2577,--,3,...,15,14,37.679185,126.750311,미운영,NaN,2007-11-19,NaN,NaN,NaN
1,경기도,고양시덕양구,신임마누엘어린이집,민간,정상,10275,경기도 고양시 덕양구 혜음로13번길 34 (고양동),031-969-8704,031-969-8772,12,...,229,75,37.702042,126.899583,운영,NaN,2007-12-03,NaN,NaN,NaN
2,경기도,고양시일산동구,고양시립저현어린이집,국공립,정상,10323,경기도 고양시 일산동구 위시티2로11번길 22-21,031-967-5665,031-967-5775,5,...,37,27,37.677383,126.813707,미운영,NaN,2014-05-01,NaN,NaN,NaN
3,경기도,고양시일산동구,동심어린이집,민간,정상,10417,"경기도 고양시 일산동구 강촌로 191 (마두동,백마마을4단지 내)",031-907-1551,031-905-5114,8,...,137,53,37.656121,126.792563,운영,NaN,2002-07-22,NaN,NaN,NaN
4,경기도,고양시일산동구,안젤라어린이집,사회복지법인,정상,10410,경기도 고양시 일산동구 강송로225번길 39 (마두동),031-906-3004,031-906-5004,5,...,69,57,37.657403,126.779241,운영,https://blog.naver.com/angelakinder1,1997-06-03,NaN,NaN,NaN

In [47]:
df = pd.read_csv(
    '경기어린이집.csv', usecols=[0,1,2,3,6,16,17],encoding='cp949')
df.head()

,시도,시군구,어린이집명,어린이집유형구분,주소,위도,경도
0,경기도,고양시일산서구,미소어린이집,가정,"경기도 고양시 일산서구 대산로 249 106동 102호(대화동, 성저마을동익1단지아파트)",37.679185,126.750311
1,경기도,고양시덕양구,신임마누엘어린이집,민간,경기도 고양시 덕양구 혜음로13번길 34 (고양동),37.702042,126.899583
2,경기도,고양시일산동구,고양시립저현어린이집,국공립,경기도 고양시 일산동구 위시티2로11번길 22-21,37.677383,126.813707
3,경기도,고양시일산동구,동심어린이집,민간,"경기도 고양시 일산동구 강촌로 191 (마두동,백마마을4단지 내)",37.656121,126.792563
4,경기도,고양시일산동구,안젤라어린이집,사회복지법인,경기도 고양시 일산동구 강송로225번길 39 (마두동),37.657403,126.779241

In [49]:
df.to_csv('경기어린이집_행정동.csv', index=False, encoding='utf-8-sig')

In [53]:
import time
import requests
import pandas as pd

# ✅ 1. 카카오 REST API 키 넣기 (여기!!)
REST_API_KEY = "YOUR_KAKAO_API_KEY"

# ✅ 2. 주소 → (위도, 경도, 법정동) 변환 함수
def get_addr_info(address):
    url = 'https://dapi.kakao.com/v2/local/search/address.json'
    headers = {"Authorization": f"KakaoAK {REST_API_KEY}"}
    params = {'query': address}
    
    try:
        response = requests.get(url, headers=headers, params=params)
        if response.status_code == 200:
            result = response.json()
            if result['documents']:
                addr_data = result['documents'][0]['address']
                lat = addr_data['y']  # 위도
                lon = addr_data['x']  # 경도
                b_dong = addr_data['region_3depth_name']  # 법정동
                h_dong = addr_data['region_3depth_h_name'] #행정동
                
                return lat, lon, b_dong, h_dong
        return None, None, None, None
    except:
        return None, None, None, None

# ✅ 3. CSV 불러오기 (네 파일)
df = pd.read_csv('교육 - 초등학교(인천).csv', encoding='cp949')

# ✅ 4. API 적용 (주소 컬럼 기준)
print("좌표 변환 중...")
info_list = []

for addr in df['도로명주소']:
    info = get_addr_info(addr)
    info_list.append(info)
    time.sleep(0.2)  # ⭐ API 제한 방지 (중요)

# ✅ 5. 컬럼 추가
df['위도'], df['경도'], df['법정동'], df['행정동'] = zip(*info_list)

# ✅ 6. 저장
df.to_csv('인천초등학교_법정동행정동.csv', index=False, encoding='utf-8-sig')

print("완료!")
df.head()

좌표 변환 중...
완료!

,학교명,도로명주소,위도,경도,동읍면,법정동,행정동
0,경인교육대학교부설초등학교,인천광역시 계양구 안남로 612 (효성동),37.5376434628106,126.712593970923,효성동,효성동,효성1동
1,서도초등학교볼음분교장,인천광역시 강화군 서도면 볼음도길 248 (서도면),37.6713673205191,126.189453918369,서도면,서도면 볼음도리,서도면
2,갑룡초등학교,"인천광역시 강화군 강화읍 갑룡길 88 , 갑룡초등학교 (강화읍,갑룡초등학교)",37.7435379928955,126.502658666842,강화읍,강화읍 갑곳리,강화읍
3,강화초등학교,"인천광역시 강화군 강화읍 북문길 36 (강화읍,강화초등학교)",37.7503470919545,126.486131242143,강화읍,강화읍 관청리,강화읍
4,교동초등학교,"인천광역시 강화군 교동면 대룡안길 29 , 교동초등학교 (교동면, 교동초등학교)",37.7841847310507,126.281350656576,교동,교동면 대룡리,교동면

In [54]:
# ✅ 1. 카카오 REST API 키 넣기 (여기!!)
REST_API_KEY = "YOUR_KAKAO_API_KEY"

# ✅ 2. 주소 → (위도, 경도, 법정동) 변환 함수
def get_addr_info(address):
    url = 'https://dapi.kakao.com/v2/local/search/address.json'
    headers = {"Authorization": f"KakaoAK {REST_API_KEY}"}
    params = {'query': address}
    
    try:
        response = requests.get(url, headers=headers, params=params)
        if response.status_code == 200:
            result = response.json()
            if result['documents']:
                addr_data = result['documents'][0]['address']
                lat = addr_data['y']  # 위도
                lon = addr_data['x']  # 경도
                b_dong = addr_data['region_3depth_name']  # 법정동
                h_dong = addr_data['region_3depth_h_name'] #행정동
                
                return lat, lon, b_dong, h_dong
        return None, None, None, None
    except:
        return None, None, None, None

# ✅ 3. CSV 불러오기 (네 파일)
df = pd.read_csv('교육 - 중학교(인천).csv', encoding='cp949')

# ✅ 4. API 적용 (주소 컬럼 기준)
print("좌표 변환 중...")
info_list = []

for addr in df['도로명주소']:
    info = get_addr_info(addr)
    info_list.append(info)
    time.sleep(0.2)  # ⭐ API 제한 방지 (중요)

# ✅ 5. 컬럼 추가
df['위도'], df['경도'], df['법정동'], df['행정동'] = zip(*info_list)

# ✅ 6. 저장
df.to_csv('인천중학교_법정동행정동.csv', index=False, encoding='utf-8-sig')

print("완료!")
df.head()

좌표 변환 중...
완료!

,학교명,도로명주소,위도,경도,읍면동,법정동,행정동
0,강남중학교,"인천광역시 강화군 길상면 강화남로 62-2 (길상면, 강남중학교)",37.643841359022,126.479099830853,길상면,길상면 온수리,길상면
1,강서중학교,"인천광역시 강화군 하점면 강화서로 909-19 (하점면, 강서중학교)",37.7731109281637,126.388107646894,하점면,하점면 이강리,하점면
2,강화여자중학교,인천광역시 강화군 강화읍 갑룡길 11 (강화읍),37.7442963095585,126.495025276909,강화읍,강화읍 갑곳리,강화읍
3,강화중학교,"인천광역시 강화군 강화읍 동문로 53 , 강화중학교 (강화읍)",37.7504037329271,126.491024632395,강화읍,강화읍 관청리,강화읍
4,교동중학교,인천광역시 강화군 교동면 교동남로 77 (교동면),37.7784626831111,126.284316914567,교동면,교동면 대룡리,교동면

In [55]:
# ✅ 1. 카카오 REST API 키 넣기 (여기!!)
REST_API_KEY = "YOUR_KAKAO_API_KEY"

# ✅ 2. 주소 → (위도, 경도, 법정동) 변환 함수
def get_addr_info(address):
    url = 'https://dapi.kakao.com/v2/local/search/address.json'
    headers = {"Authorization": f"KakaoAK {REST_API_KEY}"}
    params = {'query': address}
    
    try:
        response = requests.get(url, headers=headers, params=params)
        if response.status_code == 200:
            result = response.json()
            if result['documents']:
                addr_data = result['documents'][0]['address']
                lat = addr_data['y']  # 위도
                lon = addr_data['x']  # 경도
                b_dong = addr_data['region_3depth_name']  # 법정동
                h_dong = addr_data['region_3depth_h_name'] #행정동
                
                return lat, lon, b_dong, h_dong
        return None, None, None, None
    except:
        return None, None, None, None

# ✅ 3. CSV 불러오기 (네 파일)
df = pd.read_csv('교육 - 초등학교(서울).csv', encoding='cp949')

# ✅ 4. API 적용 (주소 컬럼 기준)
print("좌표 변환 중...")
info_list = []

for addr in df['도로명주소']:
    info = get_addr_info(addr)
    info_list.append(info)
    time.sleep(0.2)  # ⭐ API 제한 방지 (중요)

# ✅ 5. 컬럼 추가
df['위도'], df['경도'], df['법정동'], df['행정동'] = zip(*info_list)

# ✅ 6. 저장
df.to_csv('서울초등학교_법정동행정동.csv', index=False, encoding='utf-8-sig')

print("완료!")
df.head()

좌표 변환 중...
완료!

,학교명,도로명주소,위도,경도,법정동,행정동
0,서울교육대학교부설초등학교,"서울특별시 서초구 서초중앙로 96 (서초동,서울교대초등학교)",37.4907404857731,127.015424537648,서초동,서초1동
1,서울대학교사범대학부설초등학교,"서울특별시 종로구 대학로 64 (동숭동,서울사대부설초등학교)",37.5775997032467,127.004295521787,이화동,이화동
2,서울개원초등학교,"서울특별시 강남구 선릉로 29 (개포동,개원초등학교)",37.4816986136485,127.059450501428,개포동,개포1동
3,서울개일초등학교,"서울특별시 강남구 개포로 401 , 개일초등학교 (개포동,개일초등학교)",37.4862353839469,127.057790853452,개포동,개포2동
4,서울개포초등학교,"서울특별시 강남구 삼성로4길 30 (개포동, 개포초등학교)",37.4863349159759,127.070310042973,개포동,개포2동

In [58]:
# ✅ 1. 카카오 REST API 키 넣기 (여기!!)
REST_API_KEY = "YOUR_KAKAO_API_KEY"

# ✅ 2. 주소 → (위도, 경도, 법정동) 변환 함수
def get_addr_info(address):
    url = 'https://dapi.kakao.com/v2/local/search/address.json'
    headers = {"Authorization": f"KakaoAK {REST_API_KEY}"}
    params = {'query': address}
    
    try:
        response = requests.get(url, headers=headers, params=params)
        if response.status_code == 200:
            result = response.json()
            if result['documents']:
                addr_data = result['documents'][0]['address']
                lat = addr_data['y']  # 위도
                lon = addr_data['x']  # 경도
                b_dong = addr_data['region_3depth_name']  # 법정동
                h_dong = addr_data['region_3depth_h_name'] #행정동
                
                return lat, lon, b_dong, h_dong
        return None, None, None, None
    except:
        return None, None, None, None

# ✅ 3. CSV 불러오기 (네 파일)
df = pd.read_csv('교육- 중학교(서울).csv', encoding='cp949')

# ✅ 4. API 적용 (주소 컬럼 기준)
print("좌표 변환 중...")
info_list = []

for addr in df['도로명주소']:
    info = get_addr_info(addr)
    info_list.append(info)
    time.sleep(0.2)  # ⭐ API 제한 방지 (중요)

# ✅ 5. 컬럼 추가
df['위도'], df['경도'], df['법정동'], df['행정동'] = zip(*info_list)

# ✅ 6. 저장
df.to_csv('서울중학교_법정동행정동.csv', index=False, encoding='utf-8-sig')

print("완료!")
df.head()

좌표 변환 중...
완료!

,학교명,도로명주소,위도,경도,읍면동,법정동,행정동
0,서울대학교사범대학부설중학교,서울특별시 성북구 월곡로 36 (종암동),37.5958358987959,127.039066241267,종암동,종암동,종암동
1,서울대학교사범대학부설여자중학교,"서울특별시 종로구 대학로 64 , 서울대학교사범대학부설여자중학교 (이화동)",37.5775997032467,127.004295521787,이화동,이화동,이화동
2,개원중학교,"서울특별시 강남구 영동대로 101 , 개원중학교 (개포동,개원중학교)",37.4915905275033,127.071900307455,개포동,개포동,개포2동
3,개포중학교,"서울특별시 강남구 선릉로 9 (개포동,개포중학교)",37.4804473919149,127.062402866859,개포동,개포동,개포1동
4,경원중학교,"서울특별시 서초구 신반포로33길 39 (잠원동,경원중학교)",37.5115815961934,127.009018254738,잠원동,잠원동,반포3동

In [60]:
# ✅ 1. 카카오 REST API 키 넣기 (여기!!)
REST_API_KEY = "YOUR_KAKAO_API_KEY"

# ✅ 2. 주소 → (위도, 경도, 법정동) 변환 함수
def get_addr_info(address):
    url = 'https://dapi.kakao.com/v2/local/search/address.json'
    headers = {"Authorization": f"KakaoAK {REST_API_KEY}"}
    params = {'query': address}
    
    try:
        response = requests.get(url, headers=headers, params=params)
        if response.status_code == 200:
            result = response.json()
            if result['documents']:
                addr_data = result['documents'][0]['address']
                lat = addr_data['y']  # 위도
                lon = addr_data['x']  # 경도
                b_dong = addr_data['region_3depth_name']  # 법정동
                h_dong = addr_data['region_3depth_h_name'] #행정동
                
                return lat, lon, b_dong, h_dong
        return None, None, None, None
    except:
        return None, None, None, None

# ✅ 3. CSV 불러오기 (네 파일)
df = pd.read_csv('교육 - 중학교(경기).csv', encoding='cp949')

# ✅ 4. API 적용 (주소 컬럼 기준)
print("좌표 변환 중...")
info_list = []

for addr in df['도로명주소']:
    info = get_addr_info(addr)
    info_list.append(info)
    time.sleep(0.2)  # ⭐ API 제한 방지 (중요)

# ✅ 5. 컬럼 추가
df['위도'], df['경도'], df['법정동'], df['행정동'] = zip(*info_list)

# ✅ 6. 저장
df.to_csv('경기중학교_법정동행정동.csv', index=False, encoding='utf-8-sig')

print("완료!")
df.head()

좌표 변환 중...
완료!

,학교명,도로명주소,위도,경도,읍면동,법정동,행정동
0,가람중학교,"경기도 고양시 덕양구 화신로 122(행신동,가람중학교)",37.6236599713119,126.841207087385,행신동,행신동,행신3동
1,고양중학교,경기도 고양시 덕양구 동세로 82(삼송동),37.649668189667,126.884581142849,삼송동,삼송동,삼송2동
2,능곡중학교,경기도 고양시 덕양구 행당로11번길 48(토당동),37.622922016434,126.826641887462,토당동,토당동,행주동
3,대화중학교,"경기도 고양시 일산서구 고양대로 348(대화동,대화중학교)",37.6738435519202,126.744476855032,대화동,대화동,대화동
4,덕양중학교,경기도 고양시 덕양구 중앙로176번길 18-29(화전동),37.6046541593841,126.87171545085,화전동,화전동,화전동

In [61]:
# ✅ 1. 카카오 REST API 키 넣기 (여기!!)
REST_API_KEY = "YOUR_KAKAO_API_KEY"

# ✅ 2. 주소 → (위도, 경도, 법정동) 변환 함수
def get_addr_info(address):
    url = 'https://dapi.kakao.com/v2/local/search/address.json'
    headers = {"Authorization": f"KakaoAK {REST_API_KEY}"}
    params = {'query': address}
    
    try:
        response = requests.get(url, headers=headers, params=params)
        if response.status_code == 200:
            result = response.json()
            if result['documents']:
                addr_data = result['documents'][0]['address']
                lat = addr_data['y']  # 위도
                lon = addr_data['x']  # 경도
                b_dong = addr_data['region_3depth_name']  # 법정동
                h_dong = addr_data['region_3depth_h_name'] #행정동
                
                return lat, lon, b_dong, h_dong
        return None, None, None, None
    except:
        return None, None, None, None

# ✅ 3. CSV 불러오기 (네 파일)
df = pd.read_csv('교육 - 초등학교(경기).csv', encoding='cp949')

# ✅ 4. API 적용 (주소 컬럼 기준)
print("좌표 변환 중...")
info_list = []

for addr in df['도로명주소']:
    info = get_addr_info(addr)
    info_list.append(info)
    time.sleep(0.2)  # ⭐ API 제한 방지 (중요)

# ✅ 5. 컬럼 추가
df['위도'], df['경도'], df['법정동'], df['행정동'] = zip(*info_list)

# ✅ 6. 저장
df.to_csv('경기초등학교_법정동행정동.csv', index=False, encoding='utf-8-sig')

print("완료!")
df.head()

좌표 변환 중...
완료!

,학교명,도로명주소,위도,경도,읍면동,법정동,행정동
0,가람초등학교,"경기도 고양시 덕양구 행신로311번길 78 (행신동,가람초등학교)",37.6237194495748,126.842224411918,행신동,행신동,행신3동
1,강선초등학교,"경기도 고양시 일산서구 강선로 77 , 강선초등학교 (주엽동)",37.67122822894,126.764625731644,주엽동,주엽동,주엽1동
2,고봉초등학교,"경기도 고양시 일산동구 중산로 280 , 고봉초등학교 (중산동)",37.6961394442868,126.782620493164,중산동,중산동,중산1동
3,고양백석초등학교,"경기도 고양시 일산동구 강촌로 140 (백석동,고양백석초등학교)",37.6521391747615,126.78905766637,백석동,백석동,백석1동
4,고양신일초등학교,"경기도 고양시 일산서구 강선로 183 , 고양신일초등학교 (일산동)",37.6795496217272,126.770830238317,일산동,일산동,일산3동

In [62]:
df = pd.read_csv('최종-서울학급당학생수.csv',encoding='utf-8-sig')
df

      행정동  학생수(계)_초  학급수(계)_초  학생수(계)_중  학급수(계)_중  총학생수  총학급수     학급당학생수
0    가락1동      1833        84       853        30  2686   114  23.561404
1    가락2동      1409        66       896        34  2305   100  23.050000
2    가락본동       693        42       736        30  1429    72  19.847222
3    가리봉동       267        19         0         0   267    19  14.052632
4     가산동       265        15         0         0   265    15  17.666667
..    ...       ...       ...       ...       ...   ...   ...        ...
384   회기동      1957        88       847        38  2804   126  22.253968
385   효창동       567        30         0         0   567    30  18.900000
386   후암동       566        34         0         0   566    34  16.647059
387  휘경2동       852        45       712        32  1564    77  20.311688
388   흑석동      1989        98       658        26  2647   124  21.346774

[389 rows x 8 columns]

In [64]:
df2 = pd.read_csv('서울유아인구.csv',encoding='cp949')
df2

       시도명 시군구명   읍면동명  유아인구
0    서울특별시  종로구  청운효자동   250
1    서울특별시  종로구    사직동   189
2    서울특별시  종로구    삼청동    34
3    서울특별시  종로구    부암동   151
4    서울특별시  종로구    평창동   459
..     ...  ...    ...   ...
422  서울특별시  강동구  성내제2동   488
423  서울특별시  강동구  성내제3동   448
424  서울특별시  강동구     길동  1297
425  서울특별시  강동구  둔촌제1동  1986
426  서울특별시  강동구  둔촌제2동   949

[427 rows x 4 columns]

In [66]:
len(set(df2['읍면동명']) - set(df['행정동']))

194

In [68]:
# ✅ 1. 카카오 REST API 키 넣기 (여기!!)
REST_API_KEY = "YOUR_KAKAO_API_KEY"

# ✅ 2. 주소 → (위도, 경도, 법정동) 변환 함수
def get_addr_info(address):
    url = 'https://dapi.kakao.com/v2/local/search/address.json'
    headers = {"Authorization": f"KakaoAK {REST_API_KEY}"}
    params = {'query': address}
    
    try:
        response = requests.get(url, headers=headers, params=params)
        if response.status_code == 200:
            result = response.json()
            if result['documents']:
                addr_data = result['documents'][0]['address']
                lat = addr_data['y']  # 위도
                lon = addr_data['x']  # 경도
                b_dong = addr_data['region_3depth_name']  # 법정동
                h_dong = addr_data['region_3depth_h_name'] #행정동
                
                return lat, lon, b_dong, h_dong
        return None, None, None, None
    except:
        return None, None, None, None

# ✅ 3. CSV 불러오기 (네 파일)
df = pd.read_csv('서울어린이집_법정동.csv', encoding='cp949')

# ✅ 4. API 적용 (주소 컬럼 기준)
print("좌표 변환 중...")
info_list = []

for addr in df['주소']:
    info = get_addr_info(addr)
    info_list.append(info)
    time.sleep(0.2)  # ⭐ API 제한 방지 (중요)

# ✅ 5. 컬럼 추가
df['위도'], df['경도'], df['법정동'], df['행정동'] = zip(*info_list)

# ✅ 6. 저장
df.to_csv('서울어린이집_법정동행정동.csv', index=False, encoding='utf-8-sig')

print("완료!")
df.head()

좌표 변환 중...
완료!

,시도,시군구,어린이집명,어린이집유형구분,주소,위도,경도,법정동,행정동
0,서울특별시,종로구,삼청어린이집,국공립,서울특별시 종로구 삼청로7길 26 (팔판동),37.5840321640655,126.980481002242,팔판동,삼청동
1,서울특별시,종로구,창신어린이집,사회복지법인,서울특별시 종로구 창신5길 22 (창신동),37.5736477680085,127.012017293871,창신동,창신1동
2,서울특별시,종로구,아동회관어린이집,국공립,서울특별시 종로구 지봉로13길 14 아동회관어린이집,37.5789483137908,127.014467533898,창신동,창신3동
3,서울특별시,종로구,부암어린이집,국공립,서울특별시 종로구 세검정로6다길 10-7,37.601604649771,126.963099123923,신영동,부암동
4,서울특별시,종로구,낙산어린이집,국공립,서울특별시 종로구 창신길 210-11 낙산어린이집 (창신동),37.5795467508656,127.010182884217,창신동,창신2동

In [69]:
# ✅ 1. 카카오 REST API 키 넣기 (여기!!)
REST_API_KEY = "YOUR_KAKAO_API_KEY"

# ✅ 2. 주소 → (위도, 경도, 법정동) 변환 함수
def get_addr_info(address):
    url = 'https://dapi.kakao.com/v2/local/search/address.json'
    headers = {"Authorization": f"KakaoAK {REST_API_KEY}"}
    params = {'query': address}
    
    try:
        response = requests.get(url, headers=headers, params=params)
        if response.status_code == 200:
            result = response.json()
            if result['documents']:
                addr_data = result['documents'][0]['address']
                lat = addr_data['y']  # 위도
                lon = addr_data['x']  # 경도
                b_dong = addr_data['region_3depth_name']  # 법정동
                h_dong = addr_data['region_3depth_h_name'] #행정동
                
                return lat, lon, b_dong, h_dong
        return None, None, None, None
    except:
        return None, None, None, None

# ✅ 3. CSV 불러오기 (네 파일)
df = pd.read_csv('인천어린이집_법정동.csv', encoding='cp949')

# ✅ 4. API 적용 (주소 컬럼 기준)
print("좌표 변환 중...")
info_list = []

for addr in df['주소']:
    info = get_addr_info(addr)
    info_list.append(info)
    time.sleep(0.2)  # ⭐ API 제한 방지 (중요)

# ✅ 5. 컬럼 추가
df['위도'], df['경도'], df['법정동'], df['행정동'] = zip(*info_list)

# ✅ 6. 저장
df.to_csv('인천어린이집_법정동행정동.csv', index=False, encoding='utf-8-sig')

print("완료!")
df.head()

좌표 변환 중...
완료!

,시도,시군구,어린이집명,어린이집유형구분,주소,위도,경도,행정동,법정동
0,인천광역시,중구,장미어린이집,국공립,인천광역시 중구 참외전로174번길 12-1,37.471945263384,126.634784259158,동인천동,경동
1,인천광역시,중구,금산어린이집,국공립,인천광역시 중구 백운로351번길 3 (운북동),37.5058305883434,126.519962026481,영종동,운북동
2,인천광역시,중구,효성어린이집,사회복지법인,인천광역시 중구 백운로 34 (중산동),37.5010123199487,126.55262267154,영종동,중산동
3,인천광역시,중구,찬솔어린이집,국공립,"인천광역시 중구 축항대로86번길 47 3동 101호(항동7가, 라이프아파트)",37.4517673879313,126.60497770554,연안동,항동7가
4,인천광역시,중구,비둘기어린이집,국공립,인천광역시 중구 자유공원서로29번길 3-19,37.4766609983658,126.619777159028,개항동,북성동3가