In [1]:
import pandas as pd

In [6]:
a = pd.read_excel('[최종]진짜마지막최종_final.xlsx')
a

,Unnamed: 0,시군구,행정동,복지_지수,안전_지수,교육_지수,환경_지수,건강_지수,총점,100점 환산
0,0,연수구,송도2동,0.000993,0.261407,0.053170,0.124219,0.109911,0.549702,84.378765
1,1,연수구,송도1동,0.000510,0.261407,0.060113,0.087210,0.093345,0.502585,77.127319
2,2,동구,송림2동,0.080400,0.177781,0.090221,0.083398,0.088086,0.519885,80.035632
3,3,서구,가좌2동,0.004758,0.250350,0.036773,0.055803,0.096500,0.444184,65.283077
4,4,연수구,동춘2동,0.000564,0.261407,0.047372,0.072056,0.108181,0.489580,74.752663
...,...,...,...,...,...,...,...,...,...,...
858,858,종로구,무악동,0.004044,0.071460,0.033293,0.068713,0.004231,0.181741,11.994865
859,859,종로구,창신3동,0.009584,0.071460,0.027326,0.068661,0.000000,0.177031,11.506469
860,860,종로구,숭인1동,0.000000,0.071460,0.005348,0.069593,0.000000,0.146400,8.735790
861,861,종로구,평창동,0.003279,0.071460,0.001072,0.068804,0.000000,0.144615,8.594515
862,862,종로구,숭인2동,0.000903,0.071460,0.003465,0.068698,0.011353,0.155878,9.521601

In [4]:
a['행정동']= a['행정동'].str.replace('.', '·', regex=False)

In [8]:
a = a.iloc[:,1:]

In [15]:
a.to_excel('[최종]진짜마지막최종_final.xlsx', index=False)

In [11]:
a['시군구']= a['시군구'].str.replace(' ', '', regex=False)

In [13]:
a

,시군구,행정동,복지_지수,안전_지수,교육_지수,환경_지수,건강_지수,총점,100점 환산
0,연수구,송도2동,0.000993,0.261407,0.053170,0.124219,0.109911,0.549702,84.378765
1,연수구,송도1동,0.000510,0.261407,0.060113,0.087210,0.093345,0.502585,77.127319
2,동구,송림2동,0.080400,0.177781,0.090221,0.083398,0.088086,0.519885,80.035632
3,서구,가좌2동,0.004758,0.250350,0.036773,0.055803,0.096500,0.444184,65.283077
4,연수구,동춘2동,0.000564,0.261407,0.047372,0.072056,0.108181,0.489580,74.752663
...,...,...,...,...,...,...,...,...,...
858,종로구,무악동,0.004044,0.071460,0.033293,0.068713,0.004231,0.181741,11.994865
859,종로구,창신3동,0.009584,0.071460,0.027326,0.068661,0.000000,0.177031,11.506469
860,종로구,숭인1동,0.000000,0.071460,0.005348,0.069593,0.000000,0.146400,8.735790
861,종로구,평창동,0.003279,0.071460,0.001072,0.068804,0.000000,0.144615,8.594515
862,종로구,숭인2동,0.000903,0.071460,0.003465,0.068698,0.011353,0.155878,9.521601